export default {
  title: {
    home: 'الصفحة الرئيسية',
    login: 'تسجيل الدخول',
    lists: { 0: 'القوائم' },
    tags: {
      0: 'الأوسمة',
      1: '{name} وسوم للفئة {amount}',
      2: 'Search tags'
    },
    ideas: {
      0: 'اقتباسات',
      1: '«{amount}»'
    },
    sounds: { 0: 'أصوات' },
    leaderboard: { 0: 'المتصدرون' },
    extend: { 0: 'أكثر | أقل' },
    skin: {
      0: 'هذا المظهر مستوحٍ عناصرَ من مظاهر أخرى',
      1: 'انقر هنا لمزيد من المعلومات'
    },
    tools: 'أدوات'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'سِجل التغييرات',
    1: 'قائمة بجميع التنقيحات التي أجريت على النسخة الحالية',
    2: 'لا شيء هنا',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'غير مجمعة',
    5: 'جديد',
    6: 'إصلاحات',
    7: 'تغييرات',
    8: 'المحذوفات'
  },
  ideas: {
    0: 'لا نتائج',
    1: 'Screenshots of «{type}» were not uploaded to the site',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'المبتكرون',
    1: 'قائمة جميع المبتكرين الذين شاركوا في إنشاء هذا الإصدار',
    2: 'لا أحد هنا',
    3: 'البحث عن اسم لاعب سيعرض قائمة بأسماء اللاعبين.',
    4: 'محرر',
    5: 'أدوار',
    6: 'إصدارات'
  },
  tags: {
    0: 'الأوسمة',
    1: 'قائمة جميع الوسوم المتعلقة بهذا الزي',
    2: 'يبدو هذا المكان فارغ.',
    3: 'استعمل الحقل أعلاه لإيجاد وسوم جديدة',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'بحث'
  },
  videos: {
    0: 'مقاطع',
    1: 'قائمة جميع المقاطع العارضة لهذا الزي',
    2: 'عدم وجود عروض',
    3: 'ابحث عنها على Youtube أو اصنع عرضك الخاص'
  },
  sources: {
    0: 'إسناد',
    1: 'قائمة جميع الأصول أو الأدوات المستعملة في هذا الإصدار من الزي',
    2: 'المكان فارغ بعض الشيء',
    3: 'إذا استعملت أصول أم فنون من أزياء أخرى، تأكد من إضافتها في العلبة أعلاه',
    4: 'غير مجمعة'
  },
  checks: {
    0: 'الكل',
    1: 'بيانات فوقية',
    2: 'إبراز',
    3: 'Name of the skin not specified',
    4: 'ضف مبتكر زي واحد على الأقل',
    5: 'ضف بعض الوسوم',
    6: 'حجم الزي غير محدد',
    // 7: 'Select at least one gamemode',
    8: 'اختر نوع الملف (جودة عالية أو عادية)',
    9: 'اختر على الأقل نسبة باعية واحدة',
    10: 'عدم تقديم صور',
    11: 'ضف على الأقل صورة واحدة لللعب',
    12: 'عدم توفيير رابط للزي',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'قائمة المراجعة',
    23: 'Add at least one public version',
    24: 'Add at least one creator to this version',
    25: 'Some creators don\'t have roles',
    26: '{amount} screenshots doesn\'t have category',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'أزياء',
    1: 'محبوبة',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'حديث',
    5: 'عشوائية',
    6: 'جميع اللأزياء',
    7: 'نسبة باعية',
    8: 'جميع الأزياء | أزياء اللعبة',
    9: 'زي | أزياء | أزياء',
    10: 'لأزياء اللعبة من إصدار {name} | أزياء اللعبة من',
    11: 'بحث',
    12: '{name} skins',
    13: 'Explore skins',
    14: 'Popular skins'
  },
  skin: {
    0: 'تعديل',
    1: 'ميزات إضافية',
    2: 'HD جودة عالية',
    3: 'FullHD جودة أعلى',
    4: 'متحرك',
    5: 'صور',
    6: 'لعب فقط',
    7: 'رابط التحميل | تحميل الزي',
    8: 'منشور المنتدى | منتدى اللعبة',
    9: 'Reddit منشور',
    10: 'المبتكرون',
    11: 'الأوسمة',
    13: 'مقاطع',
    14: 'الإصدارات الجديدة | التحكم بالإصدارات',
    15: 'تحديث | إرسال',
    16: 'أنماط اللعب',
    17: 'اسم الزي',
    18: 'الإصدار | الإصدارات',
    19: 'الحجم',
    20: 'بيانات فوقية',
    21: 'التقييم',
    22: 'التحميلات',
    23: 'سيتوفر التحميل قريبا',
    24: '{amount} ثواني متبقية',
    25: 'لست واحد منا',
    26: 'يبدو أنك لست مؤلفا أو معدلا لهذا الزي',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!',
    45: 'uploader'
  },
  drag: {
    0: 'اُنقر هنا',
    1: 'أو اسحب و اسقط الصور هنا'
  },
  footer: {
    0: 'صناعة cyberdark',
    1: 'اعتمادات',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'شخصيات كرتونية',
    1: 'فنون',
    2: 'أيقونات',
    3: '{name} كل الأيقونات مأخوذة من',
    4: 'أعلام',
    5: '{name} كل الأعلام مأخوذة من',
    6: 'مواقع',
    7: 'أي شخص؟ [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'البحث عن الزي',
    1: 'مشاهدات',
    2: 'عنوان',
    3: 'التقييم',
    4: 'الحجم',
    5: 'تاريخ',
    7: 'لا نتائج',
    8: 'Try using different search filters',
    9: 'تتم معالجة الاستفسار',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'التحميلات',
    12: 'Name',
    13: {
      0: 'أزياء',
      1: 'الأوسمة',
      2: 'Users',
      3: 'القوائم'
    },
    14: 'Search:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished',
    6: 'Contests',
    7: 'Voting page'
  },
  rules: {
    0: 'Last updated at',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} of {max} completed',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'بحث',
    1: 'تعديل',
    2: 'قائمة'
  },
  undefined: {
    0: 'فارغ',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'غير مسموح',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  settings: {
    0: 'الإعدادات',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'أنماط اللعب، نسب باعية لأزياء اللعبة',
      2: 'أزياء اللعبة المحبوبة',
      3: 'البحث عن أزياء اللعبة',
      4: '«{name}» قائمة الوسوم',
      5: '{name} v{version} زي اللعبة',
      6: 'اعتمادات',
      7: 'أزياء اللعبة',
      8: '{name} البحث عن أزياء اللعبة',
      9: 'احصل على الإلهام من أزياء osu أخرى',
      10: '{name} صمم أزياء اللعبة',
      11: 'Search tags',
      12: '{name} found tags',
      13: 'زي جديد',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! skinning tools'
    },
    description: {
      0: 'جد أفضل أزياء اوسو في موقعنا! مكتبتنا تحتوي على أزياء من أجل جميع أنماط اللعب، النسب الباعية، و أفضل اللاعبين. إضافة إلى دلك لدينا جزء خاص لمعجبي الأنمي. حسن لعبك بإيجاد الزي المثالي.',
      1: 'مشاهدة {views}. زي osu خاص ب {modes}، حجمه {size}، مصنوع من طرف {creators}.  يدعم {ratios}',
      2: 'جد الزي المثالي بفضل ميزة البحث المتقدمة. تصفح مكتبتنا الواسعة، مصنفة حسب أنماط اللعب، النسب الباعية، و أكثر. أو بإمكانك رؤية  أزياء مستعملة من قبل افضل اللاعبين.',
      3: 'اكتشف مختلف أنماط اللعب و النسب الباعية على موقعنا. اختر نمط لعبك و حمل الزي الذي تفضله.',
      4: 'جد أفضل الأزياء من أفضل اللاعبين في موقعنا. تصفح مجموعة أزيائنا و نوع لعبك. اكتشف مجال واسع من الأطرزة و السمات حسب تفضيلاتك.',
      5: 'osu قائمة اللأوسام المذكورة من أجل أزياء',
      6: '{name} حمل مجانا مجموعة الأزياء ل',
      7: '{name} حمل مجانا العديد من الأزياء من أجل',
      8: '{name} جميع الأزياء المصنوعة من',
      9: 'جد الإلهام لزيك القادم في موقعنا. تصفح العديد من المجموعات و اكتشف طرق و أفكار جديدة. خذ أفكار و ابتكر أزياء مميزة',
      10: 'Search for tags among all the tags on the site.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'تسجيل الدخول',
    1: 'الصفخة الرئيسية',
    profile_osu: 'osu! حساب',
    new_skin: 'زي جديد',
    notifications: 'إشعارات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    load_more: 'عرض المزيد',
    copy_short: 'نسخ رابط قصير',
    copied: 'تم النسخ',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! منتدى',
    skin_return: 'الرجوع إلى الزي',
    source: 'Source',
    contest_voting: 'Vote here',
    rules_agree: 'I agree',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'مبتكر',
      1: 'مازج',
      2: 'حركات',
      3: 'فنون',
      4: 'تعاون',
      5: 'أصوات',
      6: 'لعب'
    }
  },
  tooltips: {
    0: 'Views: {amount}',
    1: 'تحديث النتائج',
    2: 'متنازلة | متصاعدة',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'ctrl+enter لإضافة وسم اضغط على',
    5: 'تعديل الإصدار',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'لا يوجد وصف مختصر',
    8: 'لا يوجد رابط',
    9: 'Downloads: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'مرحبا',
      1: 'القائمة الرئيسية',
      2: 'اختيار الأغنية',
      3: 'قائمة الأنماط',
      4: 'الأوضاع',
      5: 'العد تنازلي',
      6: 'لعب',
      7: 'الدوار',
      8: 'عبور الجزء',
      9: 'إخفاق الجزء',
      10: 'شاشة التوقف',
      11: 'شاشة الاخفاق',
      12: 'شاشة النتائج',
      13: 'تخطي',
      14: 'الراية',
      15: 'Result screen (bottom)',
      16: 'Beginning image'
    },
    cats: {
      0: 'إباحي',
      1: 'Furry',
      2: 'ممزوج'
    }
  },
  select: {
    0: 'جديد',
    1: 'تم إصلاح',
    2: 'تم تغيير',
    3: 'تم حذف',
    4: 'فن',
    5: 'الخط',
    6: 'فنان',
    7: 'عنصر الزي',
    8: 'أصوات',
    9: 'أدوات',
    10: 'Image',
    views: 'مشاهدات',
    likes: 'إعجابات',
    dislikes: 'Dislikes',
    downloads: 'التحميلات',
    ratio: 'اختر نسبة باعية | نسبة',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Select size range',
    4: 'احتر مجال تاريخي',
    5: 'سنة',
    6: 'شهر',
    7: 'اختر نسبة باعية',
    8: 'اختر الأصناف',
    9: 'أنماط اللعب',
    10: 'اختر النوع',
    11: 'Youtube ألصق رابط',
    12: 'Type a description and an url. Format description:url',
    13: 'اختر ميزات إضافية',
    14: 'ألصق رابط',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation',
    52: 'Warning',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'Success',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'إشعارات',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'غير مسموح',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No',
    5: 'Reset .ini?'
  }
};