export default {
  title: {
    home: 'الصفحة الرئيسية',
    login: 'تسجيل الدخول',
    lists: { 0: 'القوائم' },
    tags: {
      0: 'الأوسمة',
      1: '{name} وسوم للفئة {amount}',
      2: 'Search tags'
    },
    ideas: {
      0: 'اقتباسات',
      1: '«{amount}»'
    },
    sounds: { 0: 'أصوات' },
    leaderboard: { 0: 'المتصدرون' },
    extend: { 0: 'أكثر | أقل' },
    skin: {
      0: 'هذا المظهر مستوحٍ عناصرَ من مظاهر أخرى',
      1: 'انقر هنا لمزيد من المعلومات'
    },
    tools: 'أدوات'
  },
  changelogs: {
    0: 'سِجل التغييرات',
    1: 'قائمة بجميع التنقيحات التي أجريت على النسخة الحالية',
    2: 'لا شيء هنا',
    3: 'ولكن يمكنك إضافة التغييرات التي أجريتها على هذا الإصدار من الزي',
    4: 'غير مجمعة',
    5: 'جديد',
    6: 'إصلاحات',
    7: 'تغييرات',
    8: 'المحذوفات'
  },
  ideas: {
    0: 'لا نتائج',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'المبتكرون',
    1: 'قائمة جميع المبتكرين الذين شاركوا في إنشاء هذا الإصدار',
    2: 'لا أحد هنا',
    3: 'البحث عن اسم لاعب سيعرض قائمة بأسماء اللاعبين.',
    4: 'محرر',
    5: 'أدوار',
    6: 'إصدارات'
  },
  tags: {
    0: 'الأوسمة',
    1: 'قائمة جميع الوسوم المتعلقة بهذا الزي',
    2: 'يبدو هذا المكان فارغ.',
    3: 'استعمل الحقل أعلاه لإيجاد وسوم جديدة',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'بحث'
  },
  videos: {
    0: 'مقاطع',
    1: 'قائمة جميع المقاطع العارضة لهذا الزي',
    2: 'عدم وجود عروض',
    3: 'ابحث عنها على Youtube أو اصنع عرضك الخاص'
  },
  sources: {
    0: 'إسناد',
    1: 'قائمة جميع الأصول أو الأدوات المستعملة في هذا الإصدار من الزي',
    2: 'المكان فارغ بعض الشيء',
    3: 'إذا استعملت أصول أم فنون من أزياء أخرى، تأكد من إضافتها في العلبة أعلاه',
    4: 'غير مجمعة'
  },
  checks: {
    0: 'الكل',
    1: 'بيانات فوقية',
    2: 'إبراز',
    3: 'Name of the skin not specified',
    4: 'ضف مبتكر زي واحد على الأقل',
    5: 'ضف بعض الوسوم',
    6: 'حجم الزي غير محدد',
    7: 'اختر على الأقل نمط لعب واحد',
    8: 'اختر نوع الملف (جودة عالية أو عادية)',
    9: 'اختر على الأقل نسبة باعية واحدة',
    10: 'عدم تقديم صور',
    11: 'ضف على الأقل صورة واحدة لللعب',
    12: 'عدم توفيير رابط للزي',
    20: 'يبدو جيد',
    21: 'تم إصلاح جميع المشاكل، و هذا جيد',
    22: 'قائمة المراجعة',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'أزياء',
    1: 'محبوبة',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'حديث',
    5: 'عشوائية',
    6: 'جميع اللأزياء',
    7: 'نسبة باعية',
    8: 'جميع الأزياء | أزياء اللعبة',
    9: 'زي | أزياء | أزياء',
    10: 'لأزياء اللعبة من إصدار {name} | أزياء اللعبة من',
    11: 'بحث',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'تعديل',
    1: 'ميزات إضافية',
    2: 'HD جودة عالية',
    3: 'FullHD جودة أعلى',
    4: 'متحرك',
    5: 'صور',
    6: 'لعب فقط',
    7: 'رابط التحميل | تحميل الزي',
    8: 'منشور المنتدى | منتدى اللعبة',
    9: 'Reddit منشور',
    10: 'المبتكرون',
    11: 'الأوسمة',
    13: 'مقاطع',
    14: 'الإصدارات الجديدة | التحكم بالإصدارات',
    15: 'تحديث | إرسال',
    16: 'أنماط اللعب',
    17: 'اسم الزي',
    18: 'الإصدار | الإصدارات',
    19: 'الحجم',
    20: 'بيانات فوقية',
    21: 'التقييم',
    22: 'التحميلات',
    23: 'سيتوفر التحميل قريبا',
    24: '{amount} ثواني متبقية',
    25: 'لست واحد منا',
    26: 'يبدو أنك لست مؤلفا أو معدلا لهذا الزي',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'اُنقر هنا',
    1: 'أو اسحب و اسقط الصور هنا'
  },
  footer: {
    0: 'صناعة cyberdark',
    1: 'اعتمادات'
  },
  credits: {
    0: 'شخصيات كرتونية',
    1: 'فنون',
    2: 'أيقونات',
    3: '{name} كل الأيقونات مأخوذة من',
    4: 'أعلام',
    5: '{name} كل الأعلام مأخوذة من',
    6: 'مواقع',
    7: 'أي شخص؟ [{lang}]',
    8: 'يبدو أن cpol نسي إضافتها. {text}'
  },
  search: {
    0: 'البحث عن الزي',
    1: 'مشاهدات',
    2: 'عنوان',
    3: 'التقييم',
    4: 'الحجم',
    5: 'تاريخ',
    7: 'لا نتائج',
    8: 'حاول اختيار معيار بحث مختلف',
    9: 'تتم معالجة الاستفسار',
    10: 'اختر معيار البحث أو اكتب فقط عنوان الزي، المبتكر أو الوسم',
    11: 'التحميلات',
    12: 'Name',
    13: {
      0: 'أزياء',
      1: 'الأوسمة',
      2: 'Users',
      3: 'القوائم'
    }
  },
  tabs: {
    0: 'بحث',
    1: 'تعديل',
    2: 'قائمة'
  },
  undefined: {
    0: 'فارغ',
    1: 'لسوء الحظ لا يوجد شيء هنا، لكن بإمكانك النظر في صفحات أخرى',
    2: 'لسوء الحظ لا يوجد شيء هنا',
    3: 'غير مسموح',
    4: 'يجب عليك تسجيل الدخول لتعديل هذا الزي.',
    5: 'يجب عليك تسجيل الدخول لإضافة زي جديد.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'أنماط اللعب، نسب باعية لأزياء اللعبة',
      2: 'أزياء اللعبة المحبوبة',
      3: 'البحث عن أزياء اللعبة',
      4: '«{name}» قائمة الوسوم',
      5: '{name} v{version} زي اللعبة',
      6: 'اعتمادات',
      7: 'أزياء اللعبة',
      8: '{name} البحث عن أزياء اللعبة',
      9: 'احصل على الإلهام من أزياء osu أخرى',
      10: '{name} صمم أزياء اللعبة',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'جد أفضل أزياء اوسو في موقعنا! مكتبتنا تحتوي على أزياء من أجل جميع أنماط اللعب، النسب الباعية، و أفضل اللاعبين. إضافة إلى دلك لدينا جزء خاص لمعجبي الأنمي. حسن لعبك بإيجاد الزي المثالي.',
      1: 'مشاهدة {views}. زي osu خاص ب {modes}، حجمه {size}، مصنوع من طرف {creators}.  يدعم {ratios}',
      2: 'جد الزي المثالي بفضل ميزة البحث المتقدمة. تصفح مكتبتنا الواسعة، مصنفة حسب أنماط اللعب، النسب الباعية، و أكثر. أو بإمكانك رؤية  أزياء مستعملة من قبل افضل اللاعبين.',
      3: 'اكتشف مختلف أنماط اللعب و النسب الباعية على موقعنا. اختر نمط لعبك و حمل الزي الذي تفضله.',
      4: 'جد أفضل الأزياء من أفضل اللاعبين في موقعنا. تصفح مجموعة أزيائنا و نوع لعبك. اكتشف مجال واسع من الأطرزة و السمات حسب تفضيلاتك.',
      5: 'osu قائمة اللأوسام المذكورة من أجل أزياء',
      6: '{name} حمل مجانا مجموعة الأزياء ل',
      7: '{name} حمل مجانا العديد من الأزياء من أجل',
      8: '{name} جميع الأزياء المصنوعة من',
      9: 'جد الإلهام لزيك القادم في موقعنا. تصفح العديد من المجموعات و اكتشف طرق و أفكار جديدة. خذ أفكار و ابتكر أزياء مميزة',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'تسجيل الدخول',
    1: 'الصفخة الرئيسية',
    profile_osu: 'osu! حساب',
    new_skin: 'زي جديد',
    notifications: 'إشعارات',
    settings: 'الإعدادات',
    logout: 'تسجيل الخروج',
    load_more: 'عرض المزيد',
    copy_short: 'نسخ رابط قصير',
    copied: 'تم النسخ',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! منتدى',
    skin_return: 'الرجوع إلى الزي'
  },
  user: {
    roles: {
      0: 'مبتكر',
      1: 'مازج',
      2: 'حركات',
      3: 'فنون',
      4: 'تعاون'
    }
  },
  tooltips: {
    0: 'Views: {amount}',
    1: 'تحديث النتائج',
    2: 'متنازلة | متصاعدة',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'ctrl+enter لإضافة وسم اضغط على',
    5: 'تعديل الإصدار',
    6: '{s}سجل الدخول{p} ,لتقييم هذا الزي',
    7: 'لا يوجد وصف مختصر',
    8: 'لا يوجد رابط',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'مرحبا',
      1: 'القائمة الرئيسية',
      2: 'اختيار الأغنية',
      3: 'قائمة الأنماط',
      4: 'الأوضاع',
      5: 'العد تنازلي',
      6: 'لعب',
      7: 'الدوار',
      8: 'عبور الجزء',
      9: 'إخفاق الجزء',
      10: 'شاشة التوقف',
      11: 'شاشة الاخفاق',
      12: 'شاشة النتائج',
      13: 'تخطي',
      14: 'الراية'
    },
    cats: {
      0: 'إباحي',
      1: 'Furry',
      2: 'ممزوج'
    }
  },
  select: {
    0: 'جديد',
    1: 'تم إصلاح',
    2: 'تم تغيير',
    3: 'تم حذف',
    4: 'فن',
    5: 'الخط',
    6: 'فنان',
    7: 'عنصر الزي',
    8: 'أصوات',
    9: 'أدوات',
    views: 'مشاهدات',
    likes: 'إعجابات',
    dislikes: 'Dislikes',
    downloads: 'التحميلات',
    size_range: 'اختر الحجم',
    date_range: 'اختر مجال تاريخي',
    ratio: 'اختر نسبة باعية | نسبة'
  },
  placeholders: {
    0: 'اختر أدوار',
    1: 'اختر الاصدارات',
    2: 'أدخل كتابة...',
    3: 'اختر الحجم',
    4: 'احتر مجال تاريخي',
    5: 'سنة',
    6: 'شهر',
    7: 'اختر نسبة باعية',
    8: 'اختر الأصناف',
    9: 'أنماط اللعب',
    10: 'اختر النوع',
    11: 'Youtube ألصق رابط',
    12: 'أكتب تفاصيل و ألحق الرابط. من الشكل تفاصيل:رابط',
    13: 'اختر ميزات إضافية',
    14: 'ألصق رابط',
    15: 'عنوان الزي، مبتكر أو وسم',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'غير مسموح',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};