export default {
  title: {
    home: 'Domovská stránka',
    login: 'Přihlásit se',
    lists: { 0: 'Seznamy' },
    tags: {
      0: 'Označení',
      1: '{amount} značky pro kategorii {name}',
      2: 'Hledat Označení'
    },
    ideas: {
      0: 'Inspirace',
      1: '«{amount}»'
    },
    sounds: { 0: 'Zvuky' },
    leaderboard: { 0: 'Žebříčky' },
    extend: { 0: 'Více | Méně' },
    skin: {
      0: 'Tento skin obsahuje prvky z jiných skinů',
      1: 'Klikněte zde pro více informací'
    },
    tools: 'Nástroje'
  },
  changelogs: {
    0: 'Seznam změn',
    1: 'Seznam všech revizí provedených v stávající verzi',
    2: 'Nic zde není',
    3: 'But you can add the changes you made\'ve to this version of the skin',
    4: 'Není seskupeno',
    5: 'Nové',
    6: 'Opravy',
    7: 'Změny',
    8: 'Odstranit'
  },
  ideas: {
    0: 'Nic nebylo nalezeno',
    1: 'Snímky obrazovky «{type}» nebyly nahrány na stránku'
  },
  creators: {
    0: 'Vývojáři',
    1: 'Seznam všech vývojářů kteří byli zapojení ve vývoji této verze',
    2: 'Nikdo zde není',
    3: 'Hledání jména hráče zobrazí seznam profilů.',
    4: 'Editor',
    5: 'Role',
    6: 'Verze'
  },
  tags: {
    0: 'Označení',
    1: 'List všech značek souvisejících s tímto skinem',
    2: 'Zde to vypadá prázdně.',
    3: 'Použijte pole nahoře pro nalezení nových značek',
    4: 'Označení nenalezeny',
    5: 'Zkus hledat něco jiného',
    6: 'Hledat'
  },
  videos: {
    0: 'Videa',
    1: 'List všech video ukázek pro tento skin',
    2: 'Žádné ukázky',
    3: 'Najděte nějaké na YouTube nebo vytvořte vlastní ukázku'
  },
  sources: {
    0: 'Atribuce',
    1: 'List všech použitých prvků a nástrojů v této verzi skinu',
    2: 'Trochu prázdno zde',
    3: 'Pokud jste použili prvky z jiných skinů nebo obrazů, přidejte je do boxu nahoře',
    4: 'Není seskupeno'
  },
  checks: {
    0: 'Všechno',
    1: 'Metadata',
    2: 'Zvýraznění',
    3: 'Name of the skin not specified',
    4: 'Přidejte alespoň jednoho autora skinu',
    5: 'Přidejte pár značek',
    6: 'Velikost skinu není specifikována',
    7: 'Vyberte alespoň jeden herní mód',
    8: 'Vyberte typ složky (SD nebo HD)',
    9: 'Vyberte nejméně jeden poměr stran',
    10: 'Žádný snímek obrazovky',
    11: 'Přidejte alespoň jeden snímek obrazovky z hraní',
    12: 'Odkaz na skin není specifikován',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Kontrolní listina',
    23: 'Přidejte alespoň jednu veřejnou verzi'
  },
  skins: {
    0: 'Skiny',
    1: 'Populární',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Aktuální',
    5: 'Náhodné',
    6: 'Všechny skiny',
    7: 'Poměr stran',
    8: 'Všechny skiny | osu skiny',
    9: 'Skin | Skiny | Skiny',
    10: 'osu Skiny od {name} | Všechny skiny od',
    11: 'Hledat',
    12: '{name} skiny',
    13: 'Projiždět skiny'
  },
  skin: {
    0: 'Upravit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animace',
    5: 'Snímky obrazovky',
    6: 'Hraní',
    7: 'Stáhnout odkaz | Stáhnout skin',
    8: 'Příspěvek na fórech | osu! fóra',
    9: 'Příspěvek na Redditu',
    10: 'Vývojáři',
    11: 'Označení',
    13: 'Videa',
    14: 'Nová verze | Spravovat verze',
    15: 'Upravit | Zveřejnit',
    16: 'Herní módy',
    17: 'Jméno skinu',
    18: 'Verze | Verze',
    19: 'Velikost',
    20: 'Metadata',
    21: 'Hodnocení',
    22: 'Počet stáhnutí',
    23: 'Stahování bude brzy dostupné',
    24: '{amount} sekund zbývá',
    25: 'Nejsi jeden z nás',
    26: 'Zdá se, že nejsti autorem ani editorem tohoto skinu',
    27: 'Skin od',
    28: 'Žádná označení',
    29: 'Žádná videa',
    30: 'Žádní autoři'
  },
  drag: {
    0: 'Klikněte zde',
    1: 'nebo přetáhněte & vložte obrázky'
  },
  footer: {
    0: 'Uděláno uživatelem cyperdark',
    1: 'Poděkování'
  },
  credits: {
    0: 'Chibi',
    1: 'Obrázky',
    2: 'Ikony',
    3: 'Všechny ikony jsou od {name}',
    4: 'Vlajky',
    5: 'Všechny vlajky jsou od {name}',
    6: 'Lokalizace',
    7: 'Je tu někdo?{lang}',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Hledat skiny',
    1: 'Zobrazení',
    2: 'Název',
    3: 'Hodnocení',
    4: 'Velikost',
    5: 'Datum',
    7: 'Nic nebylo nalezeno',
    8: 'Try using different search filters',
    9: 'Čekání na dotaz',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Počet stáhnutí',
    12: 'Jméno',
    13: {
      0: 'Skiny',
      1: 'Označení',
      2: 'Uživatelé',
      3: 'Seznamy'
    }
  },
  tabs: {
    0: 'Hledat',
    1: 'Upravit',
    2: 'Seznam'
  },
  undefined: {
    0: 'Prázdno',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Neoprávněný',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Objevovat osu skiny',
      1: 'Herní módy, poměry stran osu skinů',
      2: 'Populární osu skiny',
      3: 'Hledat osu skiny',
      4: '«{name}» list označení',
      5: '{name} v{version} osu skin',
      6: 'Poděkování',
      7: 'osu skiny',
      8: '{name} hledat osu skiny',
      9: 'Získejte inspiraci z jiných osu skinů',
      10: '{name} vyrobil osu skiny',
      11: 'Hledat Označení',
      12: '{name} nalezl označení'
    },
    description: {
      0: 'Stáhněte si osu! skiny na našich stránkách! Naše velká knihovna ma skiny pro všechny herní módy, poměry stran, a dokonce i skiny od nejlepších hráčů. Taky máme speciální sekci pro fanoušky anime. Zlepšete svoje hraní s perfektním skinem. #osuskins #osugame #anime',
      1: '{views} zobrazení. Osu! skin pro {modes}, velikost {size}, vytvořeno {creators}. Podporuje {ratios}',
      2: 'Najděte si perfektní osu! skin s naším pokročilým vyhledávacím systémem. Projděte si naší obrovskou knihovnou, rozdělené na herní módy, poměry stran, atd. Nebo můžete zkusit se podívat na skiny od nejlepších hráčů',
      3: 'Objevte na našem webu různé skiny pro různé herní režimy a poměry stran. Vyberte si ze standard, catch the beat, mánia a taiko. Najděte perfektní řešení pro vaše herní preference.',
      4: 'Najděte perfektní osu skin od nejlepších hráčů na našich stránkách. Projděte naší kolecí populárních skinů a přizpůsobte svůj herní styl. Najdete zde široký rozsah stylů a témat který vyhoví vašim preferencím.',
      5: 'List všch existujících označení pro osu skiny.',
      6: '{name} osu skiny kolekce!, neplacené stahování',
      7: 'Velký počet osu skinů pro {name}, stáhněte zadarmo!',
      8: 'Všechny osu skiny vyrobeny od {name}',
      9: 'Najděte si inspirace pro vaše další osu! skiny na našich stránkách. Projděte naší rozmanitou kolekcí skinů a najděte nové techniky a nápady. Inspirujte se a udělejte si vlastní jedinečné skiny.',
      10: 'Hledjte označení mezi všema na tomto webu.'
    }
  },
  buttons: {
    0: 'Přihlásit se',
    1: 'Domovská stránka',
    profile_osu: 'osu! Profil',
    new_skin: 'Nový skin',
    notifications: 'Notifikace',
    settings: 'Nastavení',
    logout: 'Odhlásit se',
    load_more: 'Načíst více',
    copy_short: 'Zkopírovat krátký odkaz',
    copied: 'Zkopírováno',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Fóra',
    skin_return: 'Zpátky ke skinu'
  },
  user: {
    roles: {
      0: 'Autor',
      1: 'Mixer',
      2: 'Animace',
      3: 'Obrázky',
      4: 'Spolupráce'
    }
  },
  tooltips: {
    0: 'Zobrazení: {amount}',
    1: 'obnovit výsledky',
    2: 'Klesající | Stoupající',
    3: 'Líbí se: {likes} / Nelíbí se: {dislikes}',
    4: 'Zmáčkněte ctrl+enter pro přidání označení',
    5: 'Upravit verzi',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Žádný krátký popis ',
    8: 'Žádné URL',
    9: 'Stažení: {amount}'
  },
  lists: {
    screens: {
      0: 'Vítej',
      1: 'Hlavní menu',
      2: 'Výběr hudby',
      3: 'Menu módů',
      4: 'Módy',
      5: 'Odpočet',
      6: 'Hra',
      7: 'Spiner',
      8: 'Sekce dokončena',
      9: 'Sekce nedokončena',
      10: 'Obrazovka pauzy',
      11: 'Obrazovka prohry',
      12: 'Obrazovka výsledku',
      13: 'Přeskočení',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mix'
    }
  },
  select: {
    0: 'Nové',
    1: 'Opraveno',
    2: 'Změněno',
    3: 'Odstraněno',
    4: 'Obrázky',
    5: 'Font',
    6: 'Umělec',
    7: 'Prvky skinu',
    8: 'Zvuk/Sfx',
    9: 'Nástroje',
    views: 'Zobrazení',
    likes: 'Oblíbené',
    dislikes: 'Neoblíbené',
    downloads: 'Počet stáhnutí',
    size_range: 'Vyber velikost',
    date_range: 'Vyber časové období',
    ratio: 'Vyber poměr stran | poměr'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Vyber velikost',
    4: 'Vyber časové období',
    5: 'Rok',
    6: 'Měsíc',
    7: 'Vyber poměr stran',
    8: 'Vyber kategorii',
    9: 'Herní módy',
    10: 'Vyber typ',
    11: 'Vložte odkaz na YouTube',
    12: 'Type a description and an url. Format description:url',
    13: 'Vyber extra',
    14: 'Vložte link',
    15: 'Skin title, author, or tags',
    16: 'Vyberte kategorii',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Zapojte se' },
  nsfw: {
    0: 'Upozornění!',
    1: 'Tento skin obshauje citlivý obsah nebo obsah pro dospělé',
    2: 'Tento skin obsahuje citlivý obsah nebo obsah pro dospělé, který může připadat některým uživatelům znepokojivě',
    3: 'Dobře',
    4: 'měj se o/'
  },
  removed: {
    0: 'Verze není k dispozici',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Zobrazit',
    3: 'Nenalezeno',
    4: 'Banner nebyl nalezen (aktuálně se první snímek obrazovky používá jako banner)',
    5: 'Beze změn',
    6: 'Nebyly nalezeny žádné změny',
    7: 'ID nebylo nalezeno',
    8: 'ID videa nebylo nalezeno, zkuste jiný odkaz (nyní je podporován pouze YouTube)',
    9: 'Chybička se vloudila',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Existuje',
    12: 'Toto video již bylo přidáno',
    13: 'Existuje',
    14: 'Toto označení již bylo přidáno',
    15: 'Nenalezeno',
    16: 'Smazaný štítek nelze odstranit',
    17: 'Added',
    18: 'Úspěšně jste přidali nové označení',
    19: 'Chybička se vloudila',
    20: 'Tento autor již byl přidán',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Nelze odstranit odstraněného autora',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Varování',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Varování',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Obnoveno',
    34: 'Version «{name}» has been restored',
    35: 'Odstraněno',
    36: 'Version «{name}» has been deleted',
    37: 'Chyba',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Neznámá chyba',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Úspěšně dokončeno',
    47: 'Nové změny byly odeslány k moderaci',
    48: 'Změny byly aktualizovány v moderaci',
    49: 'Zvláštní odkaz',
    50: 'Tento odkaz nelze použít jako odkaz ke stažení',
    51: 'Submitted for moderation'
  },
  restricted_view: {
    0: 'Neoprávněný',
    1: 'Přihlaste se prosím k účtu',
    2: 'Omezené zobrazení',
    3: 'Tato stránka zatím není venku.'
  }
};