export default {
  title: {
    home: 'Domovská stránka',
    login: 'Přihlásit se',
    lists: { 0: 'Seznamy' },
    tags: {
      0: 'Označení',
      1: '{amount} značky pro kategorii {name}',
      2: 'Hledat Označení'
    },
    ideas: {
      0: 'Inspirace',
      1: '«{amount}»'
    },
    sounds: { 0: 'Zvuky' },
    leaderboard: { 0: 'Žebříčky' },
    extend: { 0: 'Více | Méně' },
    skin: {
      0: 'Tento skin obsahuje prvky z jiných skinů',
      1: 'Klikněte zde pro více informací'
    },
    tools: 'Nástroje'
  },
  home: {
    0: 'Dostupné ke stažení',
    1: 'Nejvíce: _name_ skiny',
    2: 'Zobrazeno | Líbí se | Staženo',
    3: 'Publikovat nový skin',
    4: 'Jak nainstalovat skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Seznam změn',
    1: 'Seznam všech revizí provedených v stávající verzi',
    2: 'Nic zde není',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Není seskupeno',
    5: 'Nové',
    6: 'Opravy',
    7: 'Změny',
    8: 'Odstranit'
  },
  ideas: {
    0: 'Nic nebylo nalezeno',
    1: 'Snímky obrazovky «{type}» nebyly nahrány na stránku',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Vývojáři',
    1: 'Seznam všech vývojářů kteří byli zapojení ve vývoji této verze',
    2: 'Nikdo zde není',
    3: 'Hledání jména hráče zobrazí seznam profilů.',
    4: 'Editor',
    5: 'Role',
    6: 'Verze'
  },
  tags: {
    0: 'Označení',
    1: 'List všech značek souvisejících s tímto skinem',
    2: 'Zde to vypadá prázdně.',
    3: 'Použijte pole nahoře pro nalezení nových značek',
    4: 'Označení nenalezeny',
    5: 'Zkus hledat něco jiného',
    6: 'Hledat'
  },
  videos: {
    0: 'Videa',
    1: 'List všech video ukázek pro tento skin',
    2: 'Žádné ukázky',
    3: 'Najděte nějaké na YouTube nebo vytvořte vlastní ukázku'
  },
  sources: {
    0: 'Atribuce',
    1: 'List všech použitých prvků a nástrojů v této verzi skinu',
    2: 'Trochu prázdno zde',
    3: 'Pokud jste použili prvky z jiných skinů nebo obrazů, přidejte je do boxu nahoře',
    4: 'Není seskupeno'
  },
  checks: {
    0: 'Všechno',
    1: 'Metadata',
    2: 'Zvýraznění',
    3: 'Name of the skin not specified',
    4: 'Přidejte alespoň jednoho autora skinu',
    5: 'Přidejte pár značek',
    6: 'Velikost skinu není specifikována',
    // 7: 'Select at least one gamemode',
    8: 'Vyberte typ složky (SD nebo HD)',
    9: 'Vyberte nejméně jeden poměr stran',
    10: 'Žádný snímek obrazovky',
    11: 'Přidejte alespoň jeden snímek obrazovky z hraní',
    12: 'Odkaz na skin není specifikován',
    20: 'Vypadá to dobře',
    21: 'Každý problém byl opraven. Dobrá práce!',
    22: 'Kontrolní listina',
    23: 'Přidejte alespoň jednu veřejnou verzi',
    24: 'Přidat alespoň jednoho autora k této verzi',
    25: 'Někteří autoři nemají roli',
    26: '{amount} screenshots doesn\'t have category',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skiny',
    1: 'Populární',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Aktuální',
    5: 'Náhodné',
    6: 'Všechny skiny',
    7: 'Poměr stran',
    8: 'Všechny skiny | osu skiny',
    9: 'Skin | Skiny | Skiny',
    10: 'osu Skiny od {name} | Všechny skiny od',
    11: 'Hledat',
    12: '{name} skiny',
    13: 'Projiždět skiny',
    14: 'Popular skins'
  },
  skin: {
    0: 'Upravit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animace',
    5: 'Snímky obrazovky',
    6: 'Hraní',
    7: 'Stáhnout odkaz | Stáhnout skin',
    8: 'Příspěvek na fórech | osu! fóra',
    9: 'Příspěvek na Redditu',
    10: 'Vývojáři',
    11: 'Označení',
    13: 'Videa',
    14: 'Nová verze | Spravovat verze',
    15: 'Upravit | Zveřejnit',
    16: 'Herní módy',
    17: 'Jméno skinu',
    18: 'Verze | Verze',
    19: 'Velikost',
    20: 'Metadata',
    21: 'Hodnocení',
    22: 'Počet stáhnutí',
    23: 'Stahování bude brzy dostupné',
    24: '{amount} sekund zbývá',
    25: 'Nejsi jeden z nás',
    26: 'Zdá se, že nejsti autorem ani editorem tohoto skinu',
    27: 'Skin od',
    28: 'Žádná označení',
    29: 'Žádná videa',
    30: 'Žádní autoři',
    31: 'Ohodnotit skin',
    32: 'Hlasovat a komentovat na redditu',
    33: 'Komentovat na osu! fóru',
    34: 'Více skinů od tohoto autora | Více skinů od těchto autorů',
    35: 'Podpořit skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!',
    45: 'uploader'
  },
  drag: {
    0: 'Klikněte zde',
    1: 'nebo přetáhněte & vložte obrázky'
  },
  footer: {
    0: 'Uděláno uživatelem cyperdark',
    1: 'Poděkování',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Obrázky',
    2: 'Ikony',
    3: 'Všechny ikony jsou od {name}',
    4: 'Vlajky',
    5: 'Všechny vlajky jsou od {name}',
    6: 'Lokalizace',
    7: 'Je tu někdo?{lang}',
    8: 'Vypadá to, že cpol je zapomněl přidat {text}'
  },
  search: {
    0: 'Hledat skiny',
    1: 'Zobrazení',
    2: 'Název',
    3: 'Hodnocení',
    4: 'Velikost',
    5: 'Datum',
    7: 'Nic nebylo nalezeno',
    8: 'Try using different search filters',
    9: 'Čekání na dotaz',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Počet stáhnutí',
    12: 'Jméno',
    13: {
      0: 'Skiny',
      1: 'Označení',
      2: 'Uživatelé',
      3: 'Seznamy'
    },
    14: 'Hledat:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished',
    6: 'Contests',
    7: 'Voting page'
  },
  rules: {
    0: 'Last updated at',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} of {max} completed',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'Hledat',
    1: 'Upravit',
    2: 'Seznam'
  },
  undefined: {
    0: 'Prázdno',
    1: 'Bohužel zde nic není, ale můžete se podívat na ostatní stránky',
    2: 'Bohužel zde nic není',
    3: 'Neoprávněný',
    4: 'Pro úpravu tohoto skinu musíte být přihlášeni.',
    5: 'Musíte být přihlášený pro přidání nového skinu.'
  },
  settings: {
    0: 'Nastavení',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.',
    5: 'English comments',
    6: 'Show English translation of the comments'
  },
  meta: {
    title: {
      0: 'Objevovat osu skiny',
      1: 'Herní módy, poměry stran osu skinů',
      2: 'Populární osu skiny',
      3: 'Hledat osu skiny',
      4: '«{name}» list označení',
      5: '{name} v{version} osu skin',
      6: 'Poděkování',
      7: 'osu skiny',
      8: '{name} hledat osu skiny',
      9: 'Získejte inspiraci z jiných osu skinů',
      10: '{name} vyrobil osu skiny',
      11: 'Hledat Označení',
      12: '{name} nalezl označení',
      13: 'Nový skin',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: 'Stáhněte si osu! skiny na našich stránkách! Naše velká knihovna ma skiny pro všechny herní módy, poměry stran, a dokonce i skiny od nejlepších hráčů. Taky máme speciální sekci pro fanoušky anime. Zlepšete svoje hraní s perfektním skinem. #osuskins #osugame #anime',
      1: '{views} zobrazení. Osu! skin pro {modes}, velikost {size}, vytvořeno {creators}. Podporuje {ratios}',
      2: 'Najděte si perfektní osu! skin s naším pokročilým vyhledávacím systémem. Projděte si naší obrovskou knihovnou, rozdělené na herní módy, poměry stran, atd. Nebo můžete zkusit se podívat na skiny od nejlepších hráčů',
      3: 'Objevte na našem webu různé skiny pro různé herní režimy a poměry stran. Vyberte si ze standard, catch the beat, mánia a taiko. Najděte perfektní řešení pro vaše herní preference.',
      4: 'Najděte perfektní osu skin od nejlepších hráčů na našich stránkách. Projděte naší kolecí populárních skinů a přizpůsobte svůj herní styl. Najdete zde široký rozsah stylů a témat který vyhoví vašim preferencím.',
      5: 'List všch existujících označení pro osu skiny.',
      6: '{name} osu skiny kolekce!, neplacené stahování',
      7: 'Velký počet osu skinů pro {name}, stáhněte zadarmo!',
      8: 'Všechny osu skiny vyrobeny od {name}',
      9: 'Najděte si inspirace pro vaše další osu! skiny na našich stránkách. Projděte naší rozmanitou kolekcí skinů a najděte nové techniky a nápady. Inspirujte se a udělejte si vlastní jedinečné skiny.',
      10: 'Hledjte označení mezi všema na tomto webu.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Přihlásit se',
    1: 'Domovská stránka',
    profile_osu: 'osu! Profil',
    new_skin: 'Nový skin',
    notifications: 'Notifikace',
    settings: 'Nastavení',
    logout: 'Odhlásit se',
    load_more: 'Načíst více',
    copy_short: 'Zkopírovat krátký odkaz',
    copied: 'Zkopírováno',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Fóra',
    skin_return: 'Zpátky ke skinu',
    source: 'Source',
    contest_voting: 'Vote here',
    rules_agree: 'I agree',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Autor',
      1: 'Mixer',
      2: 'Animace',
      3: 'Obrázky',
      4: 'Spolupráce',
      5: 'Zvuky',
      6: 'Hra'
    }
  },
  tooltips: {
    0: 'Zobrazení: {amount}',
    1: 'obnovit výsledky',
    2: 'Klesající | Stoupající',
    3: 'Líbí se: {likes} / Nelíbí se: {dislikes}',
    4: 'Zmáčkněte ctrl+enter pro přidání označení',
    5: 'Upravit verzi',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Žádný krátký popis ',
    8: 'Žádné URL',
    9: 'Stažení: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Vítej',
      1: 'Hlavní menu',
      2: 'Výběr hudby',
      3: 'Menu módů',
      4: 'Módy',
      5: 'Odpočet',
      6: 'Hra',
      7: 'Spiner',
      8: 'Sekce dokončena',
      9: 'Sekce nedokončena',
      10: 'Obrazovka pauzy',
      11: 'Obrazovka prohry',
      12: 'Obrazovka výsledku',
      13: 'Přeskočení',
      14: 'Banner',
      15: 'Result screen (bottom)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mix'
    }
  },
  select: {
    0: 'Nové',
    1: 'Opraveno',
    2: 'Změněno',
    3: 'Odstraněno',
    4: 'Obrázky',
    5: 'Font',
    6: 'Umělec',
    7: 'Prvky skinu',
    8: 'Zvuk/Sfx',
    9: 'Nástroje',
    10: 'Image',
    views: 'Zobrazení',
    likes: 'Oblíbené',
    dislikes: 'Neoblíbené',
    downloads: 'Počet stáhnutí',
    ratio: 'Vyber poměr stran | poměr',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Vyberte role',
    1: 'Vyberte Verze',
    2: 'Zadejte text...',
    3: 'Select size range',
    4: 'Vyber časové období',
    5: 'Rok',
    6: 'Měsíc',
    7: 'Vyber poměr stran',
    8: 'Vyber kategorii',
    9: 'Herní módy',
    10: 'Vyber typ',
    11: 'Vložte odkaz na YouTube',
    12: 'Zadejte popis a url. Popis formátu:url',
    13: 'Vyber extra',
    14: 'Vložte odkaz',
    15: 'Název skinu, autor, nebo označení',
    16: 'Vyberte kategorii',
    17: 'Zadejte název označení',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Zapojte se' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'Tento skin obshauje citlivý obsah nebo obsah pro dospělé',
    2: 'Tento skin obsahuje citlivý obsah nebo obsah pro dospělé, který může připadat některým uživatelům znepokojivě',
    3: 'Dobře',
    4: 'měj se o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Verze není k dispozici',
    1: 'Autor skinu se rozhodl odstranit tuto verzi z webu.',
    2: 'Přepnout na dostupnou verzi'
  },
  notify: {
    0: 'Problémy nebyly opraveny',
    1: 'Nebyla vyplněna všechna povinná pole',
    2: 'Zobrazit',
    3: 'Nenalezeno',
    4: 'Banner nebyl nalezen (aktuálně se první snímek obrazovky používá jako banner)',
    5: 'Beze změn',
    6: 'Nebyly nalezeny žádné změny',
    7: 'ID nebylo nalezeno',
    8: 'ID videa nebylo nalezeno, zkuste jiný odkaz (nyní je podporován pouze YouTube)',
    9: 'Chybička se vloudila',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Existuje',
    12: 'Toto video již bylo přidáno',
    13: 'Existuje',
    14: 'Toto označení již bylo přidáno',
    15: 'Nenalezeno',
    16: 'Smazaný štítek nelze odstranit',
    17: 'Added',
    18: 'Úspěšně jste přidali nové označení',
    19: 'Chybička se vloudila',
    20: 'Tento autor již byl přidán',
    21: 'EZ',
    22: 'New autor byl přidán',
    23: 'HUH',
    24: 'Nelze odstranit odstraněného autora',
    25: 'Existuje',
    26: 'Tato změna již byla přidána dříve.',
    27: 'Existuje',
    28: 'Tato adresa Url již byla přidána dříve.',
    29: 'Varování',
    30: 'Zapomněli jste přidat popis pro url. Příklad: Popis:url',
    31: 'Varování',
    32: 'Zapomněli jste přidat Url pro popis. Příklad: Popis:url',
    33: 'Obnoveno',
    34: 'Verze {name} byla obnovena',
    35: 'Odstraněno',
    36: 'Verze {name} byla odstraněna',
    37: 'Chyba',
    38: 'Server si zřejmě myslí, že jste robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Nesrovnalé přihlašovací údaje (znovu se přihlásit do účtu. Nebojte se, vše bylo automaticky uloženo)',
    41: 'Neznámá chyba',
    42: 'Nemůžete upravovat neexistující skin',
    43: 'Zdá se, že nemáte oprávnění k úpravě tohoto skinu',
    44: 'Nemůžete odeslat tuto verzi, protože je stejná jako předchozí.',
    45: 'Tyto změny již byly odeslány k moderování',
    46: 'Úspěšně dokončeno',
    47: 'Nové změny byly odeslány k moderaci',
    48: 'Změny byly aktualizovány v moderaci',
    49: 'Zvláštní odkaz',
    50: 'Tento odkaz nelze použít jako odkaz ke stažení',
    51: 'Odesláno k moderaci',
    52: 'Varování',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'Úspěšně dokončeno',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'Notifikace',
    1: 'Sledujte nás na těchto platformách a získejte oznámení o nových skinech'
  },
  restricted_view: {
    0: 'Neoprávněný',
    1: 'Přihlaste se prosím k účtu',
    2: 'Omezené zobrazení',
    3: 'Tato stránka zatím není venku.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No',
    5: 'Reset .ini?'
  }
};