export default {
  title: {
    home: 'Αρχική',
    login: 'Log in',
    lists: { 0: 'Λίστες' },
    tags: {
      0: 'Ετικέτες',
      1: '{amount} ετικέτες για την κατηγορία {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Έμπνευση',
      1: '«{amount}»'
    },
    sounds: { 0: 'Ήχοι' },
    leaderboard: { 0: 'Κατατάξεις' },
    extend: { 0: 'Περισσότερα | Λιγότερα' },
    skin: {
      0: 'Αυτό το skin περιέχει στοιχεία από άλλα skin',
      1: 'Κάντε κλικ εδώ για περισσότερες πληροφορίες'
    },
    tools: 'Εργαλεία'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Αλλαγές',
    1: 'Λίστα όλων των αναθεωρήσεων που έγιναν στην τρέχουσα έκδοση',
    2: 'Δεν υπάρχει κάτι εδώ',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Μη ομαδοποιημένο',
    5: 'Νέα',
    6: 'Διορθώσεις',
    7: 'Αλλαγές',
    8: 'Αφαιρέσεις'
  },
  ideas: {
    0: 'Δε βρέθηκε τίποτα',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Δημιουργοί',
    1: 'Λίστα όλων των δημιουργών που συμμετείχαν στη δημιουργία αυτής της έκδοσης',
    2: 'Κανένας δεν είναι εδώ',
    3: 'Η αναζήτηση ονόματος ενός παίκτη θα εμφανίσει μια λίστα με προφίλ.',
    4: 'Επεξεργαστής',
    5: 'Ρόλοι',
    6: 'Εκδόσεις'
  },
  tags: {
    0: 'Ετικέτες',
    1: 'Λίστα όλων των ετικετών που σχετίζονται με αυτό το skin',
    2: 'Φαίνεται πολύ άδειο εδώ.',
    3: 'Χρησιμοποιήστε το παραπάνω πεδίο για να βρείτε νέες ετικέτες',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Αναζήτηση'
  },
  videos: {
    0: 'Βίντεο',
    1: 'Λίστα όλων των βίντεο για αυτό το skin',
    2: 'Έλλειψη βίντεο',
    3: 'Αναζητήστε μερικά στο YouTube ή δημιουργήστε το δικό σας'
  },
  sources: {
    0: 'Ιδιότητες',
    1: 'Κατάλογος όλων των χρησιμοποιούμενων στοιχείων ή εργαλείων σε αυτήν την έκδοση του skin',
    2: 'Κάπως άδειο εδώ',
    3: 'Αν έχετε χρησιμοποιήσει στοιχεία από άλλα skins, ή δημιουργήματα, φροντίστε να τα προσθέσετε στο παραπάνω πλαίσιο',
    4: 'Μη ομαδοποιημένο'
  },
  checks: {
    0: 'Όλα',
    1: 'Μεταδεδομένα (Metadata)',
    2: 'Highlight',
    3: 'Name of the skin not specified',
    4: 'Προσθέστε τουλάχιστον έναν δημιουργό skin',
    5: 'Προσθέστε μερικές ετικέτες',
    6: 'Μη καθορισμένο μέγεθος skin',
    7: 'Επιλέξτε τουλάχιστον μία κατηγορία',
    8: 'Επιλογή ανάλυσης εικόνας (SD ή HD)',
    9: 'Επιλέξτε τουλάχιστον μία αναλογία διαστάσεων',
    10: 'Δεν παρέχονται στιγμιότυπα',
    11: 'Προσθέστε τουλάχιστον ένα στιγμιότυπο παιχνιδιού',
    12: 'Μη καθορισμένος σύνδεσμος για το skin',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Λίστα ελέγχου',
    23: 'Add at least one public version',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Skins',
    1: 'Δημοφιλή',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Πρόσφατα',
    5: 'Τυχαίο',
    6: 'Όλα τα skins',
    7: 'Αναλογία διαστάσεων',
    8: 'Όλα τα skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins από {name} - Όλα τα skins από',
    11: 'Αναζήτηση',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Επεξεργασία',
    1: 'Έξτρα',
    2: 'HD',
    3: 'FullHD',
    4: 'Κινητικά εφέ',
    5: 'Στιγμιότυπα',
    6: 'Μόνο gameplay',
    7: 'Σύνδεσμος λήψης | Λήψη του skin',
    8: 'Ανάρτηση forum | osu! Forum',
    9: 'Ανάρτηση Reddit',
    10: 'Δημιουργοί',
    11: 'Ετικέτες',
    13: 'Βίντεο',
    14: 'Νέα έκδοση | Διαχείριση εκδόσεων',
    15: 'Ενημέρωση | Υποβολή',
    16: 'Είδος παιχνιδιού',
    17: 'Όνομα του skin',
    18: 'Έκδοση | Εκδόσεις',
    19: 'Μέγεθος',
    20: 'Μεταδεδομένα (Metadata)',
    21: 'Βαθμολογία',
    22: 'Λήψεις',
    23: 'Η λήψη θα είναι διαθέσιμη σύντομα',
    24: 'Απομένουν {amount} δευτερόλεπτα',
    25: 'Δεν είσαι ένας από εμάς',
    26: 'Φαίνεται πως δεν είστε δημιουργός ή επεξεργαστής του skin',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately skin was deleted by {author} request'
  },
  drag: {
    0: 'Κάντε κλικ εδώ',
    1: 'ή σύρετε & αφήστε εικόνες εδώ'
  },
  footer: {
    0: 'Φτιαγμένο από τον cyperdark',
    1: 'Ευχαριστίες'
  },
  credits: {
    0: 'Chibi',
    1: 'Εικόνες',
    2: 'Εικονίδια',
    3: 'Όλα τα εικονίδια έχουν ληφθεί από το {name}',
    4: 'Σημαίες',
    5: 'Όλες οι εικόνες των σημαιών είναι από το {name}',
    6: 'Μετάφραση',
    7: 'Κανένας; [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Αναζήτηση skin',
    1: 'Προβολές',
    2: 'Τίτλος',
    3: 'Βαθμολογία',
    4: 'Μέγεθος',
    5: 'Ημερομηνία',
    7: 'Δε βρέθηκε τίποτα',
    8: 'Try using different search filters',
    9: 'Εκκρεμεί ένα αίτημα',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Λήψεις',
    12: 'Name',
    13: {
      0: 'Skins',
      1: 'Ετικέτες',
      2: 'Users',
      3: 'Λίστες'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Αναζήτηση',
    1: 'Επεξεργασία',
    2: 'Λίστα'
  },
  undefined: {
    0: 'Άδειο',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Μη εξουσιοδοτημένο',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'Τρόποι παιχνιδιού, αναλογία διαστάσεων, osu skins',
      2: 'Δημοφιλή osu skins',
      3: 'Αναζητήστε osu skins',
      4: 'Λίστα ετικετών, {name}',
      5: '{name} v{version} osu skin',
      6: 'Ευχαριστίες',
      7: 'osu skins',
      8: '{name} αναζήτηση osu skins',
      9: 'Πάρτε έμπνευση από άλλα osu skin',
      10: '{name} δημιουργημένα osu skins',
      11: 'Search tags',
      12: '{name} found tags',
      13: 'Νέο skin'
    },
    description: {
      0: 'Αποκτήστε τα καλύτερα osu! skins στο site μας! Η τεράστια συλλογή μας έχει skins για όλους τους τρόπους παιχνιδιού, αναλογίες διαστάσεων και ακόμα και για τους κορυφαίους παίκτες. Ακόμη, έχουμε ένα ειδικό τμήμα για τους anime fans. Βελτιώστε το παιχνίδι σας με το τέλειο skin. #osuskins #osugame #anime',
      1: '{views} προβολές. Ένα osu skin για {modes}, με μέγεθος {size}, δημιουργήθηκε από {creators}. Υποστηρίζει {ratios}',
      2: 'Βρείτε το τέλειο osu! skin με τη προηγμένη μας αναζήτηση. Περιηγηθείτε στην τεράστια συλλογή μας, με φίλτρα gamemode, αναλογίας διαστάσεων και πολλά άλλα. Ή, δείτε τα skins που χρησιμοποιούνται από κορυφαίους παίκτες.',
      3: 'Ανακαλύψτε μια ποικιλία skin για διαφορετικούς τρόπους παιχνιδιού και αναλογίες διαστάσεων στην ιστοσελίδα μας. Επιλέξτε από standard, catch the beat, mania και taiko. Βρείτε το τέλειο skin για τις προτιμήσεις παιχνιδιού σας.',
      4: 'Βρείτε το τέλειο osu skin των κορυφαίων παιχτών στην ιστοσελίδα μας. Περιηγηθείτε την συλλογή μας δημοφιλών skins και προσαρμόσετε το παιχνίδι σας. Ανακαλύψτε ένα ευρύ φάσμα στυλ και θέματων που ταιριάζουν στις προτιμήσεις σας.',
      5: 'Λίστα υπαρχουσών ετικετών για osu skins.',
      6: '{name} osu skins συλλογή!, δωρεάν λήψη',
      7: 'Τεράστια ποσότητα osu skins για {name}, κατεβάστε δωρεάν!',
      8: 'Όλα τα osu skins που δημιουργήθηκαν από {name}',
      9: 'Βρείτε έμπνευση για το επόμενο osu! skin σας στο site μας. Περιηγηθείτε μια ποικιλία skin και ανακαλύψτε νέες τεχνικές και ιδέες. Εμπνευστείτε και δημιουργήστε τα δικά σας μοναδικά skin.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Είσοδος',
    1: 'Αρχική σελίδα',
    profile_osu: 'Προφίλ osu!',
    new_skin: 'Νέο skin',
    notifications: 'Ειδοποιήσεις',
    settings: 'Ρυθμίσεις',
    logout: 'Αποσύνδεση',
    load_more: 'Φόρτωση περισσοτέρων',
    copy_short: 'Αντιγραφή σύντομου συνδέσμου',
    copied: 'Αντιγράφηκε',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Επιστροφή στο skin'
  },
  user: {
    roles: {
      0: 'Δημιουργός',
      1: 'Μίκτης',
      2: 'Εφέ Κίνησης',
      3: 'Εικόνες',
      4: 'Συνεργασία'
    }
  },
  tooltips: {
    0: 'Views: {amount}',
    1: 'Ανανέωση αποτελεσμάτων',
    2: 'Φθίνουσα | Αύξουσα',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'Πατήστε ctrl+enter για να προσθέσετε μια ετικέτα',
    5: 'Επεξεργασία έκδοσης',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Χωρίς σύντομη περιγραφή',
    8: 'Χωρίς διεύθυνση url',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Καλώς ήρθατε',
      1: 'Κύριο μενού',
      2: 'Επιλογή τραγουδιού',
      3: 'Μενού λειτουργιών',
      4: 'Τροποποιήσεις',
      5: 'Αντίστροφη μέτρηση',
      6: 'Παιχνίδι',
      7: 'Σπίνερ',
      8: 'Πέρασμα Τμήματος',
      9: 'Αποτυχία Τμήματος',
      10: 'Οθόνη Παύσης',
      11: 'Οθόνη Αποτυχίας',
      12: 'Οθόνη αποτελέσματος',
      13: 'Παράλειψη',
      14: 'Πανό'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Μεικτό'
    }
  },
  select: {
    0: 'Νέα',
    1: 'Διορθώσεις',
    2: 'Αλλαγές',
    3: 'Αφαιρέθηκαν',
    4: 'Τέχνη',
    5: 'Γραμματοσειρά',
    6: 'Καλλιτέχνης',
    7: 'Στοιχείο skin',
    8: 'Ήχοι/Sfx',
    9: 'Εργαλεία',
    views: 'Προβολές',
    likes: '"Μου Αρέσει"',
    dislikes: 'Dislikes',
    downloads: 'Λήψεις',
    size_range: 'Επιλογή μεγέθους',
    date_range: 'Επιλογή εύρους ημερομηνιών',
    ratio: 'Επιλογή αναλογίας διαστάσεων | αναλογία'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Επιλογή μεγέθους',
    4: 'Επιλέξτε εύρος ημερομηνιών',
    5: 'Έτος',
    6: 'Μήνας',
    7: 'Επιλογή αναλογίας διαστάσεων',
    8: 'Επιλογή κατηγοριών',
    9: 'Είδος παιχνιδιού',
    10: 'Επιλέξτε τύπο',
    11: 'Επικολλήστε έναν σύνδεσμο YouTube',
    12: 'Type a description and an url. Format description:url',
    13: 'Επιλογή επιπλέον',
    14: 'Επικόλληση συνδέσμου',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning nsfw!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/',
    5: 'Warning furry!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation'
  },
  header: {
    0: 'Ειδοποιήσεις',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Μη εξουσιοδοτημένο',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};