export default {
  title: {
    home: 'Inicio',
    login: 'Log in',
    lists: { 0: 'Listas' },
    tags: {
      0: 'Etiquetas',
      1: '{amount} etiquetas por categoria {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiración',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sonidos' },
    leaderboard: { 0: 'Clasificación' },
    extend: { 0: 'Más | Menos' },
    skin: {
      0: 'Esta skin contiene elementos de otras skins',
      1: 'Haga clic aquí para más información'
    },
    tools: 'Herramientas'
  },
  changelogs: {
    0: 'Lista de cambios',
    1: 'Lista de todas las revisiones hechas en la versión actual',
    2: 'Nada por aquí',
    3: 'Pero puedes agregar los cambios que realizaste en esta versión de la skin',
    4: 'No agrupado',
    5: 'Nuevo',
    6: 'Arreglos',
    7: 'Cambios',
    8: 'Removidos'
  },
  ideas: {
    0: 'No se encontró nada',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Creadores',
    1: 'Lista de todos los creadores que participaron en la creación de esta versión',
    2: 'No hay nadie aquí',
    3: 'Buscar el nickname de un jugador mostrará una lista de perfiles.',
    4: 'Editor',
    5: 'Roles',
    6: 'Versiones'
  },
  tags: {
    0: 'Etiquetas',
    1: 'Lista de todas las etiquetas relacionadas con esta skin',
    2: 'Parece bastante vacío aquí.',
    3: 'Utiliza el campo de arriba para encontrar etiquetas nuevas',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Buscar'
  },
  videos: {
    0: 'Vídeos',
    1: 'Lista de todos los vídeos de demostración para esta skin',
    2: 'No hay vídeos de demostración',
    3: 'Busca un vídeo en YouTube o crea tu propio vídeo demostrativo'
  },
  sources: {
    0: 'Atribución',
    1: 'Lista de todas las cosas o herramientas utilizadas en esta skin',
    2: 'Un poco vacío aquí...',
    3: 'Si utilizaste cosas de otras skins o artes, por favor agrégalas en el campo de arriba',
    4: 'No agrupado'
  },
  checks: {
    0: 'Todo',
    1: 'Metadata',
    2: 'Destacado',
    3: 'Name of the skin not specified',
    4: 'Agrega al menos un creador de la skin',
    5: 'Agrega un par de etiquetas',
    6: 'Tamaño de la skin no especificado',
    7: 'Selecciona al menos un modo de juego',
    8: 'Selecciona una resolución de imagen (SD o HD)',
    9: 'Selecciona al menos una relación de aspecto (Ejemplo: 4:3, 16:9, 21:9...)',
    10: 'No se agregaron capturas de pantalla',
    11: 'Agrega al menos una captura de pantalla del gameplay',
    12: 'Enlace de la skin no especificado',
    20: 'Se ve bastante bien',
    21: 'Cada error fue solucionado. Buen trabajo',
    22: 'Lista de verificación',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Popular',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Reciente',
    5: 'Aleatorio',
    6: 'Todas las skins',
    7: 'Relación de aspecto',
    8: 'Todas las skins | skins de osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins de osu por {name} | Todas las skins de',
    11: 'Buscar',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Editar',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animación',
    5: 'Captura de pantalla',
    6: 'Solo gameplay',
    7: 'Link de descarga | Descarga la skin',
    8: 'Post en el foro | Foro de osu!',
    9: 'Publicación de Reddit',
    10: 'Creadores',
    11: 'Etiquetas',
    13: 'Vídeos',
    14: 'Nueva versión | Administrar versiones',
    15: 'Actualizar | Enviar',
    16: 'Modos de juego',
    17: 'Nombre de la skin',
    18: 'Versión | Versiones',
    19: 'Tamaño',
    20: 'Metadata',
    21: 'Valoración',
    22: 'Descargas',
    23: 'La descarga estará disponible pronto',
    24: 'Quedan {amount} segundos',
    25: 'No eres uno de nosotros',
    26: 'Parece que no eres el autor o editor de esta skin',
    27: 'Skin hecha por',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Click aquí',
    1: 'o arrastra y suelta imágenes aquí'
  },
  footer: {
    0: 'Hecho por cyperdark',
    1: 'Créditos'
  },
  credits: {
    0: 'Chibi',
    1: 'Arte',
    2: 'Iconos',
    3: 'Todos los íconos han sido tomados de {name}',
    4: 'Banderas',
    5: 'Todas las imágenes de las banderas son de {name}',
    6: 'Localización',
    7: '¿Alguien? [{lang}]',
    8: 'Parece que cpol se olvidó de añadirlos. {text}'
  },
  search: {
    0: 'Buscador de skins',
    1: 'Vistas',
    2: 'Título',
    3: 'Valoración',
    4: 'Tamaño',
    5: 'Fecha',
    7: 'No se encontró nada',
    8: 'Intenta utilizar diferentes filtros de búsqueda',
    9: 'Pendiente',
    10: 'Seleccione los filtros de búsqueda o simplemente escriba el título de la skin, el autor o la etiqueta',
    11: 'Descargas',
    12: 'Nombre',
    13: {
      0: 'Skins',
      1: 'Etiquetas',
      2: 'Users',
      3: 'Listas'
    }
  },
  tabs: {
    0: 'Buscar',
    1: 'Editar',
    2: 'Lista'
  },
  undefined: {
    0: 'Vacío',
    1: 'Lamentablemente no hay nada aquí, de todos modos puedes mirar otras páginas',
    2: 'Lamentablemente no hay nada aquí',
    3: 'No autorizado',
    4: 'Debes iniciar sesión para editar esta skin.',
    5: 'Debes iniciar sesión para agregar una nueva skin.'
  },
  meta: {
    title: {
      0: 'Descubre skins de osu',
      1: 'Modos de juego, relación de aspecto de las skins de osu',
      2: 'Skins populares de osu',
      3: 'Busca skins de osu',
      4: 'Lista de las etiquetas, {name}',
      5: '{name} v{version} osu skin',
      6: 'Créditos',
      7: 'skins de osu',
      8: '{name} buscador de skins de osu',
      9: 'Inspirate de otras skins de osu!',
      10: '{name} skins de osu creadas',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: '¡Consigue las mejores skins de osu! en nuestra página! Nuestra amplia librería cuenta con skins para todos los modos de juego, relaciones de aspecto e incluso con aquellas usadas por los mejores jugadores. Además, tenemos una sección especial para los fans del anime. Mejora tu gameplay con la skin perfecta. #osuskins #osugame #anime',
      1: '{views} vistas. Una skin de osu para {modes}, con un tamaño de {size}, creada por {creators}. Soporta {ratios}',
      2: 'Encuentra la skin de osu! perfecta con nuestra función de búsqueda avanzada. Busca entre nuestra amplia librería, filtrada por modo de juego, relación de aspecto, y más. O mira las skins usadas por los mejores jugadores.',
      3: 'Descubra entre una amplia variedad de skins para diferentes modos de juego y relaciones de aspecto en nuestra página. Escoja entre standard, catch the beat, mania, y taiko. Encuentra aquella que se ajuste mejor a tus preferencias al jugar.',
      4: 'Encuentra la skin de osu perfecta utilizada por los mejores jugadores en nuestra página. Navega por nuestra colección de skins populares y personaliza tu juego. Descubre una amplia variedad de estilos y temas que encajen con tus preferencias.',
      5: 'Lista de las etiquetas existentes para skins de osu.',
      6: 'Colección de skins de {name}, descarga gratuita',
      7: 'Una gran cantidad de skins de osu para {name}, ¡descarga gratuita!',
      8: 'Todas las skins creadas por {name}',
      9: 'Encuentra inspiración para tu próxima skin de osu! en nuestra página. Navega entre una diversa colección de skins y descubre nuevas técnicas e ideas. Inspírate para crear tu propia skin.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Iniciar sesión',
    1: 'Página de inicio',
    profile_osu: 'Perfil de osu!',
    new_skin: 'Nueva skin',
    notifications: 'Notificaciones',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    load_more: 'Cargar más',
    copy_short: 'Copiar enlace corto',
    copied: 'Copiado',
    reddit_link: 'Reddit',
    osu_forum_link: 'Foro de osu!',
    skin_return: 'Volver a la skin'
  },
  user: {
    roles: {
      0: 'Creador',
      1: 'Mezclador',
      2: 'Animaciones',
      3: 'Arte',
      4: 'Colaboración'
    }
  },
  tooltips: {
    0: 'Vistas: {amount}',
    1: 'Actualizar los resultados',
    2: 'Descendente | Ascendente',
    3: 'Me gusta: {likes} / No me gusta: {dislikes}',
    4: 'Presione Ctrl+Enter para agregar una etiqueta',
    5: 'Editar versión',
    6: '{s}Inicia sesión{p}, para poder valorar esta skin',
    7: 'Sin descripción corta',
    8: 'Sin enlace',
    9: 'Descargas: {amount}'
  },
  lists: {
    screens: {
      0: 'Bienvenido',
      1: 'Menú principal',
      2: 'Selección de canción',
      3: 'Menú de modos',
      4: 'Mods',
      5: 'Cuenta regresiva',
      6: 'Gameplay',
      7: 'Ruleta',
      8: 'Sección aprobada',
      9: 'Sección Fallada',
      10: 'Pantalla de pausa',
      11: 'Pantalla de fallo',
      12: 'Pantalla de resultados',
      13: 'Saltar',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mezclada'
    }
  },
  select: {
    0: 'Nuevo',
    1: 'Arreglado',
    2: 'Cambiado',
    3: 'Eliminado',
    4: 'Arte',
    5: 'Fuente',
    6: 'Artista',
    7: 'Elemento de la skin',
    8: 'Audio/Sfx',
    9: 'Herramientas',
    views: 'Vistas',
    likes: 'Me gusta',
    dislikes: 'No me gusta',
    downloads: 'Descargas',
    size_range: 'Seleccionar tamaño',
    date_range: 'Seleccione un rango de fechas',
    ratio: 'Seleccionar relación de aspecto | relación'
  },
  placeholders: {
    0: 'Elige roles',
    1: 'Elige versiones',
    2: 'Escribir...',
    3: 'Seleccionar tamaño',
    4: 'Seleccionar rango de fechas',
    5: 'Año',
    6: 'Mes',
    7: 'Seleccionar relación de aspecto',
    8: 'Seleccionar categorías',
    9: 'Modos de juego',
    10: 'Selecciona el tipo',
    11: 'Pegar un enlace de YouTube',
    12: 'Escriba la descripción y la URL. Descripción del formato:url',
    13: 'Seleccionar extra',
    14: 'Pegar un enlace',
    15: 'Título de la skin, autor o etiqueta',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Contribuir' },
  nsfw: {
    0: '¡Advertencia!',
    1: 'Esta skin contiene elementos sensibles o contenido adulto',
    2: 'Esta skin contiene elementos sensibles o contenido adulto que algunos usuarios pueden encontrar inquietante',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'No autorizado',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};