export default {
  title: {
    home: 'Inicio',
    login: 'Iniciar sesión',
    lists: { 0: 'Listas' },
    tags: {
      0: 'Etiquetas',
      1: '{amount} etiquetas por categoria {name}',
      2: 'Etiquetas de búsqueda'
    },
    ideas: {
      0: 'Inspiración',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sonidos' },
    leaderboard: { 0: 'Clasificación' },
    extend: { 0: 'Más | Menos' },
    skin: {
      0: 'Esta skin contiene elementos de otras skins',
      1: 'Haga clic aquí para más información'
    },
    tools: 'Herramientas'
  },
  home: {
    0: 'Disponible para descargar',
    1: 'Skins más _name_',
    2: 'Visto | Gustados | Descargados',
    3: 'Publicar nueva skin',
    4: 'Como instalar la skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Lista de cambios',
    1: 'Lista de todas las revisiones hechas en la versión actual',
    2: 'Nada por aquí',
    3: 'Aunque puedes agregar los cambios que realizaste a esta versión de la skin',
    4: 'No agrupado',
    5: 'Nuevo',
    6: 'Arreglos',
    7: 'Cambios',
    8: 'Removidos'
  },
  ideas: {
    0: 'No se encontró nada',
    1: 'Las capturas de pantalla de {type} no han sido subidas al sitio'
  },
  creators: {
    0: 'Creadores',
    1: 'Lista de todos los creadores que participaron en la creación de esta versión',
    2: 'No hay nadie aquí',
    3: 'Buscar el nickname de un jugador mostrará una lista de perfiles.',
    4: 'Editor',
    5: 'Roles',
    6: 'Versiones'
  },
  tags: {
    0: 'Etiquetas',
    1: 'Lista de todas las etiquetas relacionadas con esta skin',
    2: 'Parece bastante vacío aquí.',
    3: 'Utiliza el campo de arriba para encontrar etiquetas nuevas',
    4: 'Etiquetas no encontradas',
    5: 'Intenta buscar algo diferente',
    6: 'Buscar'
  },
  videos: {
    0: 'Vídeos',
    1: 'Lista de todos los vídeos de demostración para esta skin',
    2: 'No hay vídeos de demostración',
    3: 'Busca un vídeo en YouTube o crea tu propio vídeo demostrativo'
  },
  sources: {
    0: 'Atribución',
    1: 'Lista de todas las cosas o herramientas utilizadas en esta skin',
    2: 'Un poco vacío aquí...',
    3: 'Si utilizaste cosas de otras skins o artes, por favor agrégalas en el campo de arriba',
    4: 'No agrupado'
  },
  checks: {
    0: 'Todo',
    1: 'Metadata',
    2: 'Destacado',
    3: 'Nombre de la skin no especificado',
    4: 'Agrega al menos un creador de la skin',
    5: 'Agrega un par de etiquetas',
    6: 'Tamaño de la skin no especificado',
    7: 'Selecciona al menos un modo de juego',
    8: 'Selecciona una resolución de imagen (SD o HD)',
    9: 'Selecciona al menos una relación de aspecto (Ejemplo: 4:3, 16:9, 21:9...)',
    10: 'No se agregaron capturas de pantalla',
    11: 'Agrega al menos una captura de pantalla del gameplay',
    12: 'Enlace de la skin no especificado',
    20: '¡Quedó bastante bien!',
    21: 'Todos los errores han sido solucionados ¡Buen trabajo!',
    22: 'Lista de verificación',
    23: 'Añade al menos una versión pública',
    24: 'Añade al menos un creador a esta versión',
    25: 'Algunos creadores no tienen roles'
  },
  skins: {
    0: 'Skins',
    1: 'Popular',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Reciente',
    5: 'Aleatorio',
    6: 'Todas las skins',
    7: 'Relación de aspecto',
    8: 'Todas las skins | skins de osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins de osu por {name} | Todas las skins de',
    11: 'Buscar',
    12: '{name} skins',
    13: 'Explora skins'
  },
  skin: {
    0: 'Editar',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animación',
    5: 'Captura de pantalla',
    6: 'Solo gameplay',
    7: 'Link de descarga | Descarga la skin',
    8: 'Post en el foro | Foro de osu!',
    9: 'Publicación de Reddit',
    10: 'Creadores',
    11: 'Etiquetas',
    13: 'Vídeos',
    14: 'Nueva versión | Administrar versiones',
    15: 'Actualizar | Enviar',
    16: 'Modos de juego',
    17: 'Nombre de la skin',
    18: 'Versión | Versiones',
    19: 'Tamaño',
    20: 'Metadata',
    21: 'Valoración',
    22: 'Descargas',
    23: 'La descarga estará disponible pronto',
    24: 'Quedan {amount} segundos',
    25: 'No eres uno de nosotros',
    26: 'Parece que no eres el autor o editor de esta skin',
    27: 'Skin hecha por',
    28: 'Sin etiquetas',
    29: 'No videos',
    30: 'No creadores',
    31: 'Valorar skin',
    32: 'Votar y comentar en reddit',
    33: 'Comentar en el foro de osu!',
    34: 'Más skins de este autor | Más skins de estos autores',
    35: 'Apoyar la skin',
    36: 'No disponible',
    37: 'Desafortunadamente, la skin ha sido eliminada a petición de {author}',
    38: '¡Bienvenido al editor de posts de skin!',
    39: `¿Nuevo al editor de skins? ¡Dejanos guiarte por la interfaz y enseñarte el potencial completo del editor!`,
    40: '{current} de {max} completados',
    41: 'Mirar luego',
    42: `¡Empecemos!`,
    43: '¡Felicidades!',
    44: 'Has completado satisfactoriamente el tutorial, ¡diviertete!'
  },
  drag: {
    0: 'Click aquí',
    1: 'o arrastra y suelta imágenes aquí'
  },
  footer: {
    0: 'Hecho por cyperdark',
    1: 'Créditos',
    2: 'Reglas',
    3: 'Contactos'
  },
  credits: {
    0: 'Chibi',
    1: 'Arte',
    2: 'Iconos',
    3: 'Todos los íconos han sido tomados de {name}',
    4: 'Banderas',
    5: 'Todas las imágenes de las banderas son de {name}',
    6: 'Localización',
    7: '¿Alguien? [{lang}]',
    8: 'Parece que cyprdark se ha olvidado de añadirlos. {text}'
  },
  search: {
    0: 'Buscador de skins',
    1: 'Vistas',
    2: 'Título',
    3: 'Valoración',
    4: 'Tamaño',
    5: 'Fecha',
    7: 'No se encontró nada',
    8: 'Prueba a usar otros filtros de busqueda',
    9: 'Pendiente',
    10: 'Usa los filtros de busqueda o escribe el nombre, autor o tags de la skin',
    11: 'Descargas',
    12: 'Nombre',
    13: {
      0: 'Skins',
      1: 'Etiquetas',
      2: 'Usuarios',
      3: 'Listas'
    },
    14: 'Buscar:'
  },
  contests: {
    0: 'Concursos',
    1: 'Post de noticias oficial',
    2: 'Subir',
    3: 'Preparando',
    4: 'Votaciones',
    5: 'Terminado'
  },
  tabs: {
    0: 'Buscar',
    1: 'Editar',
    2: 'Lista'
  },
  undefined: {
    0: 'Vacío',
    1: 'Desafortunadamente, no hay nada aquí, pero puedes echar un vistazo a las otras páginas',
    2: 'Desafortunadamente, no hay nada aquí',
    3: 'No autorizado',
    4: 'Necesitas iniciar sesión para poder editar esta skin.',
    5: 'Necesitas iniciar sesión para poder añadir una nueva skin.'
  },
  meta: {
    title: {
      0: 'Descubre skins de osu',
      1: 'Modos de juego, relación de aspecto de las skins de osu',
      2: 'Skins populares de osu',
      3: 'Busca skins de osu',
      4: 'Lista de las etiquetas, {name}',
      5: '{name} v{version} osu skin',
      6: 'Créditos',
      7: 'skins de osu',
      8: '{name} buscador de skins de osu',
      9: 'Inspirate de otras skins de osu!',
      10: '{name} skins de osu creadas',
      11: 'Etiquetas de búsqueda',
      12: 'Etiquetas encontradas {name}',
      13: 'Nueva skin',
      14: 'Reglas del sitio',
      15: 'Concursos de osu!',
      16: 'Concursos de osu!'
    },
    description: {
      0: '¡Consigue las mejores skins de osu! en nuestra página! Nuestra amplia librería cuenta con skins para todos los modos de juego, relaciones de aspecto e incluso con aquellas usadas por los mejores jugadores. Además, tenemos una sección especial para los fans del anime. Mejora tu gameplay con la skin perfecta. #osuskins #osugame #anime',
      1: '{views} vistas. Una skin de osu para {modes}, con un tamaño de {size}, creada por {creators}. Soporta {ratios}',
      2: 'Encuentra la skin de osu! perfecta con nuestra función de búsqueda avanzada. Busca entre nuestra amplia librería, filtrada por modo de juego, relación de aspecto, y más. O mira las skins usadas por los mejores jugadores.',
      3: 'Descubra entre una amplia variedad de skins para diferentes modos de juego y relaciones de aspecto en nuestra página. Escoja entre standard, catch the beat, mania, y taiko. Encuentra aquella que se ajuste mejor a tus preferencias al jugar.',
      4: 'Encuentra la skin de osu perfecta utilizada por los mejores jugadores en nuestra página. Navega por nuestra colección de skins populares y personaliza tu juego. Descubre una amplia variedad de estilos y temas que encajen con tus preferencias.',
      5: 'Lista de las etiquetas existentes para skins de osu.',
      6: 'Colección de skins de {name}, descarga gratuita',
      7: 'Una gran cantidad de skins de osu para {name}, ¡descarga gratuita!',
      8: 'Todas las skins creadas por {name}',
      9: 'Encuentra inspiración para tu próxima skin de osu! en nuestra página. Navega entre una diversa colección de skins y descubre nuevas técnicas e ideas. Inspírate para crear tu propia skin.',
      10: 'Buscar etiquetas entre todas las etiquetas en el sitio.',
      11: 'Lista de todos los concursos de osu! activos/terminados',
      12: '{amount} entradas para el concurso {title}. {views} vistas'
    }
  },
  buttons: {
    0: 'Iniciar sesión',
    1: 'Página de inicio',
    profile_osu: 'Perfil de osu!',
    new_skin: 'Nueva skin',
    notifications: 'Notificaciones',
    settings: 'Ajustes',
    logout: 'Cerrar sesión',
    load_more: 'Cargar más',
    copy_short: 'Copiar enlace corto',
    copied: 'Copiado',
    reddit_link: 'Reddit',
    osu_forum_link: 'Foro de osu!',
    skin_return: 'Volver a la skin',
    source: 'Fuente',
    contest_voting: 'Vota aquí'
  },
  choose: {
    0: 'Opcional',
    1: 'Necesario',
    2: 'Elige por lo menos una opción'
  },
  user: {
    roles: {
      0: 'Creador',
      1: 'Mezclador',
      2: 'Animaciones',
      3: 'Arte',
      4: 'Colaboración'
    }
  },
  tooltips: {
    0: 'Vistas: {amount}',
    1: 'Actualizar los resultados',
    2: 'Descendente | Ascendente',
    3: 'Me gusta: {likes} / No me gusta: {dislikes}',
    4: 'Presione Ctrl+Enter para agregar una etiqueta',
    5: 'Editar versión',
    6: '{s}Inicia sesión{p}, para poder valorar esta skin',
    7: 'Sin descripción corta',
    8: 'Sin enlace',
    9: 'Descargas: {amount}',
    10: 'Restablecer todo',
    11: 'Mostrar guía',
    12: 'Cerrar guía',
    13: 'Para marcar una regla como leída, pase el cursor sobre ella (amarillo indica no leído)'
  },
  lists: {
    screens: {
      0: 'Bienvenido',
      1: 'Menú principal',
      2: 'Selección de canción',
      3: 'Menú de modos',
      4: 'Mods',
      5: 'Cuenta regresiva',
      6: 'Gameplay',
      7: 'Ruleta',
      8: 'Sección aprobada',
      9: 'Sección Fallada',
      10: 'Pantalla de pausa',
      11: 'Pantalla de fallo',
      12: 'Pantalla de resultados',
      13: 'Saltar',
      14: 'Banner',
      15: 'Pantalla de resultados (inferior)'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mezclada'
    }
  },
  select: {
    0: 'Nuevo',
    1: 'Arreglado',
    2: 'Cambiado',
    3: 'Eliminado',
    4: 'Arte',
    5: 'Fuente',
    6: 'Artista',
    7: 'Elemento de la skin',
    8: 'Audio/Sfx',
    9: 'Herramientas',
    views: 'Vistas',
    likes: 'Me gusta',
    dislikes: 'No me gusta',
    downloads: 'Descargas',
    size_range: 'Seleccionar tamaño',
    date_range: 'Seleccione un rango de fechas',
    ratio: 'Seleccionar relación de aspecto | relación'
  },
  placeholders: {
    0: 'Seleccionar roles',
    1: 'Seleccionar versiones',
    2: 'Escribe algo de texto...',
    3: 'Seleccionar tamaño',
    4: 'Seleccionar rango de fechas',
    5: 'Año',
    6: 'Mes',
    7: 'Seleccionar relación de aspecto',
    8: 'Seleccionar categorías',
    9: 'Modos de juego',
    10: 'Selecciona el tipo',
    11: 'Pegar un enlace de YouTube',
    12: 'Escriba una descripción y una url. Formato descripción:url',
    13: 'Seleccionar extra',
    14: 'Pegar un enlace',
    15: 'Título de la skin, autor o etiquetas',
    16: 'Seleccionar categoría',
    17: 'Escribe el nombre de la etiqueta'
  },
  contribute: { 0: 'Contribuir' },
  nsfw: {
    0: '¡Advertencia, nsfw!',
    1: 'Esta skin contiene elementos sensibles o contenido adulto',
    2: 'Esta skin contiene elementos sensibles o contenido adulto que algunos usuarios pueden encontrar inquietante',
    3: 'De acuerdo',
    4: 'bye o/',
    5: '¡Advertencia de Furry!'
  },
  removed: {
    0: 'Versión no disponible',
    1: 'El autor de la skin ha decidido eliminar esta versión del sitio.',
    2: 'Cambiar a una versión disponible'
  },
  notify: {
    0: 'No se han solucionado los problemas',
    1: 'No todos los campos obligatorios fueron rellenados',
    2: 'Mostrar',
    3: 'No encontrado',
    4: 'Banner no encontrado (actualmente, la primera captura de pantalla está siendo utilizada como el banner)',
    5: 'Sin cambios',
    6: 'No se han encontrado cambios',
    7: 'ID no encontrado',
    8: 'ID del video no encontrado, prueba con otro enlace (por el momento, solo YouTube es soportado)',
    9: 'Ups',
    10: 'Parece que tu sesión ha expirado, abre una nueva página e inicia sesión en tu cuenta (no te preocupes, todo se ha guardado automáticamente)',
    11: 'Existe',
    12: 'Este vídeo ya ha sido añadido',
    13: 'Existe',
    14: 'Esta etiqueta ya ha sido agregada',
    15: 'No encontrado',
    16: 'No puedes eliminar una etiqueta eliminada',
    17: 'Añadido',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Aparentemente, el servidor piensa que eres un robot.',
    39: 'Parece que su sesión de usuario ha caducado, abra una nueva página e inicie sesión en su cuenta (no se preocupe, todo se ha guardado automáticamente)',
    40: 'Credenciales incorrectas (hay que reiniciar sesión en la cuenta. No te preocupes, todo se guardó automáticamente)',
    41: 'Error desconocido',
    42: 'No puedes editar un skin que no existe',
    43: 'Parece que no tienes permisos para editar esta skin',
    44: 'No puede enviar esta versión porque es la misma que la anterior.',
    45: 'Estos cambios ya habían sido enviados para moderación',
    46: 'Completado',
    47: 'Se han enviado nuevos cambios para moderación',
    48: 'Los cambios han sido actualizados en moderación',
    49: 'Link raro',
    50: 'Este link no puede utilizarse como enlace de descarga',
    51: 'Enviado para moderación',
    52: 'Warning',
    53: 'Tienes que elegir el tipo de recurso'
  },
  header: {
    0: 'Notificaciones',
    1: 'Síguenos en estas plataformas para recibir notificaciones sobre nuevas skins'
  },
  restricted_view: {
    0: 'No autorizado',
    1: 'Por favor inicia sesión en tu cuenta',
    2: 'Vista restringida',
    3: 'Esta página no está disponible, todavía.'
  },
  confirm: {
    0: '¿Restablecer todo?',
    1: '¿Mostrar guía?',
    2: '¿Enviar skin?',
    3: 'Si',
    4: 'No'
  }
};