export default {
  title: {
    home: 'Koti',
    login: 'Kirjaudu sisään',
    lists: { 0: 'Luettelot' },
    tags: {
      0: 'Tägit',
      1: '{amount} tägiä kategoriassa {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiraatio',
      1: '«{amount}»'
    },
    sounds: { 0: 'Äänet' },
    leaderboard: { 0: 'Tulostaulut' },
    extend: { 0: 'Enemmän | Vähemmän' },
    skin: {
      0: 'Tässä skinissä on käytetty tiedostoja muista skineistä',
      1: 'Klikkaa tästä saadaksesi lisää tietoa'
    },
    tools: 'Työkalut'
  },
  changelogs: {
    0: 'Muutosloki',
    1: 'Luettelo kaikista nykyiseen versioon tehdyistä muutoksista',
    2: 'Tyhjää Täällä',
    3: 'Mutta voit lisätä muutokset jotka olet tehnyt tähän skinin versioon',
    4: 'Ei ryhmitelty',
    5: 'Uutta',
    6: 'Korjaukset',
    7: 'Muutokset',
    8: 'Poistot'
  },
  ideas: {
    0: 'Nothing founded',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Tekijät',
    1: 'Luettelo kaikista tekijöistä jotka olivat mukana tämän version tekemisessä',
    2: 'Täällä ei ole ketään',
    3: 'Pelaajan nimen etsiminen näyttää luettelon profiileista.',
    4: 'Muokkaaja',
    5: 'Roolit',
    6: 'Versiot'
  },
  tags: {
    0: 'Tägit',
    1: 'Luettelo kaikista tägeistä jotka liittyvät tähän skiniin',
    2: 'Täällä tuntuu tyhjältä.',
    3: 'Käytä yllä olevaa kenttää uusien tägien löytämiseen',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Haku'
  },
  videos: {
    0: 'Videot',
    1: 'Luettelo kaikista tämän skinin videoesittelyistä',
    2: 'Ei esittelyjä',
    3: 'Voit etsiä niitä YouTubesta tai tehdä oman esittelysi'
  },
  sources: {
    0: 'Attribuutio',
    1: 'Luettelo käytetyistä muiden skinejen omaisuuksista tai työkaluista tässä versiossa',
    2: 'Vähän tyhjää täällä',
    3: 'Jos olet käyttänyt elementtejä muista skineistä, varmista että lisäät ne ylläolevaan laatikkoon',
    4: 'Ei ryhmitelty'
  },
  checks: {
    0: 'Kaikki',
    1: 'Metadata',
    2: 'Korosta',
    3: 'Name of the skin not specified',
    4: 'Lisää ainakin yksi skinin tekijä',
    5: 'Lisää muutama tägi',
    6: 'Skinin koko ei ole määritelty',
    7: 'Valitse ainakin yksi pelimode',
    8: 'Valitse tiedoston tyyppi (SD tai HD)',
    9: 'Valitse ainakin yksi kuvasuhde',
    10: 'Ei annettuja kuvakaappauksia',
    11: 'Lisää ainakin yksi pelialueen kuvakaappaus',
    12: 'Skinin linkki ei ole määritelty',
    20: 'Näyttää aika hyvältä',
    21: 'Jokainen ongelma on korjattu, hyvää työtä',
    22: 'Tarkistuslista',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skinit',
    1: 'Suositut',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Uudet',
    5: 'Random',
    6: 'Kaikki skinit',
    7: 'Kuvasuhde',
    8: 'Kaikki skinit | osu skinit',
    9: 'Skini | Skinit | Skinit',
    10: 'osu Skinit joissa {name} on tekijä | Kaikki skinit joiden tekijä on',
    11: 'Haku',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Muuta',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animaatio',
    5: 'Kuvakaappaukset',
    6: 'Vain pelialue',
    7: 'Lataa linkki | Lataa skini',
    8: 'Foorumi päivitys | osu! Foorumi',
    9: 'Reddit päivitys',
    10: 'Tekijät',
    11: 'Tägit',
    13: 'Videot',
    14: 'Uusi Versio | Hallitse Versioita',
    15: 'Päivitä | Lähetä',
    16: 'Pelimuodot',
    17: 'Skinin Nimi',
    18: 'Versio | Versiot',
    19: 'Koko',
    20: 'Metadata',
    21: 'Arvosana',
    22: 'Lataukset',
    23: 'Lataaminen on saatavilla pian',
    24: '{amount} sekunteja jäljellä',
    25: 'Sinä et ole yksi meistä',
    26: 'Näyttää siltä, että et ole tämän skinin tekijä tai muokkaaja',
    27: 'Skinin on tehnyt',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Paina tästä',
    1: 'tai vedä ja pudota kuvia tähän'
  },
  footer: {
    0: 'Tekijä: cyperdark',
    1: 'Kiitokset'
  },
  credits: {
    0: 'Chibi',
    1: 'Taiteet',
    2: 'Kuvakkeet',
    3: 'Kaikki kuvakkeet ovat sivulta {name}',
    4: 'Liput',
    5: 'Kaikki lippukuvakkeet ovat lähteestä {name}',
    6: 'Lokalisointi',
    7: 'Eikö kukaan? [{lang}]',
    8: 'Näyttää siltä, että cpol unohti lisätä ne. {text}'
  },
  search: {
    0: 'Skini haku',
    1: 'Katselukerrat',
    2: 'Otsikko',
    3: 'Arvosana',
    4: 'Koko',
    5: 'Päivämäärä',
    7: 'Mitään ei löytynyt',
    8: 'Yritä erilaisia hakuasetuksia',
    9: 'Odotetaan hakua',
    10: 'Valitse hakusuodattimet tai kirjoita skinin nimi, tekijä tai tägi',
    11: 'Lataukset',
    12: 'Nimi',
    13: {
      0: 'Skinit',
      1: 'Tägit',
      2: 'Users',
      3: 'Luettelot'
    }
  },
  tabs: {
    0: 'Haku',
    1: 'Muuta',
    2: 'Luettelo'
  },
  undefined: {
    0: 'Tyhjä',
    1: 'Valitettavasti täällä ei ole mitään, voit etsiä eri sivuja',
    2: 'Valitettavasti täällä ei ole mitään',
    3: 'Ei sallittu',
    4: 'Sinun täytyy olla kirjautuneena sisään muokataksesi tätä skiniä.',
    5: 'Sinun täytyy olla kirjautuneena lisätäksesi uuden skinin.'
  },
  meta: {
    title: {
      0: 'Löydä osu skinejä',
      1: 'Pelimodet, kuvasuhteet osu skinit',
      2: 'Suositut osu skinit',
      3: 'Hae osu skinejä',
      4: '«{name}» tägiluettelo',
      5: '{name} v{version} osu skini',
      6: 'Kiitokset',
      7: 'osu skinit',
      8: '{name} hae osu skinejä',
      9: 'Hanki inspiraatiota muista osu skineistä',
      10: '{name} tehtyjä osu skinejä',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Hanki parhaat osu skinit sivumme suuresta valikoimasta! Meillä on skinejä eri pelimodeille ja kuvasuhteille, sekä jopa top pelaajille. Lisäksi, meillä on erityinen osasto animefaneille. Paranna peliäsi täydellisellä skinillä. #osuskins #osugame #anime',
      1: '{views} näyttökertaa. {modes} osu skini, jonka koko on {size}, tekijänä on {creators}. Tukee {ratios}',
      2: 'Löydä täydellinen osu! skini meidän edistyneellä hakukoneella. Selaa meidän jättimäisen valikoiman läpi, joka on suodatettu pelimodella, kuvasuhteella, ja monella muulla. Tai, katso top pelaajien käyttämiä skinejä.',
      3: 'Löydä lukuisia skinejä eri pelimodeille ja kuvasuhteille sivultamme. Valitse standard, catch the beat, mania ja taiko modeista. Löydä täidellinen tyyli sinun pelaamismieltymyksille.',
      4: 'Löydä täydellinen osu skini top pelaajilta sivultamme. Selaa meidän suosittujen skinien kokoelmasta ja muokkaa pelitapasi. Löydä suuri määrä tyylejä ja teemoja mieltymyksillesi.',
      5: 'Olemassa olevien tägien ja osu skinien luettelo.',
      6: '{name} osu skini kokoelma!, ilmainen lataus.',
      7: 'Suuri määrä skinejä jotka {name} on tehnyt, lataa ilmaiseksi!',
      8: 'Kaikki skinit jotka {name} on tehnyt',
      9: 'Löydä inspiraatiota seuraavalle osu skinillesi nettisivultamme. Selaa meidän monipuolisen skini kokoelman läpi ja löydä uusia tapoja ja ideoita. Inspiroidu ja tee oma ainutlaatuinen skinisi.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Kirjaudu sisään',
    1: 'Kotisivu',
    profile_osu: 'osu! Profiili',
    new_skin: 'Uusi skini',
    notifications: 'Ilmoitukset',
    settings: 'Asetukset',
    logout: 'Kirjaudu ulos',
    load_more: 'Lataa lisää',
    copy_short: 'Kopioi lyhyt linkki',
    copied: 'Kopioitu',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Foorumi',
    skin_return: 'Takaisin skiniin'
  },
  user: {
    roles: {
      0: 'Tekijä',
      1: 'Miksaaja',
      2: 'Animaatiot',
      3: 'Taiteet',
      4: 'Yhteistyö'
    }
  },
  tooltips: {
    0: 'Katselukerrat: {amount}',
    1: 'Päivitä tulokset',
    2: 'Laskeva | Nouseva',
    3: 'Tykkäykset: {likes} / Disliket: {dislikes}',
    4: 'Paina ctrl+enter lisätäksesi tägin',
    5: 'Muokkaa versiota',
    6: '{s}Kirjaudu sisään{p} arvostellaksesi tämän skinin',
    7: 'Ei lyhyttä kuvausta',
    8: 'Ei url-osoitetta',
    9: 'Lataukset: {amount}'
  },
  lists: {
    screens: {
      0: 'Tervetuloa',
      1: 'Päävalikko',
      2: 'Kappaleen valinta',
      3: 'Mode valikko',
      4: 'Modit',
      5: 'Lähtölaskenta',
      6: 'Pelaaminen',
      7: 'Spinneri',
      8: 'Osion läpäisy',
      9: 'Osion epäonnistuminen',
      10: 'Taukonäyttö',
      11: 'Epäonnistumisnäyttö',
      12: 'Tulosnäyttö',
      13: 'Ohitus',
      14: 'Banneri'
    },
    cats: {
      0: 'NSFW',
      1: 'Turri',
      2: 'Sekoitus'
    }
  },
  select: {
    0: 'Uutta',
    1: 'Korjattu',
    2: 'Muutettu',
    3: 'Poistettu',
    4: 'Taide',
    5: 'Fontti',
    6: 'Artisti',
    7: 'Skinin tiedosto',
    8: 'Ääni/Sfx',
    9: 'Työkalut',
    views: 'Katselukerrat',
    likes: 'Tykkäykset',
    dislikes: 'Disliket',
    downloads: 'Lataukset',
    size_range: 'Valitse koko',
    date_range: 'Valitse ajanjakso',
    ratio: 'Valitse kuvasuhde | suhde'
  },
  placeholders: {
    0: 'Valitse roolit',
    1: 'Valitse versiot',
    2: 'Kirjoita...',
    3: 'Valitse koko',
    4: 'Valitse ajanjakso',
    5: 'Vuosi',
    6: 'Kuukausi',
    7: 'Valitse kuvasuhde',
    8: 'Valitse kategoriat',
    9: 'Pelimuodot',
    10: 'Valitse tyyppi',
    11: 'Liitä youtube-linkki',
    12: 'Kirjoita kuvaus ja url formaattina: description:url',
    13: 'Valitse lisät',
    14: 'Liitä linkki',
    15: 'Skinin otsikko, tekijä, tai tägi',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Osallistu' },
  nsfw: {
    0: 'Varoitus!',
    1: 'Tämä skini sisältää herkkää tai aikuisille tarkoitettua sisältöä',
    2: 'Tämä skini sisältää herkkää tai aikuisille tarkoitettua sisältöä, jota jotkut käyttäjät voivat pitää häiritsevänä',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Ei sallittu',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};