export default {
  title: {
    home: 'Koti',
    login: 'Kirjaudu sisään',
    lists: { 0: 'Luettelot' },
    tags: {
      0: 'Tägit',
      1: '{amount} tägiä kategoriassa {name}',
      2: 'Hae tagilla'
    },
    ideas: {
      0: 'Inspiraatio',
      1: '«{amount}»'
    },
    sounds: { 0: 'Äänet' },
    leaderboard: { 0: 'Tulostaulut' },
    extend: { 0: 'Enemmän | Vähemmän' },
    skin: {
      0: 'Tässä skinissä on käytetty tiedostoja muista skineistä',
      1: 'Klikkaa tästä saadaksesi lisää tietoa'
    },
    tools: 'Työkalut'
  },
  home: {
    0: 'Valmiina ladattavaksi',
    1: 'Eniten: _name_ skins',
    2: 'Katsotut | Tykätyt | Ladatut',
    3: 'Julkaise uusi skini',
    4: 'Miten asentaa skini',
    5: '{amount} Skiniä | {amount} Skiniä | {amount} Skiniä'
  },
  changelogs: {
    0: 'Muutosloki',
    1: 'Luettelo kaikista nykyiseen versioon tehdyistä muutoksista',
    2: 'Tyhjää Täällä',
    3: 'Mutta voit lisätä muutokset, jotka olet tehnyt tähän skinin versioon',
    4: 'Ei ryhmitelty',
    5: 'Uutta',
    6: 'Korjaukset',
    7: 'Muutokset',
    8: 'Poistot'
  },
  ideas: {
    0: 'Mitään ei löytynyt',
    1: '«{type}» kuvankaappauksia ei ole ladattu sivustolle'
  },
  creators: {
    0: 'Tekijät',
    1: 'Luettelo kaikista tekijöistä jotka olivat mukana tämän version tekemisessä',
    2: 'Täällä ei ole ketään',
    3: 'Pelaajan nimen etsiminen näyttää luettelon profiileista.',
    4: 'Muokkaaja',
    5: 'Roolit',
    6: 'Versiot'
  },
  tags: {
    0: 'Tägit',
    1: 'Luettelo kaikista tägeistä jotka liittyvät tähän skiniin',
    2: 'Täällä tuntuu tyhjältä.',
    3: 'Käytä yllä olevaa kenttää uusien tägien löytämiseen',
    4: 'Tunnisteita ei löytynyt',
    5: 'Yritä hakea jotain muuta',
    6: 'Haku'
  },
  videos: {
    0: 'Videot',
    1: 'Luettelo kaikista tämän skinin videoesittelyistä',
    2: 'Ei esittelyjä',
    3: 'Voit etsiä niitä YouTubesta tai tehdä oman esittelysi'
  },
  sources: {
    0: 'Resurssit',
    1: 'Luettelo käytetyistä muiden skinejen omaisuuksista tai työkaluista tässä versiossa',
    2: 'Vähän tyhjää täällä',
    3: 'Jos olet käyttänyt elementtejä muista skineistä, varmista että lisäät ne ylläolevaan laatikkoon',
    4: 'Ei ryhmitelty'
  },
  checks: {
    0: 'Kaikki',
    1: 'Metadata',
    2: 'Korosta',
    3: 'Skinin nimeä ei ole määritelty',
    4: 'Lisää ainakin yksi skinin tekijä',
    5: 'Lisää muutama tägi',
    6: 'Skinin koko ei ole määritelty',
    7: 'Valitse ainakin yksi pelimode',
    8: 'Valitse tiedoston tyyppi (SD tai HD)',
    9: 'Valitse ainakin yksi kuvasuhde',
    10: 'Ei annettuja kuvakaappauksia',
    11: 'Lisää ainakin yksi pelialueen kuvakaappaus',
    12: 'Skinin linkki ei ole määritelty',
    20: 'Hyvältä näyttää',
    21: 'Jokainen ongelma korjattiin. Hyvää työtä!',
    22: 'Tarkistuslista',
    23: 'Lisää vähintään yksi julkinen versio',
    24: 'Lisää tähän versioon vähintään yksi tekijä',
    25: 'Joillekin tekijöille ei ole valittu rooleja'
  },
  skins: {
    0: 'Skinit',
    1: 'Suositut',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Uudet',
    5: 'Random',
    6: 'Kaikki skinit',
    7: 'Kuvasuhde',
    8: 'Kaikki skinit | osu skinit',
    9: 'Skini | Skinit | Skinit',
    10: 'osu Skinit joissa {name} on tekijä | Kaikki skinit joiden tekijä on',
    11: 'Haku',
    12: '{name} skinit',
    13: 'Tutki skinejä'
  },
  skin: {
    0: 'Muuta',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animaatio',
    5: 'Kuvakaappaukset',
    6: 'Vain pelialue',
    7: 'Lataa linkki | Lataa skini',
    8: 'Foorumi päivitys | osu! Foorumi',
    9: 'Reddit päivitys',
    10: 'Tekijät',
    11: 'Tägit',
    13: 'Videot',
    14: 'Uusi Versio | Hallitse Versioita',
    15: 'Päivitä | Lähetä',
    16: 'Pelimuodot',
    17: 'Skinin Nimi',
    18: 'Versio | Versiot',
    19: 'Koko',
    20: 'Metadata',
    21: 'Arvosana',
    22: 'Lataukset',
    23: 'Lataaminen on saatavilla pian',
    24: '{amount} sekunteja jäljellä',
    25: 'Sinä et ole yksi meistä',
    26: 'Näyttää siltä, että et ole tämän skinin tekijä tai muokkaaja',
    27: 'Skinin on tehnyt',
    28: 'Ei tunnisteita',
    29: 'Ei videoita',
    30: 'Ei tekijöitä',
    31: 'Arvostele skini',
    32: 'Tykkää ja kommentoi Redditissä',
    33: 'Kommentoi osu!-foorumilla',
    34: 'Lisää skinejä tältä tekijältä | Lisää skinejä näiltä tekijöiltä',
    35: 'Tue skiniä',
    36: 'Ei saatavilla',
    37: 'Valitettavasti tämä skini on poistettu tekijän {author} pyynnöstä',
    38: 'Tervetuloa skinin julkaisueditoriin!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Onnittelut!',
    44: 'You have successfully finished the tutorial, have fun!'
  },
  drag: {
    0: 'Paina tästä',
    1: 'tai vedä ja pudota kuvia tähän'
  },
  footer: {
    0: 'Tekijä: cyperdark',
    1: 'Kiitokset',
    2: 'Säännöt',
    3: 'Yhteystiedot'
  },
  credits: {
    0: 'Chibi',
    1: 'Taiteet',
    2: 'Kuvakkeet',
    3: 'Kaikki kuvakkeet ovat sivulta {name}',
    4: 'Liput',
    5: 'Kaikki lippukuvakkeet ovat lähteestä {name}',
    6: 'Lokalisointi',
    7: 'Eikö ketään? [{lang}]',
    8: 'Näyttää siltä, että cpol unohti lisätä heidät. {text}'
  },
  search: {
    0: 'Skini haku',
    1: 'Katselukerrat',
    2: 'Otsikko',
    3: 'Arvosana',
    4: 'Koko',
    5: 'Päivämäärä',
    7: 'Mitään ei löytynyt',
    8: 'Kokeile käyttää eri hakusuodattimia',
    9: 'Odotetaan hakua',
    10: 'Käytä hakusuodattimia tai kirjoita skinin otsikko, tekijä tai tunnisteet',
    11: 'Lataukset',
    12: 'Nimi',
    13: {
      0: 'Skinit',
      1: 'Tägit',
      2: 'Käyttäjät',
      3: 'Luettelot'
    },
    14: 'Haku:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Valmistellaan',
    4: 'Äänestys',
    5: 'Valmis'
  },
  tabs: {
    0: 'Haku',
    1: 'Muuta',
    2: 'Luettelo'
  },
  undefined: {
    0: 'Tyhjä',
    1: 'Valitettavasti täällä ei ole mitään, mutta voit kurkata muille sivuille',
    2: 'Valitettavasti täällä ei ole mitään',
    3: 'Ei sallittu',
    4: 'Sinun täytyy olla kirjautuneena sisään muokataksesi tätä skiniä.',
    5: 'Sinun täytyy olla kirjautuneena sisään lisätäksesi uuden skinin.'
  },
  meta: {
    title: {
      0: 'Löydä osu skinejä',
      1: 'Pelimodet, kuvasuhteet osu skinit',
      2: 'Suositut osu skinit',
      3: 'Hae osu skinejä',
      4: '«{name}» tägiluettelo',
      5: '{name} v{version} osu skini',
      6: 'Kiitokset',
      7: 'osu skinit',
      8: '{name} hae osu skinejä',
      9: 'Hanki inspiraatiota muista osu skineistä',
      10: '{name} tehtyjä osu skinejä',
      11: 'Hae tagilla',
      12: '{name} found tags',
      13: 'Uusi skini',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! Contests'
    },
    description: {
      0: 'Hanki parhaat osu skinit sivumme suuresta valikoimasta! Meillä on skinejä eri pelimodeille ja kuvasuhteille, sekä jopa top pelaajille. Lisäksi, meillä on erityinen osasto animefaneille. Paranna peliäsi täydellisellä skinillä. #osuskins #osugame #anime',
      1: '{views} näyttökertaa. {modes} osu skini, jonka koko on {size}, tekijänä on {creators}. Tukee {ratios}',
      2: 'Löydä täydellinen osu! skini meidän edistyneellä hakukoneella. Selaa meidän jättimäisen valikoiman läpi, joka on suodatettu pelimodella, kuvasuhteella, ja monella muulla. Tai, katso top pelaajien käyttämiä skinejä.',
      3: 'Löydä lukuisia skinejä eri pelimodeille ja kuvasuhteille sivultamme. Valitse standard, catch the beat, mania ja taiko modeista. Löydä täidellinen tyyli sinun pelaamismieltymyksille.',
      4: 'Löydä täydellinen osu skini top pelaajilta sivultamme. Selaa meidän suosittujen skinien kokoelmasta ja muokkaa pelitapasi. Löydä suuri määrä tyylejä ja teemoja mieltymyksillesi.',
      5: 'Olemassa olevien tägien ja osu skinien luettelo.',
      6: '{name} osu skini kokoelma!, ilmainen lataus.',
      7: 'Suuri määrä skinejä jotka {name} on tehnyt, lataa ilmaiseksi!',
      8: 'Kaikki skinit jotka {name} on tehnyt',
      9: 'Löydä inspiraatiota seuraavalle osu skinillesi nettisivultamme. Selaa meidän monipuolisen skini kokoelman läpi ja löydä uusia tapoja ja ideoita. Inspiroidu ja tee oma ainutlaatuinen skinisi.',
      10: 'Search for tags among all the tags on the site.',
      11: 'Luettelo kaikista aktiivisista/päättyneistä osu! -kilpailuista',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Kirjaudu sisään',
    1: 'Kotisivu',
    profile_osu: 'osu! Profiili',
    new_skin: 'Uusi skini',
    notifications: 'Ilmoitukset',
    settings: 'Asetukset',
    logout: 'Kirjaudu ulos',
    load_more: 'Lataa lisää',
    copy_short: 'Kopioi lyhyt linkki',
    copied: 'Kopioitu',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Foorumi',
    skin_return: 'Takaisin skiniin',
    source: 'Lähde',
    contest_voting: 'Vote here'
  },
  choose: {
    0: 'Optional',
    1: 'Pakollinen',
    2: 'Valitse vähintään yksi vaihtoehto'
  },
  user: {
    roles: {
      0: 'Tekijä',
      1: 'Miksaaja',
      2: 'Animaatiot',
      3: 'Taiteet',
      4: 'Yhteistyö'
    }
  },
  tooltips: {
    0: 'Katselukerrat: {amount}',
    1: 'Päivitä tulokset',
    2: 'Laskeva | Nouseva',
    3: 'Tykkäykset: {likes} / Disliket: {dislikes}',
    4: 'Paina ctrl+enter lisätäksesi tägin',
    5: 'Muokkaa versiota',
    6: '{s}Kirjaudu sisään{p} arvostellaksesi tämän skinin',
    7: 'Ei lyhyttä kuvausta',
    8: 'Ei url-osoitetta',
    9: 'Lataukset: {amount}',
    10: 'Nollaa kaikki',
    11: 'Näytä ohje',
    12: 'Sulje ohje',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)'
  },
  lists: {
    screens: {
      0: 'Tervetuloa',
      1: 'Päävalikko',
      2: 'Kappaleen valinta',
      3: 'Mode valikko',
      4: 'Modit',
      5: 'Lähtölaskenta',
      6: 'Pelaaminen',
      7: 'Spinneri',
      8: 'Osion läpäisy',
      9: 'Osion epäonnistuminen',
      10: 'Taukonäyttö',
      11: 'Epäonnistumisnäyttö',
      12: 'Tulosnäyttö',
      13: 'Ohitus',
      14: 'Banneri',
      15: 'Result screen (bottom)'
    },
    cats: {
      0: 'NSFW',
      1: 'Turri',
      2: 'Sekoitus'
    }
  },
  select: {
    0: 'Uutta',
    1: 'Korjattu',
    2: 'Muutettu',
    3: 'Poistettu',
    4: 'Taide',
    5: 'Fontti',
    6: 'Artisti',
    7: 'Skinin tiedosto',
    8: 'Ääni/Sfx',
    9: 'Työkalut',
    views: 'Katselukerrat',
    likes: 'Tykkäykset',
    dislikes: 'Disliket',
    downloads: 'Lataukset',
    size_range: 'Valitse koko',
    date_range: 'Valitse ajanjakso',
    ratio: 'Valitse kuvasuhde | suhde'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Valitse versiot',
    2: 'Kirjoita jotain...',
    3: 'Valitse koko',
    4: 'Valitse ajanjakso',
    5: 'Vuosi',
    6: 'Kuukausi',
    7: 'Valitse kuvasuhde',
    8: 'Valitse kategoriat',
    9: 'Pelimuodot',
    10: 'Valitse tyyppi',
    11: 'Liitä youtube-linkki',
    12: 'Kirjoita kuvaus ja URL-osoite muodossa kuvaus:url',
    13: 'Valitse lisät',
    14: 'Liitä linkki',
    15: 'Skinin otsikko, tekijä, tai tunnisteet',
    16: 'Valitse kategoria',
    17: 'Kirjoita tunnisteen nimi'
  },
  contribute: { 0: 'Osallistu' },
  nsfw: {
    0: 'Varoitus, nsfw!',
    1: 'Tämä skini sisältää herkkää tai aikuisille tarkoitettua sisältöä',
    2: 'Tämä skini sisältää herkkää tai aikuisille tarkoitettua sisältöä, jota jotkut käyttäjät voivat pitää häiritsevänä',
    3: 'Selvä',
    4: 'Heippa o/',
    5: 'Turrivaroitus!'
  },
  removed: {
    0: 'Versio ei ole saatavilla',
    1: 'Skinin tekijä päätti poistaa tämän version sivustolta.',
    2: 'Vaihda saatavilla olevaan versioon'
  },
  notify: {
    0: 'Ongelmia ei korjattu',
    1: 'Kaikkia vaadittuja kenttiä ei ole täytetty',
    2: 'Näytä',
    3: 'Ei löydetty',
    4: 'Banneria ei löytynyt (Tällä hetkellä ensimmäistä näyttökuvaa käytetään bannerina)',
    5: 'Ei muutoksia',
    6: 'Muutoksia ei löytynyt',
    7: 'ID not found',
    8: 'Videon ID:tä ei löydy, kokeile toista linkkiä (tällä hetkellä vain YouTube on tuettu)',
    9: 'Hups',
    10: 'Näyttää siltä, että istuntosi on vanhentunut. Avaa uusi sivu ja kirjaudu tilillesi (Älä huoli, kaikki tallennettiin automaattisesti)',
    11: 'On olemassa',
    12: 'Tämä video on jo lisätty',
    13: 'On olemassa',
    14: 'Tämä tagi on jo lisätty',
    15: 'Ei löydetty',
    16: 'Et voi poistaa poistettua tägiä',
    17: 'Lisätty',
    18: 'Olet lisännyt uuden tägin onnistuneesti',
    19: 'Hups',
    20: 'Tämä tekijä on jo lisätty',
    21: 'EZ',
    22: 'Uusi tekijä on lisätty',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Kaksoiskappale',
    26: 'Tämä muutos on lisätty jo aiemmin.',
    27: 'Kaksoiskappale',
    28: 'Tämä URL-osoite on jo lisätty aiemmin.',
    29: 'Varoitus',
    30: 'Olet unohtanut lisätä kuvauksen URL-osoitteelle. Esimerkki: Kuvaus:url',
    31: 'Varoitus',
    32: 'Unohdit lisätä URL-osoitteen kuvaukselle. Esimerkki: Kuvaus:url',
    33: 'Palautettu',
    34: 'Versio «{name}» on palautettu',
    35: 'Poistettu',
    36: 'Versio «{name}» on poistettu',
    37: 'Virhe',
    38: 'Ilmeisesti palvelimen mielestä olet robotti.',
    39: 'Näyttää siltä, että istuntosi on vanhentunut. Avaa uusi sivu ja kirjaudu tilillesi (Älä huoli, kaikki tallennettiin automaattisesti)',
    40: 'Ristiriitaiset kirjautumistiedot (kirjaudu sisään uudelleen. Älä huoli, kaikki tallennettiin automaattisesti)',
    41: 'Tuntematon virhe',
    42: 'Et voi muokata olematonta skiniä',
    43: 'Näyttää siltä, ettei sinulla ole oikeutta muokata tätä skiniä',
    44: 'Et voi lähettää tätä versiota, koska se on sama kuin edellinen versio.',
    45: 'Nämä muutokset on jo lähetetty tarkistettavaksi',
    46: 'Onnistui',
    47: 'Uudet muutokset on lähetetty tarkistettavaksi',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'Tätä linkkiä ei voi käyttää latauslinkkinä',
    51: 'Lähetetty tarkistettavaksi',
    52: 'Varoitus',
    53: 'You need to choose type of asset'
  },
  header: {
    0: 'Ilmoitukset',
    1: 'Seuraa meitä näillä alustoilla saadaksesi ilmoituksia uusista skineistä'
  },
  restricted_view: {
    0: 'Ei sallittu',
    1: 'Kirjaudu sisään tilillesi',
    2: 'Rajoitettu näkymä',
    3: 'Tätä sivua ei ole julkaistu, vielä.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Kyllä',
    4: 'Ei'
  }
};