export default {
  title: {
    home: 'Accueil',
    login: 'Connexion',
    lists: { 0: 'Listes' },
    tags: {
      0: 'Tags',
      1: '{amount} tags pour la catégorie {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiration',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sons' },
    leaderboard: { 0: 'Classements' },
    extend: { 0: 'Plus | Moins' },
    skin: {
      0: 'Ce skin contient des éléments provenant d\'autres skins',
      1: 'Cliquez ici pour plus d\'informations'
    },
    tools: 'Outils'
  },
  changelogs: {
    0: 'Journal des modifications',
    1: 'Liste de toutes les modifications effectuées dans la version actuelle',
    2: 'Il n\'y a rien à voir ici',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Non groupé',
    5: 'Nouveau',
    6: 'Correctifs',
    7: 'Changements',
    8: 'Suppressions'
  },
  ideas: {
    0: 'Rien n\'a été trouvé',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Créateurs',
    1: 'Liste de tous les créateurs impliqués dans la création de cette version',
    2: 'Il n\'y a personne ici',
    3: 'Chercher le nom d\'un joueur affichera une liste de profils.',
    4: 'Editeur',
    5: 'Rôles',
    6: 'Versions'
  },
  tags: {
    0: 'Tags',
    1: 'Liste de tous les tags liés à ce skin',
    2: 'Ca m\'a l\'air vide ici.',
    3: 'Utilisez le champ ci-dessus pour trouver de nouveaux tags',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Rechercher'
  },
  videos: {
    0: 'Vidéos',
    1: 'Liste de toutes les videos de démonstration de ce skin',
    2: 'Aucune vidéo de démonstration disponible',
    3: 'Recherchez en sur YouTube ou créez votre propre vidéo de démonstration'
  },
  sources: {
    0: 'Attribution',
    1: 'Liste de tous les outils ou éléments utilisés dans cette version du skin',
    2: 'C\'est un peu vide ici',
    3: 'Si vous avez utilisé des assets d\'autres skins ou d\'oeuvres qui ne vous appartiennent pas, ajoutez les dans le champ ci-dessus',
    4: 'Non groupé'
  },
  checks: {
    0: 'Tout',
    1: 'Métadonnées',
    2: 'Points forts',
    3: 'Name of the skin not specified',
    4: 'Ajoutez au moins un créateur',
    5: 'Ajoutez quelques tags',
    6: 'Taille du skin non spécifiée',
    7: 'Sélectionnez au moins un mode de jeu',
    8: 'Sélectionnez un type de fichier (SD ou HD)',
    9: 'Sélectionnez au moins un format d\'image',
    10: 'Aucune capture d\'écran n\'a été fournie',
    11: 'Ajoutez au moins une capture d\'écran du gameplay',
    12: 'Le lien au skin n\'est pas spécifié',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Liste de contrôle',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Populaire',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Récent',
    5: 'Aléatoire',
    6: 'Tous les skins',
    7: 'Format d\'image',
    8: 'Tous les skins | skins osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins osu par {name} | Tous les skins de',
    11: 'Rechercher',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Editer',
    1: 'En plus',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Captures d\'écran',
    6: 'Gameplay uniquement',
    7: 'Lien de téléchargement | Télécharger le skin',
    8: 'Post du forum | Forum osu!',
    9: 'Post de Reddit',
    10: 'Créateurs',
    11: 'Tags',
    13: 'Vidéos',
    14: 'Nouvelle Version | Gérer les versions',
    15: 'Mettre à Jour | Envoyer',
    16: 'Modes de jeu',
    17: 'Nom du skin',
    18: 'Version | Versions',
    19: 'Taille',
    20: 'Métadonnées',
    21: 'Note',
    22: 'Téléchargements',
    23: 'Le Téléchargement sera disponible bientôt',
    24: '{amount} secondes restantes',
    25: 'Vous n\'êtes pas l\'un d\'entre nous',
    26: 'On dirait que vous n\'êtes pas un créateur ou un éditeur de ce skin',
    27: 'Skin fait par',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Cliquez ici',
    1: 'ou glissez-déposez les images'
  },
  footer: {
    0: 'Fait par cyperdark',
    1: 'Crédits'
  },
  credits: {
    0: 'Chibi',
    1: 'Œuvres',
    2: 'Icones',
    3: 'Toutes les icônes proviennent de {name}',
    4: 'Drapeaux',
    5: 'Tous les drapeaux proviennent de {name}',
    6: 'Traductions',
    7: 'Quelqu\'un ? [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Rechercher un skin',
    1: 'Vues',
    2: 'Titre',
    3: 'Note',
    4: 'Taille',
    5: 'Date',
    7: 'Rien n\'a été trouvé',
    8: 'Try using different search filters',
    9: 'en attente d\'une requête',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Téléchargements',
    12: 'Nom',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Users',
      3: 'Listes'
    }
  },
  tabs: {
    0: 'Rechercher',
    1: 'Editer',
    2: 'Liste'
  },
  undefined: {
    0: 'Vide',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Non autorisé',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Découvrez des skins osu',
      1: 'Skins spécifiques à des modes de jeu ou formats d\'image ',
      2: 'Skins osu populaires',
      3: 'Rechercher des skins osu',
      4: 'liste des tags de «{name}» ',
      5: 'skin osu {name} v{version}',
      6: 'Crédits',
      7: 'skins osu',
      8: '{name} recherche de skin osu',
      9: 'Inspirez-vous des autres skins osu',
      10: 'Skins faits par {name}',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Trouvez les meilleurs skins d\'osu! sur notre site ! Notre gigantesque librairie possède des skins pour tous les modes de jeu, formats d\'image, et même ceux des top players. En plus, nous avons une section spéciale pour les fans d\'animé. Améliorez votre gameplay avec le meilleur skin.#osuskins #osugame #anime',
      1: '{views} vues. Un skin osu pour {modes}, sa taille est de {size}, créé par {creators}. Supporte le {ratios}',
      2: 'Trouvez le skin osu! parfait avec notre fonctionnalité de recherche avancée. Naviguez dans notre gigantesque librarie, filtrée par mode de jeu, format d\'image et plus. Ou regardez nos skins utilisés par des top players',
      3: 'Découvrez une variété de skins pour différents modes de jeux et de formats d\\\'image sur notre site. Choisissez entre standard, catch the beat, mania et taiko. Trouvez l\'ajustement parfait pour vos préférences vidéo-ludiques.',
      4: 'Trouvez le skin osu parfait des top players sur notre site. Naviguez dans notre collection de skins populaires et customisez votre gameplay. découvrez un large panel de styles et de thèmes qui conviendront à vos préférences',
      5: 'Liste des tags existants pour les skins osu.',
      6: '{name} collection de skin osu!, Téléchargement gratuit',
      7: 'Un énorme montant de skins pour un{name}, Téléchargez gratuitement!',
      8: 'Tous les skins osu! Créés par {name}',
      9: 'Trouvez l\'inspiration pour votre prochain skin osu! sur notre site. Naviguez dans une collection de skins variés et découvrez de nouvelles techniques et idées. Inspirez vous et créez vos skins uniques',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Se connecter',
    1: 'Page d\'accueil',
    profile_osu: 'Profil osu! ',
    new_skin: 'Nouveau skin',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Se déconnecter',
    load_more: 'Charger plus',
    copy_short: 'Copier le lien raccourci',
    copied: 'Copié',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Retour au skin'
  },
  user: {
    roles: {
      0: 'Créateur',
      1: 'Mixeur',
      2: 'Animations',
      3: 'Œuvres',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Vues : {amount}',
    1: 'Rafraîchir les résultats',
    2: 'Décroissant | Croissant',
    3: 'J\'aime : {likes} / Je n\'aime pas : {dislikes}',
    4: 'Appuyez sur ctrl+entrée pour ajouter un tag',
    5: 'Editer la version',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Pas de desctiption courte',
    8: 'pas d\'url',
    9: 'Téléchargements : {amount}'
  },
  lists: {
    screens: {
      0: 'Bienvenue',
      1: 'Menu principal',
      2: 'Sélection des musiques',
      3: 'Menu des modes',
      4: 'Mods',
      5: 'Compte à rebours',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section réussie',
      9: 'Section échouée',
      10: 'Ecran de pause',
      11: 'Ecran d\'échec ',
      12: 'Ecran des résultats',
      13: 'Passer',
      14: 'Bannière'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixé'
    }
  },
  select: {
    0: 'Nouveau',
    1: 'Corrigé',
    2: 'Modifié',
    3: 'Supprimé',
    4: 'Oeuvres',
    5: 'Police d\'écriture',
    6: 'Artiste',
    7: 'Element du skin',
    8: 'Audio/Sfx',
    9: 'Outils',
    views: 'Vues',
    likes: 'J\'aime',
    dislikes: 'Je n\'aime pas',
    downloads: 'Téléchargements',
    size_range: 'Sélectionnez la taille',
    date_range: 'Sélectionnez la plage de dates',
    ratio: 'Sélectionnez un format d\'image | Format dimage'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Sélectionnez la taille',
    4: 'Sélectionnez la plage de dates',
    5: 'Année',
    6: 'Mois',
    7: 'Sélectionnez un format d\'image',
    8: 'Sélectionnez les catégories',
    9: 'Modes de jeu',
    10: 'Sélectionnez le type',
    11: 'Copiez un lien YouTube',
    12: 'Type a description and an url. Format description:url',
    13: 'Sélectionnez des suppléments',
    14: 'Copiez un lien',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribuer' },
  nsfw: {
    0: 'Attention !',
    1: 'Ce skin contient du contenu sensible ou pour adultes',
    2: 'Ce skin contient du contenu sensible ou pour adultes qui peuvent déranger certains utilisateurs',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation'
  },
  restricted_view: {
    0: 'Non autorisé',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};