export default {
  title: {
    home: 'Accueil',
    login: 'Connexion',
    lists: { 0: 'Listes' },
    tags: {
      0: 'Tags',
      1: '{amount} tags pour la catégorie {name}',
      2: 'Tags de recherche'
    },
    ideas: {
      0: 'Inspiration',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sons' },
    leaderboard: { 0: 'Classements' },
    extend: { 0: 'Plus | Moins' },
    skin: {
      0: 'Ce skin contient des éléments provenant d\'autres skins',
      1: 'Cliquez ici pour plus d\'informations'
    },
    tools: 'Outils'
  },
  home: {
    0: 'Téléchargeables',
    1: 'Skin les plus : _name_',
    2: 'Vus | Aimés | Téléchargés',
    3: 'Publier un nouveau skin',
    4: 'Comment installer un skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Journal des modifications',
    1: 'Liste de toutes les modifications effectuées dans la version actuelle',
    2: 'Il n\'y a rien à voir ici',
    3: 'Mais vous pouvez ajouter les changements que vous aviez faits à cette version du skin',
    4: 'Non groupé',
    5: 'Nouveau',
    6: 'Correctifs',
    7: 'Changements',
    8: 'Suppressions'
  },
  ideas: {
    0: 'Rien n\'a été trouvé',
    1: 'Les captures d\'écrans de « {type} » n\'ont pas été envoyés sur le site'
  },
  creators: {
    0: 'Créateurs',
    1: 'Liste de tous les créateurs impliqués dans la création de cette version',
    2: 'Il n\'y a personne ici',
    3: 'Chercher le nom d\'un joueur affichera une liste de profils.',
    4: 'Editeur',
    5: 'Rôles',
    6: 'Versions'
  },
  tags: {
    0: 'Tags',
    1: 'Liste de tous les tags liés à ce skin',
    2: 'Ca m\'a l\'air vide ici.',
    3: 'Utilisez le champ ci-dessus pour trouver de nouveaux tags',
    4: 'Tags introuvables',
    5: 'Essayez de rechercher autre chose',
    6: 'Rechercher'
  },
  videos: {
    0: 'Vidéos',
    1: 'Liste de toutes les videos de démonstration de ce skin',
    2: 'Aucune vidéo de démonstration disponible',
    3: 'Recherchez en sur YouTube ou créez votre propre vidéo de démonstration'
  },
  sources: {
    0: 'Attribution',
    1: 'Liste de tous les outils ou éléments utilisés dans cette version du skin',
    2: 'C\'est un peu vide ici',
    3: 'Si vous avez utilisé des assets d\'autres skins ou d\'oeuvres qui ne vous appartiennent pas, ajoutez les dans le champ ci-dessus',
    4: 'Non groupé'
  },
  checks: {
    0: 'Tout',
    1: 'Métadonnées',
    2: 'Points forts',
    3: 'Nom du skin non spécifié',
    4: 'Ajoutez au moins un créateur',
    5: 'Ajoutez quelques tags',
    6: 'Taille du skin non spécifiée',
    // 7: 'Select at least one gamemode',
    8: 'Sélectionnez un type de fichier (SD ou HD)',
    9: 'Sélectionnez au moins un format d\'image',
    10: 'Aucune capture d\'écran n\'a été fournie',
    11: 'Ajoutez au moins une capture d\'écran du gameplay',
    12: 'Le lien au skin n\'est pas spécifié',
    20: 'Tout se porte bien',
    21: 'Chaque problème a été résolu. Bon travail !',
    22: 'Liste de contrôle',
    23: 'Ajoutez au moins une version publique',
    24: 'Ajouter au moins un créateur à cette version',
    25: 'Certains créateurs n\'ont pas de rôles',
    26: '{amount} screenshots doesn\'t have category'
  },
  skins: {
    0: 'Skins',
    1: 'Populaire',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Récent',
    5: 'Aléatoire',
    6: 'Tous les skins',
    7: 'Format d\'image',
    8: 'Tous les skins | skins osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins osu par {name} | Tous les skins de',
    11: 'Rechercher',
    12: 'skins {name}',
    13: 'Explorer les skins'
  },
  skin: {
    0: 'Editer',
    1: 'En plus',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Captures d\'écran',
    6: 'Gameplay uniquement',
    7: 'Lien de téléchargement | Télécharger le skin',
    8: 'Post du forum | Forum osu!',
    9: 'Post de Reddit',
    10: 'Créateurs',
    11: 'Tags',
    13: 'Vidéos',
    14: 'Nouvelle Version | Gérer les versions',
    15: 'Mettre à Jour | Envoyer',
    16: 'Modes de jeu',
    17: 'Nom du skin',
    18: 'Version | Versions',
    19: 'Taille',
    20: 'Métadonnées',
    21: 'Note',
    22: 'Téléchargements',
    23: 'Le Téléchargement sera disponible bientôt',
    24: '{amount} secondes restantes',
    25: 'Vous n\'êtes pas l\'un d\'entre nous',
    26: 'On dirait que vous n\'êtes pas un créateur ou un éditeur de ce skin',
    27: 'Skin fait par',
    28: 'Aucun tag',
    29: 'Aucune vidéo',
    30: 'Aucun créateur',
    31: 'Noter le skin',
    32: 'Voter & commenter sur Reddit',
    33: 'Commenter sur le forum d\'osu!',
    34: 'Plus de skins de cet auteur | Plus de skins de ces auteurs',
    35: 'Soutenir le skin',
    36: 'Indisponible',
    37: 'Malheureusement, ce skin a été supprimé suite à une demande de {author}',
    38: 'Bienvenue dans l\'éditeur de post de skin !',
    39: `Nouveau dans l'éditeur de skin ? Laissez-nous vous guider à travers l'interface et vous montrer le plein potentiel de l'éditeur !`,
    40: '{current} de {max} terminées',
    41: 'Voir plus tard',
    42: `Commençons`,
    43: 'Félicitations !',
    44: 'Vous avez terminé le tutoriel avec succès, amusez-vous !',
    45: 'uploader'
  },
  drag: {
    0: 'Cliquez ici',
    1: 'ou glissez-déposez les images'
  },
  footer: {
    0: 'Fait par cyperdark',
    1: 'Crédits',
    2: 'Règles',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Œuvres',
    2: 'Icones',
    3: 'Toutes les icônes proviennent de {name}',
    4: 'Drapeaux',
    5: 'Tous les drapeaux proviennent de {name}',
    6: 'Traductions',
    7: 'Quelqu\'un ? [{lang}]',
    8: 'On dirait que cyperdark a oublié de le(s) rajouter. {text}'
  },
  search: {
    0: 'Rechercher un skin',
    1: 'Vues',
    2: 'Titre',
    3: 'Note',
    4: 'Taille',
    5: 'Date',
    7: 'Rien n\'a été trouvé',
    8: 'Essayez d\'utiliser d\'autres filtres de recherche',
    9: 'en attente d\'une requête',
    10: 'Utilisez les filtres de recherche ou tapez le titre, l\'auteur ou les tags du skin',
    11: 'Téléchargements',
    12: 'Nom',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Utilisateurs',
      3: 'Listes'
    },
    14: 'Rechercher :'
  },
  contests: {
    0: 'Concours',
    1: 'Article officiel',
    2: 'Soumission',
    3: 'Préparation',
    4: 'Vote en cours',
    5: 'Terminé'
  },
  rules: {
    0: 'Dernière mise à jour le',
    1: 'Guide pour la publication des Skins'
  },
  tabs: {
    0: 'Rechercher',
    1: 'Editer',
    2: 'Liste'
  },
  undefined: {
    0: 'Vide',
    1: 'Malheureusement, il n\'y a rien ici, mais vous pouvez jeter un coup d\'œil aux autres pages',
    2: 'Malheureusement, il n\'y a rien ici',
    3: 'Non autorisé',
    4: 'Vous devez vous connecter afin d\'éditer ce skin.',
    5: 'Vous devez vous connecter afin d\'ajouter un nouveau skin.'
  },
  meta: {
    title: {
      0: 'Découvrez des skins osu',
      1: 'Skins spécifiques à des modes de jeu ou formats d\'image ',
      2: 'Skins osu populaires',
      3: 'Rechercher des skins osu',
      4: 'liste des tags de «{name}» ',
      5: 'skin osu {name} v{version}',
      6: 'Crédits',
      7: 'skins osu',
      8: '{name} recherche de skin osu',
      9: 'Inspirez-vous des autres skins osu',
      10: 'Skins faits par {name}',
      11: 'Tags de recherche',
      12: 'tags {name} trouvés',
      13: 'Nouveau skin',
      14: 'Règles du site',
      15: 'Concours osu!',
      16: 'Concours osu!'
    },
    description: {
      0: 'Trouvez les meilleurs skins d\'osu! sur notre site ! Notre gigantesque librairie possède des skins pour tous les modes de jeu, formats d\'image, et même ceux des top players. En plus, nous avons une section spéciale pour les fans d\'animé. Améliorez votre gameplay avec le meilleur skin.#osuskins #osugame #anime',
      1: '{views} vues. Un skin osu pour {modes}, sa taille est de {size}, créé par {creators}. Supporte le {ratios}',
      2: 'Trouvez le skin osu! parfait avec notre fonctionnalité de recherche avancée. Naviguez dans notre gigantesque librarie, filtrée par mode de jeu, format d\'image et plus. Ou regardez nos skins utilisés par des top players',
      3: 'Découvrez une variété de skins pour différents modes de jeux et de formats d\\\'image sur notre site. Choisissez entre standard, catch the beat, mania et taiko. Trouvez l\'ajustement parfait pour vos préférences vidéo-ludiques.',
      4: 'Trouvez le skin osu parfait des top players sur notre site. Naviguez dans notre collection de skins populaires et customisez votre gameplay. découvrez un large panel de styles et de thèmes qui conviendront à vos préférences',
      5: 'Liste des tags existants pour les skins osu.',
      6: '{name} collection de skin osu!, Téléchargement gratuit',
      7: 'Un énorme montant de skins pour un{name}, Téléchargez gratuitement!',
      8: 'Tous les skins osu! Créés par {name}',
      9: 'Trouvez l\'inspiration pour votre prochain skin osu! sur notre site. Naviguez dans une collection de skins variés et découvrez de nouvelles techniques et idées. Inspirez vous et créez vos skins uniques',
      10: 'Recherchez des tags parmi tous les tags du site.',
      11: 'Liste de tous les concours osu! actifs/terminés',
      12: '{amount} entrées pour le concours {title}. {views} vues'
    }
  },
  buttons: {
    0: 'Se connecter',
    1: 'Page d\'accueil',
    profile_osu: 'Profil osu! ',
    new_skin: 'Nouveau skin',
    notifications: 'Notifications',
    settings: 'Paramètres',
    logout: 'Se déconnecter',
    load_more: 'Charger plus',
    copy_short: 'Copier le lien raccourci',
    copied: 'Copié',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Retour au skin',
    source: 'Source',
    contest_voting: 'Votez ici',
    rules_agree: 'J\'accepte'
  },
  choose: {
    0: 'Facultatif',
    1: 'Obligatoire',
    2: 'Choisissez au moins une option'
  },
  user: {
    roles: {
      0: 'Créateur',
      1: 'Mixeur',
      2: 'Animations',
      3: 'Œuvres',
      4: 'Collab',
      5: 'Sons'
    }
  },
  tooltips: {
    0: 'Vues : {amount}',
    1: 'Rafraîchir les résultats',
    2: 'Décroissant | Croissant',
    3: 'J\'aime : {likes} / Je n\'aime pas : {dislikes}',
    4: 'Appuyez sur ctrl+entrée pour ajouter un tag',
    5: 'Editer la version',
    6: '{s}Connectez-vous{p}, afin de noter ce skin',
    7: 'Pas de desctiption courte',
    8: 'pas d\'url',
    9: 'Téléchargements : {amount}',
    10: 'Tout réinitialiser',
    11: 'Afficher le guide',
    12: 'Fermer le guide',
    13: 'Pour marquer une règle comme lue, passez votre souris dessus (jaune signifie non lue)'
  },
  lists: {
    screens: {
      0: 'Bienvenue',
      1: 'Menu principal',
      2: 'Sélection des musiques',
      3: 'Menu des modes',
      4: 'Mods',
      5: 'Compte à rebours',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section réussie',
      9: 'Section échouée',
      10: 'Ecran de pause',
      11: 'Ecran d\'échec ',
      12: 'Ecran des résultats',
      13: 'Passer',
      14: 'Bannière',
      15: 'Écran de résultats (bas)'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixé'
    }
  },
  select: {
    0: 'Nouveau',
    1: 'Corrigé',
    2: 'Modifié',
    3: 'Supprimé',
    4: 'Oeuvres',
    5: 'Police d\'écriture',
    6: 'Artiste',
    7: 'Element du skin',
    8: 'Audio/Sfx',
    9: 'Outils',
    10: 'Image',
    views: 'Vues',
    likes: 'J\'aime',
    dislikes: 'Je n\'aime pas',
    downloads: 'Téléchargements',
    size_range: 'Sélectionnez la taille',
    date_range: 'Sélectionnez la plage de dates',
    ratio: 'Sélectionnez un format d\'image | Format dimage'
  },
  placeholders: {
    0: 'Sélectionner des rôles',
    1: 'Sélectionner des versions',
    2: 'Tapez du texte...',
    3: 'Sélectionnez la taille',
    4: 'Sélectionnez la plage de dates',
    5: 'Année',
    6: 'Mois',
    7: 'Sélectionnez un format d\'image',
    8: 'Sélectionnez les catégories',
    9: 'Modes de jeu',
    10: 'Sélectionnez le type',
    11: 'Copiez un lien YouTube',
    12: 'Ecrivez une desctiption et un url. Format description:url',
    13: 'Sélectionnez des suppléments',
    14: 'Copiez un lien',
    15: 'Titre du skin, auteur ou tags',
    16: 'Sélectionner une catégorie',
    17: 'Entrez le nom du tag'
  },
  contribute: { 0: 'Contribuer' },
  nsfw: {
    0: 'ATTENTION, nsfw !',
    1: 'Ce skin contient du contenu sensible ou pour adultes',
    2: 'Ce skin contient du contenu sensible ou pour adultes qui peuvent déranger certains utilisateurs',
    3: 'Ça marche',
    4: 'bye o/',
    5: 'Attention, Furry !'
  },
  removed: {
    0: 'Version indisponible',
    1: 'L\'auteur du skin a décidé de supprimer cette version du site.',
    2: 'Passez à une version disponible'
  },
  notify: {
    0: 'Les problèmes n\'ont pas été résolus',
    1: 'Tous les champs obligatoires n\'ont pas été remplis',
    2: 'Afficher',
    3: 'Introuvable',
    4: 'Bannière introuvable (actuellement, la première capture d\'écran est utilisée comme bannière)',
    5: 'Aucun changement',
    6: 'Aucun changement n\'a été trouvé',
    7: 'ID introuvable',
    8: 'ID de la vidéo introuvable, essayez un autre lien (pour le moment, seul YouTube est pris en charge)',
    9: 'Oups',
    10: 'On dirait que votre session a expirée, ouvrez une nouvelle page et connectez-vous à votre compte (ne vous inquiétez pas, tout a été sauvegardé automatiquement)',
    11: 'Existe',
    12: 'Cette vidéo a déjà été ajoutée',
    13: 'Existe',
    14: 'Ce tag a déjà été ajouté',
    15: 'Introuvable',
    16: 'Vous ne pouvez pas supprimer un tag supprimé',
    17: 'Ajouté',
    18: 'Vous avez ajouté un nouveau tag avec succès',
    19: 'OUps',
    20: 'Ce créateur a déjà été ajouté',
    21: 'EZ',
    22: 'Un nouveau créateur a été ajouté',
    23: 'HEIN',
    24: 'Impossible de supprimer un créateur supprimé',
    25: 'Doublon',
    26: 'Ce changement a déjà été ajouté plus tôt.',
    27: 'Doublon',
    28: 'Cette URL a déjà été ajoutée plus tôt.',
    29: 'Attention',
    30: 'Vous avez oublié d\'ajouter une description pour l\'URL. Exemple : Description:url',
    31: 'Attention',
    32: 'Vous avez oublié d\'ajouter une URL pour la description. Exemple : Description:url',
    33: 'Restaurée',
    34: 'La version « {name} » a été restaurée',
    35: 'Supprimée',
    36: 'La version « {name} » a été supprimée',
    37: 'Erreur',
    38: 'Apparemment, le serveur pense que vous êtes un robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Les identifiants ne correspondent pas (reconnexion dans le compte. Ne vous inquiétez pas, tout a été sauvegardé automatiquement)',
    41: 'Erreur inconnue',
    42: 'Vous ne pouvez pas modifier un skin inexistant',
    43: 'On dirait que vous n\'avez pas la permission de modifier ce skin',
    44: 'Vous ne pouvez pas envoyer cette version, car elle est la même que la précédente.',
    45: 'Ces modifications ont déjà été envoyées pour modération',
    46: 'Succès',
    47: 'De nouveaux changements ont été soumis pour modération',
    48: 'Les changements ont été mis à jour dans la modération',
    49: 'Lien étrange',
    50: 'Ce lien ne peut pas être utilisé comme un lien de téléchargement',
    51: 'Soumis pour modération',
    52: 'Attention',
    53: 'Vous devez choisir le type de ressource',
    54: 'Le skin est actuellement en cours de modération. Veuillez patienter pendant le traitement'
  },
  header: {
    0: 'Notifications',
    1: 'Suivez-nous sur ces plateformes pour recevoir des notifications sur de nouveaux skins'
  },
  restricted_view: {
    0: 'Non autorisé',
    1: 'Veuillez vous connecter à votre compte',
    2: 'Vue restreinte',
    3: 'Cette page n\'est pas encore disponible.'
  },
  confirm: {
    0: 'Tout réinitialiser ?',
    1: 'Afficher le guide ?',
    2: 'Soumettre le skin ?',
    3: 'Oui',
    4: 'Non'
  }
};