export default {
  title: {
    home: 'בית',
    login: 'התחברות',
    lists: { 0: 'רשימות' },
    tags: {
      0: 'תגים',
      1: '{amount} תגים בקטגוריה {name}',
      2: 'חיפוש תגיות'
    },
    ideas: {
      0: 'השראה',
      1: '«{amount}»\n'
    },
    sounds: { 0: 'קולות' },
    leaderboard: { 0: 'לוח תוצאות' },
    extend: { 0: 'יותר, פחות' },
    skin: {
      0: 'סקין זה מכיל אלמנטים סקינים אחרים',
      1: 'לחץ כאן לקבלת מידע נוסף'
    },
    tools: 'כלים'
  },
  home: {
    0: 'זמינים להורדה',
    1: 'סקינים הכי: _name_',
    2: 'נצפים | נאהבים | מורדים',
    3: 'פרסם סקין חדש',
    4: 'איך להתקין סקין',
    5: '{amount} סקינים | {amount} סקינים | {amount} סקינים'
  },
  changelogs: {
    0: 'יומן שינויים',
    1: 'רשימה של כל התיקונים שבוצעו בגירסה הנוכחית',
    2: 'שום דבר פה',
    3: 'אבל אתה יכול להוסיף את השינויים שביצעת בגרסה זו של סקין',
    4: 'לא מקובץ',
    5: 'חדש',
    6: 'תיקונים',
    7: 'שינויים',
    8: 'הסרות'
  },
  ideas: {
    0: 'לא נמצא כלום',
    1: 'צילומי מסך של «{type}» לא הועלו לאתר',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'יוצרים',
    1: 'רשום את כל היוצרים שהיו מעורבים ביצירת גרסה זו',
    2: 'אף אחד לא כאן',
    3: 'חיפוש שם השחקן יציג רשימה של פרופילים.',
    4: 'עורך',
    5: 'תפקידים',
    6: 'גירסאות'
  },
  tags: {
    0: 'תגים',
    1: 'רשימה של כל התגים הקשורים סקין זה',
    2: 'זה נראה די ריק כאן.',
    3: 'השתמש בשדה שלמעלה כדי למצוא תגים חדשים',
    4: 'תגיות לא נמצאו',
    5: 'נסה לחפש משהו אחר',
    6: 'חיפוש'
  },
  videos: {
    0: 'סרטונים',
    1: 'רשימה של כל תצוגות הווידאו עבור סקין זה',
    2: 'אין חלונות',
    3: 'חפשו כמה כאלה ב-YouTube או צרו חלון ראווה משלכם'
  },
  sources: {
    0: 'נכסים',
    1: 'רשימה של כל הנכסים או הכלים ששומשו בגרסה זו של הסקין',
    2: 'יחסית ריק פה',
    3: 'אם השתמשת בנכסים מסקינים אחרים, או מיצירות אומנות, יש להוסיף אותם בתיבה למעלה',
    4: 'לא מקובץ'
  },
  checks: {
    0: 'הכל',
    1: 'מטא-דאטא',
    2: 'הדגשה',
    3: 'שם הסקין אינו מצויין',
    4: 'הוסף לפחות יוצר סקין אחד',
    5: 'הוסף מספר תגים',
    6: 'גודל הסקין אינו מצויין',
    // 7: 'Select at least one gamemode',
    8: 'בחר רזולוציה לתמונה (SD או HD)',
    9: 'בחר לפחות יחס גובה־רוחב אחד',
    10: 'לא סופק אף צילום מסך',
    11: 'הוסף לפחות צילום מסך אחד בזמן משחק',
    12: 'קישור לסקין אינו מצויין',
    20: 'נראה די טוב',
    21: 'כל הבעיות תוקנו. עבודה טובה!',
    22: 'צ\'ק ליסט',
    23: 'הוסף לפחות גרסה פומבית אחת',
    24: 'הוסף לפחות יוצר אחד לגרסה זו',
    25: 'לחלק מהיוצרים אין תפקיד',
    26: '{amount} צילומי מסך לא משתייכים לשום קטגוריה',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'סקינים',
    1: 'פופולרי',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'אחרונים',
    5: 'אקראי',
    6: 'כל הסקינים',
    7: 'יחס גובה־רוחב',
    8: 'כל הסקינים | - רשימת סקינים',
    9: 'סקין | סקינים | סקינים',
    10: 'סקיני osu על ידי {name} | כל הסקינים של',
    11: 'חיפוש',
    12: 'סקינים של {name}',
    13: 'חקור סקינים',
    14: 'Popular skins'
  },
  skin: {
    0: 'עריכה',
    1: 'נוסף',
    2: 'HD',
    3: 'FullHD',
    4: 'אנימציה',
    5: 'צילומי מסך',
    6: 'מהלך המשחק בלבד',
    7: 'קישור להורדה | הורד סקין',
    8: 'פוסט בפורום | פורום osu!',
    9: 'פוסט Reddit',
    10: 'יוצרים',
    11: 'תגים',
    13: 'סרטונים',
    14: 'גרסה חדשה | נהל גרסאות',
    15: 'עדכן | הגש',
    16: 'מצבי משחק',
    17: 'שם הסקין',
    18: 'גרסה | גרסאות',
    19: 'גודל',
    20: 'מטא-דאטא',
    21: 'דירוג',
    22: 'הורדות',
    23: 'הורדה תהיה זמינה בקרוב',
    24: '{amount} שניות נותרו',
    25: 'אתה לא אחד משלנו',
    26: 'נראה שאתה לא היוצר או העורך של הסקין הזה',
    27: 'סקין על ידי',
    28: 'ללא תגים',
    29: 'ללא סרטונים',
    30: 'ללא יוצרים',
    31: 'דרג סקין',
    32: 'הצבע בעד והגב ב־Reddit',
    33: 'הגב בפורום osu!',
    34: 'עוד סקינים מהיוצר הזה | עוד סקינים מהיוצרים האלו',
    35: 'תמוך בסקין',
    36: 'לא זמין',
    37: 'Unfortunately, this skin was deleted',
    38: 'ברוך הבא לעורך הסקינים!',
    39: `חדשים לעורך הסקינים? תנו לנו להדריך אתכם בממשק ולהראות לכם את יכולותיו של העורך!`,
    40: '{current} מתוך {max} הושלמו',
    41: 'בדקו מאוחר יותר',
    42: `בואו נתחיל`,
    43: 'מזל טוב!',
    44: 'סיימתם את המדריך בהצלחה, תהנו!',
    45: 'מעלה'
  },
  drag: {
    0: 'לחץ כאן',
    1: 'או גרור ושחרר תמונות כאן'
  },
  footer: {
    0: 'נוצר על ידי cyperdark',
    1: 'תודות',
    2: 'חוקים',
    3: 'אנשי קשר'
  },
  credits: {
    0: 'Chibi',
    1: 'אומנויות',
    2: 'סמלים',
    3: 'כל הסמלים נלקחו מ־{name}',
    4: 'דגלים',
    5: 'כל תמונות הדגלים נלקחו מ־{name}',
    6: 'לוקליזציה',
    7: 'מישהו? [{lang}]',
    8: 'נראה ש־cyperdark שכח להוסיף אותם. {text}'
  },
  search: {
    0: 'חיפוש סקינים',
    1: 'צפיות',
    2: 'כותרת',
    3: 'דירוג',
    4: 'גודל',
    5: 'תאריך',
    7: 'לא נמצא כלום',
    8: 'נסה להשתמש במסנני חיפוש שונים',
    9: 'ממתין לשאילתה',
    10: 'השתמש במסנני החיפוש או כתוב את כותרת, יוצר או תגי הסקין',
    11: 'הורדות',
    12: 'שם',
    13: {
      0: 'סקינים',
      1: 'תגים',
      2: 'משתמשים',
      3: 'רשימות'
    },
    14: 'חיפוש:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'תחרויות',
    1: 'פוסט חדשות רשמי',
    2: 'הגשה',
    3: 'מתכונן',
    4: 'הצבעה',
    5: 'הסתיים',
    6: 'תחרויות',
    7: 'Voting page'
  },
  rules: {
    0: 'עודכן לאחרונה ב',
    1: 'הנחיות לפרסום סקינים'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} מתוך {max} הושלמו',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'חיפוש',
    1: 'עריכה',
    2: 'רשימה'
  },
  undefined: {
    0: 'ריק',
    1: 'למרבה הצער, אין כאן כלום, אבל אתה יכול לנסות להסתכל בדפים אחרים',
    2: 'למרבה הצער, אין כאן כלום',
    3: 'לא מורשה',
    4: 'אתה צריך להיות מחובר בכדי לערוך את סקין זה.',
    5: 'אתה צריך להיות מחובר בכדי להוסיף סקין חדש.'
  },
  settings: {
    0: 'הגדרות',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.',
    5: 'English comments',
    6: 'Show English translation of the comments'
  },
  meta: {
    title: {
      0: 'גלה סקיני osu',
      1: 'סקיני osu של מצבי משחק, יחסי גובה־רוחב',
      2: 'סקיני osu פופולריים',
      3: 'חפש סקיני osu',
      4: 'רשימה של תגים, {name}',
      5: 'סקין osu של {name} v{version}',
      6: 'תודות',
      7: 'סקיני osu',
      8: '{name} חפש סקינים לאוסו',
      9: 'קבל השראה מסקיני osu אחרים',
      10: 'סקיני osu שנוצרו על ידי {name}',
      11: 'חיפוש תגיות',
      12: '{name} מצא תגים',
      13: 'סקין חדש',
      14: 'חוקי האתר',
      15: 'osu! תחרויות',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: 'קבל את סקיני ה־osu! הכי טובים באתר שלנו! ספריית הענק שלנו מכילה סקינים לכל מצבי המשחק, יחסי גובה־רוחב ואפילו לשחקני השיא. בנוסף, יש לנו מדור מיוחד עבור מעריצי אנימה. שפר את יכולת המשחק שלך עם הסקין המושלם. #osuskins #osugame #anime',
      1: '{views} צפיות. סקין osu ל-{modes}, הגודל הוא {size}, נוצר על ידי {creators}. תומך {ratios}',
      2: 'מצאו את הסקין המושלם לosu! עם תכונת החיפוש המתקדמת שלנו. דפדפו בספריה הענקית שלנו, המסוננת ע"פ מצב, יחס מסך, ועוד. תוכלו גם לבדוק סקינים המשומשים ע"י השחקנים האלופים.',
      3: 'Discover a variety of skins for different game modes and aspect ratios on our site. Choose from standard, catch the beat, mania, and taiko modes. Find the perfect fit for your gaming preferences.',
      4: 'Find the perfect osu skin from top players on our site. Browse our collection of popular skins and customize your gameplay. Discover a wide range of styles and themes to suit your preferences.',
      5: 'List of existing tags for osu skins.',
      6: '{name} osu skins collection!, free downloading',
      7: 'A huge amount of osu skins for {name}, download for free!',
      8: 'All osu skins created by {name}',
      9: 'Find inspiration for your next osu! skin at our site. Browse through a diverse collection of skins and discover new techniques and ideas. Get inspired and create your own unique skins.',
      10: 'Search for tags among all the tags on the site.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'התחברות',
    1: 'דף הבית',
    profile_osu: 'פרופיל osu!',
    new_skin: 'סקין חדש',
    notifications: 'התראות',
    settings: 'הגדרות',
    logout: 'התנתק',
    load_more: 'טען עוד',
    copy_short: 'העתק קישור קצר',
    copied: 'הועתק',
    reddit_link: 'Reddit',
    osu_forum_link: 'פורום osu!',
    skin_return: 'חזרה לסקין',
    source: 'מקור',
    contest_voting: 'הצבעה כאן',
    rules_agree: 'אני מסכים',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'אופציונלי',
    1: 'נדרש',
    2: 'בחר לפחות אופציה אחת'
  },
  user: {
    roles: {
      0: 'יוצר',
      1: 'מערבב',
      2: 'אנימציות',
      3: 'אומנויות',
      4: 'משתף פעולה',
      5: 'קולות',
      6: 'מהלך המשחק'
    }
  },
  tooltips: {
    0: 'צפיות: {amount}',
    1: 'רענן תוצאות',
    2: 'יורד | עולה',
    3: 'לייקים: {likes} / דיסלייקים: {dislikes}',
    4: 'לחץ על ctrl+enter בכדי להוסיף תג',
    5: 'ערוך גרסה',
    6: '{s}התחבר{p}, בכדי לדרג את הסקין הזה',
    7: 'אין תיאור קצר',
    8: 'אין url',
    9: 'הורדות: {amount}',
    10: 'אפס הכל',
    11: 'הצג מדריך',
    12: 'סגור מדריך',
    13: 'כדי לסמן חוק כנקראה, עבור מעליו (צהוב מסמן לא נקרא)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'ברוך הבא',
      1: 'תפריט ראשי',
      2: 'בחירת שיר',
      3: 'תפריט מצבים',
      4: 'מודים',
      5: 'ספירה לאחור',
      6: 'מהלך המשחק',
      7: 'ספינר',
      8: 'מעבר חֵלֶק',
      9: 'כישלון חֵלֶק',
      10: 'מסך השהיה',
      11: 'מסך כישלון',
      12: 'מסך תוצאה',
      13: 'דלג',
      14: 'באנר',
      15: 'מסך תוצאות (תחתית)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'פרוותי',
      2: 'מעורבב'
    }
  },
  select: {
    0: 'חדש',
    1: 'מקובע',
    2: 'עבר שינוי',
    3: 'הוסר',
    4: 'אומנות',
    5: 'גופן',
    6: 'אומן',
    7: 'אלמנט של סקין',
    8: 'שמע/Sfx',
    9: 'כלים',
    10: 'תמונה',
    views: 'צפיות',
    likes: 'לייקים',
    dislikes: 'דיסלייקים',
    downloads: 'הורדות',
    ratio: 'בחר יחס ממדים | יחס',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'בחר תפקידים',
    1: 'בחר גרסאות',
    2: 'רשום תוכן...',
    3: 'Select size range',
    4: 'בחר טווח תאריכים',
    5: 'שנה',
    6: 'חודש',
    7: 'בחר יחס ממדים',
    8: 'בחר קטגוריות',
    9: 'מצבי משחק',
    10: 'בחר סוג',
    11: 'הדבק קישור יוטיוב',
    12: 'Type a description and an url. Format description:url',
    13: 'בחר אקסטרה',
    14: 'הדבק קישור',
    15: 'בחר אקסטרה',
    16: 'בחר קטגוריה',
    17: 'רשום את שם הטג',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'לתרום' },
  nsfw: {
    0: 'אזהרה! תוכן לא לילדים!',
    1: 'הסקין הזה מכיל תוכן רגיש או תוכן למבוגרים בלבד',
    2: 'הסקין הזה מכיל תוכן רגיש או תוכן למבוגרים שחלק מהמשתמשים יכולים למצאו כמטריד',
    3: 'בסדר',
    4: 'ביי o/',
    5: 'אזהרת פורי!'
  },
  removed: {
    0: 'גרסה אינה זמינה',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'החלף לגרסה זמינה'
  },
  notify: {
    0: 'הבעיות לא תוקנו',
    1: 'Not all required fields were filled',
    2: 'הצג',
    3: 'לא נמצא',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'אין שינויים',
    6: 'לא נמצאו שינויים',
    7: 'ID לא נמצא',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'אופס',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'הסרטון הזה כבר נוסף',
    13: 'Exists',
    14: 'הטג הזה כבר נוסף',
    15: 'לא נמצא',
    16: 'בלתי אפשרי למחוק טג מחוק',
    17: 'נוסף',
    18: 'הוספת בהצלחה טג חדש',
    19: 'אופס',
    20: 'היוצר הזה כבר נוסף',
    21: 'EZ',
    22: 'יוצר חדש נוסף',
    23: 'HUH',
    24: 'בלתי אפשרי למחוק יוצר מחוק',
    25: 'שכפול',
    26: 'השינוי הזה כבר נוסף מוקדם יותר.',
    27: 'שכפול',
    28: 'הקישור הזה כבר נוסף מוקדם יותר.',
    29: 'אזהרה',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'אזהרה',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'שוחזר',
    34: 'גרסה {name} שוחזרה',
    35: 'נמחק',
    36: 'גרסה {name} נמחקה',
    37: 'שגיאה',
    38: 'לרוע המזל השרת חושב שאתה רובוט.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'שגיאה לא ידועה',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'הצליח',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'קישור מוזר',
    50: 'קישור זה אינו יכול לשמש כקישור הורדה',
    51: 'Submitted for moderation',
    52: 'אזהרה',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'הצליח',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'התראות',
    1: 'עקוב אחרינו בפלטפורמות האלה כדי לקבל התראות על סקינים חדשים'
  },
  restricted_view: {
    0: 'לא מורשה',
    1: 'אנא התחבר למשתמש שלך',
    2: 'חלק מוגבל',
    3: 'העמוד הזה עוד לא יצא.'
  },
  confirm: {
    0: 'אפס הכל?',
    1: 'הצג מדריך?',
    2: 'שלח סקין?',
    3: 'כן',
    4: 'לא',
    5: 'Reset .ini?'
  }
};