export default {
  title: {
    home: 'בית',
    login: 'התחברות',
    lists: { 0: 'רשימות' },
    tags: {
      0: 'תגים',
      1: '{amount} תגים בקטגוריה {name}',
      2: 'חיפוש תגיות'
    },
    ideas: {
      0: 'השראה',
      1: '«{amount}»\n'
    },
    sounds: { 0: 'קולות' },
    leaderboard: { 0: 'לוח תוצאות' },
    extend: { 0: 'יותר, פחות' },
    skin: {
      0: 'סקין זה מכיל אלמנטים סקינים אחרים',
      1: 'לחץ כאן לקבלת מידע נוסף'
    },
    tools: 'Tools'
  },
  home: {
    0: 'זמינים להורדה',
    1: 'סקינים הכי: _name_',
    2: 'נצפים | נאהבים | מורדים',
    3: 'פרסם סקין חדש',
    4: 'איך להתקין סקין',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'יומן שינויים',
    1: 'רשימה של כל התיקונים שבוצעו בגירסה הנוכחית',
    2: 'שום דבר פה',
    3: 'אבל אתה יכול להוסיף את השינויים שביצעת בגרסה זו של סקין',
    4: 'לא מקובץ',
    5: 'חדש',
    6: 'תיקונים',
    7: 'שינויים',
    8: 'הסרות'
  },
  ideas: {
    0: 'לא נמצא כלום',
    1: 'צילומי מסך של «{type}» לא הועלו לאתר'
  },
  creators: {
    0: 'יוצרים',
    1: 'רשום את כל היוצרים שהיו מעורבים ביצירת גרסה זו',
    2: 'אף אחד לא כאן',
    3: 'חיפוש שם השחקן יציג רשימה של פרופילים.',
    4: 'עורך',
    5: 'תפקידים',
    6: 'גירסאות'
  },
  tags: {
    0: 'תגים',
    1: 'רשימה של כל התגים הקשורים סקין זה',
    2: 'זה נראה די ריק כאן.',
    3: 'השתמש בשדה שלמעלה כדי למצוא תגים חדשים',
    4: 'תגיות לא נמצאו',
    5: 'נסה לחפש משהו אחר',
    6: 'חיפוש'
  },
  videos: {
    0: 'סרטונים',
    1: 'רשימה של כל תצוגות הווידאו עבור סקין זה',
    2: 'אין חלונות',
    3: 'חפשו כמה כאלה ב-YouTube או צרו חלון ראווה משלכם'
  },
  sources: {
    0: 'נכסים',
    1: 'רשימה של כל הנכסים או הכלים ששומשו בגרסה זו של הסקין',
    2: 'יחסית ריק פה',
    3: 'אם השתמשת בנכסים מסקינים אחרים, או מיצירות אומנות, יש להוסיף אותם בתיבה למעלה',
    4: 'לא מקובץ'
  },
  checks: {
    0: 'הכל',
    1: 'מטא-דאטא',
    2: 'הדגשה',
    3: 'שם הסקין אינו מצויין',
    4: 'הוסף לפחות יוצר סקין אחד',
    5: 'הוסף מספר תגים',
    6: 'גודל הסקין אינו מצויין',
    7: 'בחר לפחות מצב משחק אחד',
    8: 'בחר רזולוציה לתמונה (SD או HD)',
    9: 'בחר לפחות יחס גובה־רוחב אחד',
    10: 'לא סופק אף צילום מסך',
    11: 'הוסף לפחות צילום מסך אחד בזמן משחק',
    12: 'קישור לסקין אינו מצויין',
    20: 'נראה די טוב',
    21: 'כל הבעיות תוקנו. עבודה טובה!',
    22: 'צ\'ק ליסט',
    23: 'הוסף לפחות גרסה פומבית אחת',
    24: 'הוסף לפחות יוצר אחד לגרסה זו',
    25: 'לחלק מהיוצרים אין תפקיד'
  },
  skins: {
    0: 'סקינים',
    1: 'פופולרי',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'אחרונים',
    5: 'אקראי',
    6: 'כל הסקינים',
    7: 'יחס גובה־רוחב',
    8: 'כל הסקינים | - רשימת סקינים',
    9: 'סקין | סקינים | סקינים',
    10: 'סקיני osu על ידי {name} | כל הסקינים של',
    11: 'חיפוש',
    12: 'סקינים של {name}',
    13: 'חקור סקינים'
  },
  skin: {
    0: 'עריכה',
    1: 'נוסף',
    2: 'HD',
    3: 'FullHD',
    4: 'אנימציה',
    5: 'צילומי מסך',
    6: 'מהלך המשחק בלבד',
    7: 'קישור להורדה | הורד סקין',
    8: 'פוסט בפורום | פורום osu!',
    9: 'פוסט Reddit',
    10: 'יוצרים',
    11: 'תגים',
    13: 'סרטונים',
    14: 'גרסה חדשה | נהל גרסאות',
    15: 'עדכן | הגש',
    16: 'מצבי משחק',
    17: 'שם הסקין',
    18: 'גרסה | גרסאות',
    19: 'גודל',
    20: 'מטא-דאטא',
    21: 'דירוג',
    22: 'הורדות',
    23: 'הורדה תהיה זמינה בקרוב',
    24: '{amount} שניות נותרו',
    25: 'אתה לא אחד משלנו',
    26: 'נראה שאתה לא היוצר או העורך של הסקין הזה',
    27: 'סקין על ידי',
    28: 'ללא תגים',
    29: 'ללא סרטונים',
    30: 'ללא יוצרים',
    31: 'דרג סקין',
    32: 'הצבע בעד והגב ב־Reddit',
    33: 'הגב בפורום osu!',
    34: 'עוד סקינים מהיוצר הזה | עוד סקינים מהיוצרים האלו',
    35: 'תמוך בסקין',
    36: 'Unavailable',
    37: 'Unfortunately skin was deleted by {author} request'
  },
  drag: {
    0: 'לחץ כאן',
    1: 'או גרור ושחרר תמונות כאן'
  },
  footer: {
    0: 'נוצר על ידי cyperdark',
    1: 'תודות'
  },
  credits: {
    0: 'Chibi',
    1: 'אומנויות',
    2: 'סמלים',
    3: 'כל הסמלים נלקחו מ־{name}',
    4: 'דגלים',
    5: 'כל תמונות הדגלים נלקחו מ־{name}',
    6: 'לוקליזציה',
    7: 'מישהו? [{lang}]',
    8: 'נראה ש־cyperdark שכח להוסיף אותם. {text}'
  },
  search: {
    0: 'חיפוש סקינים',
    1: 'צפיות',
    2: 'כותרת',
    3: 'דירוג',
    4: 'גודל',
    5: 'תאריך',
    7: 'לא נמצא כלום',
    8: 'נסה להשתמש במסנני חיפוש שונים',
    9: 'ממתין לשאילתה',
    10: 'השתמש במסנני החיפוש או כתוב את כותרת, יוצר או תגי הסקין',
    11: 'הורדות',
    12: 'שם',
    13: {
      0: 'סקינים',
      1: 'תגים',
      2: 'משתמשים',
      3: 'רשימות'
    },
    14: 'חיפוש:'
  },
  tabs: {
    0: 'חיפוש',
    1: 'עריכה',
    2: 'רשימה'
  },
  undefined: {
    0: 'ריק',
    1: 'למרבה הצער, אין כאן כלום, אבל אתה יכול לנסות להסתכל בדפים אחרים',
    2: 'למרבה הצער, אין כאן כלום',
    3: 'לא מורשה',
    4: 'אתה צריך להיות מחובר בכדי לערוך את סקין זה.',
    5: 'אתה צריך להיות מחובר בכדי להוסיף סקין חדש.'
  },
  meta: {
    title: {
      0: 'גלה סקיני osu',
      1: 'סקיני osu של מצבי משחק, יחסי גובה־רוחב',
      2: 'סקיני osu פופולריים',
      3: 'חפש סקיני osu',
      4: 'רשימה של תגים, {name}',
      5: 'סקין osu של {name} v{version}',
      6: 'תודות',
      7: 'סקיני osu',
      8: '{name} search osu skins',
      9: 'קבל השראה מסקיני osu אחרים',
      10: 'סקיני osu שנוצרו על ידי {name}',
      11: 'חיפוש תגיות',
      12: '{name} found tags',
      13: 'סקין חדש'
    },
    description: {
      0: 'קבל את סקיני ה־osu! הכי טובים באתר שלנו! ספריית הענק שלנו מכילה סקינים לכל מצבי המשחק, יחסי גובה־רוחב ואפילו לשחקני השיא. בנוסף, יש לנו מדור מיוחד עבור מעריצי אנימה. שפר את יכולת המשחק שלך עם הסקין המושלם. #osuskins #osugame #anime',
      1: '{views} views. An osu skin for {modes}, the size is {size}, created by {creators}. Supports {ratios}',
      2: 'Find the perfect osu! skin with our advanced search feature. Browse through our huge library, filtered by gamemode, aspect ratio, and more. Or, check out skins used by top players.',
      3: 'Discover a variety of skins for different game modes and aspect ratios on our site. Choose from standard, catch the beat, mania, and taiko modes. Find the perfect fit for your gaming preferences.',
      4: 'Find the perfect osu skin from top players on our site. Browse our collection of popular skins and customize your gameplay. Discover a wide range of styles and themes to suit your preferences.',
      5: 'List of existing tags for osu skins.',
      6: '{name} osu skins collection!, free downloading',
      7: 'A huge amount of osu skins for {name}, download for free!',
      8: 'All osu skins created by {name}',
      9: 'Find inspiration for your next osu! skin at our site. Browse through a diverse collection of skins and discover new techniques and ideas. Get inspired and create your own unique skins.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'התחברות',
    1: 'דף הבית',
    profile_osu: 'פרופיל osu!',
    new_skin: 'סקין חדש',
    notifications: 'התראות',
    settings: 'הגדרות',
    logout: 'התנתק',
    load_more: 'טען עוד',
    copy_short: 'העתק קישור קצר',
    copied: 'הועתק',
    reddit_link: 'Reddit',
    osu_forum_link: 'פורום osu!',
    skin_return: 'חזרה לסקין'
  },
  user: {
    roles: {
      0: 'יוצר',
      1: 'מערבב',
      2: 'אנימציות',
      3: 'אומנויות',
      4: 'משתף פעולה'
    }
  },
  tooltips: {
    0: 'צפיות: {amount}',
    1: 'רענן תוצאות',
    2: 'יורד | עולה',
    3: 'לייקים: {likes} / דיסלייקים: {dislikes}',
    4: 'לחץ על ctrl+enter בכדי להוסיף תג',
    5: 'ערוך גרסה',
    6: '{s}התחבר{p}, בכדי לדרג את הסקין הזה',
    7: 'אין תיאור קצר',
    8: 'אין url',
    9: 'הורדות: {amount}'
  },
  lists: {
    screens: {
      0: 'ברוך הבא',
      1: 'תפריט ראשי',
      2: 'בחירת שיר',
      3: 'תפריט מצבים',
      4: 'מודים',
      5: 'ספירה לאחור',
      6: 'מהלך המשחק',
      7: 'ספינר',
      8: 'מעבר חֵלֶק',
      9: 'כישלון חֵלֶק',
      10: 'מסך השהיה',
      11: 'מסך כישלון',
      12: 'מסך תוצאה',
      13: 'דלג',
      14: 'באנר'
    },
    cats: {
      0: 'NSFW',
      1: 'פרוותי',
      2: 'מעורבב'
    }
  },
  select: {
    0: 'חדש',
    1: 'מקובע',
    2: 'עבר שינוי',
    3: 'הוסר',
    4: 'אומנות',
    5: 'גופן',
    6: 'אומן',
    7: 'Skin element',
    8: 'Audio/Sfx',
    9: 'Tools',
    views: 'צפיות',
    likes: 'Likes',
    dislikes: 'Dislikes',
    downloads: 'הורדות',
    size_range: 'Select size',
    date_range: 'Select a date range',
    ratio: 'Select aspect ratio | ratio'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Select size',
    4: 'Select date range',
    5: 'Year',
    6: 'Month',
    7: 'Select aspect ratio',
    8: 'Select categories',
    9: 'מצבי משחק',
    10: 'Select type',
    11: 'Paste a YouTube link',
    12: 'Type a description and an url. Format description:url',
    13: 'Select extra',
    14: 'Paste a link',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning nsfw!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/',
    5: 'Warning furry!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation'
  },
  header: {
    0: 'התראות',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'לא מורשה',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};