export default {
  title: {
    home: 'Főoldal',
    login: 'Log in',
    lists: { 0: 'Listák' },
    tags: {
      0: 'Címkék',
      1: '{amount} címke ehhez a kategóriához: {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiráció',
      1: '{amount}'
    },
    sounds: { 0: 'Hangok' },
    leaderboard: { 0: 'Ranglista' },
    extend: { 0: 'Több | Kevesebb' },
    skin: {
      0: 'Ez a skin más skinekből is tartalmaz elemeket',
      1: 'További információért kattints ide'
    },
    tools: 'Eszközök'
  },
  changelogs: {
    0: 'Változi napló',
    1: 'Módosítások listája, amik a jelenlegi verzión történtek',
    2: 'Nincs it semmi',
    3: 'De hozzá adhatod a változtatásaidat, amit ehhez a skin verzióhoz csináltál',
    4: 'Nem csoportosított',
    5: 'Új',
    6: 'Javítások',
    7: 'Változtatások',
    8: 'Eltávolítások'
  },
  ideas: {
    0: 'Nothing founded',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Készítők',
    1: 'Készítők listája, akik részt vettek ennek a verziónak az elkészítésében',
    2: 'Senki sincs itt',
    3: 'Játékosra való keresés egy profil listát jelenít meg.',
    4: 'Szerkesztő',
    5: 'Szerepek',
    6: 'Verziók'
  },
  tags: {
    0: 'Címkék',
    1: 'Az összes címke ami ehhez a skinhez kötődik',
    2: 'Eléggé üresnek tűnik ez a hely.',
    3: 'Új címkék kereséséhez használd a felső mezőt',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Keresés'
  },
  videos: {
    0: 'Videók',
    1: 'Összes bemutató videó ehhez a skin-hez',
    2: 'Nincs bemutató',
    3: 'Keressél YouTube-on, vagy hozzál létre saját bemutatót'
  },
  sources: {
    0: 'Attribúció',
    1: 'Összes használt adat vagy eszköz a skin-nek ebben a változatában',
    2: 'Kissé üres ez a hely',
    3: 'Ha más skin-ekből vagy műből származó elemeket használtál fel, akkor add hozzá a fenti mezőbe',
    4: 'Nem csoportosított'
  },
  checks: {
    0: 'Összes',
    1: 'Metaadatok',
    2: 'Highlightok',
    3: 'Name of the skin not specified',
    4: 'Adjál hozzá legalább egy skin készítőt',
    5: 'Adjál hozzá néhány címkét',
    6: 'Skin fájl mérete nincs megadva',
    7: 'Válasszál ki legalább egy játékmódot',
    8: 'Válasszál felbontást (SD vagy HD)',
    9: 'Válasszál ki legalább egy képarányt',
    10: 'Nincs képernyőkép megadva',
    11: 'Adjál hozzá legalább egy gameplay képernyőképet',
    12: 'Link a skin-hez nincs megadva',
    20: 'Jól néz ki',
    21: 'Minden probléma meg lett oldva, szép munka',
    22: 'Ellenőrző lista',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skin-ek',
    1: 'Népszerű',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Legutóbbiak',
    5: 'Vélentlenszerű',
    6: 'Minden skin',
    7: 'Képarány',
    8: 'Minden skin | osu skin-ek',
    9: 'Skin | Skin-ek | Skin-ek',
    10: 'osu skin-ek {name} által',
    11: 'Keresés',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Szerkesztés',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animáció',
    5: 'Képernyőképek',
    6: 'Csak gameplay',
    7: 'Letöltési link | Skin letöltése',
    8: 'Fórum bejegyzés | osu! Fórum',
    9: 'Reddit bejegyzés',
    10: 'Készítők',
    11: 'Címkék',
    13: 'Videók',
    14: 'Új verzió | Verziók kezelése',
    15: 'Frissítés | Beküldesz',
    16: 'Játékmódok',
    17: 'Skin neve',
    18: 'Verzió | Verziók',
    19: 'Méret',
    20: 'Metaadatok',
    21: 'Értékelés',
    22: 'Letöltések',
    23: 'A letöltés elérhető lesz késöbb',
    24: '{amount} másodperc maradt',
    25: 'Te nem vagy egyikünk sem',
    26: 'Úgy látszik nem te vagy a készítője vagy szerkesztője ennek a skinnek',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Kattints ide',
    1: 'vagy húzza és ejtse a képeket ide'
  },
  footer: {
    0: 'cyperdark készítette',
    1: 'Készítők'
  },
  credits: {
    0: 'Chibi',
    1: 'Rajzok',
    2: 'Ikonok',
    3: 'Összes ikon {name} által',
    4: 'Zászlók',
    5: 'Összes zászló kép {name} által',
    6: 'Lokalizáció',
    7: 'Akárki? [{lang}]',
    8: 'Úgy tűnik, hogy cpol megfeledkezett ezeket hozzáadni. {text}'
  },
  search: {
    0: 'Skin keresés',
    1: 'Megtekintés',
    2: 'Cím',
    3: 'Értékelés',
    4: 'Méret',
    5: 'Dátum',
    7: 'Nincs találat',
    8: 'Próbálj meg másik kereső filtert beállítani',
    9: 'Lekérdezés függőben',
    10: 'Válasszál ki keresési szűrőket, vagy írd be a skin címét, a készítőt vagy egy címkét',
    11: 'Letöltések',
    12: 'Name',
    13: {
      0: 'Skin-ek',
      1: 'Címkék',
      2: 'Users',
      3: 'Listák'
    }
  },
  tabs: {
    0: 'Keresés',
    1: 'Szerkesztés',
    2: 'Lista'
  },
  undefined: {
    0: 'Üres',
    1: 'Sajnos itt nincs semmi, mindenesetre megnézhetsz más oldalakat is',
    2: 'Sajnos itt nincs semmi',
    3: 'Jogosulatlan',
    4: 'A skin szerkesztéséhez be kell jelentkezned.',
    5: 'Új skin hozzáadásához be kell jelentkezned.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'Játékmódok, osu skin képarányai',
      2: 'Népszerű osu skin-ek',
      3: 'Keressél osu skin-eket',
      4: 'Címkék listája, {name}',
      5: '{name} v{version} osu skin',
      6: 'Készítők',
      7: 'osu skin-ek',
      8: '{name} keress osu skin-eket',
      9: 'Inspiráld magad más osu skin-ekkel',
      10: '{name} létre hozott osu skin-eket',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Szerezd meg a legjobb osu! skineket az oldalunkon! A hatalmas választékunkban találhatsz skin-eket minden játékmódhoz és képarányhoz, emellett a legjobb játékosok skin-jeit is letöltheted. Továbbá van egy külön részünk anime rajongók számára. Emeld új szintre a játék elményedet a neked tökéletes skin-nel. #osuskins #osugame #anime',
      1: '{views} Megtekintések. {modes} módhoz egy osu! skin, a fájl mérete {size}, {creators} által készített. Támogatja {ratios}',
      2: 'Találd meg a tökéletes osu! skin-t a legújabb keresési funkcióinkkal. Böngésszél hatalmas választékkal bíró könyvtárunkban játékmód, képarány és egyebek szerint szűrve. Vagy nézd meg a legjobb játékosok által használt skin-eket.',
      3: 'Fedezd fel a különböző játékmódokat és képarányokat oldalunkon. Válasszál standard, catch the beat, mania és taiko módok közül. Találd meg a te játékstílusodhoz megfelelő skin-t.',
      4: 'Találd meg oldalunkon a tökéletes osu skin-t a legjobb játékosoktól. Böngésszél népszerű skin-gyűjteményünkben, és szabd testre gameplay-ed. Fedezd fel a stílusok és témák széles skáláját a te preferenciádnak megfelelően.',
      5: 'Létező osu skin címkék listája.',
      6: '{name} osu skin kollekció!, ingyenes letöltés',
      7: '{name} számára hatalmas mennyiégű osu! skin, töltsed le őket ingyen!',
      8: '{name} által létrehozott összes skin',
      9: 'Merítsél ihletet a következő osu skin-edhez oldalunkon. Böngésszél a skin-ek változatos gyűjteményében, és fedezzél fel új technikákat és ötleteket. Merítsél ihletet, és készítsd el saját egyedi skin-edet.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Bejelntkezés',
    1: 'Főoldal',
    profile_osu: 'osu! Profil',
    new_skin: 'Új skin',
    notifications: 'Értesítések',
    settings: 'Beállítások',
    logout: 'Kijelentkezés',
    load_more: 'Továbbiak betöltése',
    copy_short: 'Rövid link másolása',
    copied: 'Másolva',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Fórum',
    skin_return: 'Vissza a skin-hez'
  },
  user: {
    roles: {
      0: 'Készítő',
      1: 'Mixelő',
      2: 'Animációk',
      3: 'Rajzok',
      4: 'Együttműködés'
    }
  },
  tooltips: {
    0: 'Views: {amount}',
    1: 'Találatok frissítése',
    2: 'Csökkenő | Növekvő',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'Nyomj ctrl+enter-t egy címke hozzáadásához',
    5: 'Verzió szerkesztése',
    6: '{s}Jelentkezz be{p}, hogy értékelni tudd a skint',
    7: 'Nincs rövid leírás',
    8: 'Nincs url',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Köszöntünk',
      1: 'Főmenü',
      2: 'Zene választás',
      3: 'Játékmódok menüje',
      4: 'Módok',
      5: 'Visszaszámlálás',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sikeres szakasz',
      9: 'Sikertelen szakasz',
      10: 'Szünet',
      11: 'Fail Screen',
      12: 'Eredmény',
      13: 'Átugrás',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Vegyes'
    }
  },
  select: {
    0: 'Új',
    1: 'Kijavított',
    2: 'Valtoztatott',
    3: 'Eltávolított',
    4: 'Rajzok',
    5: 'Betűtípus',
    6: 'Művész',
    7: 'Skin elem',
    8: 'Hangeffektek',
    9: 'Eszközök',
    views: 'Megtekintés',
    likes: 'Kedvelés',
    dislikes: 'Dislikes',
    downloads: 'Letöltések',
    size_range: 'Válasszad ki a fájl méretét',
    date_range: 'Válasszál dátumtartományt',
    ratio: 'Válasszál képarányt | arány'
  },
  placeholders: {
    0: 'Szerepek választása',
    1: 'Verziók választása',
    2: 'Írj valamit...',
    3: 'Válasszad ki a fájl méretét',
    4: 'Dátumtartományt választása',
    5: 'Év',
    6: 'Hónap',
    7: 'Képarány választása',
    8: 'Kategóriák választása',
    9: 'Játékmódok',
    10: 'Típus kiválasztása',
    11: 'Illesszél be egy YouTube linket',
    12: 'Írj leírást és Url. Formátum: leírás:Url',
    13: 'Extra választása',
    14: 'Link beillesztése',
    15: 'Skin cím, készítő vagy tag',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Jogosulatlan',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};