export default {
  title: {
    home: 'Főoldal',
    login: 'Bejelentkezés',
    lists: { 0: 'Listák' },
    tags: {
      0: 'Címkék',
      1: '{amount} címke ehhez a kategóriához: {name}',
      2: 'Címkék keresése'
    },
    ideas: {
      0: 'Inspiráció',
      1: '{amount}'
    },
    sounds: { 0: 'Hangok' },
    leaderboard: { 0: 'Ranglista' },
    extend: { 0: 'Több | Kevesebb' },
    skin: {
      0: 'Ez a skin más skinekből is tartalmaz elemeket',
      1: 'További információért kattints ide'
    },
    tools: 'Eszközök'
  },
  home: {
    0: 'Elérhető letöltésre',
    1: 'Legtöbbet: _name_ skinek',
    2: 'Megnézett | Likeolt | Letöltött',
    3: 'Új skin közlése',
    4: 'Hogyan telepíts fel egy skint',
    5: '{amount} Skinek | {amount} Skinek | {amount} Skinek '
  },
  changelogs: {
    0: 'Változi napló',
    1: 'Módosítások listája, amik a jelenlegi verzión történtek',
    2: 'Nincs it semmi',
    3: 'De hozzá adhatod a változtatásokat, amit ehhez a skin verzióhoz csináltál',
    4: 'Nem csoportosított',
    5: 'Új',
    6: 'Javítások',
    7: 'Változtatások',
    8: 'Eltávolítások'
  },
  ideas: {
    0: 'Nincs találat',
    1: 'Screenshots of «{type}» were not uploaded to the site',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Készítők',
    1: 'Készítők listája, akik részt vettek ennek a verziónak az elkészítésében',
    2: 'Senki sincs itt',
    3: 'Játékosra való keresés egy profil listát jelenít meg.',
    4: 'Szerkesztő',
    5: 'Szerepek',
    6: 'Verziók'
  },
  tags: {
    0: 'Címkék',
    1: 'Az összes címke ami ehhez a skinhez kötődik',
    2: 'Eléggé üresnek tűnik ez a hely.',
    3: 'Új címkék kereséséhez használd a felső mezőt',
    4: 'Címkék nem találhatóak',
    5: 'Próbálj másra keresni',
    6: 'Keresés'
  },
  videos: {
    0: 'Videók',
    1: 'Összes bemutató videó ehhez a skin-hez',
    2: 'Nincs bemutató',
    3: 'Keressél YouTube-on, vagy hozzál létre saját bemutatót'
  },
  sources: {
    0: 'Attribúció',
    1: 'Összes használt adat vagy eszköz a skin-nek ebben a változatában',
    2: 'Kissé üres ez a hely',
    3: 'Ha más skin-ekből vagy műből származó elemeket használtál fel, akkor add hozzá a fenti mezőbe',
    4: 'Nem csoportosított'
  },
  checks: {
    0: 'Összes',
    1: 'Metaadatok',
    2: 'Highlightok',
    3: 'A skin neve nincs megadva',
    4: 'Adjál hozzá legalább egy skin készítőt',
    5: 'Adjál hozzá néhány címkét',
    6: 'Skin fájl mérete nincs megadva',
    // 7: 'Select at least one gamemode',
    8: 'Válasszál felbontást (SD vagy HD)',
    9: 'Válasszál ki legalább egy képarányt',
    10: 'Nincs képernyőkép megadva',
    11: 'Adjál hozzá legalább egy gameplay képernyőképet',
    12: 'Link a skin-hez nincs megadva',
    20: 'Egész jól néz ki',
    21: 'Minden probléma meg lett oldva, szép munka!',
    22: 'Ellenőrző lista',
    23: 'Adjon hozzá legalább egy publikus verziót',
    24: 'Adjon hozzá legalább egy készítőt ehhez a verzióhoz',
    25: 'Some creators don\'t have roles',
    26: '{amount} screenshots doesn\'t have category',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skin-ek',
    1: 'Népszerű',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Legutóbbiak',
    5: 'Vélentlenszerű',
    6: 'Minden skin',
    7: 'Képarány',
    8: 'Minden skin | osu skin-ek',
    9: 'Skin | Skin-ek | Skin-ek',
    10: 'osu skin-ek {name} által',
    11: 'Keresés',
    12: '{name} skinek',
    13: 'Skinek felfedezése',
    14: 'Népszerű skinek'
  },
  skin: {
    0: 'Szerkesztés',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animáció',
    5: 'Képernyőképek',
    6: 'Csak gameplay',
    7: 'Letöltési link | Skin letöltése',
    8: 'Fórum bejegyzés | osu! Fórum',
    9: 'Reddit bejegyzés',
    10: 'Készítők',
    11: 'Címkék',
    13: 'Videók',
    14: 'Új verzió | Verziók kezelése',
    15: 'Frissítés | Beküldesz',
    16: 'Játékmódok',
    17: 'Skin neve',
    18: 'Verzió | Verziók',
    19: 'Méret',
    20: 'Metaadatok',
    21: 'Értékelés',
    22: 'Letöltések',
    23: 'A letöltés elérhető lesz késöbb',
    24: '{amount} másodperc maradt',
    25: 'Te nem vagy egyikünk sem',
    26: 'Úgy látszik nem te vagy a készítője vagy szerkesztője ennek a skinnek',
    27: 'Skint készítette',
    28: 'Nincs címke',
    29: 'Nincsenek videók',
    30: 'Nincsenek készítők',
    31: 'Skin értékelése',
    32: 'Upvote & comment on reddit',
    33: 'Kommentelj az osu! fórumon',
    34: 'Még több skin a készítőtöl | Még több skin a készítőktől',
    35: 'Skin támogatása',
    36: 'Nem elérhető',
    37: 'Sajnos, ezt a skint letörölték',
    38: 'Welcome to the skin post editor!',
    39: `Új vagy a skin editorhoz? Engedd meg hogy körülvezessünk az interfacen, és megmutassuk az editor teljes potenciálját!`,
    40: '{current} of {max} completed',
    41: 'Nézz rá később',
    42: `Kezdjünk bele`,
    43: 'Gratulálunk!',
    44: 'Sikeresen befejezted a tutorial-t, jó szórakozást!',
    45: 'feltöltő'
  },
  drag: {
    0: 'Kattints ide',
    1: 'vagy húzza és ejtse a képeket ide'
  },
  footer: {
    0: 'cyperdark készítette',
    1: 'Készítők',
    2: 'Szabályok',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Rajzok',
    2: 'Ikonok',
    3: 'Összes ikon {name} által',
    4: 'Zászlók',
    5: 'Összes zászló kép {name} által',
    6: 'Lokalizáció',
    7: 'Akárki? [{lang}]',
    8: 'Úgy tűnik cyperdark elfelejtette hozzá adni. {text}'
  },
  search: {
    0: 'Skin keresés',
    1: 'Megtekintés',
    2: 'Cím',
    3: 'Értékelés',
    4: 'Méret',
    5: 'Dátum',
    7: 'Nincs találat',
    8: 'Próbálj meg más kereső filtert használni',
    9: 'Lekérdezés függőben',
    10: 'Használja a kereső filtereket vagy írja be a skin nevét, készítőjét, címkéjét',
    11: 'Letöltések',
    12: 'Név',
    13: {
      0: 'Skin-ek',
      1: 'Címkék',
      2: 'Felhasználók',
      3: 'Listák'
    },
    14: 'Keresés:',
    15: 'Méret:',
    16: 'Értékelés:',
    17: 'Megtekintések:',
    18: 'Letöltések:'
  },
  contests: {
    0: 'Versenyek',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Előkészülés',
    4: 'Szavazás',
    5: 'Kész',
    6: 'Versenyek',
    7: 'Szavazó oldal'
  },
  rules: {
    0: 'Utoljára frissítve',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Köszöntelek a skin.ini editorban!',
    1: `Új vagy a skin.ini editorjához? Engedd meg hogy körülvezessünk az interfacen, és megmutassuk az editor teljes potenciálját!`,
    2: '{current} of {max} completed',
    3: 'Nincs találat',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'Keresés',
    1: 'Szerkesztés',
    2: 'Lista'
  },
  undefined: {
    0: 'Üres',
    1: 'Sajnos itt nincs semmi, de megnézhetsz más oldalakat is',
    2: 'Sajnos itt nincs semmi',
    3: 'Jogosulatlan',
    4: 'Be kell legyél jelentkezve, hogy szerkeszteni tudjad ezt a skint.',
    5: 'Be kell legyél jelentkezve, hogy új skint adjál hozzá.'
  },
  settings: {
    0: 'Beállítások',
    1: 'Egér görgetés',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Nagyítás',
    4: 'Enable image zoom on hover for larger skin preview.'
  },
  meta: {
    title: {
      0: 'Osu skinek felfedezése',
      1: 'Játékmódok, osu skin képarányai',
      2: 'Népszerű osu skin-ek',
      3: 'Keressél osu skin-eket',
      4: 'Címkék listája, {name}',
      5: '{name} v{version} osu skin',
      6: 'Készítők',
      7: 'osu skin-ek',
      8: '{name} keress osu skin-eket',
      9: 'Inspiráld magad más osu skin-ekkel',
      10: '{name} létre hozott osu skin-eket',
      11: 'Címkék keresése',
      12: '{name} talált címkék',
      13: 'Új skin',
      14: 'Oldal szabályok',
      15: 'osu! Versenyek',
      16: 'osu! skinning eszközök'
    },
    description: {
      0: 'Szerezd meg a legjobb osu! skineket az oldalunkon! A hatalmas választékunkban találhatsz skin-eket minden játékmódhoz és képarányhoz, emellett a legjobb játékosok skin-jeit is letöltheted. Továbbá van egy külön részünk anime rajongók számára. Emeld új szintre a játék elményedet a neked tökéletes skin-nel. #osuskins #osugame #anime',
      1: '{views} Megtekintések. {modes} módhoz egy osu! skin, a fájl mérete {size}, {creators} által készített. Támogatja {ratios}',
      2: 'Találd meg a tökéletes osu! skin-t a legújabb keresési funkcióinkkal. Böngésszél hatalmas választékkal bíró könyvtárunkban játékmód, képarány és egyebek szerint szűrve. Vagy nézd meg a legjobb játékosok által használt skin-eket.',
      3: 'Fedezd fel a különböző játékmódokat és képarányokat oldalunkon. Válasszál standard, catch the beat, mania és taiko módok közül. Találd meg a te játékstílusodhoz megfelelő skin-t.',
      4: 'Találd meg oldalunkon a tökéletes osu skin-t a legjobb játékosoktól. Böngésszél népszerű skin-gyűjteményünkben, és szabd testre gameplay-ed. Fedezd fel a stílusok és témák széles skáláját a te preferenciádnak megfelelően.',
      5: 'Létező osu skin címkék listája.',
      6: '{name} osu skin kollekció!, ingyenes letöltés',
      7: '{name} számára hatalmas mennyiégű osu! skin, töltsed le őket ingyen!',
      8: '{name} által létrehozott összes skin',
      9: 'Merítsél ihletet a következő osu skin-edhez oldalunkon. Böngésszél a skin-ek változatos gyűjteményében, és fedezzél fel új technikákat és ötleteket. Merítsél ihletet, és készítsd el saját egyedi skin-edet.',
      10: 'Search for tags among all the tags on the site.',
      11: 'Lista az aktív/befejezett osu! versenyekről',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Bejelntkezés',
    1: 'Főoldal',
    profile_osu: 'osu! Profil',
    new_skin: 'Új skin',
    notifications: 'Értesítések',
    settings: 'Beállítások',
    logout: 'Kijelentkezés',
    load_more: 'Továbbiak betöltése',
    copy_short: 'Rövid link másolása',
    copied: 'Másolva',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Fórum',
    skin_return: 'Vissza a skin-hez',
    source: 'Forrás',
    contest_voting: 'Itt szavazz',
    rules_agree: 'Elfogadom',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Készítő',
      1: 'Mixelő',
      2: 'Animációk',
      3: 'Rajzok',
      4: 'Együttműködés',
      5: 'Hangok',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: 'Megtekintések száma: {amount}',
    1: 'Találatok frissítése',
    2: 'Csökkenő | Növekvő',
    3: 'Kedvelések száma: {likes} / Nem kedvelések száma: {dislikes}',
    4: 'Nyomj ctrl+enter-t egy címke hozzáadásához',
    5: 'Verzió szerkesztése',
    6: '{s}Jelentkezz be{p} a skin értékeléséhez',
    7: 'Nincs rövid leírás',
    8: 'Nincs url',
    9: 'Letöltések száma: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Köszöntünk',
      1: 'Főmenü',
      2: 'Zene választás',
      3: 'Játékmódok menüje',
      4: 'Módok',
      5: 'Visszaszámlálás',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sikeres szakasz',
      9: 'Sikertelen szakasz',
      10: 'Szünet',
      11: 'Fail Screen',
      12: 'Eredmény',
      13: 'Átugrás',
      14: 'Banner',
      15: 'Result screen (bottom)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Vegyes'
    }
  },
  select: {
    0: 'Új',
    1: 'Kijavított',
    2: 'Valtoztatott',
    3: 'Eltávolított',
    4: 'Rajzok',
    5: 'Betűtípus',
    6: 'Művész',
    7: 'Skin elem',
    8: 'Hangeffektek',
    9: 'Eszközök',
    10: 'Image',
    views: 'Megtekintés',
    likes: 'Kedvelés',
    dislikes: 'Nem kedvelés',
    downloads: 'Letöltések',
    ratio: 'Válasszál képarányt | arány',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Válassz szerepet',
    1: 'Válassz verziót',
    2: 'Írj valamit...',
    3: 'Select size range',
    4: 'Dátumtartományt választása',
    5: 'Év',
    6: 'Hónap',
    7: 'Képarány választása',
    8: 'Kategóriák választása',
    9: 'Játékmódok',
    10: 'Típus kiválasztása',
    11: 'Illesszél be egy YouTube linket',
    12: 'Type a description and an url. Format description:url',
    13: 'Extra választása',
    14: 'Link beillesztése',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation',
    52: 'Warning',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'Success',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'Értesítések',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Jogosulatlan',
    1: 'Kérlek jelentkezz be a fiókodba',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No',
    5: 'Reset .ini?'
  }
};