export default {
  title: {
    home: 'Halaman utama',
    login: 'Masuk',
    lists: { 0: 'Daftar' },
    tags: {
      0: 'Label',
      1: 'Ada {amount} skin yang cocok dengan label {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspirasi',
      1: '«{amount}»'
    },
    sounds: { 0: 'Suara' },
    leaderboard: { 0: 'Papan Peringkat' },
    extend: { 0: 'Selebihnya | Lebih sedikit' },
    skin: {
      0: 'Skin ini mengandung beberapa konten yang bersumber dari skin lain',
      1: 'Ketuk di sini untuk informasi lebih lanjut'
    },
    tools: 'Alat'
  },
  changelogs: {
    0: 'Catatan Perubahan',
    1: 'Daftar perubahan di versi saat ini',
    2: 'Riwayat kosong',
    3: 'Kamu bisa menambahkan perubahan yang kamu buat di skin ini',
    4: 'Tidak Terorganisir',
    5: 'Baru',
    6: 'Perbaikan',
    7: 'Perubahan',
    8: 'Dihapus'
  },
  ideas: {
    0: 'Tidak menemukan apapun',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Pembuat',
    1: 'Daftar orang yang terlibat membuat versi ini',
    2: 'Tidak ada siapapun disini',
    3: 'Mencari nama pemain akan menampilkan daftar profil.',
    4: 'Editor',
    5: 'Peran',
    6: 'Versi'
  },
  tags: {
    0: 'Label',
    1: 'Daftar label yang berkaitan dengan skin ini',
    2: 'Kosong ya...',
    3: 'Gunakan bidang di atas untuk menemukan label baru',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Cari'
  },
  videos: {
    0: 'Video',
    1: 'Video review skin ini',
    2: 'Tidak ada review',
    3: 'Cari di YouTube atau buat review-mu sendiri'
  },
  sources: {
    0: 'Atribut',
    1: 'Daftar aset dan alat yang digunakan pada versi skin ini',
    2: 'Sepertinya tidak ada apa-apa',
    3: 'Jika kamu menggunakan aset dari skin lain, atau art, beritahukan di dalam box tersebut',
    4: 'Tidak Terorganisir'
  },
  checks: {
    0: 'Semua',
    1: 'Metadata',
    2: 'Sorotan',
    3: 'Name of the skin not specified',
    4: 'Tambahkan setidaknya satu pembuat skin',
    5: 'Tambahkan beberapa label',
    6: 'Ukuran skin tidak ditentukan',
    7: 'Pilih setidaknya satu gamemode',
    8: 'Pilih resolusi gambar (SD atau HD)',
    9: 'Pilih setidaknya satu aspek rasio',
    10: 'Tidak diberikan screenshot',
    11: 'Tambahkan setidaknya satu screenshot gameplay',
    12: 'Tidak ada link untuk skinnya',
    20: 'Cukup baik',
    21: 'Semua masalah sudah diperbaiki. Kerja Bagus!',
    22: 'Daftar cek',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skin',
    1: 'Populer',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Terbaru',
    5: 'Acak',
    6: 'Semua Skin',
    7: 'Aspek Rasio',
    8: 'Semua skin | skin osu',
    9: 'Skin | Skin | Skin',
    10: 'Skin osu oleh {name}',
    11: 'Cari',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Edit',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasi',
    5: 'Screenshot',
    6: 'Hanya gameplay',
    7: 'Link unduh | Unduh skin',
    8: 'Pos forum | Forum osu!',
    9: 'Postingan Reddit',
    10: 'Pembuat',
    11: 'Label',
    13: 'Video',
    14: 'Versi baru | Kelola versi',
    15: 'Perbarui | Kirim',
    16: 'Gamemode',
    17: 'Nama skin',
    18: 'Versi | Versi',
    19: 'Ukuran',
    20: 'Metadata',
    21: 'Penilaian',
    22: 'Unduh',
    23: 'Unduhan akan segera tersedia',
    24: '{amount} detik tersisa',
    25: 'Kamu bukan salah satu dari kami',
    26: 'Sepertinya kamu bukan pembuat ataupun editor dari skin ini',
    27: 'Skin oleh',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Klik disini',
    1: 'atau tarik dan lepas gambar di sini'
  },
  footer: {
    0: 'Dibuat oleh cyperdark',
    1: 'Credit'
  },
  credits: {
    0: 'Chibi',
    1: 'Art',
    2: 'Ikon',
    3: 'Semua ikon diambil dari {name}',
    4: 'Bendera',
    5: 'Semua gambar bendera diambil dari {name}',
    6: 'Lokalisasi',
    7: 'Seseorang? [{lang}]',
    8: 'Sepertinya, cpol lupa menambahkan mereka. {text}'
  },
  search: {
    0: 'Cari Skin',
    1: 'Dilihat',
    2: 'Judul',
    3: 'Penilaian',
    4: 'Ukuran',
    5: 'Tanggal',
    7: 'Tidak menemukan apapun',
    8: 'Coba pakai search filter yang berbeda',
    9: 'Menunggu pencarian',
    10: 'Pakai search filter atau tulis saja judul skin, pembuat, atau labelnya',
    11: 'Unduh',
    12: 'Nama',
    13: {
      0: 'Skin',
      1: 'Label',
      2: 'Users',
      3: 'Daftar'
    }
  },
  tabs: {
    0: 'Cari',
    1: 'Edit',
    2: 'Daftar'
  },
  undefined: {
    0: 'Kosong',
    1: 'Sayangnya halaman ini kosong, kamu bisa melihat halaman lainnya',
    2: 'Sayangnya tidak ada apa-apa disini',
    3: 'Tidak diizinkan',
    4: 'Kamu perlu masuk untuk meng-edit skin ini.',
    5: 'Kamu perlu masuk untuk menambahkan skin baru.'
  },
  meta: {
    title: {
      0: 'Temukan skin osu',
      1: 'Mode permainan, aspek rasio dari skin osu',
      2: 'osu! skin yang populer',
      3: 'Cari skin osu!',
      4: 'Daftar label, {name}',
      5: 'Skin osu! {name} v{version}',
      6: 'Credit',
      7: 'skin - skin osu!',
      8: 'Pencarian skin osu! {name}',
      9: 'Dapatkan inspirasi dari skin lain',
      10: '{name} membuat skin osu!',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Dapatkan skin osu! terbaik di website kami! Kami menyediakan berbagai skin untuk berbagai macam mode, aspek rasio, dan dari player ternama. Oh ya! Kami juga menyediakan khusus bagi user yang menyukai anime untuk mencari skin yang mengandung karakter atau anime. Kembangkan pengalaman bermain osu! mu dengan skin terbaik!! #osuskins #osugame #anime',
      1: 'Dilihat {views} kali, Skin ini bisa digunakan untuk mode {modes}, Ukuran skin ini adalah {size}, Dibuat oleh {creators}. Bisa digunakan untuk rasio layar {ratios}',
      2: 'Temukan skin osu! terbaik dengan menggunakan fitur pencarian kami. Kami menyediakan berbagai skin yang bisa dicari sesuai mode, aspek rasio layar, dan yain lain - lain. Kami juga menyediakan skin populer yang digunakan oleh pemain ternama.',
      3: 'Temukan berbagai skin untuk berbagai mode permainan dan rasio aspek di website kami. Pilih dari mode standard, catch the beat, mania, dan taiko. Temukan yang paling cocok untuk preferensi game Anda.',
      4: 'Temukan skin osu! terbaik dari para player ternama di website kami. Jelajahi koleksi skin populer kami dan sesuaikan dengan gameplay Anda. Temukan berbagai macam gaya dan tema yang cocok dengan preferensi Anda.',
      5: 'Daftar tag yang tersedia untuk skin osu.',
      6: 'Koleksi skin {name} untuk osu!, unduh gratis',
      7: 'Tersedia banyak sekali skin osu! untuk {name}, unduh secara gratis!',
      8: 'Semua skin osu! yang dibuat oleh {name}',
      9: 'Cari inspirasi untuk skin osu! mu pada website kami. Jelajahi berbagai macam koleksi skin, dan temukan teknik dan ide baru. Dapatkan inspirasi dan buat skin unik Anda sendiri.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Masuk',
    1: 'Halaman utama',
    profile_osu: 'Profil osu!',
    new_skin: 'Skin baru',
    notifications: 'Notifikasi',
    settings: 'Pengaturan',
    logout: 'Keluar',
    load_more: 'Muat lebih',
    copy_short: 'Salin link pendek',
    copied: 'Disalin',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Kembali ke skin'
  },
  user: {
    roles: {
      0: 'Pembuat',
      1: 'Mixer',
      2: 'Animasi',
      3: 'Art',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Dilihat: {amount}',
    1: 'Perbarui Hasil',
    2: 'Turun | Naik',
    3: 'Suka: {likes} / Tidak suka: {dislikes}',
    4: 'Tekan ctrl+enter untuk menambahkan label',
    5: 'Edit versi',
    6: '{s}Masuk{p}, agar bisa menilai skin ini',
    7: 'Tidak ada deskripsi singkat',
    8: 'Tidak ada URL',
    9: 'Unduh: {amount}'
  },
  lists: {
    screens: {
      0: 'Selamat datang',
      1: 'Menu utama',
      2: 'Pilihan lagu',
      3: 'Menu mode',
      4: 'Mod',
      5: 'Hitung mundur',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Layar Jeda',
      11: 'Layar Gagal',
      12: 'Layar Hasil',
      13: 'Lewati',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Campuran'
    }
  },
  select: {
    0: 'Baru',
    1: 'Perbaikan',
    2: 'Perubahan',
    3: 'Dihapus',
    4: 'Art',
    5: 'Font',
    6: 'Artis',
    7: 'Elemen skin',
    8: 'Audio/SFX',
    9: 'Alat',
    views: 'Dilihat',
    likes: 'Suka',
    dislikes: 'Tidak suka',
    downloads: 'Unduh',
    size_range: 'Pilih ukuran',
    date_range: 'Pilih rentang tanggal',
    ratio: 'Pilih aspek rasio | rasio'
  },
  placeholders: {
    0: 'Pilih peran',
    1: 'Pilih versi',
    2: 'Tulis teks...',
    3: 'Pilih ukuran',
    4: 'Pilih rentang tanggal',
    5: 'Tahun',
    6: 'Bulan',
    7: 'Pilih aspek rasio',
    8: 'Pilih kategori',
    9: 'Gamemode',
    10: 'Pilih tipe',
    11: 'Tempel link YouTube',
    12: 'Tulis deskripsi dan URL. Format: deskripsi:URL',
    13: 'Pilih ekstra',
    14: 'Tempel link',
    15: 'Judul, pembuat, atau label skin',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Kontribusi' },
  nsfw: {
    0: 'Peringatan!',
    1: 'Terdapat konten sensitif atau dewasa pada skin ini',
    2: 'Terdapat konten sensitif atau dewasa pada skin ini yang mungkin mengganggu sebagian orang',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Tidak diizinkan',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};