export default {
  title: {
    home: 'Halaman utama',
    login: 'Masuk',
    lists: { 0: 'Daftar' },
    tags: {
      0: 'Label',
      1: 'Ada {amount} skin yang cocok dengan label {name}',
      2: 'Cari label'
    },
    ideas: {
      0: 'Inspirasi',
      1: '«{amount}»'
    },
    sounds: { 0: 'Suara' },
    leaderboard: { 0: 'Papan Peringkat' },
    extend: { 0: 'Selebihnya | Lebih sedikit' },
    skin: {
      0: 'Skin ini mengandung beberapa konten yang bersumber dari skin lain',
      1: 'Ketuk di sini untuk informasi lebih lanjut'
    },
    tools: 'Alat'
  },
  home: {
    0: 'Tersedia untuk didownload',
    1: 'Skin yang: _name_ terbanyak',
    2: 'Dilihat | Disukai | Didownload',
    3: 'Publikasikan skin baru',
    4: 'Bagaimana cara memasang skin',
    5: '{amount} Skin | {amount} Skin | {amount} Skin',
    6: 'Join discord'
  },
  changelogs: {
    0: 'Catatan Perubahan',
    1: 'Daftar perubahan di versi saat ini',
    2: 'Riwayat kosong',
    3: 'Kamu bisa menambahkan perubahan yang kamu buat di skin ini',
    4: 'Tidak Terorganisir',
    5: 'Baru',
    6: 'Perbaikan',
    7: 'Perubahan',
    8: 'Dihapus'
  },
  ideas: {
    0: 'Tidak menemukan apapun',
    1: 'Screenshot «{type}» tidak diunggah ke situs',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Pembuat',
    1: 'Daftar orang yang terlibat membuat versi ini',
    2: 'Tidak ada siapapun disini',
    3: 'Mencari nama pemain akan menampilkan daftar profil.',
    4: 'Editor',
    5: 'Peran',
    6: 'Versi'
  },
  tags: {
    0: 'Label',
    1: 'Daftar label yang berkaitan dengan skin ini',
    2: 'Kosong ya...',
    3: 'Gunakan bidang di atas untuk menemukan label baru',
    4: 'Label tidak ditemukan',
    5: 'Coba cari yang lain',
    6: 'Cari'
  },
  videos: {
    0: 'Video',
    1: 'Video review skin ini',
    2: 'Tidak ada review',
    3: 'Cari di YouTube atau buat review-mu sendiri'
  },
  sources: {
    0: 'Atribut',
    1: 'Daftar aset dan alat yang digunakan pada versi skin ini',
    2: 'Sepertinya tidak ada apa-apa',
    3: 'Jika kamu menggunakan aset dari skin lain, atau art, beritahukan di dalam box tersebut',
    4: 'Tidak Terorganisir'
  },
  checks: {
    0: 'Semua',
    1: 'Metadata',
    2: 'Sorotan',
    3: 'Nama skin tidak ditentukan',
    4: 'Tambahkan setidaknya satu pembuat skin',
    5: 'Tambahkan beberapa label',
    6: 'Ukuran skin tidak ditentukan',
    // 7: 'Select at least one gamemode',
    8: 'Pilih resolusi gambar (SD atau HD)',
    9: 'Pilih setidaknya satu aspek rasio',
    10: 'Tidak diberikan screenshot',
    11: 'Tambahkan setidaknya satu screenshot gameplay',
    12: 'Tidak ada link untuk skinnya',
    20: 'Terlihat bagus',
    21: 'Semua masalah sudah diperbaiki. Kerja bagus!',
    22: 'Daftar cek',
    23: 'Tambahkan setidaknya satu versi publik',
    24: 'Tambahkan setidaknya satu pembuat untuk versi ini',
    25: 'Beberapa pembuat tidak mempunyai peran',
    26: '{amount} screenshot tidak memiliki kategori',
    27: 'Specifiy gameplay name for {mode} screenshots | Specifiy gameplay name for {mode} screenshot',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skin',
    1: 'Populer',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Terbaru',
    5: 'Acak',
    6: 'Semua Skin',
    7: 'Aspek Rasio',
    8: 'Semua skin | skin osu',
    9: 'Skin | Skin | Skin',
    10: 'Skin osu oleh {name}',
    11: 'Cari',
    12: '{name} skin',
    13: 'Temukan skin',
    14: 'Popular skins'
  },
  skin: {
    0: 'Edit',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasi',
    5: 'Screenshot',
    6: 'Hanya gameplay',
    7: 'Link unduh | Unduh skin',
    8: 'Pos forum | Forum osu!',
    9: 'Postingan Reddit',
    10: 'Pembuat',
    11: 'Label',
    13: 'Video',
    14: 'Versi baru | Kelola versi',
    15: 'Perbarui | Kirim',
    16: 'Gamemode',
    17: 'Nama skin',
    18: 'Versi | Versi',
    19: 'Ukuran',
    20: 'Metadata',
    21: 'Penilaian',
    22: 'Unduh',
    23: 'Unduhan akan segera tersedia',
    24: '{amount} detik tersisa',
    25: 'Kamu bukan salah satu dari kami',
    26: 'Sepertinya kamu bukan pembuat ataupun editor dari skin ini',
    27: 'Skin oleh',
    28: 'Tidak ada label',
    29: 'Tidak ada video',
    30: 'Tidak ada pembuat',
    31: 'Beri nilai',
    32: 'Komentar & Upvote di reddit',
    33: 'Komentar di forum osu!',
    34: 'Lebih banyak skin dari pembuat | Lebih banyak skin dari pembuat',
    35: 'Dukung skin ini',
    36: 'Tidak tersedia',
    37: 'Unfortunately, this skin was deleted',
    38: 'Selamat datang di skin post editor!',
    39: `Baru saja memakai skin editor?, Kami akan memberikan tutorial dan memperlihatkan potensi penuh editor!`,
    40: '{current} dari {max} telah terselesaikan',
    41: 'Cek kembali nanti',
    42: `Mari kita mulai`,
    43: 'Selamat!',
    44: 'Kamu telah sukses menamatkan tutorial, have fun!',
    45: 'uploader'
  },
  drag: {
    0: 'Klik disini',
    1: 'atau tarik dan lepas gambar di sini'
  },
  footer: {
    0: 'Dibuat oleh cyperdark',
    1: 'Credit',
    2: 'Peraturan',
    3: 'Kontak'
  },
  credits: {
    0: 'Chibi',
    1: 'Art',
    2: 'Ikon',
    3: 'Semua ikon diambil dari {name}',
    4: 'Bendera',
    5: 'Semua gambar bendera diambil dari {name}',
    6: 'Lokalisasi',
    7: 'Seseorang? [{lang}]',
    8: 'Sepertinya, cyperdark lupa menambahkan mereka. {text}'
  },
  search: {
    0: 'Cari Skin',
    1: 'Dilihat',
    2: 'Judul',
    3: 'Penilaian',
    4: 'Ukuran',
    5: 'Tanggal',
    7: 'Tidak menemukan apapun',
    8: 'Coba gunakan filter pencarian yang berbeda',
    9: 'Menunggu pencarian',
    10: 'Gunakan filter pencarian atau ketik nama skin, pembuat atau label',
    11: 'Unduh',
    12: 'Nama',
    13: {
      0: 'Skin',
      1: 'Label',
      2: 'Pengguna',
      3: 'Daftar'
    },
    14: 'Cari:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Kontes',
    1: 'Berita resmi',
    2: 'Pengajuan',
    3: 'Persiapan',
    4: 'Pemungutan suara',
    5: 'Diselesaikan',
    6: 'Kontes',
    7: 'Voting page'
  },
  rules: {
    0: 'Terakhir diperbarui pada',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} dari {max} telah terselesaikan',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'Cari',
    1: 'Edit',
    2: 'Daftar'
  },
  undefined: {
    0: 'Kosong',
    1: 'Sayangnya, disini tidak ada apa-apa, tetapi kamu bisa melihat halaman yang lain',
    2: 'Sayangnya, disini tidak ada apa-apa',
    3: 'Tidak diizinkan',
    4: 'Kemu perlu masuk untuk mengedit skin ini.',
    5: 'Kamu perlu masuk untuk menambahkan skin baru.'
  },
  settings: {
    0: 'Pengaturan',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.',
    5: 'English comments',
    6: 'Show English translation of the comments'
  },
  meta: {
    title: {
      0: 'Temukan skin osu',
      1: 'Mode permainan, aspek rasio dari skin osu',
      2: 'osu! skin yang populer',
      3: 'Cari skin osu!',
      4: 'Daftar label, {name}',
      5: 'Skin osu! {name} v{version}',
      6: 'Credit',
      7: 'skin - skin osu!',
      8: 'Pencarian skin osu! {name}',
      9: 'Dapatkan inspirasi dari skin lain',
      10: '{name} membuat skin osu!',
      11: 'Cari label',
      12: '{name} tags ditemukan',
      13: 'Skin baru',
      14: 'Peraturan',
      15: 'Kontes osu!',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: 'Dapatkan skin osu! terbaik di website kami! Kami menyediakan berbagai skin untuk berbagai macam mode, aspek rasio, dan dari player ternama. Oh ya! Kami juga menyediakan khusus bagi user yang menyukai anime untuk mencari skin yang mengandung karakter atau anime. Kembangkan pengalaman bermain osu! mu dengan skin terbaik!! #osuskins #osugame #anime',
      1: 'Dilihat {views} kali, Skin ini bisa digunakan untuk mode {modes}, Ukuran skin ini adalah {size}, Dibuat oleh {creators}. Bisa digunakan untuk rasio layar {ratios}',
      2: 'Temukan skin osu! terbaik dengan menggunakan fitur pencarian kami. Kami menyediakan berbagai skin yang bisa dicari sesuai mode, aspek rasio layar, dan yain lain - lain. Kami juga menyediakan skin populer yang digunakan oleh pemain ternama.',
      3: 'Temukan berbagai skin untuk berbagai mode permainan dan rasio aspek di website kami. Pilih dari mode standard, catch the beat, mania, dan taiko. Temukan yang paling cocok untuk preferensi game Anda.',
      4: 'Temukan skin osu! terbaik dari para player ternama di website kami. Jelajahi koleksi skin populer kami dan sesuaikan dengan gameplay Anda. Temukan berbagai macam gaya dan tema yang cocok dengan preferensi Anda.',
      5: 'Daftar tag yang tersedia untuk skin osu.',
      6: 'Koleksi skin {name} untuk osu!, unduh gratis',
      7: 'Tersedia banyak sekali skin osu! untuk {name}, unduh secara gratis!',
      8: 'Semua skin osu! yang dibuat oleh {name}',
      9: 'Cari inspirasi untuk skin osu! mu pada website kami. Jelajahi berbagai macam koleksi skin, dan temukan teknik dan ide baru. Dapatkan inspirasi dan buat skin unik Anda sendiri.',
      10: 'Cari label diantara semua label disitus.',
      11: 'List dari seluruh aktif/selesai kontes osu!',
      12: '{amount} Jumlah entri untuk kontes {title}, {views} dibaca'
    }
  },
  buttons: {
    0: 'Masuk',
    1: 'Halaman utama',
    profile_osu: 'Profil osu!',
    new_skin: 'Skin baru',
    notifications: 'Notifikasi',
    settings: 'Pengaturan',
    logout: 'Keluar',
    load_more: 'Muat lebih',
    copy_short: 'Salin link pendek',
    copied: 'Disalin',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Kembali ke skin',
    source: 'Source',
    contest_voting: 'Vote di sini',
    rules_agree: 'Aku setuju',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Opsional',
    1: 'Dibutuhkan',
    2: 'Tambahkan setidaknya satu opsi'
  },
  user: {
    roles: {
      0: 'Pembuat',
      1: 'Mixer',
      2: 'Animasi',
      3: 'Art',
      4: 'Collab',
      5: 'Suara',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: 'Dilihat: {amount}',
    1: 'Perbarui Hasil',
    2: 'Turun | Naik',
    3: 'Suka: {likes} / Tidak suka: {dislikes}',
    4: 'Tekan ctrl+enter untuk menambahkan label',
    5: 'Edit versi',
    6: '{s}Masuk{p}, agar bisa menilai skin ini',
    7: 'Tidak ada deskripsi singkat',
    8: 'Tidak ada URL',
    9: 'Unduh: {amount}',
    10: 'Reset semuanya',
    11: 'Liat paduan',
    12: 'Tutup paduan',
    13: 'Untuk menandai sebuah peraturan sebagai terbaca, hover ke peraturan (kuning menandakan tidak terbaca)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Selamat datang',
      1: 'Menu utama',
      2: 'Pilihan lagu',
      3: 'Menu mode',
      4: 'Mod',
      5: 'Hitung mundur',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Layar Jeda',
      11: 'Layar Gagal',
      12: 'Layar Hasil',
      13: 'Lewati',
      14: 'Banner',
      15: 'Hasil layar (bagian bawah)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Campuran'
    }
  },
  select: {
    0: 'Baru',
    1: 'Perbaikan',
    2: 'Perubahan',
    3: 'Dihapus',
    4: 'Art',
    5: 'Font',
    6: 'Artis',
    7: 'Elemen skin',
    8: 'Audio/SFX',
    9: 'Alat',
    10: 'Gambar',
    views: 'Dilihat',
    likes: 'Suka',
    dislikes: 'Tidak suka',
    downloads: 'Unduh',
    ratio: 'Pilih aspek rasio | rasio',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Pilih peran',
    1: 'Pilih versi',
    2: 'Ketikan sesuatu...',
    3: 'Select size range',
    4: 'Pilih rentang tanggal',
    5: 'Tahun',
    6: 'Bulan',
    7: 'Pilih aspek rasio',
    8: 'Pilih kategori',
    9: 'Gamemode',
    10: 'Pilih tipe',
    11: 'Tempel link YouTube',
    12: 'Tulis deskripsi dan url. Format: deskripsi:url',
    13: 'Pilih ekstra',
    14: 'Tempel link',
    15: 'Judul, pembuat, atau label skin',
    16: 'Pilih kategori',
    17: 'Ketik nama dari label',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Kontribusi' },
  nsfw: {
    0: 'Peringatan nsfw!',
    1: 'Terdapat konten sensitif atau dewasa pada skin ini',
    2: 'Terdapat konten sensitif atau dewasa pada skin ini yang mungkin mengganggu sebagian orang',
    3: 'Baiklah',
    4: 'dadah o/',
    5: 'Peringatan Furry!'
  },
  removed: {
    0: 'Versi tidak tersedia',
    1: 'Pembuat skin memilih untuk menghapus versi ini dari situs.',
    2: 'Beralih ke skin yang tersedia'
  },
  notify: {
    0: 'Masalah belum diperbaiki',
    1: 'Tidak semua boks di isi',
    2: 'Tampilkan',
    3: 'Tidak ditemukan',
    4: 'Banner tidak ditemukan (untuk sekarang, screenshot pertama sedang di gunakan sebagai banner)',
    5: 'Tidak ada perubahan',
    6: 'Tidak ada perubahan yang ditemukan',
    7: 'ID tidak ditemukan',
    8: 'ID video tidak ditemukan, silahkan coba link yang lain (Saat ini hanya YouTube yang didukung)',
    9: 'Ups',
    10: 'Sepertinya sesi-mu berakhir, mohon untuk membuka page baru dan log in ke akun mu (Jangan khawatir, semuanya telah di save secara otomatis)',
    11: 'Ada',
    12: 'Video ini telah ditambahkan',
    13: 'Ada',
    14: 'Label ini telah ditambahkan',
    15: 'Tidak ditemukan',
    16: 'Kamu tidak bisa menghapus tag yang sudah di hapus',
    17: 'Ditambahkan',
    18: 'Kamu telah berhasil menambahkan label baru',
    19: 'Ups',
    20: 'Pembuat ini telah ditambahkan',
    21: 'EZ',
    22: 'Pembuat baru telah ditambahkan',
    23: 'HUH',
    24: 'Tidak mungkin untuk menghapus creator (telah dihapus)',
    25: 'Terduplikat',
    26: 'Perubahan ini telah ditambahkan.',
    27: 'Terduplikat',
    28: 'URL ini telah ditambahkan.',
    29: 'Peringatan',
    30: 'Kamu lupa menambahkan deskripsi untuk url. Contoh: Deskripsi:url',
    31: 'Peringatan',
    32: 'Kamu lupa menambahkan url untuk deskripsi. Contoh: Deskripsi:url',
    33: 'Dipulihkan',
    34: 'Versi «{name}» telah dipulihkan',
    35: 'Dihapus',
    36: 'Versi «{name}» telah dihapus',
    37: 'Eror',
    38: 'Rupanya server menganggap anda robot.',
    39: 'Sesi login kamu telah habis. untuk melanjutkan, mohon untuk membuka laman baru dan masuk kembali ke akunmu. Setelah itu, kembali ke laman ini dah coba lagi.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Kesalahan tidak diketahui',
    42: 'Kamu tidak dapat mengedit skin yang tidak ada',
    43: 'Sepertinya kamu tidak memiliki izin untuk mengedit skin ini',
    44: 'Kamu tidak bisa mengirim versi ini karena ini sama dengan versi sebelumnya.',
    45: 'Perubahan ini telah dikirim untuk moderasi',
    46: 'Sukses',
    47: 'Perubahan baru telah dikirim untuk moderasi',
    48: 'Perubahan telah diperbarui dalam moderasi',
    49: 'Link aneh',
    50: 'Tautan ini tidak dapat digunakan sebagai tautan unduhan',
    51: 'Dikirimkan untuk moderasi',
    52: 'Peringatan',
    53: 'Kamu butuh memilih tipe aset',
    54: 'Skin ini sedang di moderasi. Harap bersabar selagi skinnya di proses',
    55: 'Sukses',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'Notifikasi',
    1: 'Ikuti kami di platform ini untuk menerima pemberitahuan tentang skin baru'
  },
  restricted_view: {
    0: 'Tidak diizinkan',
    1: 'Mohon masuk ke akun anda',
    2: 'Penglihatan terbatas',
    3: 'Halaman ini belum keluar.'
  },
  confirm: {
    0: 'Reset semuanya?',
    1: 'Show guide?',
    2: 'Kirim skin?',
    3: 'Iya',
    4: 'Tidak',
    5: 'Reset .ini?'
  }
};