export default {
  title: {
    home: 'Pagina',
    login: 'Accedi',
    lists: { 0: 'Liste' },
    tags: {
      0: 'Tags',
      1: '{amount} tag per la categoria {name}',
      2: 'Tag di ricerca'
    },
    ideas: {
      0: 'Ispirazioni',
      1: '«{amount}»'
    },
    sounds: { 0: 'Suoni' },
    leaderboard: { 0: 'Classifiche' },
    extend: { 0: 'Di più | Di meno' },
    skin: {
      0: 'Questa skin contiene elementi da altre skin',
      1: 'Clicca qui per maggiori informazioni'
    },
    tools: 'Strumenti'
  },
  home: {
    0: 'Disponibile per il download',
    1: 'Le skin _name_',
    2: 'Viste | Piaciute | Scaricate',
    3: 'Pubblica una nuova skin',
    4: 'Come installare una skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Changelog',
    1: 'Lista di tutte le revisioni fatte nella versione corrente',
    2: 'Niente qui',
    3: 'Ma puoi aggiungere le modifiche apportate a questa versione della skin',
    4: 'Non raggruppato',
    5: 'Nuovo',
    6: 'Correzioni',
    7: 'Cambiamenti',
    8: 'Eliminazioni'
  },
  ideas: {
    0: 'Trovato niente',
    1: 'Screenshot di «{type}» non sono stati caricati sul sito'
  },
  creators: {
    0: 'Creatori',
    1: 'Lista tutti i creatori che si sono impegnati nel fare questa versione',
    2: 'Nessuno è qui',
    3: 'Cercare il nome di un player mostrerà una lista di profili.',
    4: 'Editor',
    5: 'Ruoli',
    6: 'Versioni'
  },
  tags: {
    0: 'Tags',
    1: 'Lista delle tag di questa skin',
    2: 'Sembra vuoto qui.',
    3: 'Utilizza il campo in alto per trovare nuovi tag',
    4: 'Tag non trovate',
    5: 'Prova a cercare qualcos\'altro',
    6: 'Cerca'
  },
  videos: {
    0: 'Video',
    1: 'Elenco di tutte le immagini di questa skin',
    2: 'Zero immagini',
    3: 'Cerca su Youtube o crea la tua immagine'
  },
  sources: {
    0: 'Attribuzioni',
    1: 'Elenco di tutte le risorse o strumenti utilizzati nella versione della skin',
    2: 'Abbastanza vuoto qui',
    3: 'Se hai utilizzato risorse di altre skin o arti, assicurati di aggiungerle nella casella in alto',
    4: 'Non raggruppato'
  },
  checks: {
    0: 'Tutti',
    1: 'Metadata',
    2: 'Momenti salienti',
    3: 'Nome della skin non specificato',
    4: 'Aggiungi almeno un creatore di skin',
    5: 'Aggiungi un paio di tags',
    6: 'Peso della skin non specificato',
    7: 'Seleziona al meno una modalità',
    8: 'Seleziona tipo del file (SD o HD)',
    9: 'Seleziona almeno un formato',
    10: 'Nessuno screenshot fornito',
    11: 'Aggiungi almeno uno screenshot del gameplay',
    12: 'Link alla skin non specificato',
    20: 'Qui non c\'è nessun errore',
    21: 'Tutti gli errori sono stati risolti. Ottimo lavoro!',
    22: 'Lista di controllo',
    23: 'Aggiungi almeno una versione pubblica',
    24: 'Aggiungi almeno un creatore a questa versione',
    25: 'Qualche creatore non ha i ruoli'
  },
  skins: {
    0: 'Skins',
    1: 'Popolari',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recenti',
    5: 'Random',
    6: 'Tutte le skins',
    7: 'Formato',
    8: 'Tutte le skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins di {name} | Tutte le skins da',
    11: 'Cerca',
    12: 'skin di {name}',
    13: 'Esplora le skin'
  },
  skin: {
    0: 'Edita',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animazione',
    5: 'Screenshots',
    6: 'Solo gameplay',
    7: 'Link download | Scarica skin',
    8: 'Post forum | Forum di osu!',
    9: 'Reddit post',
    10: 'Creatori',
    11: 'Tags',
    13: 'Video',
    14: 'Nuova Versione | Gestisci le versioni',
    15: 'Aggiorna | Invia',
    16: 'Modalità',
    17: 'Nome della skin',
    18: 'Versione | Versioni',
    19: 'Peso',
    20: 'Metadata',
    21: 'Valutazione',
    22: 'Downloads',
    23: 'Il download sarà disponibile presto',
    24: '{amount} secondi rimanenti',
    25: 'Non sei uno di noi',
    26: 'Sembra che tu non sia l\'autore o un editor di questa skin',
    27: 'Skin di',
    28: 'Nessun tag',
    29: 'Nessun video',
    30: 'Nessun creatore',
    31: 'Valuta la skin',
    32: 'Upvota e commenta su reddit',
    33: 'Commenta nel forum di osu!',
    34: 'Più skin di questo autore | Più skin di questi autori',
    35: 'Supporta la skin',
    36: 'Non disponibile',
    37: 'Sfortunatamente, la skin è stata eliminata dall\'autore ({author}) per scelta sua',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!'
  },
  drag: {
    0: 'Clicca qui',
    1: 'o trascina e rilascia le immagini'
  },
  footer: {
    0: 'Fatto da cyperdark',
    1: 'Crediti',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Arti',
    2: 'Icone',
    3: 'Tutte le icone sono state prese da {nome}',
    4: 'Bandiere',
    5: 'Tutte le immagini delle bandiere sono da {nome}',
    6: 'Localizzazione',
    7: 'C\'è qualcuno?',
    8: 'Sembra che cyperdark abbia dimenticato di aggiungerli. {text}'
  },
  search: {
    0: 'Ricerca skin',
    1: 'Visualizzazioni',
    2: 'Titolo',
    3: 'Valutazione',
    4: 'Peso',
    5: 'Data',
    7: 'Trovato niente',
    8: 'Prova a usare filtri di ricerca diversi',
    9: 'In attesa di una domanda',
    10: 'Usa i filtri di ricerca o digita il titolo, l\'autore oi tag della skin',
    11: 'Downloads',
    12: 'Nome',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Utenti',
      3: 'Liste'
    },
    14: 'Cerca:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished'
  },
  tabs: {
    0: 'Cerca',
    1: 'Edita',
    2: 'Lista'
  },
  undefined: {
    0: 'Vuoto',
    1: 'Sfortunatamente, non c\'è niente qui, però puoi andare a dare un\'occhiata alle altre pagine',
    2: 'Sfortunatamente, non c\'è niente qui',
    3: 'Non Autorizzato',
    4: 'Devi essere loggato per poter modificare questa skin.',
    5: 'Devi essere loggato per poter aggiungere una nuova skin.'
  },
  meta: {
    title: {
      0: 'Scopri le skin di osu',
      1: 'Modalità di gioco, proporzioni osu skin',
      2: 'Osu skin popolari',
      3: 'Cerca osu skins',
      4: '«{name}» tags lista',
      5: '{name} v{version} osu skin',
      6: 'Crediti',
      7: 'osu skins',
      8: '{name} cerca osu skins',
      9: 'Prendi ispirazione da altre skin',
      10: '{name} ha creato la skin',
      11: 'Tag di ricerca',
      12: '{name} tag trovati',
      13: 'Nuova skin',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! Contests'
    },
    description: {
      0: 'Ottieni le migliori skin di osu! sul nostro sito! La nostra vasta libreria ha skin per tutte le modalità di gioco, proporzioni e persino per i migliori giocatori. Inoltre, abbiamo una sezione speciale per i fan degli anime. Migliora il tuo gameplay con la skin perfetta. #osuskins #osugame #anime',
      1: '{views} visualizzazioni. Una skin osu per {modes}, il suo peso è {size}, creata da {creators}. Supporta {ratios}',
      2: 'Trova la skin perfetta con la nostra funzione di ricerca avanzata. Sfoglia la nostra vasta libreria, filtrata per modalità di gioco, proporzioni e altro. Oppure dai un\'occhiata alle skin utilizzate dai migliori giocatori',
      3: 'Scopri una varietà di skin per diverse modalità di gioco e proporzioni dello schermo sul nostro sito. Scegli fra standard, catch the beat, mania e taiko. Trova la soluzione perfetta per le tue preferenze di gioco.',
      4: 'Trova la skin osu perfetta dai migliori giocatori sul nostro sito. Sfoglia la nostra raccolta di skin popolari e personalizza il tuo gameplay. Scopri una vasta gamma di stili e temi per soddisfare le tue preferenze.',
      5: 'Elenco dei tag esistenti per le skin osu.',
      6: '{name} collezione di skin osu!, download gratuito',
      7: 'Un\'enorme quantità di skin osu per {name}, scarica gratis!',
      8: 'Tutte le skin osu create da {name}',
      9: 'Trova l\'ispirazione per la tua prossima osu! skin sul nostro sito. Sfoglia una vasta collezione di skin e scopri nuove tecniche e idee. Lasciati ispirare e crea le tue skin uniche.',
      10: 'Cerca i tag tra tutti i tag presenti sul sito.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Accedi',
    1: 'Pagina iniziale',
    profile_osu: 'osu! Profile',
    new_skin: 'Nuova skin',
    notifications: 'Notifiche',
    settings: 'Impostazioni',
    logout: 'Disconnettiti',
    load_more: 'Carica altro',
    copy_short: 'Copia link corto',
    copied: 'Copiato',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Ritorna alla skin',
    source: 'Source',
    contest_voting: 'Vote here'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Creatore',
      1: 'Mixer',
      2: 'Animazioni',
      3: 'Arti',
      4: 'Collaborazioni'
    }
  },
  tooltips: {
    0: 'Visualizzazioni: {amount}',
    1: 'Ricarica risultati',
    2: 'Discendente | Ascendente',
    3: 'Mi piace: {likes} / Non mi piace: {dislikes}',
    4: 'Premi ctrl+enter per aggiungere una tag',
    5: 'Modifica versione',
    6: 'Fai il {s}Log In{p} per valutare questa skin',
    7: 'Non c\'è una descrizione corta',
    8: 'Senza url',
    9: 'Download: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)'
  },
  lists: {
    screens: {
      0: 'Benvenuto',
      1: 'Menu principale',
      2: 'Seleziona canzone',
      3: 'Menu modalità',
      4: 'Mods',
      5: 'Conto alla rovescia',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sezione Passata',
      9: 'Sezione Fallita',
      10: 'Schermo di pausa',
      11: 'Fail Screen',
      12: 'Schermo dei risultati',
      13: 'Salta',
      14: 'Banner',
      15: 'Result screen (bottom)'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Nuovo',
    1: 'Aggiustato',
    2: 'Cambiato',
    3: 'Rimosso',
    4: 'Arti',
    5: 'Fonti',
    6: 'Artisti',
    7: 'Elementi della skin',
    8: 'Audio/Effetti',
    9: 'Strumenti',
    views: 'Visualizzazioni',
    likes: 'Mi piace',
    dislikes: 'Non mi piace',
    downloads: 'Downloads',
    size_range: 'Seleziona peso',
    date_range: 'Seleziona una data',
    ratio: 'Seleziona proporzioni | ratio'
  },
  placeholders: {
    0: 'Seleziona i ruoli',
    1: 'Seleziona la versione',
    2: 'Scrivi un po\' di testo...',
    3: 'Seleziona peso',
    4: 'Seleziona una data',
    5: 'Anno',
    6: 'Mese',
    7: 'Seleziona proporzioni',
    8: 'Seleziona categorie',
    9: 'Modalità',
    10: 'Seleziona tipo',
    11: 'Incolla un link YouTube',
    12: 'Digita una descrizione e un url. Formato: descrizione:url',
    13: 'Seleziona extra',
    14: 'Incolla un link',
    15: 'Titolo skin, autore o tag',
    16: 'Seleziona categoria',
    17: 'Scrivi il nome del tag'
  },
  contribute: { 0: 'Contribuisci' },
  nsfw: {
    0: 'Attenzione, nsfw!',
    1: 'Questa skin contiene contenuti sensibili o per adulti',
    2: 'Questa skin contiene contenuti sensibili o per adulti che alcuni utenti possono trovare disturbanti',
    3: 'Va bene',
    4: 'bye o/',
    5: 'Avviso Furry!'
  },
  removed: {
    0: 'Versione non disponibile',
    1: 'L\'autore di questa skin ha deciso di rimuovere questa versione dal sito.',
    2: 'Passa a una versione disponibile'
  },
  notify: {
    0: 'L\'errore non è stato risolto',
    1: 'Non tutti i campi obbligatori sono stati compilati',
    2: 'Mostra',
    3: 'Nessun risultato',
    4: 'Banner non trovato (Per ora, il primo screenshot viene utilizzato come banner)',
    5: 'Nessuna modifica',
    6: 'Nessuna modifica è stata trovata',
    7: 'ID non trovato',
    8: 'ID del video non trovato, prova un altro link (Al momento solo YouTube è supportato)',
    9: 'Oops',
    10: 'Sembra che la tua sessione sia scaduta, apri una nuova pagina e accedi al tuo account (non preoccuparti, tutto è stato salvato automaticamente)',
    11: 'Esiste',
    12: 'Questo video è già stato aggiunto',
    13: 'Esiste',
    14: 'Questo tag è già stato aggiunto',
    15: 'Nessun risultato',
    16: 'Non puoi eliminare un tag eliminato',
    17: 'Aggiunto',
    18: 'Hai aggiunto con successo una nuova tag',
    19: 'OOps',
    20: 'Questo creatore è già stato aggiunto',
    21: 'EZ',
    22: 'Un nuovo creatore è stato aggiunto',
    23: 'HUH',
    24: 'Impossibile rimuovere un creatore eliminato',
    25: 'Duplicato',
    26: 'Questa modifica è già stata fatta in precedenza.',
    27: 'Duplicato',
    28: 'Questo url è già stato messo in precedenza.',
    29: 'Attenzione',
    30: 'Hai dimenticato di aggiungere una descrizione al url, ad esempio: Descrizione:url',
    31: 'Attenzione',
    32: 'Hai dimenticato di aggiungere l\'url per la descrizione. Esempio: Descrizione:url',
    33: 'Ripristinato',
    34: 'La versione «{name}» è stata ripristinata',
    35: 'Eliminato',
    36: 'La versione «{name}» è stata eliminata',
    37: 'Errore',
    38: 'A quanto pare, il server pensa che sei un robot.',
    39: 'Sembra che la tua sessione utente sia scaduta, apri una nuova pagina e accedi al tuo account (non preoccuparti, tutto è stato salvato automaticamente)',
    40: 'Le credenziali non corrispondono (accedi di nuovo all\'account. Non preoccuparti, tutto è stato salvato automaticamente)',
    41: 'Errore sconosciuto',
    42: 'Non puoi modificare una skin inesistente',
    43: 'Sembra che tu non abbia il permesso di modificare questa skin',
    44: 'Non puoi inviare questa versione perché è la stessa versione di quella precedente.',
    45: 'Queste modifiche sono già state inviate per moderazione',
    46: 'Successo',
    47: 'Le nuove modifiche sono state presentate per moderazione',
    48: 'I cambiamenti sono stati aggiornati in moderazione',
    49: 'Collegamento strano',
    50: 'Questo link non può essere utilizzato come link per il download',
    51: 'Inviato per moderazione',
    52: 'Attenzione',
    53: 'You need to choose type of asset'
  },
  header: {
    0: 'Notifiche',
    1: 'Seguici in queste piattaforme per ricevere notifiche delle nuove skin'
  },
  restricted_view: {
    0: 'Non Autorizzato',
    1: 'Per favore, accedi al tuo account',
    2: 'Visualizzazione ristretta',
    3: 'Questa pagina non è ancora accessibile.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No'
  }
};