export default {
  title: {
    home: 'Pagina',
    login: 'Accedi',
    lists: { 0: 'Liste' },
    tags: {
      0: 'Tags',
      1: '{amount} tag per la categoria {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Ispirazioni',
      1: '«{amount}»'
    },
    sounds: { 0: 'Suoni' },
    leaderboard: { 0: 'Classifiche' },
    extend: { 0: 'Di più | Di meno' },
    skin: {
      0: 'Questa skin contiene elementi da altre skin',
      1: 'Clicca qui per maggiori informazioni'
    },
    tools: 'Strumenti'
  },
  changelogs: {
    0: 'Changelog',
    1: 'Lista di tutte le revisioni fatte nella versione corrente',
    2: 'Niente qui',
    3: 'Ma puoi aggiungere i cambiamenti che hai fatto su questa versione della skin',
    4: 'Non raggruppato',
    5: 'Nuovo',
    6: 'Correzioni',
    7: 'Cambiamenti',
    8: 'Eliminazioni'
  },
  ideas: {
    0: 'Nothing founed',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Creatori',
    1: 'Lista tutti i creatori che si sono impegnati nel fare questa versione',
    2: 'Nessuno è qui',
    3: 'Cercare il nome di un player mostrerà una lista di profili.',
    4: 'Editor',
    5: 'Ruoli',
    6: 'Versioni'
  },
  tags: {
    0: 'Tags',
    1: 'Lista delle tag di questa skin',
    2: 'Sembra vuoto qui.',
    3: 'Utilizza il campo in alto per trovare nuovi tag',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Cerca'
  },
  videos: {
    0: 'Video',
    1: 'Elenco di tutte le immagini di questa skin',
    2: 'Zero immagini',
    3: 'Cerca su Youtube o crea la tua immagine'
  },
  sources: {
    0: 'Attribuzioni',
    1: 'Elenco di tutte le risorse o strumenti utilizzati nella versione della skin',
    2: 'Abbastanza vuoto qui',
    3: 'Se hai utilizzato risorse di altre skin o arti, assicurati di aggiungerle nella casella in alto',
    4: 'Non raggruppato'
  },
  checks: {
    0: 'Tutti',
    1: 'Metadata',
    2: 'Momenti salienti',
    3: 'Name of the skin not specified',
    4: 'Aggiungi almeno un creatore di skin',
    5: 'Aggiungi un paio di tags',
    6: 'Peso della skin non specificato',
    7: 'Seleziona al meno una modalità',
    8: 'Seleziona tipo del file (SD o HD)',
    9: 'Seleziona almeno un formato',
    10: 'Nessuno screenshot fornito',
    11: 'Aggiungi almeno uno screenshot del gameplay',
    12: 'Link alla skin non specificato',
    20: 'Sembra piuttosto buono',
    21: 'Ogni singolo problema è stato risolto, il che è abbastanza buono',
    22: 'Lista di controllo',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Popolari',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recenti',
    5: 'Random',
    6: 'Tutte le skins',
    7: 'Formato',
    8: 'Tutte le skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins di {name} | Tutte le skins da',
    11: 'Cerca',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Edita',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animazione',
    5: 'Screenshots',
    6: 'Solo gameplay',
    7: 'Link download | Scarica skin',
    8: 'Post forum | Forum di osu!',
    9: 'Reddit post',
    10: 'Creatori',
    11: 'Tags',
    13: 'Video',
    14: 'Nuova Versione | Gestisci le versioni',
    15: 'Aggiorna | Invia',
    16: 'Modalità',
    17: 'Nome della skin',
    18: 'Versione | Versioni',
    19: 'Peso',
    20: 'Metadata',
    21: 'Valutazione',
    22: 'Downloads',
    23: 'Il download sarà disponibile presto',
    24: '{amount} secondi rimanenti',
    25: 'Non sei uno di noi',
    26: 'Sembra che tu non sia l\'autore o un editor di questa skin',
    27: 'Skin di',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Clicca qui',
    1: 'o trascina e rilascia le immagini'
  },
  footer: {
    0: 'Fatto da cyperdark',
    1: 'Crediti'
  },
  credits: {
    0: 'Chibi',
    1: 'Arti',
    2: 'Icone',
    3: 'Tutte le icone sono state prese da {nome}',
    4: 'Bandiere',
    5: 'Tutte le immagini delle bandiere sono da {nome}',
    6: 'Localizzazione',
    7: 'C\'è qualcuno?',
    8: 'Sembra che cpol si sia dimenticato di aggiungerli.'
  },
  search: {
    0: 'Ricerca skin',
    1: 'Visualizzazioni',
    2: 'Titolo',
    3: 'Valutazione',
    4: 'Peso',
    5: 'Data',
    7: 'Trovato niente',
    8: 'Prova a impostare criteri di ricerca diversi',
    9: 'In attesa di una domanda',
    10: 'Seleziona i criteri di ricerca o scrivi semplicemente il titolo della skin, l\'autore o il tag',
    11: 'Downloads',
    12: 'Nome',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Users',
      3: 'Liste'
    }
  },
  tabs: {
    0: 'Cerca',
    1: 'Edita',
    2: 'Lista'
  },
  undefined: {
    0: 'Vuoto',
    1: 'Purtroppo non c\'è niente qui, comunque puoi guardare altre pagine',
    2: 'Purtroppo non c\'è niente qui',
    3: 'Non Autorizzato',
    4: 'Devi aver eseguito l\'accesso per modificare questa skin.',
    5: 'Devi aver eseguito l\'accesso per aggiungere una nuova skin.'
  },
  meta: {
    title: {
      0: 'Scopri le skin di osu',
      1: 'Modalità di gioco, proporzioni osu skin',
      2: 'Osu skin popolari',
      3: 'Cerca osu skins',
      4: '«{name}» tags lista',
      5: '{name} v{version} osu skin',
      6: 'Crediti',
      7: 'osu skins',
      8: '{name} cerca osu skins',
      9: 'Prendi ispirazione da altre skin',
      10: '{name} ha creato la skin',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Ottieni le migliori skin di osu! sul nostro sito! La nostra vasta libreria ha skin per tutte le modalità di gioco, proporzioni e persino per i migliori giocatori. Inoltre, abbiamo una sezione speciale per i fan degli anime. Migliora il tuo gameplay con la skin perfetta. #osuskins #osugame #anime',
      1: '{views} visualizzazioni. Una skin osu per {modes}, il suo peso è {size}, creata da {creators}. Supporta {ratios}',
      2: 'Trova la skin perfetta con la nostra funzione di ricerca avanzata. Sfoglia la nostra vasta libreria, filtrata per modalità di gioco, proporzioni e altro. Oppure dai un\'occhiata alle skin utilizzate dai migliori giocatori',
      3: 'Scopri una varietà di skin per diverse modalità di gioco e proporzioni dello schermo sul nostro sito. Scegli fra standard, catch the beat, mania e taiko. Trova la soluzione perfetta per le tue preferenze di gioco.',
      4: 'Trova la skin osu perfetta dai migliori giocatori sul nostro sito. Sfoglia la nostra raccolta di skin popolari e personalizza il tuo gameplay. Scopri una vasta gamma di stili e temi per soddisfare le tue preferenze.',
      5: 'Elenco dei tag esistenti per le skin osu.',
      6: '{name} collezione di skin osu!, download gratuito',
      7: 'Un\'enorme quantità di skin osu per {name}, scarica gratis!',
      8: 'Tutte le skin osu create da {name}',
      9: 'Trova l\'ispirazione per la tua prossima osu! skin sul nostro sito. Sfoglia una vasta collezione di skin e scopri nuove tecniche e idee. Lasciati ispirare e crea le tue skin uniche.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Accedi',
    1: 'Pagina iniziale',
    profile_osu: 'osu! Profile',
    new_skin: 'Nuova skin',
    notifications: 'Notifiche',
    settings: 'Impostazioni',
    logout: 'Disconnettiti',
    load_more: 'Carica altro',
    copy_short: 'Copia link corto',
    copied: 'Copiato',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Ritorna alla skin'
  },
  user: {
    roles: {
      0: 'Creatore',
      1: 'Mixer',
      2: 'Animazioni',
      3: 'Arti',
      4: 'Collaborazioni'
    }
  },
  tooltips: {
    0: 'Visualizzazioni: {amount}',
    1: 'Ricarica risultati',
    2: 'Discendente | Ascendente',
    3: 'Mi piace: {likes} / Non mi piace: {dislikes}',
    4: 'Premi ctrl+enter per aggiungere una tag',
    5: 'Modifica versione',
    6: '{s}Log in{p}, per essere in grado di votare questa skin',
    7: 'Non c\'è una descrizione corta',
    8: 'Senza url',
    9: 'Download: {amount}'
  },
  lists: {
    screens: {
      0: 'Benvenuto',
      1: 'Menu principale',
      2: 'Seleziona canzone',
      3: 'Menu modalità',
      4: 'Mods',
      5: 'Conto alla rovescia',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sezione Passata',
      9: 'Sezione Fallita',
      10: 'Schermo di pausa',
      11: 'Fail Screen',
      12: 'Schermo dei risultati',
      13: 'Salta',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Nuovo',
    1: 'Aggiustato',
    2: 'Cambiato',
    3: 'Rimosso',
    4: 'Arti',
    5: 'Fonti',
    6: 'Artisti',
    7: 'Elementi della skin',
    8: 'Audio/Effetti',
    9: 'Strumenti',
    views: 'Visualizzazioni',
    likes: 'Mi piace',
    dislikes: 'Non mi piace',
    downloads: 'Downloads',
    size_range: 'Seleziona peso',
    date_range: 'Seleziona una data',
    ratio: 'Seleziona proporzioni | ratio'
  },
  placeholders: {
    0: 'Scegli ruoli',
    1: 'Scegli versioni',
    2: 'Scrivi testo...',
    3: 'Seleziona peso',
    4: 'Seleziona una data',
    5: 'Anno',
    6: 'Mese',
    7: 'Seleziona proporzioni',
    8: 'Seleziona categorie',
    9: 'Modalità',
    10: 'Seleziona tipo',
    11: 'Incolla un link YouTube',
    12: 'Scrivi descrizione e URL. Formato della descrizione:url',
    13: 'Seleziona extra',
    14: 'Incolla un link',
    15: 'Titolo della skin, autore, o tag',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Contribuisci' },
  nsfw: {
    0: 'Attenzione!',
    1: 'Questa skin contiene contenuti sensibili o per adulti',
    2: 'Questa skin contiene contenuti sensibili o per adulti che alcuni utenti possono trovare disturbanti',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Non Autorizzato',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};