export default {
  title: {
    home: 'Pagina',
    login: 'Accedi',
    lists: { 0: 'Liste' },
    tags: {
      0: 'Tags',
      1: '{amount} tag per la categoria {name}',
      2: 'Tag di ricerca'
    },
    ideas: {
      0: 'Ispirazioni',
      1: '«{amount}»'
    },
    sounds: { 0: 'Suoni' },
    leaderboard: { 0: 'Classifiche' },
    extend: { 0: 'Di più | Di meno' },
    skin: {
      0: 'Questa skin contiene elementi da altre skin',
      1: 'Clicca qui per maggiori informazioni'
    },
    tools: 'Strumenti'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin'
  },
  changelogs: {
    0: 'Changelog',
    1: 'Lista di tutte le revisioni fatte nella versione corrente',
    2: 'Niente qui',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Non raggruppato',
    5: 'Nuovo',
    6: 'Correzioni',
    7: 'Cambiamenti',
    8: 'Eliminazioni'
  },
  ideas: {
    0: 'Trovato niente',
    1: 'Screenshot di «{type}» non sono stati caricati sul sito'
  },
  creators: {
    0: 'Creatori',
    1: 'Lista tutti i creatori che si sono impegnati nel fare questa versione',
    2: 'Nessuno è qui',
    3: 'Cercare il nome di un player mostrerà una lista di profili.',
    4: 'Editor',
    5: 'Ruoli',
    6: 'Versioni'
  },
  tags: {
    0: 'Tags',
    1: 'Lista delle tag di questa skin',
    2: 'Sembra vuoto qui.',
    3: 'Utilizza il campo in alto per trovare nuovi tag',
    4: 'Tag non trovate',
    5: 'Prova a cercare qualcos\'altro',
    6: 'Cerca'
  },
  videos: {
    0: 'Video',
    1: 'Elenco di tutte le immagini di questa skin',
    2: 'Zero immagini',
    3: 'Cerca su Youtube o crea la tua immagine'
  },
  sources: {
    0: 'Attribuzioni',
    1: 'Elenco di tutte le risorse o strumenti utilizzati nella versione della skin',
    2: 'Abbastanza vuoto qui',
    3: 'Se hai utilizzato risorse di altre skin o arti, assicurati di aggiungerle nella casella in alto',
    4: 'Non raggruppato'
  },
  checks: {
    0: 'Tutti',
    1: 'Metadata',
    2: 'Momenti salienti',
    3: 'Nome della skin non specificato',
    4: 'Aggiungi almeno un creatore di skin',
    5: 'Aggiungi un paio di tags',
    6: 'Peso della skin non specificato',
    7: 'Seleziona al meno una modalità',
    8: 'Seleziona tipo del file (SD o HD)',
    9: 'Seleziona almeno un formato',
    10: 'Nessuno screenshot fornito',
    11: 'Aggiungi almeno uno screenshot del gameplay',
    12: 'Link alla skin non specificato',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Lista di controllo',
    23: 'Aggiungi almeno una versione pubblica',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Skins',
    1: 'Popolari',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recenti',
    5: 'Random',
    6: 'Tutte le skins',
    7: 'Formato',
    8: 'Tutte le skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins di {name} | Tutte le skins da',
    11: 'Cerca',
    12: 'skin di {name}',
    13: 'Esplora le skin'
  },
  skin: {
    0: 'Edita',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animazione',
    5: 'Screenshots',
    6: 'Solo gameplay',
    7: 'Link download | Scarica skin',
    8: 'Post forum | Forum di osu!',
    9: 'Reddit post',
    10: 'Creatori',
    11: 'Tags',
    13: 'Video',
    14: 'Nuova Versione | Gestisci le versioni',
    15: 'Aggiorna | Invia',
    16: 'Modalità',
    17: 'Nome della skin',
    18: 'Versione | Versioni',
    19: 'Peso',
    20: 'Metadata',
    21: 'Valutazione',
    22: 'Downloads',
    23: 'Il download sarà disponibile presto',
    24: '{amount} secondi rimanenti',
    25: 'Non sei uno di noi',
    26: 'Sembra che tu non sia l\'autore o un editor di questa skin',
    27: 'Skin di',
    28: 'Nessun tag',
    29: 'Nessun video',
    30: 'Nessun creatore',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin'
  },
  drag: {
    0: 'Clicca qui',
    1: 'o trascina e rilascia le immagini'
  },
  footer: {
    0: 'Fatto da cyperdark',
    1: 'Crediti'
  },
  credits: {
    0: 'Chibi',
    1: 'Arti',
    2: 'Icone',
    3: 'Tutte le icone sono state prese da {nome}',
    4: 'Bandiere',
    5: 'Tutte le immagini delle bandiere sono da {nome}',
    6: 'Localizzazione',
    7: 'C\'è qualcuno?',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Ricerca skin',
    1: 'Visualizzazioni',
    2: 'Titolo',
    3: 'Valutazione',
    4: 'Peso',
    5: 'Data',
    7: 'Trovato niente',
    8: 'Try using different search filters',
    9: 'In attesa di una domanda',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Downloads',
    12: 'Nome',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Utenti',
      3: 'Liste'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Cerca',
    1: 'Edita',
    2: 'Lista'
  },
  undefined: {
    0: 'Vuoto',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Non Autorizzato',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Scopri le skin di osu',
      1: 'Modalità di gioco, proporzioni osu skin',
      2: 'Osu skin popolari',
      3: 'Cerca osu skins',
      4: '«{name}» tags lista',
      5: '{name} v{version} osu skin',
      6: 'Crediti',
      7: 'osu skins',
      8: '{name} cerca osu skins',
      9: 'Prendi ispirazione da altre skin',
      10: '{name} ha creato la skin',
      11: 'Tag di ricerca',
      12: '{name} tag trovati',
      13: 'Nuova skin'
    },
    description: {
      0: 'Ottieni le migliori skin di osu! sul nostro sito! La nostra vasta libreria ha skin per tutte le modalità di gioco, proporzioni e persino per i migliori giocatori. Inoltre, abbiamo una sezione speciale per i fan degli anime. Migliora il tuo gameplay con la skin perfetta. #osuskins #osugame #anime',
      1: '{views} visualizzazioni. Una skin osu per {modes}, il suo peso è {size}, creata da {creators}. Supporta {ratios}',
      2: 'Trova la skin perfetta con la nostra funzione di ricerca avanzata. Sfoglia la nostra vasta libreria, filtrata per modalità di gioco, proporzioni e altro. Oppure dai un\'occhiata alle skin utilizzate dai migliori giocatori',
      3: 'Scopri una varietà di skin per diverse modalità di gioco e proporzioni dello schermo sul nostro sito. Scegli fra standard, catch the beat, mania e taiko. Trova la soluzione perfetta per le tue preferenze di gioco.',
      4: 'Trova la skin osu perfetta dai migliori giocatori sul nostro sito. Sfoglia la nostra raccolta di skin popolari e personalizza il tuo gameplay. Scopri una vasta gamma di stili e temi per soddisfare le tue preferenze.',
      5: 'Elenco dei tag esistenti per le skin osu.',
      6: '{name} collezione di skin osu!, download gratuito',
      7: 'Un\'enorme quantità di skin osu per {name}, scarica gratis!',
      8: 'Tutte le skin osu create da {name}',
      9: 'Trova l\'ispirazione per la tua prossima osu! skin sul nostro sito. Sfoglia una vasta collezione di skin e scopri nuove tecniche e idee. Lasciati ispirare e crea le tue skin uniche.',
      10: 'Cerca i tag tra tutti i tag presenti sul sito.'
    }
  },
  buttons: {
    0: 'Accedi',
    1: 'Pagina iniziale',
    profile_osu: 'osu! Profile',
    new_skin: 'Nuova skin',
    notifications: 'Notifiche',
    settings: 'Impostazioni',
    logout: 'Disconnettiti',
    load_more: 'Carica altro',
    copy_short: 'Copia link corto',
    copied: 'Copiato',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Ritorna alla skin'
  },
  user: {
    roles: {
      0: 'Creatore',
      1: 'Mixer',
      2: 'Animazioni',
      3: 'Arti',
      4: 'Collaborazioni'
    }
  },
  tooltips: {
    0: 'Visualizzazioni: {amount}',
    1: 'Ricarica risultati',
    2: 'Discendente | Ascendente',
    3: 'Mi piace: {likes} / Non mi piace: {dislikes}',
    4: 'Premi ctrl+enter per aggiungere una tag',
    5: 'Modifica versione',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Non c\'è una descrizione corta',
    8: 'Senza url',
    9: 'Download: {amount}'
  },
  lists: {
    screens: {
      0: 'Benvenuto',
      1: 'Menu principale',
      2: 'Seleziona canzone',
      3: 'Menu modalità',
      4: 'Mods',
      5: 'Conto alla rovescia',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sezione Passata',
      9: 'Sezione Fallita',
      10: 'Schermo di pausa',
      11: 'Fail Screen',
      12: 'Schermo dei risultati',
      13: 'Salta',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Nuovo',
    1: 'Aggiustato',
    2: 'Cambiato',
    3: 'Rimosso',
    4: 'Arti',
    5: 'Fonti',
    6: 'Artisti',
    7: 'Elementi della skin',
    8: 'Audio/Effetti',
    9: 'Strumenti',
    views: 'Visualizzazioni',
    likes: 'Mi piace',
    dislikes: 'Non mi piace',
    downloads: 'Downloads',
    size_range: 'Seleziona peso',
    date_range: 'Seleziona una data',
    ratio: 'Seleziona proporzioni | ratio'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Seleziona peso',
    4: 'Seleziona una data',
    5: 'Anno',
    6: 'Mese',
    7: 'Seleziona proporzioni',
    8: 'Seleziona categorie',
    9: 'Modalità',
    10: 'Seleziona tipo',
    11: 'Incolla un link YouTube',
    12: 'Type a description and an url. Format description:url',
    13: 'Seleziona extra',
    14: 'Incolla un link',
    15: 'Skin title, author, or tags',
    16: 'Seleziona categoria',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribuisci' },
  nsfw: {
    0: 'Attenzione!',
    1: 'Questa skin contiene contenuti sensibili o per adulti',
    2: 'Questa skin contiene contenuti sensibili o per adulti che alcuni utenti possono trovare disturbanti',
    3: 'Va bene',
    4: 'bye o/'
  },
  removed: {
    0: 'Versione non disponibile',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Mostra',
    3: 'Nessun risultato',
    4: 'Banner non trovato (Per ora, il primo screenshot viene utilizzato come banner)',
    5: 'Nessuna modifica',
    6: 'Nessuna modifica è stata trovata',
    7: 'ID non trovato',
    8: 'ID del video non trovato, prova un altro link (Al momento solo YouTube è supportato)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Esiste',
    12: 'Questo video è già stato aggiunto',
    13: 'Esiste',
    14: 'Questo tag è già stato aggiunto',
    15: 'Nessun risultato',
    16: 'Non puoi eliminare un tag eliminato',
    17: 'Aggiunto',
    18: 'Hai aggiunto con successo una nuova tag',
    19: 'OOps',
    20: 'Questo creatore è già stato aggiunto',
    21: 'EZ',
    22: 'Un nuovo creatore è stato aggiunto',
    23: 'HUH',
    24: 'Impossibile rimuovere un creatore eliminato',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Attenzione',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Attenzione',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Ripristinato',
    34: 'Version «{name}» has been restored',
    35: 'Eliminato',
    36: 'Version «{name}» has been deleted',
    37: 'Errore',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Errore sconosciuto',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Successo',
    47: 'Le nuove modifiche sono state presentate per moderazione',
    48: 'I cambiamenti sono stati aggiornati in moderazione',
    49: 'Collegamento strano',
    50: 'Questo link non può essere utilizzato come link per il download',
    51: 'Submitted for moderation'
  },
  header: {
    0: 'Notifiche',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Non Autorizzato',
    1: 'Please log into your account',
    2: 'Visualizzazione ristretta',
    3: 'Questa pagina non è ancora accessibile.'
  }
};