export default {
  title: {
    home: 'ホーム',
    login: 'ログイン',
    lists: { 0: 'リスト' },
    tags: {
      0: 'タグ',
      1: 'カテゴリ {name} の {amount} タグ',
      2: 'Search tags'
    },
    ideas: {
      0: 'インスピレーション',
      1: '«{amount}»'
    },
    sounds: { 0: '音' },
    leaderboard: { 0: 'リーダーボード' },
    extend: { 0: 'もっと見る | 折りたたむ' },
    skin: {
      0: 'このスキンは他のスキンからの要素を含んでいます',
      1: '詳細情報を見るには、ここをクリックします'
    },
    tools: 'ツール'
  },
  changelogs: {
    0: '変更ログ',
    1: '現在のバージョンで行われたすべてのリビジョンのリスト',
    2: 'ここには何もありません',
    3: 'しかし、あなたが行った変更をこのバージョンのスキンに追加することができます',
    4: 'グループ化されていない',
    5: '新',
    6: '修正',
    7: '変更点',
    8: 'とりはずし'
  },
  ideas: {
    0: '何も見つかりませんでした',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'クリエイター',
    1: 'このバージョンの作成に携わったすべてのクリエイターを一覧表示する',
    2: '誰もいません。',
    3: 'プレイヤー名を検索すると、プロフィールのリストが表示されます。',
    4: '編集者',
    5: '役割',
    6: 'バージョン'
  },
  tags: {
    0: 'タグ',
    1: 'このスキンに関連するすべてのタグの一覧',
    2: 'ここではかなり空っぽのようです。',
    3: '新しいタグを見つけるには上のフィールドを使用してください',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: '検索'
  },
  videos: {
    0: '動画',
    1: 'このスキンのすべてのビデオショーケースのリスト',
    2: 'ショーケースはありません',
    3: 'YouTube で検索するか、独自のショーケースを作成します'
  },
  sources: {
    0: 'アトリビューション',
    1: 'このバージョンのスキンで使用されているすべてのアセットまたはツールのリスト',
    2: 'ここはちょっと空いてる',
    3: '他のスキンやアートのアセットを使用した場合は、必ず上のボックスに追加してください。',
    4: 'グループ化されていない'
  },
  checks: {
    0: '全て',
    1: 'メタデータ',
    2: 'ハイライト',
    3: 'Name of the skin not specified',
    4: '少なくとも1人のスキンクリエーターを追加する',
    5: 'いくつかのタグを追加',
    6: 'スキンのサイズが指定されていません',
    7: '少なくとも１つのゲームモードを選択してください',
    8: '画像解像度(SDまたはHD) の選択',
    9: '少なくとも１つのアスペクト比を選択してください',
    10: 'スクリーンショットが提供されていません',
    11: '少なくとも１つのゲームプレイのスクリーンショットを追加してください',
    12: 'スキンへのリンクが指定されていません',
    20: 'かなり良い感じ',
    21: 'すべての問題が修正されました。グッジョブ',
    22: 'チェックリスト',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'スキン',
    1: '一番人気',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: '新着',
    5: 'ランダム',
    6: '全スキン',
    7: 'アスペクト比',
    8: '全スキン | osu スキン',
    9: 'Skin | Skins | Skins',
    10: '{name} によるosu スキン | から 全てのスキン',
    11: '検索',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: '編集',
    1: 'エクストラ',
    2: 'HD',
    3: 'フルHD',
    4: 'アニメーション',
    5: 'スクリーンショット',
    6: 'ゲームプレイのみ',
    7: 'ダウンロードリンク | スキンをダウンロード',
    8: 'フォーラムの投稿 | osu! フォーラム',
    9: 'Redditの投稿',
    10: 'クリエイター',
    11: 'タグ',
    13: '動画',
    14: '新バージョン｜バージョンを管理する',
    15: '更新 | 送信',
    16: 'ゲームモード',
    17: 'スキンの名前',
    18: 'Version | Versions',
    19: 'サイズ',
    20: 'メタデータ',
    21: '評価',
    22: 'ダウンロード',
    23: 'ダウンロードはまもなく可能になります',
    24: '残り{amount} 秒',
    25: 'あなたは私たちの仲間ではありません',
    26: 'あなたは、このスキンの作成者や編集者ではないようです。',
    27: 'スキン by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'ここをクリック',
    1: 'またはここに画像をドラッグ＆ドロップする'
  },
  footer: {
    0: 'cyperdark 制作',
    1: 'クレジット'
  },
  credits: {
    0: 'チビ',
    1: 'アート',
    2: 'アイコン',
    3: 'アイコンはすべて{name} から引用しています。',
    4: '国旗',
    5: '国旗画像はすべて {name} のものです',
    6: '翻訳',
    7: '誰かいませんか？[{lang}]',
    8: 'cpolが追加し忘れているようです。{text}'
  },
  search: {
    0: 'スキン検索',
    1: 'ビュー',
    2: 'タイトル',
    3: '評価',
    4: 'サイズ',
    5: '日付',
    7: '何も見つかりませんでした',
    8: '異なる検索フィルターを設定してみてください',
    9: '保留中のクエリ',
    10: '検索フィルタを選択するか、スキンのタイトル、作成者、またはタグを入力してください',
    11: 'ダウンロード',
    12: '名前',
    13: {
      0: 'スキン',
      1: 'タグ',
      2: 'Users',
      3: 'リスト'
    }
  },
  tabs: {
    0: '検索',
    1: '編集',
    2: 'リスト'
  },
  undefined: {
    0: 'エンプティ',
    1: '残念ながらここには何もありません。ほかのページを見てみましょう',
    2: '残念ながらここには何もありません',
    3: '権限がありません',
    4: 'このスキンを編集するにはログインする必要があります',
    5: '新しいスキンを追加するにはログインする必要があります。'
  },
  meta: {
    title: {
      0: 'osuスキンを見つける',
      1: 'ゲームモード、アスペクト比、osuスキン',
      2: '人気のosuスキン',
      3: 'osu スキンを検索',
      4: 'タグのリスト, {name}',
      5: '{name} v{version} osu スキン',
      6: 'クレジット',
      7: 'osu スキン',
      8: '{name} 検索 osu スキン',
      9: '他のosuスキンからインスピレーションを得る',
      10: '{name} が作成したスキン',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'このサイトでベストなosu! スキンを手に入れよう！ 私たちの膨大なライブラリには、すべてのゲームモード、アスペクト比、さらにはトッププレイヤーのスキンがあります。さらに、アニメーション向けの特別セクションもあります。完璧なスキンでゲームプレイを向上させましょう。',
      1: '{views} 閲覧。{modes} 用のosuスキン、サイズは{size}、{creators} によって製作、{ratios} をサポート',
      2: '私たちの高度な検索機能で完璧なosu! スキンを見つけましょう！ゲームモードやアスペクト比などで分けられた膨大なライブラリの中から探せます。また、osu!のトッププレーヤーが使用しているスキンもご覧いただけます。',
      3: 'このサイトでゲームモードやアスペクト比に応じた様々なスキンを見つけよう！各モード別（std, ctb, mania, taiko）で選ぶこともできます。あなたにぴったりなスキンでゲームプレイを向上させましょう。',
      4: '当サイトでトッププレイヤーの中からぴったりなosu! スキンを探そう！人気スキンのコレクションを探して、ゲームプレイをカスタマイズしましょう。あなたの好みに合った幅広いスタイルやテーマを見つけてください。',
      5: 'osuスキンの既存タグの一覧です。',
      6: '{name} osuスキンコレクション！, 無料ダウンロード',
      7: '{name} 用のosuスキンがたくさん、無料でダウンロードできます。',
      8: '{name} によって作成されたすべてのosuスキン。',
      9: '当サイトで次のosu! スキンのインスピレーションを身につけよう！多彩なスキンコレクションを見て、新しいテクニックやアイデアを見つけることができます。インスピレーションを受けて、自分だけのosu!スキンを作りましょう。',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'ログイン',
    1: 'ホームページ',
    profile_osu: 'osu! プロフィール',
    new_skin: '新着のスキン',
    notifications: '通知',
    settings: '設定',
    logout: 'ログアウト',
    load_more: 'もっと見る',
    copy_short: '短縮リンクをコピー',
    copied: 'コピーしました',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! フォーラム',
    skin_return: 'スキンへ戻る'
  },
  user: {
    roles: {
      0: 'クリエーター',
      1: 'ミキサー',
      2: 'アニメーション',
      3: 'アート',
      4: 'コラボ'
    }
  },
  tooltips: {
    0: 'ビュー数: {amount}',
    1: '結果を更新',
    2: '降順｜昇順',
    3: 'いいね: {likes} / よくないね: {dislikes}',
    4: 'Ctrl+enterでタグを追加',
    5: 'バージョンを編集',
    6: '{s}ログイン{p}して、このスキンを評価してください',
    7: '短い説明文はありません',
    8: 'URL がありません',
    9: 'ダウンロード数: {amount}'
  },
  lists: {
    screens: {
      0: 'ようこそ',
      1: 'メインメニュー',
      2: '譜面選択',
      3: 'モードメニュー',
      4: 'モッド',
      5: 'カウントダウン',
      6: 'ゲームプレイ',
      7: 'スピナー',
      8: 'セクションパス',
      9: 'セクションフェイル',
      10: 'ポーズ画面',
      11: '失敗した画面',
      12: 'リザルト画面',
      13: 'スキップ',
      14: 'バナー'
    },
    cats: {
      0: 'NSFW',
      1: '毛皮のような',
      2: 'ミックス'
    }
  },
  select: {
    0: '新',
    1: '修正済',
    2: '変更あり',
    3: '削除済',
    4: 'アート',
    5: 'フォント',
    6: 'アーティスト',
    7: 'スキンエレメント',
    8: 'オーディオ/Sfx',
    9: 'ツール',
    views: 'ビュー',
    likes: '高評価',
    dislikes: '低評価',
    downloads: 'ダウンロード',
    size_range: 'サイズ選択',
    date_range: '日付範囲を選択',
    ratio: 'アスペクト比を選択 | 比率'
  },
  placeholders: {
    0: 'ロールを選択',
    1: 'バージョンを選択',
    2: 'テキストを入力...',
    3: 'サイズ選択',
    4: '日付の範囲を選択',
    5: '年',
    6: '月',
    7: 'アスペクト比を選択',
    8: 'カテゴリーを選択',
    9: 'ゲームモード',
    10: 'タイプを選択',
    11: 'YouTubeのリンクを貼り付け',
    12: '説明文とURLを入力します。フォーマット説明:url',
    13: 'エクストラを選択',
    14: 'リンクを貼り付け',
    15: 'スキンのタイトル、作者、またはタグ',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: '貢献する' },
  nsfw: {
    0: '警告！！',
    1: 'このスキンにはセンシティブまたはアダルトなコンテンツが含まれています',
    2: 'このスキンには、一部のユーザーが不快に感じる可能性があるセンシティブまたはアダルトなコンテンツが含まれています',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: '権限がありません',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};