export default {
  title: {
    home: 'Mājaslapa',
    login: 'Pieslēgties',
    lists: { 0: 'Saraksti' },
    tags: {
      0: 'Tagi',
      1: '{amount} tagi kategorijai {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Iedvesma',
      1: '«{amount}»'
    },
    sounds: { 0: 'Skaņas' },
    leaderboard: { 0: 'Līdersaraksti' },
    extend: { 0: 'Vairāk | Mazāk' },
    skin: {
      0: 'Šis skins satur elementus no citiem skiniem',
      1: 'Spied šeit, lai iegūtu vairāk informācijas'
    },
    tools: 'Instrumenti'
  },
  changelogs: {
    0: 'Izmaiņu saraksts',
    1: 'Saraksts ar visām veiktajām revīzijām pašreizējā versijā',
    2: 'Šeit nekā nav',
    3: 'Bet tu vari pievienot izmaiņas, kuras tu veici šai skina versijai',
    4: 'Nav grupēts',
    5: 'Jaunais',
    6: 'Labotais',
    7: 'Pārmainītais',
    8: 'Izņemtais'
  },
  ideas: {
    0: 'Nekas nav atrasts',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Veidotāji',
    1: 'Kreditē visus, kuri bija iesaistīti šīs versijas izveidē',
    2: 'Neviena šeit nav',
    3: 'Ierakstot spēlētāja vārdu, parādīsies profilu saraksts.',
    4: 'Rediģētājs',
    5: 'Lomas',
    6: 'Versijas'
  },
  tags: {
    0: 'Tagi',
    1: 'Saraksts ar visiem tagiem, kas ir saistīti ar šo skinu',
    2: 'Šeit liekas diezgan klusi.',
    3: 'Izmanto augšējo lauku, lai atrastu jaunus tagus',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Meklēt'
  },
  videos: {
    0: 'Video',
    1: 'Saraksts ar visām video izstādēm šim skinam',
    2: 'Nulle izrāžu',
    3: 'Meklē YouTubē vai uztaisi pats savu izrādi'
  },
  sources: {
    0: 'Atribūcija',
    1: 'Saraksts ar visiem izmantotajiem elementiem vai rīkiem šajā skina versijā',
    2: 'Šeit liekas diezgan klusi',
    3: 'Ja tu esi izmantojis elementus no citiem skiniem vai zīmējumiem, lūdzu, pievieno tos augšējā laukā',
    4: 'Nav grupēts'
  },
  checks: {
    0: 'Viss',
    1: 'Metadata',
    2: 'Izceltais',
    3: 'Name of the skin not specified',
    4: 'Pievieno vismaz vienu skina veidotāju',
    5: 'Pievieno pāris tagu',
    6: 'Skina lielums nav specificēts',
    7: 'Izvēlies vismaz vienu spēles režīmu',
    8: 'Izvēlies bildes izšķirtspēju (SD vai HD)',
    9: 'Izvēlies vismaz vienu malu attiecību',
    10: 'Nav ekrānuzņēmumu',
    11: 'Pievieno vismaz vienu ekrānuzņēmumu ar gameplay',
    12: 'Saite uz linku nav norādīta',
    20: 'Neslikti',
    21: 'Tu izlaboji visas problēmas. Malacis!',
    22: 'Problēmu saraksts',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skini',
    1: 'Populāri',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Jaunākie',
    5: 'Nejaušie',
    6: 'Visi skini',
    7: 'Malu attiecība',
    8: 'Visi skini | osu skini',
    9: 'Skins | Skina | Skinu',
    10: 'osu Skini pēc {name} | Visi skini no',
    11: 'Meklēt',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Rediģēt',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Ekrānuzņēmumi',
    6: 'Tikai gameplay',
    7: 'Lejupielādes saite | Lejupielādēt skinu',
    8: 'Foruma post | osu! Forums',
    9: 'Reddit post',
    10: 'Veidotāji',
    11: 'Tagi',
    13: 'Video',
    14: 'Jauna versija | Pārvaldīt versijas',
    15: 'Atjaunināt | Iesūtīt',
    16: 'Spēles režīmi',
    17: 'Skina nosaukums',
    18: 'Versija | Versijas',
    19: 'Izmērs',
    20: 'Metadata',
    21: 'Vērtējums',
    22: 'Lejupielādes',
    23: 'Lejupielāde drīzumā būs pieejama',
    24: 'Atlikušas {amount} sekundes',
    25: 'Tu neesi viens no mums',
    26: 'Šķiet, ka tu neesi šī skina veidotājs vai rediģētājs',
    27: 'Skinu veidoja',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Klikšķini šeit',
    1: 'vai velc ekrānuzņēmumus šeit'
  },
  footer: {
    0: 'Veidoja cyperdark',
    1: 'Izmantotie materiāli'
  },
  credits: {
    0: 'Chibi',
    1: 'Mākslas darbi',
    2: 'Ikonas',
    3: 'Visas ikonas ir ņemtas no {name}',
    4: 'Karogi',
    5: 'Visas karogu bildes ir no {name}',
    6: 'Tulkošana',
    7: 'Neviens? [{lang}]',
    8: 'Šķiet, ka cpol aizmirsa viņus pievienot. {text}'
  },
  search: {
    0: 'Meklēt skinu',
    1: 'Skatījumi',
    2: 'Tituls',
    3: 'Vērtējums',
    4: 'Izmērs',
    5: 'Datums',
    7: 'Nekas nav atrasts',
    8: 'Izmēģini citus meklēšanas kritērijus',
    9: 'Gaida pieprasījumu',
    10: 'Izvēlies meklēsanas kritērijus vai vienkārši ieraksti skina nosaukumu, autoru vai tagu',
    11: 'Lejupielādes',
    12: 'Nosaukums',
    13: {
      0: 'Skini',
      1: 'Tagi',
      2: 'Users',
      3: 'Saraksti'
    }
  },
  tabs: {
    0: 'Meklēt',
    1: 'Rediģēt',
    2: 'Saraksts'
  },
  undefined: {
    0: 'Nav nekā',
    1: 'Diemžēl šajā lapā nekā nav, pamēģini paskatīties citās lapās',
    2: 'Diemžēl šeit nekā nav',
    3: 'Neautorizēts',
    4: 'Tev vajag pieslēgties, lai rediģētu šo skinu.',
    5: 'Tev jāpieslēdzas, lai pievienotu jaunu skinu.'
  },
  meta: {
    title: {
      0: 'Atklāj osu skinus',
      1: 'Osu skinu kategorijas',
      2: 'Populārie osu skini',
      3: 'Meklēt osu skinus',
      4: 'Tagu saraksts, «{name}»',
      5: '{name} v{version} osu skins',
      6: 'Izmantotie materiāli',
      7: 'osu skini',
      8: '{name} meklēt osu skinus',
      9: 'Iedvesmojies no citiem osu skiniem',
      10: '{name} veidoja osu skinus',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Dabū labākos osu! skinus mūsu saitē! Mūzu milzīgajā klāstā ir skini visiem spēļu režīmiem, visām malu attiecībām un pat top spēlētājiem. Un, mums ir īpaša sadaļa anime faniem. Uzlabo savu gameplay ar perfekto skinu. #osuskins #osugame #anime',
      1: '{views} skatījumi. Osu skins priekš {modes}, lielums ir {size}, veidoja {creators}. Atbalsta {ratios}',
      2: 'Atrodi perfekto osu! skinu ar mūsu attīstīto meklēšanas funkciju. Pārlūko mūsu milzīgo klāstu, filtrējot ar spēles režīmu, malas attiecību un vairāk. Vai apskati kādus skinus izmanto top spēlētāji.',
      3: 'Atklāj dažādas skinu variācijas visiem spēļu režīmiem un malu attiecībām mūsu saitē. Izvēlies starp standard mode, catch the beat, mania un taiko. Atrodi perfekto skinu savām spēļu priekšrocībām.',
      4: 'Atrodi perfekto osu skinu no top spēlētājiem mūsu saitē. Pārlūko mūsu populāro skinu kolekciju un pielāgo savu gameplay. Atklāj lielu klāstu ar stiliem un motīviem atbilstoši savām vēlmēm.',
      5: 'Saraksts ar visiem tagiem osu skiniem.',
      6: '{name} osu skinu kolecija!, bezmaksas lejupielāde',
      7: 'Liela kolekcija osu skinu priekš {name}, bezmaksas lejupielāde!',
      8: 'Visus skinus sastādījis {name}',
      9: 'Atrodi iedvesmu savam nākamajam osu! skinam mūsu saitē. Pārlūko daudzveidīgu kolekciju ar skiniem, un atklāj jaunas metodes un idejas. Gūsti iedvesmu un izveido pats savu skinu.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Pieslēgties',
    1: 'Galvenā lapa',
    profile_osu: 'osu! Profils',
    new_skin: 'Jauns skins',
    notifications: 'Notifikācijas',
    settings: 'Iestatījumi',
    logout: 'Iziet',
    load_more: 'Ielādēt vairāk',
    copy_short: 'Kopēt saīsināto saiti',
    copied: 'Nokopēts',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forums',
    skin_return: 'Atpakaļ uz skinu'
  },
  user: {
    roles: {
      0: 'Veidotājs',
      1: 'Miksētājs',
      2: 'Animācijas',
      3: 'Mākslas darbi',
      4: 'Sadarbība'
    }
  },
  tooltips: {
    0: 'Skatījumi: {amount}',
    1: 'Atsvaidzini rezultātus',
    2: 'Dilstoši | Augoši',
    3: 'Patīk: {likes} / Nepatīk: {dislikes}',
    4: 'Spied ctrl+enter, lai pievienotu tagu',
    5: 'Rediģēt versiju',
    6: '{s}Jāpieslēdzas{p}, lai varētu novērtēt šo skinu',
    7: 'Nav īsā apraksta',
    8: 'Nav saites',
    9: 'Lejupielādes: {amount}'
  },
  lists: {
    screens: {
      0: 'Sveiciena ekrāns',
      1: 'Galvenā izvēlne',
      2: 'Kartes izvēles ekrāns',
      3: 'Režīmu izvēlne',
      4: 'Modi',
      5: 'Atskaitīšana',
      6: 'Gameplay',
      7: 'Spineris',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pauzes Ekrāns',
      11: 'Fail Screen',
      12: 'Rezultātu ekrāns',
      13: 'Izlaist',
      14: 'Baneris'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Jaunais',
    1: 'Labots',
    2: 'Mainīts',
    3: 'Noņemts',
    4: 'Māksla',
    5: 'Fonts',
    6: 'Mākslinieks',
    7: 'Skina elements',
    8: 'Audio/Sfx',
    9: 'Instrumenti',
    views: 'Skatījumi',
    likes: 'Patīk',
    dislikes: 'Nepatīk',
    downloads: 'Lejupielādes',
    size_range: 'Skina izmērs',
    date_range: 'Datuma diapazons',
    ratio: 'Malu attiecība | attiecība'
  },
  placeholders: {
    0: 'Atlasi lomas',
    1: 'Izvēlies versijas',
    2: 'Ievadi tekstu...',
    3: 'Skina izmērs',
    4: 'Datuma diapazons',
    5: 'Gads',
    6: 'Mēnesis',
    7: 'Malu attiecība',
    8: 'Izvēlies kategorijas',
    9: 'Spēles režīmi',
    10: 'Izvēlies tipu',
    11: 'Ielīmē YouTube saiti',
    12: 'Ievadi aprakstu un saiti. Piemērs: apraksts:saite',
    13: 'Izvēlies vairāk',
    14: 'Ielīmē saiti',
    15: 'Skina nosaukums, veidotājs vai tags',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Izpalīdzēt' },
  nsfw: {
    0: 'Brīdinājums!',
    1: 'Šis skins satur aizskarošu vai nepiemērotu saturu',
    2: 'Šis skins satur aizskarošu vai nepiemērotu saturu, kas dažiem lietotājiem varētu likties satraucošs',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Neautorizēts',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};