export default {
  title: {
    home: 'Mājaslapa',
    login: 'Pieslēgties',
    lists: { 0: 'Saraksti' },
    tags: {
      0: 'Tagi',
      1: '{amount} tagi kategorijai {name}',
      2: 'Meklē tagus'
    },
    ideas: {
      0: 'Iedvesma',
      1: '«{amount}»'
    },
    sounds: { 0: 'Skaņas' },
    leaderboard: { 0: 'Līdersaraksti' },
    extend: { 0: 'Vairāk | Mazāk' },
    skin: {
      0: 'Šis skins satur elementus no citiem skiniem',
      1: 'Spied šeit, lai iegūtu vairāk informācijas'
    },
    tools: 'Instrumenti'
  },
  home: {
    0: 'Pieejams lejupielādēt',
    1: 'Visvairāk: _name_ skini',
    2: 'Skatīts | Patīkots | Lejupielādēts',
    3: 'Publicēt jaunu skinu',
    4: 'Kā lejupielādēt skinu'
  },
  changelogs: {
    0: 'Izmaiņu saraksts',
    1: 'Saraksts ar visām veiktajām revīzijām pašreizējā versijā',
    2: 'Šeit nekā nav',
    3: 'Bet tu vari pievienot izmaiņas, kuras tu esi veicis šai skina versijai',
    4: 'Nav grupēts',
    5: 'Jaunais',
    6: 'Labotais',
    7: 'Pārmainītais',
    8: 'Izņemtais'
  },
  ideas: {
    0: 'Nekas nav atrasts',
    1: 'Ekrānuzņēmumi no «{type}» netika augšupielādēti uz saiti'
  },
  creators: {
    0: 'Veidotāji',
    1: 'Kreditē visus, kuri bija iesaistīti šīs versijas izveidē',
    2: 'Neviena šeit nav',
    3: 'Ierakstot spēlētāja vārdu, parādīsies profilu saraksts.',
    4: 'Rediģētājs',
    5: 'Lomas',
    6: 'Versijas'
  },
  tags: {
    0: 'Tagi',
    1: 'Saraksts ar visiem tagiem, kas ir saistīti ar šo skinu',
    2: 'Šeit liekas diezgan klusi.',
    3: 'Izmanto augšējo lauku, lai atrastu jaunus tagus',
    4: 'Tagi netika atrasti',
    5: 'Mēģini meklēt kaut ko citu',
    6: 'Meklēt'
  },
  videos: {
    0: 'Video',
    1: 'Saraksts ar visām video izstādēm šim skinam',
    2: 'Nulle izrāžu',
    3: 'Meklē YouTubē vai uztaisi pats savu izrādi'
  },
  sources: {
    0: 'Atribūcija',
    1: 'Saraksts ar visiem izmantotajiem elementiem vai rīkiem šajā skina versijā',
    2: 'Šeit liekas diezgan klusi',
    3: 'Ja tu esi izmantojis elementus no citiem skiniem vai zīmējumiem, lūdzu, pievieno tos augšējā laukā',
    4: 'Nav grupēts'
  },
  checks: {
    0: 'Viss',
    1: 'Metadata',
    2: 'Izceltais',
    3: 'Skina nosaukums nav norādīts',
    4: 'Pievieno vismaz vienu skina veidotāju',
    5: 'Pievieno pāris tagu',
    6: 'Skina lielums nav specificēts',
    7: 'Izvēlies vismaz vienu spēles režīmu',
    8: 'Izvēlies bildes izšķirtspēju (SD vai HD)',
    9: 'Izvēlies vismaz vienu malu attiecību',
    10: 'Nav ekrānuzņēmumu',
    11: 'Pievieno vismaz vienu ekrānuzņēmumu ar gameplay',
    12: 'Saite uz linku nav norādīta',
    20: 'Viss ir čikiniekā!',
    21: 'Tu salaboji visas problēmas. Malacis!',
    22: 'Problēmu saraksts',
    23: 'Pievieno vismaz vienu publisku versiju',
    24: 'Pievieno vismaz vienu veidotāju pie šīs versijas',
    25: 'Dažiem veidotājiem nav lomu'
  },
  skins: {
    0: 'Skini',
    1: 'Populāri',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Jaunākie',
    5: 'Nejaušie',
    6: 'Visi skini',
    7: 'Malu attiecība',
    8: 'Visi skini | osu skini',
    9: 'Skins | Skina | Skinu',
    10: 'osu Skini pēc {name} | Visi skini no',
    11: 'Meklēt',
    12: '{name} skini',
    13: 'Izpētīt skinus'
  },
  skin: {
    0: 'Rediģēt',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Ekrānuzņēmumi',
    6: 'Tikai gameplay',
    7: 'Lejupielādes saite | Lejupielādēt skinu',
    8: 'Foruma post | osu! Forums',
    9: 'Reddit post',
    10: 'Veidotāji',
    11: 'Tagi',
    13: 'Video',
    14: 'Jauna versija | Pārvaldīt versijas',
    15: 'Atjaunināt | Iesūtīt',
    16: 'Spēles režīmi',
    17: 'Skina nosaukums',
    18: 'Versija | Versijas',
    19: 'Izmērs',
    20: 'Metadata',
    21: 'Vērtējums',
    22: 'Lejupielādes',
    23: 'Lejupielāde drīzumā būs pieejama',
    24: 'Atlikušas {amount} sekundes',
    25: 'Tu neesi viens no mums',
    26: 'Šķiet, ka tu neesi šī skina veidotājs vai rediģētājs',
    27: 'Skinu veidoja',
    28: 'Nav tagu',
    29: 'Nav video',
    30: 'Nav viedotāju',
    31: 'Novērtēt skinu',
    32: 'Augšupbalso & komentē redditā',
    33: 'Komentē osu! forumā',
    34: 'Vairāk skini no šī veidotāja | Vairāk skini no šī veidotāja',
    35: 'Atbalsti skinu'
  },
  drag: {
    0: 'Klikšķini šeit',
    1: 'vai velc ekrānuzņēmumus šeit'
  },
  footer: {
    0: 'Veidoja cyperdark',
    1: 'Izmantotie materiāli'
  },
  credits: {
    0: 'Chibi',
    1: 'Mākslas darbi',
    2: 'Ikonas',
    3: 'Visas ikonas ir ņemtas no {name}',
    4: 'Karogi',
    5: 'Visas karogu bildes ir no {name}',
    6: 'Tulkošana',
    7: 'Neviens? [{lang}]',
    8: 'Izskatās, ka cyperdark aizmirsa tos pievienot. {text}'
  },
  search: {
    0: 'Meklēt skinu',
    1: 'Skatījumi',
    2: 'Tituls',
    3: 'Vērtējums',
    4: 'Izmērs',
    5: 'Datums',
    7: 'Nekas nav atrasts',
    8: 'Mēģini izmantot citus meklēšanas filtrus',
    9: 'Gaida pieprasījumu',
    10: 'Izmanto pašreizējos filtrus vai ierkasti skina nosaukumu, veidotāju vai tagus',
    11: 'Lejupielādes',
    12: 'Nosaukums',
    13: {
      0: 'Skini',
      1: 'Tagi',
      2: 'Lietotāji',
      3: 'Saraksti'
    },
    14: 'Meklē:'
  },
  tabs: {
    0: 'Meklēt',
    1: 'Rediģēt',
    2: 'Saraksts'
  },
  undefined: {
    0: 'Nav nekā',
    1: 'Diemžēl šajā lapā nekā nav, bet tu vari pamēģināt paskatīties citās lapās',
    2: 'Diemžēl šeit nekā nav',
    3: 'Neautorizēts',
    4: 'Tev jāpieslēdzas, lai rediģētu šo skinu.',
    5: 'Tev jāpieslēdzas, lai pievienotu jaunu skinu.'
  },
  meta: {
    title: {
      0: 'Atklāj osu skinus',
      1: 'Osu skinu kategorijas',
      2: 'Populārie osu skini',
      3: 'Meklēt osu skinus',
      4: 'Tagu saraksts, «{name}»',
      5: '{name} v{version} osu skins',
      6: 'Izmantotie materiāli',
      7: 'osu skini',
      8: '{name} meklēt osu skinus',
      9: 'Iedvesmojies no citiem osu skiniem',
      10: '{name} veidoja osu skinus',
      11: 'Meklē tagus',
      12: '{name} atrada tagus',
      13: 'Jauns skins'
    },
    description: {
      0: 'Dabū labākos osu! skinus mūsu saitē! Mūzu milzīgajā klāstā ir skini visiem spēļu režīmiem, visām malu attiecībām un pat top spēlētājiem. Un, mums ir īpaša sadaļa anime faniem. Uzlabo savu gameplay ar perfekto skinu. #osuskins #osugame #anime',
      1: '{views} skatījumi. Osu skins priekš {modes}, lielums ir {size}, veidoja {creators}. Atbalsta {ratios}',
      2: 'Atrodi perfekto osu! skinu ar mūsu attīstīto meklēšanas funkciju. Pārlūko mūsu milzīgo klāstu, filtrējot ar spēles režīmu, malas attiecību un vairāk. Vai apskati kādus skinus izmanto top spēlētāji.',
      3: 'Atklāj dažādas skinu variācijas visiem spēļu režīmiem un malu attiecībām mūsu saitē. Izvēlies starp standard mode, catch the beat, mania un taiko. Atrodi perfekto skinu savām spēļu priekšrocībām.',
      4: 'Atrodi perfekto osu skinu no top spēlētājiem mūsu saitē. Pārlūko mūsu populāro skinu kolekciju un pielāgo savu gameplay. Atklāj lielu klāstu ar stiliem un motīviem atbilstoši savām vēlmēm.',
      5: 'Saraksts ar visiem tagiem osu skiniem.',
      6: '{name} osu skinu kolecija!, bezmaksas lejupielāde',
      7: 'Liela kolekcija osu skinu priekš {name}, bezmaksas lejupielāde!',
      8: 'Visus skinus sastādījis {name}',
      9: 'Atrodi iedvesmu savam nākamajam osu! skinam mūsu saitē. Pārlūko daudzveidīgu kolekciju ar skiniem, un atklāj jaunas metodes un idejas. Gūsti iedvesmu un izveido pats savu skinu.',
      10: 'Meklē tagus starp visiem tagiem, kas ir šājā mājaslapā.'
    }
  },
  buttons: {
    0: 'Pieslēgties',
    1: 'Galvenā lapa',
    profile_osu: 'osu! Profils',
    new_skin: 'Jauns skins',
    notifications: 'Notifikācijas',
    settings: 'Iestatījumi',
    logout: 'Iziet',
    load_more: 'Ielādēt vairāk',
    copy_short: 'Kopēt saīsināto saiti',
    copied: 'Nokopēts',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forums',
    skin_return: 'Atpakaļ uz skinu'
  },
  user: {
    roles: {
      0: 'Veidotājs',
      1: 'Miksētājs',
      2: 'Animācijas',
      3: 'Mākslas darbi',
      4: 'Sadarbība'
    }
  },
  tooltips: {
    0: 'Skatījumi: {amount}',
    1: 'Atsvaidzini rezultātus',
    2: 'Dilstoši | Augoši',
    3: 'Patīk: {likes} / Nepatīk: {dislikes}',
    4: 'Spied ctrl+enter, lai pievienotu tagu',
    5: 'Rediģēt versiju',
    6: '{s}Jāpieslēdzas{p}, lai varētu novērtēt šo skinu',
    7: 'Nav īsā apraksta',
    8: 'Nav saites',
    9: 'Lejupielādes: {amount}'
  },
  lists: {
    screens: {
      0: 'Sveiciena ekrāns',
      1: 'Galvenā izvēlne',
      2: 'Kartes izvēles ekrāns',
      3: 'Režīmu izvēlne',
      4: 'Modi',
      5: 'Atskaitīšana',
      6: 'Gameplay',
      7: 'Spineris',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pauzes Ekrāns',
      11: 'Fail Screen',
      12: 'Rezultātu ekrāns',
      13: 'Izlaist',
      14: 'Baneris'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Jaunais',
    1: 'Labots',
    2: 'Mainīts',
    3: 'Noņemts',
    4: 'Māksla',
    5: 'Fonts',
    6: 'Mākslinieks',
    7: 'Skina elements',
    8: 'Audio/Sfx',
    9: 'Instrumenti',
    views: 'Skatījumi',
    likes: 'Patīk',
    dislikes: 'Nepatīk',
    downloads: 'Lejupielādes',
    size_range: 'Skina izmērs',
    date_range: 'Datuma diapazons',
    ratio: 'Malu attiecība | attiecība'
  },
  placeholders: {
    0: 'Izvēlies lomas',
    1: 'Izvēlies versijas',
    2: 'Ievadi tekstu...',
    3: 'Skina izmērs',
    4: 'Datuma diapazons',
    5: 'Gads',
    6: 'Mēnesis',
    7: 'Malu attiecība',
    8: 'Izvēlies kategorijas',
    9: 'Spēles režīmi',
    10: 'Izvēlies tipu',
    11: 'Ielīmē YouTube saiti',
    12: 'Ievadi aprakstu un saiti. Piemērs: apraksts:saite',
    13: 'Izvēlies vairāk',
    14: 'Ielīmē saiti',
    15: 'Skina nosaukums, veidotājs vai tagi',
    16: 'Izvēlies kategoriju',
    17: 'Ieraksti taga nosaukumu'
  },
  contribute: { 0: 'Izpalīdzēt' },
  nsfw: {
    0: 'Brīdinājums!',
    1: 'Šis skins satur aizskarošu vai nepiemērotu saturu',
    2: 'Šis skins satur aizskarošu vai nepiemērotu saturu, kas dažiem lietotājiem varētu likties satraucošs',
    3: 'Labi',
    4: 'atā o/'
  },
  removed: {
    0: 'Versija nav pieejama',
    1: 'Šī skina veidotājs nolēma noņemt šo versiju no mājaslapas.',
    2: 'Pārej uz pieejamu versiju'
  },
  notify: {
    0: 'Problēmas netika salabotas',
    1: 'Visi obligātie laukumi netika aizpildīti',
    2: 'Parādīt',
    3: 'Nav atrasts',
    4: 'Baneris netika atrasts (Šobrīd pirmais ekrānuzņēmums tiek izmantots kā baneris)',
    5: 'Nav izmaiņu',
    6: 'Izmaiņas netika atrastas',
    7: 'ID netika atrasts',
    8: 'Video ID netika atrasts, pamēģini citu saiti (Dotajā brīdī tikai YouTube ir atbalstīta)',
    9: 'Ups',
    10: 'Izskatās, ka tava sesija ir beigusies. Atver jaunu lapu un pieslēdzies savam kontam (Neraizējies, viss automātiski tika saglabāts)',
    11: 'Eksistē',
    12: 'Šis video jau ir ticis pievienots',
    13: 'Eksistē',
    14: 'Šis tags jau ir ticis pievienots',
    15: 'Nav atrasts',
    16: 'Tu nevari izdzēst jau izdzēstu tagu',
    17: 'Pievienots',
    18: 'Tu esi veiksmīgi pievienojis jaunu tagu',
    19: 'Ups',
    20: 'Šis veidotājs jau tika pievienots',
    21: 'EZ',
    22: 'Jaunais veidotājs ir ticis pievienots',
    23: 'KO',
    24: 'Neiespējami noņemt izdzēstu veidotāju',
    25: 'Dublēt',
    26: 'Šī pārmaiņa jau iepriekš ir tikusi pievienota.',
    27: 'Dublēt',
    28: 'Šī saite jau iepriekš ir tikusi pievienota.',
    29: 'Brīdinājums',
    30: 'Tu aizmirsi pievienot aprakstu saitei. Piemērs: apraksts:saite',
    31: 'Brīdinājums',
    32: 'Tu aizmirsi pievienot saiti aprakstam. Piemēram: apraksts:saite',
    33: 'Atjaunots',
    34: 'Versija «{name}» ir tikusi atjaunota',
    35: 'Izdzēsts',
    36: 'Versija «{name}» ir tikusi izdzēsta',
    37: 'Kļūda',
    38: 'Izskatās, ka serveris domā, ka tu esi robots.',
    39: 'Izskatās, ka tava sesija ir beigusies. Atver jaunu lapu un pieslēdzies savam kontam (Neraizējies, viss automātiski tika saglabāts)',
    40: 'Neatbilstoši akreditācijas dati (No jauna pieslēdzies savam kontam. Neraizējies, viss automātiski tika saglabāts)',
    41: 'Nezināma kļūda',
    42: 'Tu nevari rediģēt neeksistējošu skinu',
    43: 'Izskatās, ka tev nav atļaujas rediģēt šo skinu',
    44: 'Tu nevari ielikt šo versiju, jo tā ir tāda pati kā iepriekšējā.',
    45: 'Šīš izmaiņas jau ir tikušas aizsūtītas moderācijai',
    46: 'Veiksmīgi',
    47: 'Jaunas izmaiņas ir tikušas iesūtītas moderācijai',
    48: 'Ir veiktas pārmaiņas moderācijā',
    49: 'Savāda saite',
    50: 'Šī saite nevar tikt izmantota kā lejupielādes saite',
    51: 'Iesūtīts moderācijai'
  },
  header: {
    0: 'Notifikācijas',
    1: 'Seko mums šajās platformās, lai saņemtu notifikācijas par jauniem skiniem'
  },
  restricted_view: {
    0: 'Neautorizēts',
    1: 'Lūdzu pieslēdzies savam kontam',
    2: 'Ierobežots skats',
    3: 'Šī lapa vēl nav iznākusi.'
  }
};