export default {
  title: {
    home: 'Почетна',
    login: 'Најави се',
    lists: { 0: 'Листи' },
    tags: {
      0: 'Тагови',
      1: '{amount} Тагови за категории {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Инспирација',
      1: '«{amount}»'
    },
    sounds: { 0: 'Звукови' },
    leaderboard: { 0: 'Рангирачка листа' },
    extend: { 0: 'Повеќе | Помалку' },
    skin: {
      0: 'Овој скин содржи елементи од други скинови',
      1: 'Кликнете овде за повеќе информации'
    },
    tools: 'Алатки'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Промени',
    1: 'Листа на сите ревизии направени во оваа верзија',
    2: 'Ништо нема тука',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Не е групирано',
    5: 'Ново',
    6: 'Fix',
    7: 'Change',
    8: 'Removal'
  },
  ideas: {
    0: 'Ништо не е пронајдено',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Создаватели',
    1: 'Листа на сите создаватели кој се инволвирано во правење на оваа верзија',
    2: 'Никој не е тука',
    3: 'Пребарување на име на играч ќе покаже листа од профили.',
    4: 'Едитор',
    5: 'Улоги',
    6: 'Верзии'
  },
  tags: {
    0: 'Тагови',
    1: 'Листа на сите тагови поврзани со овој скин',
    2: 'Изгледа многу празно овде.',
    3: 'Користете го полето погоре за да најдете нови тагови',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Пребарувај'
  },
  videos: {
    0: 'Видеа',
    1: 'Листа на сите видео прикажувања на овој скин',
    2: 'Нема прикажувања',
    3: 'Пребарувај за некои на YouTube или направи свое прикажување'
  },
  sources: {
    0: 'Атрибуција',
    1: 'Листа на сите алатки користени во оваа верзија на овој скин',
    2: 'Малку е празно овде',
    3: 'Ако имате користени алатки од други скинови, или цртежи, додадете ги погоре',
    4: 'Не е групирано'
  },
  checks: {
    0: 'Сите',
    1: 'Метаподатоци',
    2: 'Нагласи',
    3: 'Name of the skin not specified',
    4: 'Додајте барем еден создавател на скинот',
    5: 'Додајте неколку тагови',
    6: 'Големина на скинот не е специфирана',
    7: 'Изберете барем еден гејм-мод',
    8: 'Изберете резолуција на сликата (SD или HD)',
    9: 'Изберете барем еден сооднос',
    10: 'Нема слики',
    11: 'Додадете барем една слика од гејмплејот',
    12: 'Нема линк од скинот',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Чеклиста',
    23: 'Add at least one public version',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Скинови',
    1: 'Популарно',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Последно',
    5: 'Рандом',
    6: 'Сите скинови',
    7: 'Сооднос',
    8: 'Сите скинови | osu скинови',
    9: 'Скин | Скинови | Скинови',
    10: 'osu Skinови од {name} | Сите скинови од',
    11: 'Пребарувај',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Едит',
    1: 'Екстра',
    2: 'HD',
    3: 'FullHD',
    4: 'Анимација',
    5: 'Слики',
    6: 'Само гејмплеј',
    7: 'Линк за слегнување | Слегни го скинот',
    8: 'Форум објава | osu! Форум',
    9: 'Редит објава',
    10: 'Создаватели',
    11: 'Тагови',
    13: 'Видеа',
    14: 'Нова Верзија | Изменувај верзии',
    15: 'Апдејт | Објави',
    16: 'Гејм-модови',
    17: 'Име на скинот',
    18: 'Верзија | Верзии',
    19: 'Големина',
    20: 'Метаподатоци',
    21: 'Рејтинг',
    22: 'Слегнувања',
    23: 'Слегнувањето ќе биде достапно скоро',
    24: '{amount} секунди преостанати',
    25: 'Ти не си еден од нас',
    26: 'Изгледа дека не сте автор на овој скин',
    27: 'Скин од',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted at {author} request',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You successfully finished the tutorial, have fun!'
  },
  drag: {
    0: 'Кликнете овде',
    1: 'Или привлечете слика овде'
  },
  footer: {
    0: 'Создадено од cyperdark',
    1: 'Кредити',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Цртежи',
    2: 'Икуни',
    3: 'Сите икуни се превземени од {name}',
    4: 'Знамиња',
    5: 'Сите слики од знамињата се превземени од {name}',
    6: 'Локализација',
    7: 'Некој? [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Пребарување на скинови',
    1: 'Прегледи',
    2: 'Име',
    3: 'Рејтинг',
    4: 'Големина',
    5: 'Дата',
    7: 'Ништо не е пронајдено',
    8: 'Try using different search filters',
    9: 'Чекање на пребарување',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Слегнувања',
    12: 'Име',
    13: {
      0: 'Скинови',
      1: 'Тагови',
      2: 'Users',
      3: 'Листи'
    },
    14: 'Search:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished'
  },
  tabs: {
    0: 'Пребарувај',
    1: 'Едит',
    2: 'Листа'
  },
  undefined: {
    0: 'Празно',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Неауторизирано',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Пребарувајте osu скинови',
      1: 'Гејм-модови, соодноси osu скинови',
      2: 'Популарни osu скинови',
      3: 'Пребарувај osu скинови',
      4: 'Листа на тагови, {name}',
      5: '{name} v{version} osu скин',
      6: 'Кредити',
      7: 'osu скинови',
      8: '{name} пребарувај osu скинови',
      9: 'Добијте инспирација од други osu скинови',
      10: '{name} направиле osu скинови',
      11: 'Search tags',
      12: '{name} found tags',
      13: 'Нов скин',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! Contests'
    },
    description: {
      0: 'Добијте ги најдобрите osu! скинови на нашиот сајт! Нашата голема галерија има скинови за сите гејм-модови, соодноси и скинови на топ играчи. Плус, ја имаме специјалната секција за фанови на аниме. Подобрете си го гејмплејот со перфектниот скин. #osuskins #osugame #anime',
      1: '{views} прегледи. osu скин за {modes}, големината е {size}, создадено од {creators}. Подршка {ratios}',
      2: 'Најдете го перфектиниот osu! скин со нашиот подобар пребарувач. Пребарувајте во нашата голема галерија, филтрирана по гејм-модови, соодноси, и повеќе. Или, погледнете ги скиновите користени од топ играчи.',
      3: 'Пребарувајте многу скинови од различни гејм модови и соодноси на нашиот сајт. Изберете од standard, catch the beat, mania, и taiko модовите. Пронајдете го перфектниот фит за вашиот гејминг стил.',
      4: 'Пронајдете го префектниот osu скин од топ играчи на нашиот сајт. Пребарувајте ја нашата колекција од популарни скинови и направете го поубав вашиот гејмплеј. Пребарувајте многу стилови по ваш стил.',
      5: 'Листа на постојачки тагови на osu скинови.',
      6: '{name} колекција од osu скинови!, бесплатно слегнување',
      7: 'Голема бројка на osu скинови за {name}, слегнете бесплатно!',
      8: 'Сите osu скинови се направени од {name}',
      9: 'Пронајдете инспирација за вашиот следен osu! скин на нашиот сајт. Пребарувајте многу диверзна колекција од скинови и пронајдете нови техники и идеји. Бидете инспирирани и напревете си свој скинови.',
      10: 'Search for tags among all the tags on the site.',
      11: 'List of all past/active osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Најавете се',
    1: 'Почетна',
    profile_osu: 'osu! Профил',
    new_skin: 'Нов скин',
    notifications: 'Нотификации',
    settings: 'Опции',
    logout: 'Одјавување',
    load_more: 'Прикажи повеќе',
    copy_short: 'Копирај краток линк',
    copied: 'Копирано',
    reddit_link: 'Редит',
    osu_forum_link: 'osu! Форум',
    skin_return: 'Назад на скинот',
    source: 'Source',
    contest_voting: 'Vote here'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Создавател',
      1: 'Миксер',
      2: 'Анимации',
      3: 'Цртежи',
      4: 'Заедникчка работа'
    }
  },
  tooltips: {
    0: 'Прегледи: {amount}',
    1: 'Рефреширај резултати',
    2: 'Намалувачки | Накачувачки',
    3: 'Лајкови: {likes} / Дислајкови: {dislikes}',
    4: 'Претиснете ctrl+enter за да додадете тагови',
    5: 'Измени верзија',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Нема кратка дескрипција',
    8: 'Нема URL',
    9: 'Слегнувања: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)'
  },
  lists: {
    screens: {
      0: 'Добредојдовте',
      1: 'Главно Мени',
      2: 'Избирање песна',
      3: 'Мод Мени',
      4: 'Модови',
      5: 'Одбројување',
      6: 'Гејмплеј',
      7: 'Спинер',
      8: 'Поминета Секција',
      9: 'Изгубена Секција',
      10: 'Екран за Паузирање',
      11: 'Екран за Неуспевање',
      12: 'Result screen (top)',
      13: 'Прескокнување',
      14: 'Банер',
      15: 'Result screen (bottom)'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Помешано'
    }
  },
  select: {
    0: 'Ново',
    1: 'Поправено',
    2: 'Променето',
    3: 'Тргнето',
    4: 'Цртежи',
    5: 'Фонт',
    6: 'Артист',
    7: 'Елемент на скин',
    8: 'Аудио/Звучни ефекти',
    9: 'Алатки',
    views: 'Прегледи',
    likes: 'Лајкови',
    dislikes: 'Дислајкови',
    downloads: 'Слегнувања',
    size_range: 'Избери величина',
    date_range: 'Избери одредена дата',
    ratio: 'Избери сооднос | размер'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Избери величина',
    4: 'Избери одредена дата',
    5: 'Година',
    6: 'Месец',
    7: 'Избери сооднос',
    8: 'Избери категории',
    9: 'Гејм-модови',
    10: 'Избери вид',
    11: 'Пејстирај YouTube линк',
    12: 'Type a description and an url. Format description:url',
    13: 'Избери екстра',
    14: 'Пејстирај линк',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Помагај' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'Овој скин содржи работи за возрасни',
    2: 'Овој скин содржи работи за возрасни и некој корисници може да го најдат нарушувачки',
    3: 'Alright',
    4: 'bye o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation',
    52: 'Warning',
    53: 'You need to choose type of asset'
  },
  header: {
    0: 'Нотификации',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Неауторизирано',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No'
  }
};