export default {
  title: {
    home: 'Utama',
    login: 'Log masuk',
    lists: { 0: 'Senarai' },
    tags: {
      0: 'Penanda',
      1: '{amount} penanda untuk kategori {name}',
      2: 'Cari tag'
    },
    ideas: {
      0: 'Inspirasi',
      1: '«{amount}»'
    },
    sounds: { 0: 'Bunyi' },
    leaderboard: { 0: 'Papan pendahulu' },
    extend: { 0: 'Lebih | Kurang' },
    skin: {
      0: 'Skin ini mempunyai elemen-elemen daripada skin-skin yang lain',
      1: 'Klik di sini untuk maklumat lanjut'
    },
    tools: 'Alat'
  },
  changelogs: {
    0: 'Log perubahan',
    1: 'Senarai semua penyemakan yang telah dibuat di dalam versi terkini',
    2: 'Tiada apa-apa di sini',
    3: 'But you can add the changes you made\'ve to this version of the skin',
    4: 'Tidak dikumpulkan',
    5: 'Baharu',
    6: 'Pembetulan',
    7: 'Perubahan',
    8: 'Pembuangan'
  },
  ideas: {
    0: 'Tiada apa-apa dijumpai',
    1: 'Screenshot untuk «{type}» tidak dimuat naik kepada site'
  },
  creators: {
    0: 'Pembuat',
    1: 'Senarai semua pembuat yang terlibat dalam pembuatan versi ini',
    2: 'Tiada sesiapa di sini',
    3: 'Mencari untuk nama pemain akan menyenaraikan profil-profil.',
    4: 'Penyunting',
    5: 'Peranan',
    6: 'Versi-versi'
  },
  tags: {
    0: 'Penanda',
    1: 'Senarai semua penanda yang berkait dengan skin ini',
    2: 'Ia kelihatan sunyi di sini.',
    3: 'Gunakan medan di atas untuk mencari penanda-penanda yang baharu',
    4: 'Tag-tag tidak dijumpai',
    5: 'Cari perkara lain',
    6: 'Cari'
  },
  videos: {
    0: 'Video-video',
    1: 'Senarai semua video penunjukkan untuk skin ini',
    2: 'Tiada video penunjukkan',
    3: 'Layari untuk beberapa di YouTube atau buat sendiri anda punya video penunjukkan'
  },
  sources: {
    0: 'Atribusi',
    1: 'Senarai semua aset atau peralatan yang digunakan untuk versi skin ini',
    2: 'Nampak macam kosong kat sini',
    3: 'Jika anda menggunakan aset daripada skin lain, atau seni lain, sila mengisinya di dalam kotak di atas',
    4: 'Tidak dikumpulkan'
  },
  checks: {
    0: 'Semua',
    1: 'Metadata',
    2: 'Sorotan',
    3: 'Nama skin tidak dispesifikasi',
    4: 'Menambah sekurang-kurangnya satu pembuat skin',
    5: 'Letakkan beberapa tag',
    6: 'Saiz skin tidak dispesifikasi',
    7: 'Pilih sekurang-kurangnya satu mod permainan',
    8: 'Pilih resolusi gambar (SD atau HD)',
    9: 'Pilih sekurang-kurangnya satu nisbah aspek',
    10: 'Tiada screenshot yang diberikan',
    11: 'Masukkan sekurang-kurangnya satu screenshot bagi gameplay',
    12: 'Pautan bagi skin tidak dispesifikasi',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Senarai semak',
    23: 'Letakkan sekurang-kurangnya satu versi awam'
  },
  skins: {
    0: 'Skin-skin',
    1: 'Popular',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Terbaharu',
    5: 'Rawak',
    6: 'Semua skin',
    7: 'Nisbah aspek',
    8: 'Semua skin | skin osu',
    9: 'Skin | Skin | Skin',
    10: 'Skin osu oleh {name} | Semua skin daripada',
    11: 'Cari',
    12: '{name} skin-skin',
    13: 'Meneroka skin lain'
  },
  skin: {
    0: 'Mengedit',
    1: 'Tambahan',
    2: 'HD',
    3: 'FullHD',
    4: 'Aminasi',
    5: 'Screenshots',
    6: 'Gameplay sahaja',
    7: 'Pautan muat turun | Muat turun skin',
    8: 'Pos forum | Forum osu!',
    9: 'Pos Reddit',
    10: 'Pembuat',
    11: 'Penanda',
    13: 'Video-video',
    14: 'Versi baharu | Mengurus versi',
    15: 'Mengemaskini | Menyerahkan',
    16: 'Mod permainan',
    17: 'Nama skin',
    18: 'Versi | Versi-versi',
    19: 'Saiz',
    20: 'Metadata',
    21: 'Penilaian',
    22: 'Muat turun',
    23: 'Muat turun akan disediakan nanti',
    24: '{amount} saat tinggal',
    25: 'Kamu bukan salah satu dari kami',
    26: 'Kelihatan seperti kamu bukan pembuat atau penyunting skin ini',
    27: 'Skin oleh',
    28: 'Tiada tag',
    29: 'Tiada video',
    30: 'Tiada pembuat'
  },
  drag: {
    0: 'Ketik di sini',
    1: 'atau tarik dan lepas gambar di sini'
  },
  footer: {
    0: 'Dibuat oleh cyperdark',
    1: 'Penghargaan'
  },
  credits: {
    0: 'Chibi',
    1: 'Lukisan',
    2: 'Ikon-ikon',
    3: 'Semua ikon diambil daripada {name}',
    4: 'Bendera-bendera',
    5: 'Semua gambar bendera diambil dari {name}',
    6: 'Lokalisasi',
    7: 'Sesiapa? [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Cari skin',
    1: 'Tontonan',
    2: 'Tajuk',
    3: 'Penilaian',
    4: 'Saiz',
    5: 'Tarikh',
    7: 'Tiada apa-apa dijumpai',
    8: 'Try using different search filters',
    9: 'Menunggu pertanyaan',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Muat turun',
    12: 'Nama',
    13: {
      0: 'Skin-skin',
      1: 'Penanda',
      2: 'Pengguna',
      3: 'Senarai'
    }
  },
  tabs: {
    0: 'Cari',
    1: 'Mengedit',
    2: 'Senarai'
  },
  undefined: {
    0: 'Kosong',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Tiada kebenaran',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Meneroka skin-skin osu',
      1: 'Mod permainan, nisbah aspek skin osu',
      2: 'Skin osu yang popular',
      3: 'Mencari skin osu',
      4: 'Senarai penanda, {name}',
      5: '{name} v{version} skin osu',
      6: 'Penghargaan',
      7: 'skin-skin osu',
      8: '{name} mencari skin osu',
      9: 'Dapatkan inspirasi dari skin osu yang lain',
      10: '{name} membuat skin osu',
      11: 'Cari tag',
      12: '{name} tag-tag dijumpai'
    },
    description: {
      0: 'Dapatkan skin osu! yang terbaik dari laman web kami! Kami mempunyai banyak skin untuk semua mod permainan, nisbah aspek dan juga pemain-pemain terbaik. Tambahan, kami juga mempunyai bahagian yang istimewa untuk peminat-peminat anime. Menaik taraf permainan anda dengan skin yang sempurna. #osuskins #osugame #anime',
      1: '{views} tontonan. osu skin untuk {modes}, saiznya adalah {size}, dibuat oleh {creators}. Menyokong {ratios}',
      2: 'Cari skin osu! yang sempurna dengan ciri carian kami yang hebat. Semak melalui koleksi kami yang luas, ditapis dengan mod permainan, aspek nisbah, dan banyak lagi. Atau, lihat skin yang digunakan oleh pemain-pemain terbaik.',
      3: 'Meneroka skin yang pelbagai untuk mod permainan dan aspek nisbah di laman web kami. Pilih daripada mod standard, catch the beat, mania, dan taiko. Cari skin yang sempurna untuk pemainan anda.',
      4: 'Cari osu skin yang sempurna daripada permain terkenama di website kami. Imbas kembali koleksi skin terkemuka kami dan hiasi gameplay anda. Ketemuilah pelbagai gaya dan tema yang menepati pilihan anda.',
      5: 'Senarai tag yang wujud untuk skin osu.',
      6: '{name} koleksi skin osu!, muat turun secara percuma',
      7: 'Skin osu yang banyak untuk {name}, muat turun secara percuma!',
      8: 'Semua skin osu dibuat oleh {name}',
      9: 'Cari inspirasi untuk skin osu! anda yang seterusnya di laman web kami. Semak melalui koleksi skin yang pelbagai dan teroka pelbagai teknik dan idea. Dapatkan inspirasi dan cipta skin anda yang unik.',
      10: 'Cari tag-tag dari kesemua tag di site ini.'
    }
  },
  buttons: {
    0: 'Daftar masuk',
    1: 'Muka depan',
    profile_osu: 'profil osu',
    new_skin: 'Skin baharu',
    notifications: 'Notifikasi',
    settings: 'Aturcara',
    logout: 'Keluar',
    load_more: 'Tambah lagi',
    copy_short: 'Menyalin pautan pendek',
    copied: 'Telah disalin',
    reddit_link: 'Reddit',
    osu_forum_link: 'forum osu',
    skin_return: 'Balik ke skin'
  },
  user: {
    roles: {
      0: 'Pencipta',
      1: 'Penggubah',
      2: 'Animasi',
      3: 'Lukisan',
      4: 'Kolaborasi'
    }
  },
  tooltips: {
    0: 'Tontonan: {amount}',
    1: 'Muat semula hasil',
    2: 'Menurun | Menaik',
    3: 'Suka: {likes} / Tidak suka: {dislikes}',
    4: 'Tekan ctrl+tag untuk menambah tag',
    5: 'Edit versi',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Tiada kandungan',
    8: 'Tiada url',
    9: 'Muat turun: {amount}'
  },
  lists: {
    screens: {
      0: 'Selamat datang',
      1: 'Menu utama',
      2: 'Pilih lagu',
      3: 'Menu mode',
      4: 'Mod',
      5: 'Kiraan',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section pass',
      9: 'Section Fail',
      10: 'Skrin berhenti',
      11: 'Skrin Gagal',
      12: 'Skrin keputusan',
      13: 'Skip',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Digubah'
    }
  },
  select: {
    0: 'Baharu',
    1: 'Telah dibetulkan',
    2: 'Telah ditukar',
    3: 'Telah dibuang',
    4: 'Lukisan',
    5: 'Font',
    6: 'Pelukis',
    7: 'Unsur skin',
    8: 'Audio/Sfx',
    9: 'Alat',
    views: 'Tontonan',
    likes: 'Suka',
    dislikes: 'Tidak suka',
    downloads: 'Muat turun',
    size_range: 'Pilih saiz',
    date_range: 'Pilih julat tarikh',
    ratio: 'Pilih nisbah aspek | nisbah'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Pilih saiz',
    4: 'Pilih julat tarikh',
    5: 'Tahun',
    6: 'Bulan',
    7: 'Pilih nisbah aspek',
    8: 'Pilih kategori',
    9: 'Mod permainan',
    10: 'Pilih taip',
    11: 'Letakkan pautan Youtube',
    12: 'Type a description and an url. Format description:url',
    13: 'Pilih tambahan',
    14: 'Letakkan pautan',
    15: 'Skin title, author, or tags',
    16: 'Pilih katergori',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Sumbangan' },
  nsfw: {
    0: 'Amaran!',
    1: 'Skin ini mengandungi kandungan sensitif ataupun kandungan dewasa',
    2: 'Skin ini mengandungi kandungan sensitif atau kandungan dewasa yang mungkin tidak disukai oleh sesetengah pengguna',
    3: 'Ok',
    4: 'jumpa lagi o/'
  },
  removed: {
    0: 'Versi tidak ada',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Tunjuk',
    3: 'Tidak dijumpai',
    4: 'Banner tidak dijumpai (Screenshot pertama sedang digunakan sebagai banner)',
    5: 'Tiada perubahan',
    6: 'Tiada perubahan dijumpai',
    7: 'ID tidak dijumpai',
    8: 'ID untuk video tidak dijumpai, cuba pautan yang lain (Buat masa sekarang hanya pautan Youtube sahaja yang disokong)',
    9: 'Alamak',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Wujud',
    12: 'Video ini telah pun ditambah',
    13: 'Wujud',
    14: 'Tag ini telah pun ditambah',
    15: 'Tidak dijumpai',
    16: 'Anda tidak boleh memadamkan tag',
    17: 'Telah ditambah',
    18: 'Anda berjaya menambah tag baharu',
    19: 'Alamak',
    20: 'Pencipta ini telah pun diletakkan',
    21: 'EZ',
    22: 'Pencipta baharu telah pun ditambah',
    23: 'HUH',
    24: 'Mustahil untuk memadam sesebuah pencipta',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Amaran',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Amaran',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Telah dipulihkan',
    34: 'Version «{name}» has been restored',
    35: 'Dibuang',
    36: 'Version «{name}» has been deleted',
    37: 'Ralat',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Ralat tidak diketahui',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Berjaya',
    47: 'Perubahan baharu telah diserahkan kepada pihak moderasi',
    48: 'Perubahan telah dimuat naik kepada pihak moderasi',
    49: 'Link pelik',
    50: 'Link ini tidak boleh diguna sebagai link muat turun',
    51: 'Submitted for moderation'
  },
  restricted_view: {
    0: 'Tiada kebenaran',
    1: 'Please log into your account',
    2: 'Pengelihatan terhad',
    3: 'Helaian ini belum dikeluarkan, lagi.'
  }
};