export default {
  title: {
    home: 'Startpagina',
    login: 'Inloggen',
    lists: { 0: 'Lijsten' },
    tags: {
      0: 'Categorieën',
      1: '{amount} tags voor categorie {name}',
      2: 'Zoek categorieën'
    },
    ideas: {
      0: 'Inspiratie',
      1: '«{amount}»'
    },
    sounds: { 0: 'Geluiden' },
    leaderboard: { 0: 'Ranglijsten' },
    extend: { 0: 'Meer | Minder' },
    skin: {
      0: 'Deze skin bevat een of meerdere elementen van andere skins',
      1: 'Klik hier voor meer informatie'
    },
    tools: 'Hulpmiddelen'
  },
  home: {
    0: 'Beschikbaar om te downloaden',
    1: 'Meest: _name_skins',
    2: 'Bekeken | Duimpie omhoog | Gedownload',
    3: 'Publiceer een nieuwe skin',
    4: 'Hoe een skin te installeren',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Veranderingen',
    1: 'Lijst van alle gemaakte wijzigingen in de huidige versie',
    2: 'Niks hier',
    3: 'Maar je kan de aanpassingen die jij gemaakt hebt aan deze versie van de skin toevoegen',
    4: 'Niet gegroepeerd',
    5: 'Nieuw',
    6: 'Verbeteringen',
    7: 'Veranderingen',
    8: 'Verwijderingen'
  },
  ideas: {
    0: 'Niks gevonden',
    1: 'Schermafbeeldingen of «{type}» zijn niet geüpload naar de website',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Auteurs',
    1: 'Lijst van alle auteurs die hielpen met het maken van deze versie',
    2: 'Er is niemand is hier',
    3: 'Zoeken naar een spelers naam zal een lijst van profielen laten zien.',
    4: 'Editor',
    5: 'Rollen',
    6: 'Versies'
  },
  tags: {
    0: 'Categorieën',
    1: 'Lijst van alle tags gerelateerd aan deze skin',
    2: 'Het is hier vrij leeg.',
    3: 'Gebruik het bovenstaande veld om nieuwe tags te vinden',
    4: 'Categorieën niet gevonden',
    5: 'Probeer naar iets anders te zoeken',
    6: 'Zoek'
  },
  videos: {
    0: 'Video\'s',
    1: 'Lijst van alle video\'s gerelateerd aan deze skin',
    2: 'Nul showcases',
    3: 'Zoek er een op YouTube of maak er zelf een'
  },
  sources: {
    0: 'Erkenning',
    1: 'Lijst van alle gebruikte hulpmiddelen in de versie van de skin',
    2: 'Beetje leeg hier',
    3: 'Als je hulpmiddelen van andere skins of kunst hebt gebruikt, voeg ze vooral toe in het vak hierboven',
    4: 'Niet gegroepeerd'
  },
  checks: {
    0: 'Alles',
    1: 'Metadata',
    2: 'Uitgelicht',
    3: 'Naam van de skin is niet gespecificeerd',
    4: 'Voeg tenminste één auteur van de skin toe',
    5: 'Voeg een paar tags toe',
    6: 'Grootte van de skin is niet gegeven',
    // 7: 'Select at least one gamemode',
    8: 'Selecteer een file type (SD of HD)',
    9: 'Selecteer tenminste één aspect ratio',
    10: 'Geen schermopnames aangeboden',
    11: 'Voeg tenminste één schermopname toe terwijl je speelt',
    12: 'Link naar de skin is niet gegeven',
    20: 'Ziet er goed uit',
    21: 'Elk probleem is opgelost. Lekker gedaan!',
    22: 'Checklist',
    23: 'Voeg minimaal één openbare versie toe',
    24: 'Voeg tenminste één maker toe aan deze versie',
    25: 'Sommige auteurs hebben geen rollen',
    26: '{amount} schermafbeeldingen hebben geen categorie',
    28: 'Selecteer de gamemode voor schermafbeeldingen van gameplay'
  },
  skins: {
    0: 'Skins',
    1: 'Populair',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recent',
    5: 'Willekeurig',
    6: 'Alle skins',
    7: 'Aspect ratio',
    8: 'Alle skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins door {name} | Alle skins van',
    11: 'Zoek',
    12: '{name} skins',
    13: 'Ontdek skins',
    14: 'Populaire skins'
  },
  skin: {
    0: 'Bewerk',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animatie',
    5: 'Schermopnames',
    6: 'Alleen van tijdens het spelen',
    7: 'Download link | Download skin',
    8: 'Forum berichten | osu! Forum',
    9: 'Reddit post',
    10: 'Auteurs',
    11: 'Categorieën',
    13: 'Video\'s',
    14: 'Nieuwe Versie | Beheer versies',
    15: 'Update | Indienen',
    16: 'Gamemodes',
    17: 'Naam van de skin',
    18: 'Versie | Versies',
    19: 'Grootte',
    20: 'Metadata',
    21: 'Beoordeling',
    22: 'Downloads',
    23: 'Download komt er binnenkort aan',
    24: '{amount} seconden over',
    25: 'Jij hoort niet bij ons',
    26: 'Het ziet ernaar uit dat je niet de auteur of editor van deze skin bent',
    27: 'Skin door',
    28: 'Geen categorieën',
    29: 'Geen video\'s',
    30: 'Geen makers',
    31: 'Beoordeel de skin',
    32: 'Geef een pijltje omhoog & bespreek op reddit',
    33: 'Bespreek op het osu! forum',
    34: 'Meer skins van deze auteur | Meer skins van deze auteurs',
    35: 'Steun de skin',
    36: 'Onbeschikbaar',
    37: 'Deze skin is helaas verwijderd',
    38: 'Welkom bij de skin post editor!',
    39: `Onbekend met de skin editor? Laat je begeleiden door de interface zodat je het maximale eruit kan halen!`,
    40: '{current} van {max} afgemaakt',
    41: 'Bekijk later',
    42: `Laten we beginnen`,
    43: 'Gefeliciteerd!',
    44: 'Je hebt succesvol de introductie voltooid, veel plezier!',
    45: 'uploader'
  },
  drag: {
    0: 'Klik hier',
    1: 'of sleep foto\'s hierheen'
  },
  footer: {
    0: 'Gemaakt door cyperdark',
    1: 'Dank aan',
    2: 'Regels',
    3: 'Contacten'
  },
  credits: {
    0: 'Chibi',
    1: 'Kunstwerken',
    2: 'Icoontjes',
    3: 'Alle icoontjes zijn genomen van {name}',
    4: 'Vlaggen',
    5: 'Alle vlaggen zijn genomen van {name}',
    6: 'Vertalingen',
    7: 'Iemand? [{lang}]',
    8: 'Het ziet ernaar uit dat cyperdark ze is vergeten toe te voegen. {text}'
  },
  search: {
    0: 'Zoek naar skin',
    1: 'Weergaven',
    2: 'Titel',
    3: 'Beoordeling',
    4: 'Grootte',
    5: 'Datum',
    7: 'Niks gevonden',
    8: 'Probeer andere zoek criteria',
    9: 'We wachten op je zoekopdracht',
    10: 'Gebruik de zoekfilters of typ de titel van de skin, auteur of tags',
    11: 'Downloads',
    12: 'Naam',
    13: {
      0: 'Skins',
      1: 'Categorieën',
      2: 'Gebruikers',
      3: 'Lijsten'
    },
    14: 'Zoek:',
    15: 'Groote:',
    16: 'Beoordeling:',
    17: 'Weergaven:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Wedstrijden',
    1: 'Officiële nieuwspost',
    2: 'Inzending',
    3: 'Aan het voorbereiden',
    4: 'Stemmen',
    5: 'Voltooid',
    6: 'Wedstrijden',
    7: 'Stem pagina'
  },
  rules: {
    0: 'Laatst bijgewerkt op',
    1: 'Regels rond skins publiceren'
  },
  skinini: {
    0: 'Welkom bij de skin.ini bewerker!',
    1: `Onbekend met de skin.ini bewerker? Laat ons je door de interface begeleiden en alle mogelijkheden laten zien!`,
    2: '{current} van {max} afgemaakt',
    3: 'Geen resultaten',
    4: 'Je query mag spelfouten bevatten'
  },
  tabs: {
    0: 'Zoek',
    1: 'Bewerk',
    2: 'Lijst'
  },
  undefined: {
    0: 'Leeg',
    1: 'Helaas pindakaas, er is hier niks, maar je kan op andere pagina\'s wel wat vinden',
    2: 'Helaas pindakaas, er is hier niks',
    3: 'Niet geautoriseerd',
    4: 'Je moet ingelogd zijn om deze skin te veranderen.',
    5: 'Je moet ingelogd zijn om een nieuwe skin toe te voegen.'
  },
  settings: {
    0: 'Instellingen',
    1: 'Muis scrol',
    2: 'Schakel muisaanwijzing in voor afbeeldingscarrousel, wat links naar rechts of rechts naar links mogelijk maakt.',
    3: 'Vergroot',
    4: 'Zet het vergroten van afbeeldingen bij erboven zweven aan voor een groter skin voorbeeld.'
  },
  meta: {
    title: {
      0: 'Ontdek osu skins',
      1: 'Gamemodes, aspect ratio\'s van de skins',
      2: 'Populaire osu skins',
      3: 'Zoek osu skins',
      4: '«{name}» tags lijst',
      5: '{name} v{version} osu skin',
      6: 'Dank aan',
      7: 'osu skins',
      8: '{name} zoek osu skins',
      9: 'Krijg inspiratie van andere osu skins',
      10: '{name} maakte osu skins',
      11: 'Zoek categorieën',
      12: '{name} gevonden tags',
      13: 'Nieuwe skin',
      14: 'Website regels',
      15: 'osu! Wedstrijden',
      16: 'osu! skinning hulpmiddelen'
    },
    description: {
      0: 'Pak de beste osu! skins van onze website! Ons grote aanbod heeft skins voor alle gamemodes, aspect ratio’s  en we hebben zelfs skins van de beste spelers. Maar dan heb je anime sectie nog niet gezien. Speel beter met onze hoge skins van hoge kwaliteit. #osuskins #osugame #anime',
      1: '{views} weergaven. Een osu skin voor {modes}, de grootte is {size}, gemaakt door {creators}. Ondersteunt {ratios}',
      2: 'Vind de perfecte osu! skin met onze geavanceerd zoek mechanisme. Verdwaal in onze gigantische bibliotheek, gefilterd op gamemode, aspect ratio en meer, of neem een kijkje bij skins die de beste spelers gebruiken.',
      3: 'Ontdek veel verschillende skins voor elke gamemode en aspect ratio op onze site. Kies uit standaard, catch the beat, mania of taiko en vindt wat het beste past bij jou.',
      4: 'Vindt de perfecte osu skin van de beste spelers op onze site. Verdwaal in onze collectie van populaire skins en verander ze naar jouw voorkeuren. Ga op avontuur in een diverse selectie  van stijlen en thema’s om voor jouw de perfecte skin te vinden.',
      5: 'Lijst van bestaande tags voor osu skins.',
      6: '{name} osu skin collectie!, gratis om te downloaden',
      7: 'Een gigantische hoeveelheid osu skins voor een {name}, gratis te downloaden!',
      8: 'Alle osu skins gemaakt door {name}',
      9: 'Vindt inspiratie voor jouw volgende osu! skin op onze site. Verdwaal in ons gevarieerde bos van skins en ontdek nieuwe technieken en ideeën. Wordt geïnspireerd en maak je eigen unieke skins.',
      10: 'Zoek naar categorieën tussen alle categorieën op de website.',
      11: 'Lijst van alle actieve/voltooide osu! wedstrijden',
      12: '{amount} inzendingen voor {title} wedstrijd. {views} weergaven'
    }
  },
  buttons: {
    0: 'Inloggen',
    1: 'Thuispagina',
    profile_osu: 'osu! Profiel',
    new_skin: 'Nieuwe skin',
    notifications: 'Notificaties',
    settings: 'Instellingen',
    logout: 'Uitloggen',
    load_more: 'Laad meer in',
    copy_short: 'Kopieer de korte link',
    copied: 'Gekopieerd',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Terug naar skin',
    source: 'Bron',
    contest_voting: 'Stem hier',
    rules_agree: 'Ik ben het ermee eens',
    report_issue: 'Meldt een probleem',
    ghost_creator: 'Ghost maker',
    close: 'Sluit',
    quick_select: 'Snel selecteren'
  },
  choose: {
    0: 'Optioneel',
    1: 'Verplicht',
    2: 'Kies ten minste één optie'
  },
  user: {
    roles: {
      0: 'Auteur',
      1: 'Mixer',
      2: 'Animaties',
      3: 'Kunstwerken',
      4: 'Samenwerking ',
      5: 'Geluiden',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: 'Weergaven: {amount}',
    1: 'Herlaad resultaten',
    2: 'Aflopend | Oplopend',
    3: 'Duimpies: {likes} / Duimpies omlaag: {dislikes}',
    4: 'Druk op ctrl+enter om een tag toe te voegen',
    5: 'Bewerk versie',
    6: '{s}Log in{p}, om deze skin te beoordelen',
    7: 'Geen korte beschrijving',
    8: 'Geen url',
    9: 'Keren gedownload: {amount}',
    10: 'Herstel alles',
    11: 'Toon tips',
    12: 'Verberg tips',
    13: 'Om een regel als gelezen te markeren, beweeg erover (Geel betekent ongelezen)',
    14: {
      0: '[hl]{example}[/hl] - [b]gelijk aan[/b] aan {amount}',
      1: '[hl]{example}[/hl] - [b]hoger dan[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]lager dan[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]van[/b] {amount} [b]tot[/b] {amount_2}'
    },
    15: 'Deselecteer',
    16: 'Verwijder bestand'
  },
  lists: {
    screens: {
      0: 'Welkom',
      1: 'Hoofdmenu',
      2: 'Nummer selecteren',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Aftelling',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sectie gehaald',
      9: 'Sectie gefaald',
      10: 'Pauzeerscherm',
      11: 'Faalscherm',
      12: 'Resultatenscherm',
      13: 'Sla over',
      14: 'Banner',
      15: 'Resultatenscherm (onderaan)',
      16: 'Startafbeelding'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Nieuw',
    1: 'Verbeterd',
    2: 'Veranderd',
    3: 'Verwijderd',
    4: 'Kunst',
    5: 'Font',
    6: 'Artiest',
    7: 'Skin element',
    8: 'Geluid/Geluidseffecten',
    9: 'Hulpmiddelen',
    10: 'Afbeelding',
    views: 'Weergaven',
    likes: 'Duimpies',
    dislikes: 'Duimpies omlaag',
    downloads: 'Downloads',
    ratio: 'Selecteer een aspect ratio | ratio',
    sorting: 'Opl. | Afl.'
  },
  sorting: {
    0: 'Meeste | Minste',
    1: 'Meeste | Minste',
    2: 'Hoogste | Laagste',
    3: 'Grootste | Kleinste',
    4: 'Nieuwste | Oudste',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Selecteer rollen',
    1: 'Selecteer versies',
    2: 'Type wat tekst...',
    3: 'Selecteer groote',
    4: 'Selecteer tijdsperiode',
    5: 'Jaar',
    6: 'Maand',
    7: 'Selecteer aspect ratio',
    8: 'Selecteer categorieën',
    9: 'Gamemodes',
    10: 'Selecteer type',
    11: 'Plak een youtube link',
    12: 'Typ een omschrijving en URL. Formaat omschrijving:URL',
    13: 'Selecteer extra',
    14: 'Plak een link',
    15: 'Skin titel, auteur of categorieën',
    16: 'Selecteer categorie',
    17: 'Type de naam van de categorie',
    18: 'Type de naam van de skin',
    19: 'Type de naam van de auteur ',
    20: 'Selcteer bestand',
    24: 'Typede gameplay naam...',
    25: 'Typ bereik',
    26: 'Type tekst'
  },
  contribute: { 0: 'Draag je steentje bij' },
  nsfw: {
    0: 'Pas op, nsfw!',
    1: 'Deze skin bevat gevoelige of volwassen onderdelen',
    2: 'Deze skin bevat gevoelige of volwassen onderdelen die sommige gebruikers schokkend kunnen vinden',
    3: 'Oké',
    4: 'laters o/',
    5: 'Furry Waarschuwing!'
  },
  removed: {
    0: 'Versie onbeschikbaar',
    1: 'De auteur van de skin heeft besloten deze versie van de site te verwijderen.',
    2: 'Ga naar een beschikbare versie'
  },
  notify: {
    0: 'Problemen zijn niet opgelost',
    1: 'Niet alle verplichte velden zijn ingevuld',
    2: 'Geef weer',
    3: 'Niet gevonden',
    4: 'Banner niet gevonden (momenteel wordt de eerste schermafbeelding als de banner gebruikt)',
    5: 'Geen wijzigingen',
    6: 'Er zijn geen wijzigingen gevonden',
    7: 'ID niet gevonden',
    8: 'ID van de video niet gevonden, probeer een andere link (Op het moment wordt alleen YouTube ondersteund)',
    9: 'Oepsie',
    10: 'Het lijkt erop dat je sessie is verlopen, open een nieuwe pagina en log in op je account (Geen zorgen, alles is automatisch opgeslagen)',
    11: 'Bestaat',
    12: 'Deze video is al toegevoegd',
    13: 'Bestaat',
    14: 'Deze categorie is al toegevoegd',
    15: 'Niet gevonden',
    16: 'Je kan een verwijderde categorie niet verwijderen',
    17: 'Toegevoegd',
    18: 'Je hebt een nieuwe categorie toegevoegd',
    19: 'OEpsie',
    20: 'Deze maker is al toegevoegd',
    21: 'EZ',
    22: 'Nieuwe maker is toegevoegd',
    23: 'HUH',
    24: 'Onmogelijk om een verwijderde maker te verwijderen',
    25: 'Dupliceer',
    26: 'Deze wijziging is al eerder toegevoegd.',
    27: 'Dupliceer',
    28: 'Deze URL is al eerder toegevoegd.',
    29: 'Waarschuwing',
    30: 'U bent vergeten een beschrijving voor de URL toe te voegen. Voorbeeld: Omschrijving:URL',
    31: 'Waarschuwing',
    32: 'U bent vergeten een beschrijving voor de URL toe te voegen. Voorbeeld: Omschrijving:URL',
    33: 'Hersteld',
    34: 'Versie «{name}» is hersteld',
    35: 'Verwijderd',
    36: 'Versie «{name}» is verwijderd',
    37: 'Foutmelding',
    38: 'Blijkbaar denkt de server dat je een robot bent.',
    39: 'Je huidige login sessie is verlopen. Open een nieuwe pagina om verder te gaan en log opnieuw in op je account. Zodra je dat hebt gedaan, kom terug naar deze pagina en probeer het opnieuw.',
    40: 'Niet overeenkomende gegevens (opnieuw inloggen in account. Geen zorgen, alles is automatisch opgeslagen)',
    41: 'Onbekende foutmelding',
    42: 'Je kan een niet bestaande skin niet bewerken',
    43: 'Het ziet ernaar uit dat je geen toestemming hebt om deze skin te bewerken',
    44: 'Je kunt deze versie niet insturen, omdat die hetzelfde is als de vorige.',
    45: 'Deze wijzigingen zijn al verstuurd voor moderatie',
    46: 'Succes',
    47: 'Nieuwe wijzigingen zijn ingediend voor moderatie',
    48: 'Nieuwe wijzigingen zijn ingediend voor moderatie',
    49: 'Vreemde link',
    50: 'Deze link kan niet gebruikt worden als download link',
    51: 'Ingediend voor moderatie',
    52: 'Waarschuwing',
    53: 'Je moet een type of asset keizen',
    54: 'De skin is momenteel onder controle. Bedankt voor je geduld',
    55: 'Succes',
    56: 'Nieuwe ghost maker is toegevoegd',
    57: 'Kleur gekopieerd',
    58: `De RGB-code "{color}" is nu beschikbaar via je klembord!`
  },
  header: {
    0: 'Notificaties',
    1: 'Volg ons op deze plekken om notificaties te ontvangen over nieuwe skins'
  },
  restricted_view: {
    0: 'Niet geautoriseerd',
    1: 'Meld je aan op je account',
    2: 'Beperkte weergave',
    3: 'Deze pagina is nog niet uit.'
  },
  confirm: {
    0: 'Herstel alles?',
    1: 'Toon tips?',
    2: 'Verstuur skin?',
    3: 'Ja',
    4: 'Nee',
    5: 'Herstel .ini?'
  }
};