export default {
  title: {
    home: 'Startpagina',
    login: 'Inloggen',
    lists: { 0: 'Lijsten' },
    tags: {
      0: 'Categorieën',
      1: '{amount} tags voor categorie {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiratie',
      1: '«{amount}»'
    },
    sounds: { 0: 'Geluiden' },
    leaderboard: { 0: 'Ranglijsten' },
    extend: { 0: 'Meer | Minder' },
    skin: {
      0: 'Deze skin bevat een of meerdere elementen van andere skins',
      1: 'Klik hier voor meer informatie'
    },
    tools: 'Hulpmiddelen'
  },
  changelogs: {
    0: 'Veranderingen',
    1: 'Lijst van alle gemaakte wijzigingen in de huidige versie',
    2: 'Niks hier',
    3: 'Maar je kan veranderingen toevoegen die jij hebt gemaakt bij deze versie van de skin',
    4: 'Niet gegroepeerd',
    5: 'Nieuw',
    6: 'Verbeteringen',
    7: 'Veranderingen',
    8: 'Verwijderingen'
  },
  ideas: {
    0: 'Niks gevonden',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Auteurs',
    1: 'Lijst van alle auteurs die hielpen met het maken van deze versie',
    2: 'Er is niemand is hier',
    3: 'Zoeken naar een spelers naam zal een lijst van profielen laten zien.',
    4: 'Editor',
    5: 'Rollen',
    6: 'Versies'
  },
  tags: {
    0: 'Categorieën',
    1: 'Lijst van alle tags gerelateerd aan deze skin',
    2: 'Het is hier vrij leeg.',
    3: 'Gebruik het bovenstaande veld om nieuwe tags te vinden',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Zoek'
  },
  videos: {
    0: 'Video\'s',
    1: 'Lijst van alle video\'s gerelateerd aan deze skin',
    2: 'Nul showcases',
    3: 'Zoek er een op YouTube of maak er zelf een'
  },
  sources: {
    0: 'Erkenning',
    1: 'Lijst van alle gebruikte hulpmiddelen in de versie van de skin',
    2: 'Beetje leeg hier',
    3: 'Als je hulpmiddelen van andere skins of kunst hebt gebruikt, voeg ze vooral toe in het vak hierboven',
    4: 'Niet gegroepeerd'
  },
  checks: {
    0: 'Alles',
    1: 'Metadata',
    2: 'Uitgelicht',
    3: 'Name of the skin not specified',
    4: 'Voeg tenminste één auteur van de skin toe',
    5: 'Voeg een paar tags toe',
    6: 'Grootte van de skin is niet gegeven',
    7: 'Selecteer tenminste één gamemode',
    8: 'Selecteer een file type (SD of HD)',
    9: 'Selecteer tenminste één aspect ratio',
    10: 'Geen schermopnames aangeboden',
    11: 'Voeg tenminste één schermopname toe terwijl je speelt',
    12: 'Link naar de skin is niet gegeven',
    20: 'Ziet er lekker uit',
    21: 'Elk probleem is opgelost en dat is best fijn',
    22: 'Checklist',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Populair',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recent',
    5: 'Willekeurig',
    6: 'Alle skins',
    7: 'Aspect ratio',
    8: 'Alle skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins door {name} | Alle skins van',
    11: 'Zoek',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Bewerk',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animatie',
    5: 'Schermopnames',
    6: 'Alleen van tijdens het spelen',
    7: 'Download link | Download skin',
    8: 'Forum berichten | osu! Forum',
    9: 'Reddit post',
    10: 'Auteurs',
    11: 'Categorieën',
    13: 'Video\'s',
    14: 'Nieuwe Versie | Beheer versies',
    15: 'Update | Indienen',
    16: 'Gamemodes',
    17: 'Naam van de skin',
    18: 'Versie | Versies',
    19: 'Grootte',
    20: 'Metadata',
    21: 'Beoordeling',
    22: 'Downloads',
    23: 'Download komt er binnenkort aan',
    24: '{amount} seconden over',
    25: 'Jij hoort niet bij ons',
    26: 'Het ziet ernaar uit dat je niet de auteur of editor van deze skin bent',
    27: 'Skin door',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Klik hier',
    1: 'of sleep foto\'s hierheen'
  },
  footer: {
    0: 'Gemaakt door cyperdark',
    1: 'Dank aan'
  },
  credits: {
    0: 'Chibi',
    1: 'Kunstwerken',
    2: 'Icoontjes',
    3: 'Alle icoontjes zijn genomen van {name}',
    4: 'Vlaggen',
    5: 'Alle vlaggen zijn genomen van {name}',
    6: 'Vertalingen',
    7: 'Iemand? [{lang}]',
    8: 'Het ziet ernaar uit dat cpol ze is vergeten toe te voegen. {text}'
  },
  search: {
    0: 'Zoek naar skin',
    1: 'Weergaven',
    2: 'Titel',
    3: 'Beoordeling',
    4: 'Grootte',
    5: 'Datum',
    7: 'Niks gevonden',
    8: 'Probeer andere zoek criteria',
    9: 'We wachten op je zoekopdracht',
    10: 'Selecteer de zoek criteria of type gewoon de titel, auteur of tag van de skin',
    11: 'Downloads',
    12: 'Naam',
    13: {
      0: 'Skins',
      1: 'Categorieën',
      2: 'Users',
      3: 'Lijsten'
    }
  },
  tabs: {
    0: 'Zoek',
    1: 'Bewerk',
    2: 'Lijst'
  },
  undefined: {
    0: 'Leeg',
    1: 'Helaas pindakaas, er is hier niks, maar je kan op andere pagina\'s wel wat vinden',
    2: 'Helaas pindakaas, er is hier niks',
    3: 'Niet geautoriseerd',
    4: 'Je moet ingelogd zijn om deze skin te veranderen.',
    5: 'Je moet ingelogd zijn om een nieuwe skin toe te voegen.'
  },
  meta: {
    title: {
      0: 'Ontdek osu skins',
      1: 'Gamemodes, aspect ratio\'s van de skins',
      2: 'Populaire osu skins',
      3: 'Zoek osu skins',
      4: '«{name}» tags lijst',
      5: '{name} v{version} osu skin',
      6: 'Dank aan',
      7: 'osu skins',
      8: '{name} zoek osu skins',
      9: 'Krijg inspiratie van andere osu skins',
      10: '{name} maakte osu skins',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Pak de beste osu! skins van onze website! Ons grote aanbod heeft skins voor alle gamemodes, aspect ratio’s  en we hebben zelfs skins van de beste spelers. Maar dan heb je anime sectie nog niet gezien. Speel beter met onze hoge skins van hoge kwaliteit. #osuskins #osugame #anime',
      1: '{views} weergaven. Een osu skin voor {modes}, de grootte is {size}, gemaakt door {creators}. Ondersteunt {ratios}',
      2: 'Vind de perfecte osu! skin met onze geavanceerd zoek mechanisme. Verdwaal in onze gigantische bibliotheek, gefilterd op gamemode, aspect ratio en meer, of neem een kijkje bij skins die de beste spelers gebruiken.',
      3: 'Ontdek veel verschillende skins voor elke gamemode en aspect ratio op onze site. Kies uit standaard, catch the beat, mania of taiko en vindt wat het beste past bij jou.',
      4: 'Vindt de perfecte osu skin van de beste spelers op onze site. Verdwaal in onze collectie van populaire skins en verander ze naar jouw voorkeuren. Ga op avontuur in een diverse selectie  van stijlen en thema’s om voor jouw de perfecte skin te vinden.',
      5: 'Lijst van bestaande tags voor osu skins.',
      6: '{name} osu skin collectie!, gratis om te downloaden',
      7: 'Een gigantische hoeveelheid osu skins voor een {name}, gratis te downloaden!',
      8: 'Alle osu skins gemaakt door {name}',
      9: 'Vindt inspiratie voor jouw volgende osu! skin op onze site. Verdwaal in ons gevarieerde bos van skins en ontdek nieuwe technieken en ideeën. Wordt geïnspireerd en maak je eigen unieke skins.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Inloggen',
    1: 'Thuispagina',
    profile_osu: 'osu! Profiel',
    new_skin: 'Nieuwe skin',
    notifications: 'Notificaties',
    settings: 'Instellingen',
    logout: 'Uitloggen',
    load_more: 'Laad meer in',
    copy_short: 'Kopieer de korte link',
    copied: 'Gekopieerd',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Terug naar skin'
  },
  user: {
    roles: {
      0: 'Auteur',
      1: 'Mixer',
      2: 'Animaties',
      3: 'Kunstwerken',
      4: 'Samenwerking '
    }
  },
  tooltips: {
    0: 'Weergaven: {amount}',
    1: 'Herlaad resultaten',
    2: 'Aflopend | Oplopend',
    3: 'Duimpies: {likes} / Duimpies omlaag: {dislikes}',
    4: 'Druk op ctrl+enter om een tag toe te voegen',
    5: 'Bewerk versie',
    6: '{s}Log in{p}, om deze skin een beoordeling te kunnen geven',
    7: 'Geen korte beschrijving',
    8: 'Geen url',
    9: 'Keren gedownload: {amount}'
  },
  lists: {
    screens: {
      0: 'Welkom',
      1: 'Hoofdmenu',
      2: 'Nummer selecteren',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Aftelling',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Sectie gehaald',
      9: 'Sectie gefaald',
      10: 'Pauzeerscherm',
      11: 'Faalscherm',
      12: 'Resultatenscherm',
      13: 'Sla over',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Nieuw',
    1: 'Verbeterd',
    2: 'Veranderd',
    3: 'Verwijderd',
    4: 'Kunst',
    5: 'Font',
    6: 'Artiest',
    7: 'Skin element',
    8: 'Geluid/Geluidseffecten',
    9: 'Hulpmiddelen',
    views: 'Weergaven',
    likes: 'Duimpies',
    dislikes: 'Duimpies omlaag',
    downloads: 'Downloads',
    size_range: 'Selecteer grootte',
    date_range: 'Selecteer een tijdsperiode',
    ratio: 'Selecteer een aspect ratio | ratio'
  },
  placeholders: {
    0: 'Kies rollen',
    1: 'Kies versies',
    2: 'Typ tekst...',
    3: 'Selecteer grootte',
    4: 'Selecteer tijdsperiode',
    5: 'Jaar',
    6: 'Maand',
    7: 'Selecteer aspect ratio',
    8: 'Selecteer categorieën',
    9: 'Gamemodes',
    10: 'Selecteer type',
    11: 'Plak een youtube link',
    12: 'Typ een omschrijving en URL. Formaat omschrijving:URL',
    13: 'Selecteer extra',
    14: 'Plak een link',
    15: 'Skin titel, auteur of tag',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Draag je steentje bij' },
  nsfw: {
    0: 'Pas op!',
    1: 'Deze skin bevat gevoelige of volwassen onderdelen',
    2: 'Deze skin bevat gevoelige of volwassen onderdelen die sommige gebruikers schokkend kunnen vinden',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Niet geautoriseerd',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};