export default {
  title: {
    home: 'Hjem',
    login: 'Logg inn',
    lists: { 0: 'Lister' },
    tags: {
      0: 'Tags',
      1: '{amount} tags for kategori {name}',
      2: 'Søkefilter'
    },
    ideas: {
      0: 'Inspirasjon',
      1: '{amount}'
    },
    sounds: { 0: 'Lyder' },
    leaderboard: { 0: 'Ledertavler' },
    extend: { 0: 'Mer | Mindre' },
    skin: {
      0: 'Dette skinnet inneholder elementer fra andre skins',
      1: 'Klikk her for mer informasjon'
    },
    tools: 'Verktøy'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Endringslogg',
    1: 'Liste over alle endringene som er gjort i den gjeldende versjonen',
    2: 'Ingenting her',
    3: 'Men du kan bare legge til endringene som du har gjort på denne versjonen av skinnet',
    4: 'Ikke gruppert',
    5: 'Ny',
    6: 'Rettelser',
    7: 'Endringer',
    8: 'Fjerning'
  },
  ideas: {
    0: 'Ingenting funnet',
    1: 'Skjermbilder av «{type}» ble ikke lastet opp til siden',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Skapere',
    1: 'Legg til en liste med alle skapere eller med de som er involvert i å skape denne versjonen',
    2: 'Ingen er her',
    3: 'Søk etter en spillers navn vil vise en liste av profiler.',
    4: 'Redaktør',
    5: 'Roller',
    6: 'Versjoner'
  },
  tags: {
    0: 'Tags',
    1: 'Legg til en liste med alle tags relatert til skinnet',
    2: 'Det ser ut til å være tomt her.',
    3: 'Bruk feltet ovenfor for å finne tags',
    4: 'Ingen tags funnet',
    5: 'Prøv å søk etter noe annet',
    6: 'Søk'
  },
  videos: {
    0: 'Videoer',
    1: 'Legg til en liste med alle videoer som viser skinnet',
    2: 'Ingenting å vise',
    3: 'Søk etter noen på youtube eller lag din egen video om skinnet'
  },
  sources: {
    0: 'Attribusjon',
    1: 'Liste over alle brukte ressurser eller verktøy i denne vesjonen av skinnet',
    2: 'Det er tomt her',
    3: 'Om du har brukt noen elementer fra andre skins, eller bilder, vær sikker på å legge dem til i boksen ovenfor',
    4: 'Ikke gruppert'
  },
  checks: {
    0: 'Alle',
    1: 'Metadata',
    2: 'Fremhevd',
    3: 'Navnet på skinnet er ikke spesifisert',
    4: 'Legg til hvertfall en skin skaper',
    5: 'Legg til noen tags',
    6: 'Størrelsen på skinnet er ikke spesifisert',
    // 7: 'Select at least one gamemode',
    8: 'Velg bilde oppløsning (SD eller HD)',
    9: 'Velg hvertfall et størrelsesformat',
    10: 'Ingen skjermbilder postet',
    11: 'Legg til hvertfall et skjermbilde av skinnet i bruk',
    12: 'Lenke til skinnet er ikke spesifisert',
    20: 'Ser bra ut',
    21: 'Alle feil er fikset. Bra jobba!',
    22: 'Sjekkliste',
    23: 'Legg ved minst en offentlig versjon',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles',
    26: '{amount} screenshots doesn\'t have category',
    27: 'Specifiy gameplay name for {mode} screenshots | Specifiy gameplay name for {mode} screenshot',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skins',
    1: 'Populær',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Nylige',
    5: 'Tilfeldige',
    6: 'Alle skins',
    7: 'Størrelsesformat',
    8: 'Alle skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins med navn {name} | Alle skin fra',
    11: 'Søk',
    12: '{name} skins',
    13: 'Utforsk skins',
    14: 'Popular skins'
  },
  skin: {
    0: 'Rediger',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasjon',
    5: 'Skjermbilde',
    6: 'Bare spill',
    7: 'Nedlastings lenke | Last ned skin',
    8: 'Forum innlegg | osu! Forum',
    9: 'Reddit post',
    10: 'Skapere',
    11: 'Tags',
    13: 'Videoer',
    14: 'Ny versjon | Administrer versjoner',
    15: 'Oppdater | Send inn',
    16: 'Spillmodus',
    17: 'Navn på skin',
    18: 'Versjon | Versjoner',
    19: 'Størrelse',
    20: 'Metadata',
    21: 'Vurdering',
    22: 'Nedlasting',
    23: 'Nedlasting er snart tilgjengelig',
    24: '{amount} sekunder igjen',
    25: 'Du er ikke en av oss',
    26: 'Ser ut som at du ikke er forfatter eller editor av dette skinnet',
    27: 'Skin laget av',
    28: 'Ingen tags',
    29: 'Ingen videoer',
    30: 'Ingen skapere',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!',
    45: 'uploader'
  },
  drag: {
    0: 'Trykk her',
    1: 'eller dra og slipp bildene her'
  },
  footer: {
    0: 'Laget av cyperdark',
    1: 'Kreditt',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Kunst',
    2: 'Iconer',
    3: 'Alle iconer er tatt fra {name}',
    4: 'Flagg',
    5: 'Alle flagg bilder er fra {name}',
    6: 'Lokasjon',
    7: 'Noen? [{lang}]',
    8: 'Ser ut som cyperdark glemte å legge den til. {text}'
  },
  search: {
    0: 'Skin søk',
    1: 'Visninger',
    2: 'Tittel',
    3: 'Vurdering',
    4: 'Størrelse',
    5: 'Dato',
    7: 'Ingenting funnet',
    8: 'Prøv et annet søkefilter',
    9: 'Venter godkjenning',
    10: 'Bruk søkefilteret eller skriv inn skinnets tittel, skaper eller tags',
    11: 'Nedlasting',
    12: 'Navn',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Brukere',
      3: 'Lister'
    },
    14: 'Search:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished',
    6: 'Contests',
    7: 'Voting page'
  },
  rules: {
    0: 'Last updated at',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} of {max} completed',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'Søk',
    1: 'Rediger',
    2: 'Liste'
  },
  undefined: {
    0: 'Tomt',
    1: 'Her var det dessverre ingenting, uansett så kan du se på våre andre sider',
    2: 'Her var det dessverre ingenting',
    3: 'Ikke autorisert',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  settings: {
    0: 'Innstillinger',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.',
    5: 'English comments',
    6: 'Show English translation of the comments'
  },
  meta: {
    title: {
      0: 'Oppdag osu skins',
      1: 'Spillmodus, aspect ratios osu skins',
      2: 'Populære osu skins',
      3: 'Søk osu skins',
      4: 'Liste med tags, {name}',
      5: '{name} v{version} osu skin',
      6: 'Kreditt',
      7: 'osu skins',
      8: '{name} søk osu skins',
      9: 'Get inspiration from other osu skins',
      10: '{name} laget osu skins',
      11: 'Søkefilter',
      12: '{name} found tags',
      13: 'Nytt skin',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: 'Få de beste osu! skins på vår nettside! Vårt store lager med skins for alle spillmoduser, størrelsesformat og spillere i toppen. Plus, vi har en spesiell seksjon for anime fans. Forbedre spillingen din med det perfekte skinnet. #osuskins #osugame #anime',
      1: '{views} visninger. Et osu skin for {modes}, filstørrelsen er {size}, laget av {creators}, Støtter {ratios}',
      2: 'Finn det perfekte osu! skinnet med våres avanserte søk funksjon. Bla gjennom våre mange sider, filtrer etter spillmodus, størrelsesforhold med mer. Eller, sjekk ut skins som andre spillere i toppen bruker.',
      3: 'Oppdag en rekke med skins for forskjellige spill moduser og størrelsesformat på vår nettside. Velg mellom standard, catch the beat, mania, og taiko moduser. Finn det som passer deg perfekt for dine spill preferanser.',
      4: 'Finn det perfekte osu skin fra andre toppspillere på vårt nettsted. Bla gjennom samlingene våre av populære skins og tilpass din spillopplevelse. Oppdag et bredt spekter av stiler og temaer som passer for deg.',
      5: 'Liste for eksisterende osu skin tags.',
      6: '{name} osu skins kolleksjon!, gratis nedlasting',
      7: 'En stor menge osu skins for {name}, last dem ned her gratis!',
      8: 'Alle osu skins er laget av {name}',
      9: 'Finn inspirasjon for ditt neste osu! skin på vår nettside. Bla gjennom diverse kolleksjoner med skins og finn ut nye teknikker og ideer. Bli inspirert og lag dine egne unike skins.',
      10: 'Search for tags among all the tags on the site.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Logg inn',
    1: 'Hjemmeside',
    profile_osu: 'osu! Profil',
    new_skin: 'Nytt skin',
    notifications: 'Varslinger',
    settings: 'Innstillinger',
    logout: 'Logg ut',
    load_more: 'Last mer',
    copy_short: 'Kopier liten link',
    copied: 'Kopiert',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Tilbake til skin',
    source: 'Source',
    contest_voting: 'Vote here',
    rules_agree: 'I agree',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Skaper',
      1: 'Mikser',
      2: 'Animasjoner',
      3: 'Kunst',
      4: 'Samarbeid',
      5: 'Lyder',
      6: 'Spill'
    }
  },
  tooltips: {
    0: 'Visninger: {amount}',
    1: 'Oppdater resultat',
    2: 'Synkende | Økende',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'Press ctrl+enter for å legge til en tagg',
    5: 'Rediger versjon',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Ingen liten beskrivelse',
    8: 'Ingen link',
    9: 'Downloads: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Velkommen',
      1: 'Hovedmeny',
      2: 'Sang valg',
      3: 'Modus meny',
      4: 'Modifikasjoner',
      5: 'Nedtelling',
      6: 'Spill',
      7: 'Spinner',
      8: 'Seksjon Passert',
      9: 'Seksjon Feilet',
      10: 'Pauset Skjerm',
      11: 'Feilet Skjerm',
      12: 'Resultat skjerm',
      13: 'Hopp over',
      14: 'Banner',
      15: 'Result screen (bottom)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mikset'
    }
  },
  select: {
    0: 'Ny',
    1: 'Fikset',
    2: 'Endret',
    3: 'Fjernet',
    4: 'Kunst',
    5: 'Font',
    6: 'Artist',
    7: 'Skin elementer',
    8: 'Lyd/Sfx',
    9: 'Verktøy',
    10: 'Image',
    views: 'Visninger',
    likes: 'Liker',
    dislikes: 'Liker ikke',
    downloads: 'Nedlasting',
    ratio: 'Velg størrelsesformat | format',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Velg roller',
    1: 'Velg versjoner',
    2: 'Skriv inn litt tekst...',
    3: 'Select size range',
    4: 'Velg dato ',
    5: 'År',
    6: 'Måned',
    7: 'Velg aspect ratio',
    8: 'Velg kategorier',
    9: 'Spillmodus',
    10: 'Velg type',
    11: 'Lim inn en YouTube lenke',
    12: 'Skriv en beskrivelse med en url. Format for beskrivelsen:url',
    13: 'Velg ekstra',
    14: 'Lim inn lenke',
    15: 'Skin tittel, skaper, eller tags',
    16: 'Velg kategori',
    17: 'Skriv inn navnet på taggen',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Bidra' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'Dette skinnet inneholder sensitivt eller voksent innhold',
    2: 'Dette skinnet inneholder sensitivt eller voksent innhold som noen brukere kan finne forstyrrende',
    3: 'Okei',
    4: 'bye o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'Du kan ikke redigere et ikke-eksisterende skin',
    43: 'Ser ikke ut som om du har tillatelse til å redigere dette skinnet',
    44: 'Du kan ikke sende denne versjonen fordi den er den samme som den forige.',
    45: 'Disse endringene er allerede sendt inn for moderering',
    46: 'Vellykket',
    47: 'Ny endringer har blitt sendt inn for moderasjon',
    48: 'Endringene har blitt oppdatert i moderering',
    49: 'Merkeling lenke',
    50: 'Denne lenken kan ikke brukes som en nedlastningslenke',
    51: 'Sendt inn, avventer moderasjon',
    52: 'Warning',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'Vellykket',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'Varslinger',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Ikke autorisert',
    1: 'Vennligst logg inn på kontoen din',
    2: 'Begrenset visning',
    3: 'Denne siden er ikke ute, enda.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No',
    5: 'Reset .ini?'
  }
};