export default {
  title: {
    home: 'Hjem',
    login: 'Logg inn',
    lists: { 0: 'Lister' },
    tags: {
      0: 'Tags',
      1: '{amount} tags for kategori {name}',
      2: 'Søkefilter'
    },
    ideas: {
      0: 'Inspirasjon',
      1: '{amount}'
    },
    sounds: { 0: 'Lyder' },
    leaderboard: { 0: 'Ledertavler' },
    extend: { 0: 'Mer | Mindre' },
    skin: {
      0: 'Dette skinnet inneholder elementer fra andre skins',
      1: 'Klikk her for mer informasjon'
    },
    tools: 'Verktøy'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Endringslogg',
    1: 'Liste over alle endringene som er gjort i den gjeldende versjonen',
    2: 'Ingenting her',
    3: 'Men du kan bare legge til endringene som du har gjort på denne versjonen av skinnet',
    4: 'Ikke gruppert',
    5: 'Ny',
    6: 'Rettelser',
    7: 'Endringer',
    8: 'Fjerning'
  },
  ideas: {
    0: 'Ingenting funnet',
    1: 'Skjermbilder av «{type}» ble ikke lastet opp til siden'
  },
  creators: {
    0: 'Skapere',
    1: 'Legg til en liste med alle skapere eller med de som er involvert i å skape denne versjonen',
    2: 'Ingen er her',
    3: 'Søk etter en spillers navn vil vise en liste av profiler.',
    4: 'Redaktør',
    5: 'Roller',
    6: 'Versjoner'
  },
  tags: {
    0: 'Tags',
    1: 'Legg til en liste med alle tags relatert til skinnet',
    2: 'Det ser ut til å være tomt her.',
    3: 'Bruk feltet ovenfor for å finne tags',
    4: 'Ingen tags funnet',
    5: 'Prøv å søk etter noe annet',
    6: 'Søk'
  },
  videos: {
    0: 'Videoer',
    1: 'Legg til en liste med alle videoer som viser skinnet',
    2: 'Ingenting å vise',
    3: 'Søk etter noen på youtube eller lag din egen video om skinnet'
  },
  sources: {
    0: 'Attribusjon',
    1: 'Liste over alle brukte ressurser eller verktøy i denne vesjonen av skinnet',
    2: 'Det er tomt her',
    3: 'Om du har brukt noen elementer fra andre skins, eller bilder, vær sikker på å legge dem til i boksen ovenfor',
    4: 'Ikke gruppert'
  },
  checks: {
    0: 'Alle',
    1: 'Metadata',
    2: 'Fremhevd',
    3: 'Navnet på skinnet er ikke spesifisert',
    4: 'Legg til hvertfall en skin skaper',
    5: 'Legg til noen tags',
    6: 'Størrelsen på skinnet er ikke spesifisert',
    7: 'Velg hvertfall et spillmodus',
    8: 'Velg bilde oppløsning (SD eller HD)',
    9: 'Velg hvertfall et størrelsesformat',
    10: 'Ingen skjermbilder postet',
    11: 'Legg til hvertfall et skjermbilde av skinnet i bruk',
    12: 'Lenke til skinnet er ikke spesifisert',
    20: 'Ser bra ut',
    21: 'Alle feil er fikset. Bra jobba!',
    22: 'Sjekkliste',
    23: 'Legg ved minst en offentlig versjon',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Skins',
    1: 'Populær',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Nylige',
    5: 'Tilfeldige',
    6: 'Alle skins',
    7: 'Størrelsesformat',
    8: 'Alle skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins med navn {name} | Alle skin fra',
    11: 'Søk',
    12: '{name} skins',
    13: 'Utforsk skins'
  },
  skin: {
    0: 'Rediger',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasjon',
    5: 'Skjermbilde',
    6: 'Bare spill',
    7: 'Nedlastings lenke | Last ned skin',
    8: 'Forum innlegg | osu! Forum',
    9: 'Reddit post',
    10: 'Skapere',
    11: 'Tags',
    13: 'Videoer',
    14: 'Ny versjon | Administrer versjoner',
    15: 'Oppdater | Send inn',
    16: 'Spillmodus',
    17: 'Navn på skin',
    18: 'Versjon | Versjoner',
    19: 'Størrelse',
    20: 'Metadata',
    21: 'Vurdering',
    22: 'Nedlasting',
    23: 'Nedlasting er snart tilgjengelig',
    24: '{amount} sekunder igjen',
    25: 'Du er ikke en av oss',
    26: 'Ser ut som at du ikke er forfatter eller editor av dette skinnet',
    27: 'Skin laget av',
    28: 'Ingen tags',
    29: 'Ingen videoer',
    30: 'Ingen skapere',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately skin was deleted by {author} request'
  },
  drag: {
    0: 'Trykk her',
    1: 'eller dra og slipp bildene her'
  },
  footer: {
    0: 'Laget av cyperdark',
    1: 'Kreditt'
  },
  credits: {
    0: 'Chibi',
    1: 'Kunst',
    2: 'Iconer',
    3: 'Alle iconer er tatt fra {name}',
    4: 'Flagg',
    5: 'Alle flagg bilder er fra {name}',
    6: 'Lokasjon',
    7: 'Noen? [{lang}]',
    8: 'Ser ut som cyperdark glemte å legge den til. {text}'
  },
  search: {
    0: 'Skin søk',
    1: 'Visninger',
    2: 'Tittel',
    3: 'Vurdering',
    4: 'Størrelse',
    5: 'Dato',
    7: 'Ingenting funnet',
    8: 'Prøv et annet søkefilter',
    9: 'Venter godkjenning',
    10: 'Bruk søkefilteret eller skriv inn skinnets tittel, skaper eller tags',
    11: 'Nedlasting',
    12: 'Navn',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Brukere',
      3: 'Lister'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Søk',
    1: 'Rediger',
    2: 'Liste'
  },
  undefined: {
    0: 'Tomt',
    1: 'Her var det dessverre ingenting, uansett så kan du se på våre andre sider',
    2: 'Her var det dessverre ingenting',
    3: 'Ikke autorisert',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Oppdag osu skins',
      1: 'Spillmodus, aspect ratios osu skins',
      2: 'Populære osu skins',
      3: 'Søk osu skins',
      4: 'Liste med tags, {name}',
      5: '{name} v{version} osu skin',
      6: 'Kreditt',
      7: 'osu skins',
      8: '{name} søk osu skins',
      9: 'Get inspiration from other osu skins',
      10: '{name} laget osu skins',
      11: 'Søkefilter',
      12: '{name} found tags',
      13: 'Nytt skin'
    },
    description: {
      0: 'Få de beste osu! skins på vår nettside! Vårt store lager med skins for alle spillmoduser, størrelsesformat og spillere i toppen. Plus, vi har en spesiell seksjon for anime fans. Forbedre spillingen din med det perfekte skinnet. #osuskins #osugame #anime',
      1: '{views} visninger. Et osu skin for {modes}, filstørrelsen er {size}, laget av {creators}, Støtter {ratios}',
      2: 'Finn det perfekte osu! skinnet med våres avanserte søk funksjon. Bla gjennom våre mange sider, filtrer etter spillmodus, størrelsesforhold med mer. Eller, sjekk ut skins som andre spillere i toppen bruker.',
      3: 'Oppdag en rekke med skins for forskjellige spill moduser og størrelsesformat på vår nettside. Velg mellom standard, catch the beat, mania, og taiko moduser. Finn det som passer deg perfekt for dine spill preferanser.',
      4: 'Finn det perfekte osu skin fra andre toppspillere på vårt nettsted. Bla gjennom samlingene våre av populære skins og tilpass din spillopplevelse. Oppdag et bredt spekter av stiler og temaer som passer for deg.',
      5: 'Liste for eksisterende osu skin tags.',
      6: '{name} osu skins kolleksjon!, gratis nedlasting',
      7: 'En stor menge osu skins for {name}, last dem ned her gratis!',
      8: 'Alle osu skins er laget av {name}',
      9: 'Finn inspirasjon for ditt neste osu! skin på vår nettside. Bla gjennom diverse kolleksjoner med skins og finn ut nye teknikker og ideer. Bli inspirert og lag dine egne unike skins.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Logg inn',
    1: 'Hjemmeside',
    profile_osu: 'osu! Profil',
    new_skin: 'Nytt skin',
    notifications: 'Varslinger',
    settings: 'Innstillinger',
    logout: 'Logg ut',
    load_more: 'Last mer',
    copy_short: 'Kopier liten link',
    copied: 'Kopiert',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Tilbake til skin'
  },
  user: {
    roles: {
      0: 'Skaper',
      1: 'Mikser',
      2: 'Animasjoner',
      3: 'Kunst',
      4: 'Samarbeid'
    }
  },
  tooltips: {
    0: 'Visninger: {amount}',
    1: 'Oppdater resultat',
    2: 'Synkende | Økende',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'Press ctrl+enter for å legge til en tagg',
    5: 'Rediger versjon',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Ingen liten beskrivelse',
    8: 'Ingen link',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Velkommen',
      1: 'Hovedmeny',
      2: 'Sang valg',
      3: 'Modus meny',
      4: 'Modifikasjoner',
      5: 'Nedtelling',
      6: 'Spill',
      7: 'Spinner',
      8: 'Seksjon Passert',
      9: 'Seksjon Feilet',
      10: 'Pauset Skjerm',
      11: 'Feilet Skjerm',
      12: 'Resultat skjerm',
      13: 'Hopp over',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mikset'
    }
  },
  select: {
    0: 'Ny',
    1: 'Fikset',
    2: 'Endret',
    3: 'Fjernet',
    4: 'Kunst',
    5: 'Font',
    6: 'Artist',
    7: 'Skin elementer',
    8: 'Lyd/Sfx',
    9: 'Verktøy',
    views: 'Visninger',
    likes: 'Liker',
    dislikes: 'Liker ikke',
    downloads: 'Nedlasting',
    size_range: 'Velg størrelse',
    date_range: 'Velg en dato',
    ratio: 'Velg størrelsesformat | format'
  },
  placeholders: {
    0: 'Velg roller',
    1: 'Velg versjoner',
    2: 'Skriv inn litt tekst...',
    3: 'Velg størrelse',
    4: 'Velg dato ',
    5: 'År',
    6: 'Måned',
    7: 'Velg aspect ratio',
    8: 'Velg kategorier',
    9: 'Spillmodus',
    10: 'Velg type',
    11: 'Lim inn en YouTube lenke',
    12: 'Skriv en beskrivelse med en url. Format for beskrivelsen:url',
    13: 'Velg ekstra',
    14: 'Lim inn lenke',
    15: 'Skin tittel, skaper, eller tags',
    16: 'Velg kategori',
    17: 'Skriv inn navnet på taggen'
  },
  contribute: { 0: 'Bidra' },
  nsfw: {
    0: 'Warning nsfw!',
    1: 'Dette skinnet inneholder sensitivt eller voksent innhold',
    2: 'Dette skinnet inneholder sensitivt eller voksent innhold som noen brukere kan finne forstyrrende',
    3: 'Okei',
    4: 'bye o/',
    5: 'Warning furry!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'Du kan ikke redigere et ikke-eksisterende skin',
    43: 'Ser ikke ut som om du har tillatelse til å redigere dette skinnet',
    44: 'Du kan ikke sende denne versjonen fordi den er den samme som den forige.',
    45: 'Disse endringene er allerede sendt inn for moderering',
    46: 'Vellykket',
    47: 'Ny endringer har blitt sendt inn for moderasjon',
    48: 'Endringene har blitt oppdatert i moderering',
    49: 'Merkeling lenke',
    50: 'Denne lenken kan ikke brukes som en nedlastningslenke',
    51: 'Sendt inn, avventer moderasjon'
  },
  header: {
    0: 'Varslinger',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Ikke autorisert',
    1: 'Vennligst logg inn på kontoen din',
    2: 'Begrenset visning',
    3: 'Denne siden er ikke ute, enda.'
  }
};