export default {
  title: {
    home: 'Główna',
    login: 'Zaloguj się',
    lists: { 0: 'Listy' },
    tags: {
      0: 'Tagi',
      1: '{amount} tagów dla kategorii {name}',
      2: 'Wyszukaj tagi'
    },
    ideas: {
      0: 'Inspiracje',
      1: '«{amount}»'
    },
    sounds: { 0: 'Efekty dzwiękowe' },
    leaderboard: { 0: 'Ranking' },
    extend: { 0: 'Rozwiń | Schowaj' },
    skin: {
      0: 'Ten skin posiada elementy z innych skinów',
      1: 'Kliknij tutaj po więcej informacji'
    },
    tools: 'Narzędzia'
  },
  home: {
    0: 'Dostępne do pobrania',
    1: 'Najczęściej: _name_ skiny',
    2: 'Obejrzane | Polubione | Pobrane',
    3: 'Opublikuj nowego skina',
    4: 'Jak wgrać skina',
    5: '{amount} Skinów | {amount} Skinów | {amount} Skinów'
  },
  changelogs: {
    0: 'Changelog',
    1: 'Lista zmian w najnowszej wersji',
    2: 'Nic tu jeszcze nie ma',
    3: 'Ale możesz dodać zmiany, które wprowadziłeś w tej wersji skina',
    4: 'Brak grupowania',
    5: 'Nowe',
    6: 'Naprawione błędy',
    7: 'Zmiany',
    8: 'Usunięte'
  },
  ideas: {
    0: 'Nic nie znaleziono',
    1: 'Zrzuty ekranu «{type}» nie zostały przesłane na stronę',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Twórcy',
    1: 'Lista twórców którzy pracowali przy tej wersji',
    2: 'Nikogo tu nie ma',
    3: 'Wpisanie nazwy gracza ukaże listę profili.',
    4: 'Edytor',
    5: 'Role',
    6: 'Wersje'
  },
  tags: {
    0: 'Tagi',
    1: 'Lista wszystkich tagów opisujących tego skina',
    2: 'Troszkę tu pusto.',
    3: 'Użyj pola powyżej aby znaleźć nowe tagi',
    4: 'Nie znaleziono tagów',
    5: 'Spróbuj poszukać czegoś innego',
    6: 'Szukaj'
  },
  videos: {
    0: 'Wideo',
    1: 'Lista wszystkich filmów pokazujących skina',
    2: 'Brak wideoprezentacji',
    3: 'Poszukaj ich w serwise YouTube, lub stwórz własną'
  },
  sources: {
    0: 'Atrybucja',
    1: 'Lista wszystkich elementów lub narzędzi użytych w tej wersji skina',
    2: 'Troszkę tu pusto',
    3: 'Jeżeli zostały użyte elementy, lub arty, upewnij się, że zostały one dodane w polu powyżej',
    4: 'Brak grupowania'
  },
  checks: {
    0: 'Wszystkie',
    1: 'Metadata',
    2: 'Hightlight',
    3: 'Nie podano nazwy skina',
    4: 'Dodaj przynajmniej jednego twórcę',
    5: 'Dodaj kilka tagów',
    6: 'Nie podano wagi skina',
    // 7: 'Select at least one gamemode',
    8: 'Wybierz rozdzielczość plików (SD lub HD)',
    9: 'Wybierz przynajmniej jedną proporcję ekranu',
    10: 'Nie dodano screenshotów',
    11: 'Dodaj przynajmniej jeden screenshot z gameplay\'u',
    12: 'Nie podano linka do skina',
    20: 'Wygląda w porządku',
    21: 'Każdy błąd został naprawiony. Dobra robota!',
    22: 'Check list',
    23: 'Dodaj co najmniej jedną publiczną wersję',
    24: 'Dodaj co najmniej jednego twórcę tej wersji',
    25: 'Niektórzy twórcy nie mają ról',
    26: '{amount} zrzuty ekranu nie mają kategorii',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skiny',
    1: 'Popularne',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Nowe',
    5: 'Losowe',
    6: 'Wszystkie skiny',
    7: 'Proporcje obrazu',
    8: 'Wszystkie skiny | osu skiny',
    9: 'Skin | Skiny | Skiny',
    10: 'osu Skiny od {name} | Wszystkie skiny od',
    11: 'Szukaj',
    12: '{name} skiny',
    13: 'Przeglądaj skiny',
    14: 'Popular skins'
  },
  skin: {
    0: 'Edytuj',
    1: 'Dodatki',
    2: 'HD',
    3: 'FullHD',
    4: 'Animacje',
    5: 'Screenshoty',
    6: 'Tylko gameplay',
    7: 'Link do pobrania | Pobierz skin',
    8: 'Post na forum | osu! Forum',
    9: 'Post na Reddicie',
    10: 'Twórcy',
    11: 'Tagi',
    13: 'Wideo',
    14: 'Nowa wersja | Edytuj Wersje',
    15: 'Zaktualizuj | Wyslij',
    16: 'Tryby gry',
    17: 'Nazwa skina',
    18: 'Wersja | Wersje',
    19: 'Wielkość',
    20: 'Metadata',
    21: 'Ocena',
    22: 'Pobrania',
    23: 'Możliwość pobrania będzie dostępna wkrótce',
    24: 'zostało {amount} sekund',
    25: 'Nie jesteś jednym z nas',
    26: 'Wygląda na to, że nie jesteś autorem tego skina, bądź nie masz permisji do jego edytowania',
    27: 'Skin od',
    28: 'Brak tagów',
    29: 'Brak filmów',
    30: 'Brak twórców',
    31: 'Oceń skina',
    32: 'Zostaw upvote\'a i skomentuj na Reddicie',
    33: 'Skomentuj na forum osu!',
    34: 'Więcej skinów od tego autora | Więcej skinów od tych autorów',
    35: 'Wspomóż skórkę',
    36: 'Niedostępny',
    37: 'Unfortunately, this skin was deleted',
    38: 'Witaj w edytorze postów skinów!',
    39: `Pierwszy raz korzystasz z edytora skinów? Pozwól nam poprowadzić cię przez interfejs, aby pokazać ci pełny potencjał edytora!`,
    40: 'Ukończono {current} z {max}',
    41: 'Zobacz później',
    42: `Zacznijmy`,
    43: 'Gratulacje!',
    44: 'Pomyślnie ukończyłeś samouczek, baw się dobrze!',
    45: 'Przesyłający'
  },
  drag: {
    0: 'Kliknij',
    1: 'lub przeciągnij zdjęcia tutaj'
  },
  footer: {
    0: 'Made by cyperdark',
    1: 'Credits',
    2: 'Zasady',
    3: 'Kontakty'
  },
  credits: {
    0: 'Chibi',
    1: 'Arty',
    2: 'Ikony',
    3: 'Wszystkie ikony pochodzą z {name}',
    4: 'Flagi',
    5: 'Wszystkie flagi pochodzą z {name}',
    6: 'Lokalizacja',
    7: 'Ktokolwiek? [{lang}]',
    8: 'Wygląda na to, że cyperdark zapomniał dodać je. {text}'
  },
  search: {
    0: 'Wyszukiwarka skinów',
    1: 'Wyświetlenia',
    2: 'Tytuł',
    3: 'Ocena',
    4: 'Wielkość',
    5: 'Data',
    7: 'Nic nie znaleziono',
    8: 'Spróbuj użyć innych filtrów wyszukiwania',
    9: 'Czekam na zapytanie',
    10: 'Użyj filtrów wyszukiwania lub wpisz nazwę skina, autora lub tagi',
    11: 'Pobrania',
    12: 'Nazwa',
    13: {
      0: 'Skiny',
      1: 'Tagi',
      2: 'Użytkownicy',
      3: 'Listy'
    },
    14: 'Szukaj:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Konkursy',
    1: 'Oficjalny post',
    2: 'Zgłoszenie',
    3: 'Przygotowywanie',
    4: 'Głosowanie',
    5: 'Zakończone',
    6: 'Konkursy',
    7: 'Voting page'
  },
  rules: {
    0: 'Ostatnio zaktualizowane',
    1: 'Wytyczne Dodawania Skinów'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: 'Ukończono {current} z {max}',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: 'Szukaj',
    1: 'Edytuj',
    2: 'Lista'
  },
  undefined: {
    0: 'Pusto',
    1: 'Niestety nic tu nie ma, ale możesz spojrzeć na inne strony',
    2: 'Niestety, nic tu nie ma',
    3: 'Błąd uwierzytelnienia',
    4: 'Musisz być zalogowany, aby edytować tego skina.',
    5: 'Musisz być zalogowany, aby dodać nowego skina.'
  },
  settings: {
    0: 'Ustawienia',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.'
  },
  meta: {
    title: {
      0: 'Odkryj skiny do osu',
      1: 'Gamemodes, aspect ratios osu skins',
      2: 'Popular osu skins',
      3: 'Wyszukaj skiny do osu',
      4: '«{name}» tags list',
      5: '{name} v{version} skin do osu',
      6: 'Credits',
      7: 'skiny do osu',
      8: '{name} search osu skins',
      9: 'Zainspiruj się innymi skinami',
      10: '{name} stworzył/a skiny do osu',
      11: 'Wyszukaj tagi',
      12: '{name} znalezione tagi',
      13: 'Nowy skin',
      14: 'Zasady strony',
      15: 'Konkursy osu!',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: 'Najlepsze skiny do osu! tylko u nas! W naszej ogromnej bibliotece znajdziesz skiny dla wszystkich trybów gry, proporcji ekranu, a nawet skiny używane przez topowych graczy. Posiadamy również sekcję dla fanów anime. Udoskonal swoją rozgrywkę z idealnym dla ciebie skinem. #osuskins #osugame #anime',
      1: '{views} wyświetleń. Skin osu! dla {modes}, o wadze {size}, stworzony przez {creators}. Wspiera {ratios}',
      2: 'Znajdź swój perfekcyjny skin do osu! dzieki naszej zaawansowanej wyszukiwarce. Zajrzyj też do ogromnej biblioteki, sortowanej przez tryb gry, proporcji ekranu, i więcej. Sprawdź też skiny używane przez topowych graczy',
      3: 'Odkryj tysiące różnych skinów dla różnych trybów gry i proporcji ekranu u nas. Wybierz pomiędzy standardem, catch the beat, manią, i taiko. Odkryj idealne dopasowanie pod swoje preferencje.',
      4: 'Znajdź swój perfekcyjny skin od topowych graczy u nas. Przejrzyj naszą kolekcję popularnych skinów i dostosuj swój gameplay. Odkryj szeroką gamę styli i motywów dla swoich preferencji',
      5: 'Lista istniejących tagów dla skinów.',
      6: 'Kolekcja skinów osu {name}!, darmowe pobieranie',
      7: 'Ogromna ilość skinów od {name}, pobierz za darmo!',
      8: 'Wszystkie skiny stworzone przez {name}',
      9: 'Znajdź inspirację na swój najnowszy skin u nas. Przejrzyj różnorodną kolekcję skinów i odkryj nowe techniki i pomysły. Zainspiruj się i stwórz jedyne w swoim rodzaju skiny.',
      10: 'Szukaj tagów spośród wszystkich tagów na stronie.',
      11: 'Lista wszystkich aktywnych/zakończonych konkursów osu!',
      12: '{amount} wpisów do konkursu {title}. {views} wyświetleń'
    }
  },
  buttons: {
    0: 'Zaloguj się',
    1: 'Home page',
    profile_osu: 'Profil osu!',
    new_skin: 'Nowy skin',
    notifications: 'Powiadomienia',
    settings: 'Ustawienia',
    logout: 'Wyloguj się',
    load_more: 'Załaduj więcej',
    copy_short: 'Skopiuj skrócony link',
    copied: 'Skopiowano',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Powrót do skina',
    source: 'Źródło',
    contest_voting: 'Zagłosuj tutaj',
    rules_agree: 'Zgadzam się',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Opcjonalne',
    1: 'Wymagane',
    2: 'Wybierz co najmniej jedną opcję'
  },
  user: {
    roles: {
      0: 'Autor',
      1: 'Mixer',
      2: 'Animacje',
      3: 'Arty',
      4: 'Kolaboracja',
      5: 'Efekty dzwiękowe',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: 'Wyświetlenia: {amount}',
    1: 'Odśwież wyniki',
    2: 'Malejąco | Rosnąco',
    3: 'Lubię to: {likes} / Nie lubię tego: {dislikes}',
    4: 'Naciśnij ctrl+enter aby dodać tag',
    5: 'Edytuj wersję',
    6: '{s}Zaloguj się{p}, aby ocenić tego skina',
    7: 'Brak krótkiego opisu',
    8: 'Brak linka',
    9: 'Pobrania: {amount}',
    10: 'Zresetuj wszystko',
    11: 'Pokaż poradnik',
    12: 'Zamknij poradnik',
    13: 'Aby oznaczyć regułę jako przeczytaną, najedź na nią (Żółty oznacza nieprzeczytaną)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Main menu',
      2: 'Song select',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Countdown',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pause Screen',
      11: 'Fail Screen',
      12: 'Result screen',
      13: 'Skip',
      14: 'Banner',
      15: 'Ekran wyników (dolny)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mix'
    }
  },
  select: {
    0: 'Nowe',
    1: 'Naprawiono',
    2: 'Zmieniono',
    3: 'Usunięto',
    4: 'Art',
    5: 'Czcionka',
    6: 'Artysta',
    7: 'Element skina',
    8: 'Audio/Efekty Dźwiękowe',
    9: 'Narzędzia',
    10: 'Zdjęcie',
    views: 'Wyświetlenia',
    likes: 'Polubienia',
    dislikes: 'Nie lubię tego',
    downloads: 'Pobrania',
    ratio: 'Wybierz proporcje ekranu | proporcje ekranu',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Wybierz rolę',
    1: 'Wybierz wersję',
    2: 'Wpisz jakiś tekst...',
    3: 'Select size range',
    4: 'Wybierz zakres dat',
    5: 'Rok',
    6: 'Miesiąc',
    7: 'Wybierz proporcje ekranu',
    8: 'Wybierz kategorie',
    9: 'Tryby gry',
    10: 'Wybierz typ',
    11: 'Wklej link do YouTube',
    12: 'Wpisz opis oraz link. Format opis:link',
    13: 'Wybierz dodatki',
    14: 'Wklej link',
    15: 'Nazwa skina, autor, lub tagi',
    16: 'Wybierz kategorię',
    17: 'Wpisz nazwę tagu',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: 'Współtwórz' },
  nsfw: {
    0: 'Uwaga, nsfw!',
    1: 'Ten skin zawiera treści wrażliwe lub dla dorosłych',
    2: 'Ten skin zawiera treści wrażliwe lub dla dorosłych, które niektórzy użytkownicy mogą uznać za niepokojące',
    3: 'Okej',
    4: 'pa o/',
    5: 'Uwaga, futrzaki!'
  },
  removed: {
    0: 'Wersja niedostępna',
    1: 'Autor skina zdecydował się usunąć tę wersję ze strony.',
    2: 'Zmień na dostępną wersję'
  },
  notify: {
    0: 'Problemy nie zostały rozwiązane',
    1: 'Nie wszystkie wymagane pola zostały wypełnione',
    2: 'Pokaż',
    3: 'Nie znaleziono',
    4: 'Nie znaleziono baneru (Obecnie, pierwszy zrzut ekranu jest używany jako baner)',
    5: 'Bez zmian',
    6: 'Nie znaleziono zmian',
    7: 'ID nie zostało znalezione',
    8: 'ID filmu nie zostało znalezione, spróbuj użyć innego linku (Obecnie obsługiwany jest tylko YouTube)',
    9: 'Ups',
    10: 'Wygląda na to, że Twoja sesja wygasła, otwórz nową stronę i zaloguj się na swoje konto (Nie martw się, wszystko zostało automatycznie zapisane)',
    11: 'Istnieje',
    12: 'Ten film został już dodany',
    13: 'Istnieje',
    14: 'Ten tag został już dodany',
    15: 'Nie znaleziono',
    16: 'Nie możesz usunąć usuniętego tagu',
    17: 'Dodano',
    18: 'Pomyślnie dodałeś nowy tag',
    19: 'Ups',
    20: 'Ten twórca został już dodany',
    21: 'EZ',
    22: 'Dodano nowego twórcę',
    23: 'HUH',
    24: 'Nie można usunąć usuniętego twórcy',
    25: 'Kopia',
    26: 'Ta zmiana została już wcześniej dodana.',
    27: 'Kopia',
    28: 'Ten link został już dodany.',
    29: 'Uwaga',
    30: 'Zapomniałeś dodać opisu do linku. Przykład: Opis:link',
    31: 'Uwaga',
    32: 'Zapomniałeś dodać linku do opisu. Przykład: Opis:link',
    33: 'Przywrócono',
    34: 'Wersja «{name}» została przywrócona',
    35: 'Usunięto',
    36: 'Wersja «{name}» została usunięta',
    37: 'Błąd',
    38: 'Najwyraźniej serwer uważa, że jesteś robotem.',
    39: 'Twoja obecna sesja logowania wygasła. Aby kontynuować, otwórz nową stronę i zaloguj się ponownie na swoje konto. Gdy to zrobisz, wróć tutaj i spróbuj ponownie.',
    40: 'Niepasujące dane (ponownie zaloguj się na konto. Nie martw się, wszystko zostało automatycznie zapisane)',
    41: 'Nieznany błąd',
    42: 'Nie możesz edytować nieistniejącego skina',
    43: 'Wygląda na to, że nie masz uprawnień do edycji tego skina',
    44: 'Nie możesz wysłać tej wersji, ponieważ jest taka sama jak poprzednia.',
    45: 'Te zmiany zostały już wysłane w celu weryfikacji przez moderacje',
    46: 'Sukces',
    47: 'Nowe zmiany zostały wysłane w celu weryfikacji przez moderacje',
    48: 'Zmiany zostały zaktualizowane podczas moderacji',
    49: 'Dziwny link',
    50: 'Ten link nie może być użyty jako link do pobrania',
    51: 'Wysłano w celu weryfikacji przez moderacje',
    52: 'Uwaga',
    53: 'Musisz wybrać typ zasobu',
    54: 'Ten skin jest obecnie weryfikowany przez moderacje. Bądź cierpliwy podczas przetwarzania',
    55: 'Sukces',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: 'Powiadomienia',
    1: 'Obserwuj nas na tych platformach, aby otrzymywać powiadomienia o nowych skinach'
  },
  restricted_view: {
    0: 'Błąd uwierzytelnienia',
    1: 'Zaloguj się do swojego konta',
    2: 'Ograniczony widok',
    3: 'Ta strona jeszcze nie jest gotowa.'
  },
  confirm: {
    0: 'Zresetować wszystko?',
    1: 'Pokazać poradnik?',
    2: 'Przesłać skina?',
    3: 'Tak',
    4: 'Nie',
    5: 'Reset .ini?'
  }
};