export default {
  title: {
    home: 'Główna',
    login: 'Zaloguj się',
    lists: { 0: 'Listy' },
    tags: {
      0: 'Tagi',
      1: '{amount} tagów dla kategorii {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiracje',
      1: '«{amount}»'
    },
    sounds: { 0: 'Efekty dzwiękowe' },
    leaderboard: { 0: 'Ranking' },
    extend: { 0: 'Rozwiń | Schowaj' },
    skin: {
      0: 'Ten skin posiada elementy z innych skinów',
      1: 'Kliknij tutaj po więcej informacji'
    },
    tools: 'Narzędzia'
  },
  changelogs: {
    0: 'Changelog',
    1: 'Lista zmian w najnowszej wersji',
    2: 'Nic tu jeszcze nie ma',
    3: 'Ale możesz dodać zmieny które zostały wprowadzone w tej wersji skina',
    4: 'Brak grupowania',
    5: 'Nowe',
    6: 'Naprawione błędy',
    7: 'Zmiany',
    8: 'Usunięte'
  },
  ideas: {
    0: 'Nothing founded',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Twórcy',
    1: 'Lista twórców którzy pracowali przy tej wersji',
    2: 'Nikogo tu nie ma',
    3: 'Wpisanie nazwy gracza ukaże listę profili.',
    4: 'Edytor',
    5: 'Role',
    6: 'Wersje'
  },
  tags: {
    0: 'Tagi',
    1: 'Lista wszystkich tagów opisujących tego skina',
    2: 'Troszkę tu pusto.',
    3: 'Użyj pola powyżej aby znaleźć nowe tagi',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Szukaj'
  },
  videos: {
    0: 'Wideo',
    1: 'Lista wszystkich wideoprezentacji',
    2: 'Brak wideoprezentacji',
    3: 'Poszukaj ich w serwise YouTube, lub stwórz własną'
  },
  sources: {
    0: 'Atrybucja',
    1: 'Lista wszystkich elementów lub narzędzi użytych w tej wersji skina',
    2: 'Troszkę tu pusto',
    3: 'Jeżeli zostały użyte elementy, lub arty, upewnij się, że zostały one dodane w polu powyżej',
    4: 'Brak grupowania'
  },
  checks: {
    0: 'Wszystkie',
    1: 'Metadata',
    2: 'Hightlight',
    3: 'Name of the skin not specified',
    4: 'Dodaj przynajmniej jednego twórcę',
    5: 'Dodaj kilka tagów',
    6: 'Nie podano wagi skina',
    7: 'Wybierz przynajmniej jeden tryb gry',
    8: 'Wybierz rozdzielczość plików (SD lub HD)',
    9: 'Wybierz przynajmniej jedną proporcję ekranu',
    10: 'Nie dodano screenshotów',
    11: 'Dodaj przynajmniej jeden screenshot z gameplay\'u',
    12: 'Nie podano linka do skina',
    20: 'Wszystko w normie',
    21: 'Naprawiono każdy błąd, wszystko jest w normie',
    22: 'Check list',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skiny',
    1: 'Popularne',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Nowe',
    5: 'Losowe',
    6: 'Wszystkie skiny',
    7: 'Proporcje obrazu',
    8: 'Wszystkie skiny | osu skiny',
    9: 'Skin | Skiny | Skiny',
    10: 'osu Skiny od {name} | Wszystkie skiny od',
    11: 'Szukaj',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Edytuj',
    1: 'Dodatki',
    2: 'HD',
    3: 'FullHD',
    4: 'Animacje',
    5: 'Screenshoty',
    6: 'Tylko gameplay',
    7: 'Link do pobrania | Pobierz skin',
    8: 'Post na forum | osu! Forum',
    9: 'Post na Reddicie',
    10: 'Twórcy',
    11: 'Tagi',
    13: 'Wideo',
    14: 'Nowa wersja | Edytuj Wersje',
    15: 'Zaktualizuj | Wyslij',
    16: 'Tryby gry',
    17: 'Nazwa skina',
    18: 'Wersja | Wersje',
    19: 'Wielkość',
    20: 'Metadata',
    21: 'Ocena',
    22: 'Pobrania',
    23: 'Możliwość pobrania będzie dostępna wkrótce',
    24: 'zostało {amount} sekund',
    25: 'Nie jesteś jednym z nas',
    26: 'Wygląda na to, że nie jesteś autorem tego skina, bądź nie masz permisji do jego edytowania',
    27: 'Skin od',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Kliknij',
    1: 'lub przeciągnij zdjęcia tutaj'
  },
  footer: {
    0: 'Made by cyperdark',
    1: 'Credits'
  },
  credits: {
    0: 'Chibi',
    1: 'Arty',
    2: 'Ikony',
    3: 'Wszystkie ikony pochodzą z {name}',
    4: 'Flagi',
    5: 'Wszystkie flagi pochodzą z {name}',
    6: 'Lokalizacja',
    7: 'Ktokolwiek? [{lang}]',
    8: 'Wygląda na to, że cpol zapomniał o ich dodaniu. {text}'
  },
  search: {
    0: 'Wyszukiwarka skinów',
    1: 'Wyświetlenia',
    2: 'Tytuł',
    3: 'Ocena',
    4: 'Wielkość',
    5: 'Data',
    7: 'Nic nie znaleziono',
    8: 'Spróbuj ustawić inne kryteria wyszukiwania',
    9: 'Czekam na zapytanie',
    10: 'Wybierz kryteria wyszukiwania, lub wpisz nazwę skina, autora, lub tag',
    11: 'Pobrania',
    12: 'Nazwa',
    13: {
      0: 'Skiny',
      1: 'Tagi',
      2: 'Users',
      3: 'Listy'
    }
  },
  tabs: {
    0: 'Szukaj',
    1: 'Edytuj',
    2: 'Lista'
  },
  undefined: {
    0: 'Pusto',
    1: 'Niestety nic tu nie ma, ale możesz obejrzeć inne strony',
    2: 'Niestety ale nic tu nie ma',
    3: 'Błąd uwierzytelnienia',
    4: 'Musisz być zalogowany, aby edytować ten skin.',
    5: 'Musisz się zalogować, aby dodać nowy skin.'
  },
  meta: {
    title: {
      0: 'Odkryj skiny do osu',
      1: 'Gamemodes, aspect ratios osu skins',
      2: 'Popular osu skins',
      3: 'Wyszukaj skiny do osu',
      4: '«{name}» tags list',
      5: '{name} v{version} skin do osu',
      6: 'Credits',
      7: 'skiny do osu',
      8: '{name} search osu skins',
      9: 'Zainspiruj się innymi skinami',
      10: '{name} stworzył/a skiny do osu',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Najlepsze skiny do osu! tylko u nas! W naszej ogromnej bibliotece znajdziesz skiny dla wszystkich trybów gry, proporcji ekranu, a nawet skiny używane przez topowych graczy. Posiadamy również sekcję dla fanów anime. Udoskonal swoją rozgrywkę z idealnym dla ciebie skinem. #osuskins #osugame #anime',
      1: '{views} wyświetleń. Skin osu! dla {modes}, o wadze {size}, stworzony przez {creators}. Wspiera {ratios}',
      2: 'Znajdź swój perfekcyjny skin do osu! dzieki naszej zaawansowanej wyszukiwarce. Zajrzyj też do ogromnej biblioteki, sortowanej przez tryb gry, proporcji ekranu, i więcej. Sprawdź też skiny używane przez topowych graczy',
      3: 'Odkryj tysiące różnych skinów dla różnych trybów gry i proporcji ekranu u nas. Wybierz pomiędzy standardem, catch the beat, manią, i taiko. Odkryj idealne dopasowanie pod swoje preferencje.',
      4: 'Znajdź swój perfekcyjny skin od topowych graczy u nas. Przejrzyj naszą kolekcję popularnych skinów i dostosuj swój gameplay. Odkryj szeroką gamę styli i motywów dla swoich preferencji',
      5: 'Lista istniejących tagów dla skinów.',
      6: 'Kolekcja skinów osu {name}!, darmowe pobieranie',
      7: 'Ogromna ilość skinów od {name}, pobierz za darmo!',
      8: 'Wszystkie skiny stworzone przez {name}',
      9: 'Znajdź inspirację na swój najnowszy skin u nas. Przejrzyj różnorodną kolekcję skinów i odkryj nowe techniki i pomysły. Zainspiruj się i stwórz jedyne w swoim rodzaju skiny.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Zaloguj się',
    1: 'Home page',
    profile_osu: 'Profil osu!',
    new_skin: 'Nowy skin',
    notifications: 'Powiadomienia',
    settings: 'Ustawienia',
    logout: 'Wyloguj się',
    load_more: 'Załaduj więcej',
    copy_short: 'Skopiuj skrócony link',
    copied: 'Skopiowano',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Powrót do skina'
  },
  user: {
    roles: {
      0: 'Autor',
      1: 'Mixer',
      2: 'Animacje',
      3: 'Arty',
      4: 'Kolaboracja'
    }
  },
  tooltips: {
    0: 'Wyświetlenia: {amount}',
    1: 'Odśwież wyniki',
    2: 'Malejąco | Rosnąco',
    3: 'Lubię to: {likes} / Nie lubię tego: {dislikes}',
    4: 'Naciśnij ctrl+enter aby dodać tag',
    5: 'Edytuj wersję',
    6: '{s}Zaloguj się{p}, aby oceniś ten skin',
    7: 'Brak krótkiego opisu',
    8: 'Brak linka',
    9: 'Pobrania: {amount}'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Main menu',
      2: 'Song select',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Countdown',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pause Screen',
      11: 'Fail Screen',
      12: 'Result screen',
      13: 'Skip',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mix'
    }
  },
  select: {
    0: 'Nowe',
    1: 'Naprawiono',
    2: 'Zmieniono',
    3: 'Usunięto',
    4: 'Art',
    5: 'Czcionka',
    6: 'Artysta',
    7: 'Element skina',
    8: 'Audio/Efekty Dźwiękowe',
    9: 'Narzędzia',
    views: 'Wyświetlenia',
    likes: 'Polubienia',
    dislikes: 'Nie lubię tego',
    downloads: 'Pobrania',
    size_range: 'Wybierz rozmiar',
    date_range: 'Wybierz zakres dat',
    ratio: 'Wybierz proporcje ekranu | proporcje ekranu'
  },
  placeholders: {
    0: 'Wybierz role',
    1: 'Wybierz wersje',
    2: 'Wpisz tekst...',
    3: 'Wybierz rozmiar',
    4: 'Wybierz zakres dat',
    5: 'Rok',
    6: 'Miesiąc',
    7: 'Wybierz proporcje ekranu',
    8: 'Wybierz kategorie',
    9: 'Tryby gry',
    10: 'Wybierz typ',
    11: 'Wklej link do YouTube',
    12: 'Wpisz opis oraz link. Format opis:link',
    13: 'Wybierz dodatki',
    14: 'Wklej link',
    15: 'Tytuł, autor, lub tag',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Współtwórz' },
  nsfw: {
    0: 'Uwaga!',
    1: 'Ten skin zawiera treści wrażliwe lub dla dorosłych',
    2: 'Ten skin zawiera treści wrażliwe lub dla dorosłych, które niektórzy użytkownicy mogą uznać za niepokojące',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was field',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creater has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Błąd uwierzytelnienia',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};