export default {
  title: {
    home: 'Página Inicial',
    login: 'Entrar',
    lists: { 0: 'Listas' },
    tags: {
      0: 'Tags',
      1: '{amount} tags para a categoria {name}',
      2: 'Tags de pesquisa'
    },
    ideas: {
      0: 'Inspiração',
      1: '{amount}'
    },
    sounds: { 0: 'Sons' },
    leaderboard: { 0: 'Placares' },
    extend: { 0: 'Mostrar mais | Mostrar menos' },
    skin: {
      0: 'Esta skin contém elementos retirados de outras skins',
      1: 'Clique aqui para mais informações'
    },
    tools: 'Ferramentas'
  },
  home: {
    0: 'Disponível para baixar',
    1: 'Mais skins do tipo: _name_',
    2: 'Visto | curtido | Baixado',
    3: 'Publique uma nova skin',
    4: 'Como instalar uma skin'
  },
  changelogs: {
    0: 'Histórico de mudanças',
    1: 'Lista de todas as revisões feitas na versão atual',
    2: 'Nada aqui',
    3: 'Mas você pode fazer mudanças para o que você fez nesta versão da skin',
    4: 'Não agrupado',
    5: 'Novo',
    6: 'Correções',
    7: 'Alterações',
    8: 'Remoções'
  },
  ideas: {
    0: 'Nada foi encontrado',
    1: 'Capturas de tela desta {type} não foram publicadas no site'
  },
  creators: {
    0: 'Criadores',
    1: 'Liste todos os criadores que estavam envolvidos na criação desta versão',
    2: 'Não há ninguém aqui',
    3: 'Procurar o nome de um jogador exibirá uma lista de perfis.',
    4: 'Editor',
    5: 'Funções',
    6: 'Versões'
  },
  tags: {
    0: 'Tags',
    1: 'Listar todos os filtros relacionados a esta skin',
    2: 'Parece bastante vazio aqui.',
    3: 'Utilize o campo acima para adicionar novas tags',
    4: 'Tags não foram encontradas',
    5: 'Tente procurar por algo diferente',
    6: 'Buscar'
  },
  videos: {
    0: 'Vídeos',
    1: 'Lista de todos os vídeos apresentando para está skin',
    2: 'Sem demonstrações',
    3: 'Procure por alguns no YouTube ou crie sua própria demonstração'
  },
  sources: {
    0: 'Atribuições',
    1: 'Lista de todos os arquivos ou ferramentas utilizados nesta versão da skin',
    2: 'Aqui parece estar um pouco vazio',
    3: 'Se você usou arquivos de outras skins ou artes, certifique-se de adicioná-los na caixa acima',
    4: 'Não agrupado'
  },
  checks: {
    0: 'Tudo',
    1: 'Metadados',
    2: 'Destaque',
    3: 'Nome da skin não foi especificado',
    4: 'Adicione ao menos um criador de skin',
    5: 'Adicione algumas tags',
    6: 'O tamanho da skin não foi especificado',
    7: 'Selecione pelo menos um modo de jogo',
    8: 'Selecione a resolução da imagem (SD ou HD)',
    9: 'Selecione pelo menos uma resolução',
    10: 'Nenhuma captura de tela fornecida',
    11: 'Adicione ao mínimo uma captura de tela da gameplay',
    12: 'O link para a skin não foi especificado',
    20: 'Parece muito bom',
    21: 'Todos os problemas forma solucionados. Bom Trabalho! Camarada!',
    22: 'Lista de verificação',
    23: 'Adicione no mínimo una versão pública',
    24: 'Adicione ao menos um criador para esta versão ',
    25: 'Alguns criadores não possuem funções'
  },
  skins: {
    0: 'Skins',
    1: 'Popular',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recente',
    5: 'Aleatório',
    6: 'Todas as skins',
    7: 'Resolução',
    8: 'Todas as skins | skins osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins de osu por {name} | Todas as skins de',
    11: 'Buscar',
    12: '{name} skins',
    13: 'Explore por skins'
  },
  skin: {
    0: 'Editar',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animação',
    5: 'Capturas de Tela',
    6: 'Somente gameplay',
    7: 'Link do download | Download da skin\n',
    8: 'Post do fórum | Fórum do osu!',
    9: 'Post no Reddit',
    10: 'Criadores',
    11: 'Tags',
    13: 'Vídeos',
    14: 'Nova Versão | Gerenciar versões',
    15: 'Atualizar | Enviar',
    16: 'Modos de jogo',
    17: 'Nome da skin',
    18: 'Versão | Versões',
    19: 'Tamanho',
    20: 'Metadados',
    21: 'Avaliação',
    22: 'Downloads',
    23: 'O download estará disponível em breve',
    24: '{amount} segundos restantes',
    25: 'Você não é um de nós',
    26: 'Parece que você não é o autor ou um editor desta skin',
    27: 'Skin de',
    28: 'Sem tags',
    29: 'Sem vídeo',
    30: 'Nenhum criador',
    31: 'Avalie esta skin',
    32: 'De um Upvote & comente no reddit',
    33: 'Comente num fórum de osu!',
    34: 'Mais skins feitas por este autor | Mais skins deste autor',
    35: 'Apoie a skin'
  },
  drag: {
    0: 'Clique aqui',
    1: 'ou arraste e solte as imagens aqui'
  },
  footer: {
    0: 'Feito por cyperdark',
    1: 'Créditos'
  },
  credits: {
    0: 'Chibi',
    1: 'Artes',
    2: 'Ícones',
    3: 'Todos os icones foram providenciados por {name}',
    4: 'Bandeiras',
    5: 'Todas as imagens das bandeiras são de {name}',
    6: 'Localização',
    7: 'Alguém?[{lang}]',
    8: 'Parece que o cyperdark esqueceu de adicionar eles. {text}'
  },
  search: {
    0: 'Buscar skin',
    1: 'Visualizações',
    2: 'Título',
    3: 'Avaliação',
    4: 'Tamanho',
    5: 'Data',
    7: 'Nada foi encontrado',
    8: 'Tente usar outros filtros de pesquisa',
    9: 'Esperando a busca',
    10: 'Use os filtros de pesquisa ou algo parecido com o título da skin, autor ou tag',
    11: 'Downloads',
    12: 'Nome',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Usuários',
      3: 'Listas'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Buscar',
    1: 'Editar',
    2: 'Lista'
  },
  undefined: {
    0: 'Vazio',
    1: 'Infelizmente, não há nada aqui, mas você pode dar uma olhada em outras páginas',
    2: 'Infelizmente, não há nada aqui :(',
    3: 'Não autorizado',
    4: 'Você precisa estar logado para poder editar a skin.',
    5: 'Você precisa estar logado para poder adicionar uma nova skin.'
  },
  meta: {
    title: {
      0: 'Descubra novas skins de osu',
      1: 'Modos de jogo, resolução skins osu',
      2: 'Skins populares de osu',
      3: 'Procure por skins de osu',
      4: 'Lista de filtros, {name}',
      5: '{name} {version} skin de osu',
      6: 'Créditos',
      7: 'osu skins',
      8: '{name} procure por skins de osu',
      9: 'Consiga inspiração com outras skins de osu!',
      10: '{name} criou skins de osu',
      11: 'Tags de pesquisa',
      12: '{name} tags encontradas',
      13: 'Nova skin'
    },
    description: {
      0: 'Encontre as melhores skins de osu! em nosso site! Nossa grande coleção de skins para todos os modos de jogo, resoluções e até mesmo dos melhores jogadores. Além disso, nós possuímos uma seção especial aosfãs de anime. Melhore sua gameplay com a skin perfeita. #osuskins #osugame #anime',
      1: '{views} views. Uma skin para {modes}, O tamanho é {size}, criado por {creators}. Suporta {ratios}',
      2: 'Encontre a skin perfeita com nossa busca avançada. Navegue por nossa grande coleção,filtrada por modo de jogo,proporção, e muito mais. Ou, observe as skins usadas por top players.',
      3: 'Descubra uma variedade de skins de outros modos de jogo e até de diferentes proporções em nosso site. Escolha entre standard, catch the beat, mania,e taiko. Encontre aquela que encaixa perfeitamente com a sua preferência.',
      4: 'Encontre a skin perfeita utilizada pelos melhores jogadores de osu! em nosso site. Explore nossa coleção de skins populares e customize sua gameplay. Descubra uma ampla diversidade de estilos e temas para adaptar com suas preferências.',
      5: 'Lista das tags existentes para as skins.',
      6: '{name} coleção de skins de osu!, baixe de graça',
      7: 'Uma grande quantidade de skins de {name}, baixe de graça!',
      8: 'Todas as skins foram criadas por {name}',
      9: 'Ache a inspiração para sua próxima skin em nosso site. Navegue entre uma grande diversidade de skins e descubra novas técnicas e ideías. Se inspire e crie sua própria e única skin.',
      10: 'Procure por alguma tag entre todas as tags do site.'
    }
  },
  buttons: {
    0: 'Entrar',
    1: 'Página inicial',
    profile_osu: 'Perfil do osu!',
    new_skin: 'Nova skin',
    notifications: 'Notificações',
    settings: 'Configurações',
    logout: 'Finalize sua sessão',
    load_more: 'Carregar mais',
    copy_short: 'Encurtar link',
    copied: 'Copiado',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'De volta a skin'
  },
  user: {
    roles: {
      0: 'Criador',
      1: 'Mixador',
      2: 'Animações',
      3: 'Artes',
      4: 'Colaboração'
    }
  },
  tooltips: {
    0: 'Views:{amount}',
    1: 'Atualizar resultados',
    2: 'Descendente | Ascendente',
    3: 'Curtidas: {likes} / Não Curtiram: {dislikes}',
    4: 'Pressione Ctrl+Enter para adicionar uma tag',
    5: 'Editar versão',
    6: '{s} Log in {p}, para poder avaliar a skin',
    7: 'Sem resumo',
    8: 'Sem url',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Boas-vindas',
      1: 'Menu Principal',
      2: 'Seleção de músicas',
      3: 'Menu de modos',
      4: 'Modificações',
      5: 'Contagem regressiva',
      6: 'Jogabilidade',
      7: 'Spinner',
      8: 'Seção de Pass',
      9: 'Seção de Falha',
      10: 'Tela de pausa',
      11: 'Tela de falha',
      12: 'Tela de resultados',
      13: 'Pular',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Misturada'
    }
  },
  select: {
    0: 'Novo',
    1: 'Corrigido',
    2: 'Alterado',
    3: 'Removido',
    4: 'Arte',
    5: 'Fonte',
    6: 'Artista',
    7: 'Elementos da skin',
    8: 'Áudio/Sfx',
    9: 'Ferramentas',
    views: 'Visualizações',
    likes: 'Curtidas',
    dislikes: 'Dislikes',
    downloads: 'Downloads',
    size_range: 'Selecionar tamanho',
    date_range: 'Selecionar período',
    ratio: 'Selecionar resolução | resolução'
  },
  placeholders: {
    0: 'Selecione a funções',
    1: 'Selecione a versão',
    2: 'Escreva alguma coisa...',
    3: 'Selecionar tamanho',
    4: 'Selecionar período',
    5: 'Ano',
    6: 'Mês',
    7: 'Selecionar resolução',
    8: 'Selecionar categorias',
    9: 'Modos de jogo',
    10: 'Selecionar tipo',
    11: 'Inserir um link do YouTube',
    12: 'Escreva uma descrição e uma url. Descrição formatada em:url',
    13: 'Selecionar extra',
    14: 'Cole um link',
    15: 'Título da skin, autor, ou tags',
    16: 'Selecione a categoria',
    17: 'Escreva o nome da tag'
  },
  contribute: { 0: 'Contribua' },
  nsfw: {
    0: 'Cuidado!',
    1: 'Essa skin contém conteúdos considerados sensíveis ou conteúdo adulto',
    2: 'Essa skin contém conteúdo sensível o adulto que alguns usuários consideram perturbador',
    3: 'Tudo bem',
    4: 'Tchau o/'
  },
  removed: {
    0: 'Versão indisponível',
    1: 'O autor da skin decidiu remover esta versão da skin do site',
    2: 'Mude para uma versão disponível'
  },
  notify: {
    0: 'Os erros não foram corrigidos',
    1: 'Nem todos os campos foram preenchidos',
    2: 'Mostrar',
    3: 'Não encontrado',
    4: 'Banner não foi encontrado (atualmente, a primeira captura de tela está sendo usada de banner)',
    5: 'Sem mudanças',
    6: 'Nenhuma modificação foi encontrada',
    7: 'ID não foi encontrado',
    8: 'ID do video não foi encontrado, tente outro link (por enquanto apenas links do Youtube estão disponíveis)',
    9: 'Opa',
    10: 'Parece que sua sessão expirou, abra uma nova página e se logue com sua conta (Não se preocupe, tudo o que foi feito é salvo automaticamente) ',
    11: 'Existe',
    12: 'Este vídeo já foi adicionado',
    13: 'Existe',
    14: 'Esta tag já foi adicionada',
    15: 'Não encontrado',
    16: 'Você não pode deletar uma tag que já foi deletada',
    17: 'Adicionado',
    18: 'Você conseguiu adicionar uma nova tag',
    19: 'Ooopa ',
    20: 'Este criador já foi adicionado',
    21: 'EZ',
    22: 'Novo criador foi adicionado',
    23: 'Huum',
    24: 'É impossível remover um criador apagado',
    25: 'Duplicado',
    26: 'Esta mudança já foi adicionada antes.',
    27: 'Duplicado',
    28: 'Está url já foi adicionada antes.',
    29: 'Cuidado',
    30: 'Você se esqueceu de adicionar uma descrição a url. Por exemplo: Descrição:url',
    31: 'Cuidado',
    32: 'Você se esqueceu de adicionar uma url a descrição. Por exemplo: Descrição:Url',
    33: 'Recuperado',
    34: 'Versão «{name}» foi restaurada',
    35: 'Excluído',
    36: 'Versão «{name}» foi excluída ',
    37: 'Erro',
    38: 'Aparentemente, o servidor pensa que você é um robô.',
    39: 'Parece que sua sessão expirou, abre uma nova página e logue na sua conta (Não se preocupe, tudo foi salvo automaticamente)',
    40: 'Credenciais não correspondidas (Logue-se em uma conta. Não se preocupe, tudo foi salvo automaticamente)',
    41: 'Erro desconhecido',
    42: 'Você não pode editar uma skin inexistente',
    43: 'Parece que você não tem permissão para editar esta skin',
    44: 'Você não pode enviar esta versão porque é idêntica a anterior.',
    45: 'As mudanças já foram enviadas para moderação',
    46: 'Bem sucedido',
    47: 'Novas mudanças foram enviadas para moderação',
    48: 'Mudanças foram atualizadas na moderação',
    49: 'Link estranho',
    50: 'Este link não pode ser usado como um link de download',
    51: 'Enviado para moderação'
  },
  header: {
    0: 'Notificações',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Não autorizado',
    1: 'Porfavor logue em sua conta ',
    2: 'Visão restrita',
    3: 'Está página não foi lançada, ainda.'
  }
};