export default {
  title: {
    home: 'Página Inicial',
    login: 'Entrar',
    lists: { 0: 'Listas' },
    tags: {
      0: 'Tags',
      1: '{amount} tags para a categoria {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiração',
      1: '{amount}'
    },
    sounds: { 0: 'Sons' },
    leaderboard: { 0: 'Placares' },
    extend: { 0: 'Mostrar mais | Mostrar menos' },
    skin: {
      0: 'Esta skin contém elementos retirados de outras skins',
      1: 'Clique aqui para mais informações'
    },
    tools: 'Ferramentas'
  },
  changelogs: {
    0: 'Histórico de mudanças',
    1: 'Lista de todas as revisões feitas na versão atual',
    2: 'Nada aqui',
    3: 'But you can add the changes you made\'ve to this version of the skin',
    4: 'Não agrupado',
    5: 'Novo',
    6: 'Correções',
    7: 'Alterações',
    8: 'Remoções'
  },
  ideas: {
    0: 'Nada foi encontrado',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Criadores',
    1: 'Liste todos os criadores que estavam envolvidos na criação desta versão',
    2: 'Não há ninguém aqui',
    3: 'Procurar o nome de um jogador exibirá uma lista de perfis.',
    4: 'Editor',
    5: 'Funções',
    6: 'Versões'
  },
  tags: {
    0: 'Tags',
    1: 'Listar todos os filtros relacionados a esta skin',
    2: 'Parece bastante vazio aqui.',
    3: 'Utilize o campo acima para adicionar novas tags',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Buscar'
  },
  videos: {
    0: 'Vídeos',
    1: 'Lista de todos os vídeos apresentando para está skin',
    2: 'Sem demonstrações',
    3: 'Procure por alguns no YouTube ou crie sua própria demonstração'
  },
  sources: {
    0: 'Atribuições',
    1: 'Lista de todos os arquivos ou ferramentas utilizados nesta versão da skin',
    2: 'Aqui parece estar um pouco vazio',
    3: 'Se você usou arquivos de outras skins ou artes, certifique-se de adicioná-los na caixa acima',
    4: 'Não agrupado'
  },
  checks: {
    0: 'Tudo',
    1: 'Metadados',
    2: 'Destaque',
    3: 'Name of the skin not specified',
    4: 'Adicione ao menos um criador de skin',
    5: 'Adicione algumas tags',
    6: 'O tamanho da skin não foi especificado',
    7: 'Selecione pelo menos um modo de jogo',
    8: 'Selecione a resolução da imagem (SD ou HD)',
    9: 'Selecione pelo menos uma resolução',
    10: 'Nenhuma captura de tela fornecida',
    11: 'Adicione ao mínimo uma captura de tela da gameplay',
    12: 'O link para a skin não foi especificado',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Lista de verificação',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Popular',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recente',
    5: 'Aleatório',
    6: 'Todas as skins',
    7: 'Resolução',
    8: 'Todas as skins | skins osu',
    9: 'Skin | Skins | Skins',
    10: 'Skins de osu por {name} | Todas as skins de',
    11: 'Buscar',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Editar',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animação',
    5: 'Capturas de Tela',
    6: 'Somente gameplay',
    7: 'Link do download | Download da skin\n',
    8: 'Post do fórum | Fórum do osu!',
    9: 'Post no Reddit',
    10: 'Criadores',
    11: 'Tags',
    13: 'Vídeos',
    14: 'Nova Versão | Gerenciar versões',
    15: 'Atualizar | Enviar',
    16: 'Modos de jogo',
    17: 'Nome da skin',
    18: 'Versão | Versões',
    19: 'Tamanho',
    20: 'Metadados',
    21: 'Avaliação',
    22: 'Downloads',
    23: 'O download estará disponível em breve',
    24: '{amount} segundos restantes',
    25: 'Você não é um de nós',
    26: 'Parece que você não é o autor ou um editor desta skin',
    27: 'Skin de',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Clique aqui',
    1: 'ou arraste e solte as imagens aqui'
  },
  footer: {
    0: 'Feito por cyperdark',
    1: 'Créditos'
  },
  credits: {
    0: 'Chibi',
    1: 'Artes',
    2: 'Ícones',
    3: 'Todos os icones foram providenciados por {name}',
    4: 'Bandeiras',
    5: 'Todas as imagens das bandeiras são de {name}',
    6: 'Localização',
    7: 'Alguém?[{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Buscar skin',
    1: 'Visualizações',
    2: 'Título',
    3: 'Avaliação',
    4: 'Tamanho',
    5: 'Data',
    7: 'Nada foi encontrado',
    8: 'Try using different search filters',
    9: 'Esperando a busca',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Downloads',
    12: 'Nome',
    13: {
      0: 'Skins',
      1: 'Tags',
      2: 'Users',
      3: 'Listas'
    }
  },
  tabs: {
    0: 'Buscar',
    1: 'Editar',
    2: 'Lista'
  },
  undefined: {
    0: 'Vazio',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Não autorizado',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Descubra novas skins de osu',
      1: 'Modos de jogo, resolução skins osu',
      2: 'Skins populares de osu',
      3: 'Procure por skins de osu',
      4: 'Lista de filtros, {name}',
      5: '{name} {version} skin de osu',
      6: 'Créditos',
      7: 'osu skins',
      8: '{name} procure por skins de osu',
      9: 'Consiga inspiração com outras skins de osu!',
      10: '{name} criou skins de osu',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Encontre as melhores skins de osu! em nosso site! Nossa grande coleção de skins para todos os modos de jogo, resoluções e até mesmo dos melhores jogadores. Além disso, nós possuímos uma seção especial aosfãs de anime. Melhore sua gameplay com a skin perfeita. #osuskins #osugame #anime',
      1: '{views} views. Uma skin para {modes}, O tamanho é {size}, criado por {creators}. Suporta {ratios}',
      2: 'Encontre a skin perfeita com nossa busca avançada. Navegue por nossa grande coleção,filtrada por modo de jogo,proporção, e muito mais. Ou, observe as skins usadas por top players.',
      3: 'Descubra uma variedade de skins de outros modos de jogo e até de diferentes proporções em nosso site. Escolha entre standard, catch the beat, mania,e taiko. Encontre aquela que encaixa perfeitamente com a sua preferência.',
      4: 'Encontre a skin perfeita utilizada pelos melhores jogadores de osu! em nosso site. Explore nossa coleção de skins populares e customize sua gameplay. Descubra uma ampla diversidade de estilos e temas para adaptar com suas preferências.',
      5: 'Lista das tags existentes para as skins.',
      6: '{name} coleção de skins de osu!, baixe de graça',
      7: 'Uma grande quantidade de skins de {name}, baixe de graça!',
      8: 'Todas as skins foram criadas por {name}',
      9: 'Ache a inspiração para sua próxima skin em nosso site. Navegue entre uma grande diversidade de skins e descubra novas técnicas e ideías. Se inspire e crie sua própria e única skin.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Entrar',
    1: 'Página inicial',
    profile_osu: 'Perfil do osu!',
    new_skin: 'Nova skin',
    notifications: 'Notificações',
    settings: 'Configurações',
    logout: 'Finalize sua sessão',
    load_more: 'Carregar mais',
    copy_short: 'Encurtar link',
    copied: 'Copiado',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'De volta a skin'
  },
  user: {
    roles: {
      0: 'Criador',
      1: 'Mixador',
      2: 'Animações',
      3: 'Artes',
      4: 'Colaboração'
    }
  },
  tooltips: {
    0: 'Views:{amount}',
    1: 'Atualizar resultados',
    2: 'Descendente | Ascendente',
    3: 'Curtidas: {likes} / Não Curtiram: {dislikes}',
    4: 'Pressione Ctrl+Enter para adicionar uma tag',
    5: 'Editar versão',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Sem resumo',
    8: 'Sem url',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Boas-vindas',
      1: 'Menu Principal',
      2: 'Seleção de músicas',
      3: 'Menu de modos',
      4: 'Modificações',
      5: 'Contagem regressiva',
      6: 'Jogabilidade',
      7: 'Spinner',
      8: 'Seção de Pass',
      9: 'Seção de Falha',
      10: 'Tela de pausa',
      11: 'Tela de falha',
      12: 'Tela de resultados',
      13: 'Pular',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Misturada'
    }
  },
  select: {
    0: 'Novo',
    1: 'Corrigido',
    2: 'Alterado',
    3: 'Removido',
    4: 'Arte',
    5: 'Fonte',
    6: 'Artista',
    7: 'Elementos da skin',
    8: 'Áudio/Sfx',
    9: 'Ferramentas',
    views: 'Visualizações',
    likes: 'Curtidas',
    dislikes: 'Dislikes',
    downloads: 'Downloads',
    size_range: 'Selecionar tamanho',
    date_range: 'Selecionar período',
    ratio: 'Selecionar resolução | resolução'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Selecionar tamanho',
    4: 'Selecionar período',
    5: 'Ano',
    6: 'Mês',
    7: 'Selecionar resolução',
    8: 'Selecionar categorias',
    9: 'Modos de jogo',
    10: 'Selecionar tipo',
    11: 'Inserir um link do YouTube',
    12: 'Type a description and an url. Format description:url',
    13: 'Selecionar extra',
    14: 'Cole um link',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribua' },
  nsfw: {
    0: 'Cuidado!',
    1: 'Essa skin contém conteúdos considerados sensíveis ou conteúdo adulto',
    2: 'Essa skin contém conteúdo sensível o adulto que alguns usuários consideram perturbador',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation'
  },
  restricted_view: {
    0: 'Não autorizado',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};