export default {
  title: {
    home: 'Pagina principală',
    login: 'Conectează-te',
    lists: { 0: 'Liste' },
    tags: {
      0: 'Etichete',
      1: '{amount} etichete pentru categoria {name}',
      2: 'Caută etichete'
    },
    ideas: {
      0: 'Inspirație',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sunete' },
    leaderboard: { 0: 'Clasamente' },
    extend: { 0: 'Mai mult | Mai puțin' },
    skin: {
      0: 'Acest skin conține elemente din alte skinuri',
      1: 'Apasă aici pentru mai multe informații'
    },
    tools: 'Instrumente'
  },
  changelogs: {
    0: 'Jurnal de Modificări',
    1: 'Lista tuturor reviziilor efectuate în versiunea curentă',
    2: 'Nimic aici',
    3: 'Dar poți adăuga modificările pe care le-ai făcut acestei versiuni a skin-ului',
    4: 'Nu sunt grupate',
    5: 'Nou',
    6: 'Probleme rezolvate',
    7: 'Modificări',
    8: 'Desființări'
  },
  ideas: {
    0: 'Nu am găsit nimic',
    1: 'Capturile de ecran din «{type}» nu au fost încărcate pe site'
  },
  creators: {
    0: 'Creatori',
    1: 'Menționează toți creatorii care au fost implicați in crearea acestei versiuni',
    2: 'Nu e nimeni aici',
    3: 'Căutând numele unui jucător va afișa o listă de profiluri.',
    4: 'Editor',
    5: 'Roluri',
    6: 'Versiuni'
  },
  tags: {
    0: 'Etichete',
    1: 'Listă cu toate etichetele legate de acest skin',
    2: 'Pare cam gol aici.',
    3: 'Folosește-te de caseta de mai sus pentru a găsi etichete noi',
    4: 'Etichetele nu au fost găsite',
    5: 'Încearcă să cauți altceva',
    6: 'Căutare'
  },
  videos: {
    0: 'Videoclipuri',
    1: 'Lista tuturor prezentărilor video a acestui skin',
    2: 'Zero prezentări',
    3: 'Caută câteva pe YouTube sau creează-ți propria prezentare'
  },
  sources: {
    0: 'Atribuții',
    1: 'Lista tuturor materialelor sau instrumentelor folosite în această versiune a skinului',
    2: 'Cam pustiu pe aici',
    3: 'Dacă ai folosit materiale din alte skinuri sau creații, nu uita să le adaugi în caseta de mai sus',
    4: 'Nu sunt grupate'
  },
  checks: {
    0: 'Toate',
    1: 'Metadata',
    2: 'Hightlight',
    3: 'Nume skinului nu este specificat',
    4: 'Adaugă cel puțin un creator al skinului',
    5: 'Adaugă câteva etichete',
    6: 'Mărimea skinului nespecificată',
    7: 'Selectează cel puțin un mod de joc',
    8: 'Selectează tipul fișierului (SD sau HD)',
    9: 'Selectează cel puțin un aspect ratio',
    10: 'Nici o captură de ecran furnizată',
    11: 'Adaugă cel puțin o captură de ecran a unui mod de joc',
    12: 'Link spre skin nespecificat',
    20: 'Arată destul de bine',
    21: 'Fiecare problema a fost corectată, ceea ce este destul de bine',
    22: 'Listă de verificare',
    23: 'Adaugă cel puțin o versiune publică'
  },
  skins: {
    0: 'Skinuri',
    1: 'Populare',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Recente',
    5: 'Aleatorii',
    6: 'Toate skinurile',
    7: 'Aspect ratio',
    8: 'Toate skinurile | skinuri osu',
    9: 'Skin | Skinuri | Skinuri',
    10: 'Skinuri osu realizate de {name} | Toate skinurile de la',
    11: 'Căutare',
    12: 'Skinuri {name}',
    13: 'Descoperă skinuri'
  },
  skin: {
    0: 'Edit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animații',
    5: 'Capturi de ecran',
    6: 'Doar gameplay',
    7: 'Link de descărcare | Descarcă skinul',
    8: 'Postarea de pe forum | Forumul osu!',
    9: 'Postare Reddit',
    10: 'Creatori',
    11: 'Etichete',
    13: 'Videoclipuri',
    14: 'Versiune nouă | Gestionează versiunile',
    15: 'Actualizează | Trimite',
    16: 'Moduri de joc',
    17: 'Numele skinului',
    18: 'Versiune | Versiuni',
    19: 'Dimensiune',
    20: 'Metadata',
    21: 'Rating',
    22: 'Descărcări',
    23: 'Descărcarea va fi valabilă in curând',
    24: '{amount} secunde rămase',
    25: 'Nu ești unul dintre noi',
    26: 'Pare că nu ești un autor sau editor al acestui skin',
    27: 'Skin creat de',
    28: 'Nicio etichetă',
    29: 'Niciun videoclip',
    30: 'Niciun creator'
  },
  drag: {
    0: 'Apasă aici',
    1: 'sau trage și plasează imaginile'
  },
  footer: {
    0: 'Creat de cyperdark',
    1: 'Credite'
  },
  credits: {
    0: 'Chibi',
    1: 'Opere',
    2: 'Pictograme',
    3: 'Toate pictogramele sunt luate de pe {name}',
    4: 'Steaguri',
    5: 'Toate steagurile sunt luate de pe {name}',
    6: 'Localizare',
    7: 'Cineva? [{lang}]',
    8: 'Se pare că cpol a uitat să adauge persoane. {text}'
  },
  search: {
    0: 'Căutarea unui skin',
    1: 'Vizualizări',
    2: 'Titlu',
    3: 'Rating',
    4: 'Dimensiune',
    5: 'Dată',
    7: 'Nu am găsit nimic',
    8: 'Încearcă să schimbi criteriile de căutare',
    9: 'În așteptarea unei solicitări',
    10: 'Selectează criteriile căutării sau scrie titlul, autorul sau etichetele skin-ului',
    11: 'Descărcări',
    12: 'Nume',
    13: {
      0: 'Skinuri',
      1: 'Etichete',
      2: 'Utilizatori',
      3: 'Liste'
    }
  },
  tabs: {
    0: 'Căutare',
    1: 'Edit',
    2: 'Listă'
  },
  undefined: {
    0: 'Gol',
    1: 'Din păcate nu am găsit nimic aici, dar poți să te uiți pe celelalte pagini',
    2: 'Din păcate nu am găsit nimic aici',
    3: 'Neautorizat',
    4: 'Trebuie să fi conectat pentru a edita acest skin.',
    5: 'Trebuie să fi conectat pentru a adăuga un nou skin.'
  },
  meta: {
    title: {
      0: 'Descoperă skinuri de osu',
      1: 'Gamemodes, aspect ratios osu skins',
      2: 'Skinuri de osu populare',
      3: 'Caută skinuri de osu',
      4: 'Lista de etichete, {name}',
      5: 'Skinul de osu {name} v{version}',
      6: 'Credite',
      7: 'skinuri de osu',
      8: 'caută skinuri osu {name}',
      9: 'Inspiră-te de la alte skinuri de osu',
      10: '{name} a creat skinuri de osu',
      11: 'Caută etichete',
      12: 'etichete {name} găsite'
    },
    description: {
      0: 'Obține cele mai bune skin-uri de osu pe site-ul nostru! Librăria noastră imensă conține skin-uri pentru toate modurile de joc, aspect ratio-urile și pana și skinuri ale jucătorilor de top. Plus, avem o secțiune specială pentru fanii anime-urilor. îmbunătăţeşte-ți gameplay-ul cu skin-ul perfect. #osuskins #osugame #anime',
      1: '{views} vizualizări. Un skin de osu pentru {modes}, cu mărimea de {size}, creat de {creators}. Compatibil cu ratio-urile {ratios}',
      2: 'Găsește skinul de osu! perfect cu ajutorul funcției noastre de căutare avansată. Răsfoiește biblioteca noastră imensă, filtrată după modul de joc, aspect ratio și multe altele. Sau aruncați o privire la skinurile folosite de jucătorii de top.',
      3: 'Descoperă o varietate de skinuri pentru diferite moduri de joc și aspect ratio-uri diferite pe site-ul nostru. Alege din modurile de joc standard, catch the beat, mania și taiko. Găsește cea care se potrivește perfect preferințelor tale de joc.',
      4: 'Găsește skinul osu perfect al jucătorilor de top de pe site-ul nostru. Răsfoiește colecția noastră de skinuri populare și personalizează-ți jocul. Descoperă o gamă largă de stiluri și teme care să se potrivească preferințelor tale.',
      5: 'Lista etichetelor existente pentru skinurile de osu.',
      6: 'Colecția de skinuri {name} pentru osu! Descărcare gratuită',
      7: 'O mulțime de skinuri osu! pentru {name}, descarcă gratuit!',
      8: 'Toate skinurile de osu realizate de {name}',
      9: 'Găsește inspirație pentru următorul tău skin de osu! pe site-ul nostru. Navighează printr-o colecție diversă de skin-uri și descoperă noi tehnici și idei. Inspiră-te si creează-ți propriile skin-uri unice.',
      10: 'Caută etichete printre toate etichetele de pe site.'
    }
  },
  buttons: {
    0: 'Conectează-te',
    1: 'Pagină principală',
    profile_osu: 'Profilul de osu!',
    new_skin: 'Skin nou',
    notifications: 'Notificări',
    settings: 'Setări',
    logout: 'Deconectează-te',
    load_more: 'Încarcă mai multe',
    copy_short: 'Copiază link prescurtat',
    copied: 'Copiat',
    reddit_link: 'Reddit',
    osu_forum_link: 'Forum osu!',
    skin_return: 'Înapoi la skin'
  },
  user: {
    roles: {
      0: 'Creator',
      1: 'Mixer',
      2: 'Animații',
      3: 'Opere',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Vizualizări: {amount}',
    1: 'Reîmprospătează rezultatele',
    2: 'Descrescător | Crescător',
    3: 'Like-uri: {likes} / Dislike-uri: {dislikes}',
    4: 'Apasă ctrl+enter pentru a adăuga o etichetă',
    5: 'Modifică versiunea',
    6: '{s}Conectează-te{p}, pentru a putea evalua acest skin',
    7: 'Nici o descriere scurtă',
    8: 'Nici un url',
    9: 'Descărcări: {amount}'
  },
  lists: {
    screens: {
      0: 'Bine ai venit',
      1: 'Meniu principal',
      2: 'Selectare piesă',
      3: 'Meniu moduri de joc',
      4: 'Moduri',
      5: 'Numărătoarea inversă',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Secțiune trecută',
      9: 'Secțiune eșuată',
      10: 'Ecranul de pauză',
      11: 'Ecranul de eșec',
      12: 'Ecranul cu rezultate',
      13: 'Skip',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixt'
    }
  },
  select: {
    0: 'Nou',
    1: 'Corectat',
    2: 'Modificat',
    3: 'Eliminat',
    4: 'Artă',
    5: 'Font',
    6: 'Artist',
    7: 'Elementul/Elementele skinului',
    8: 'Audio/Sfx',
    9: 'Instrumente',
    views: 'Vizualizări',
    likes: 'Like-uri',
    dislikes: 'Dislike-uri',
    downloads: 'Descărcări',
    size_range: 'Selectați dimensiunea',
    date_range: 'Selectați un interval de timp',
    ratio: 'Selectați un aspect ratio | ratio'
  },
  placeholders: {
    0: 'Alege rolurile',
    1: 'Alege versiunile',
    2: 'Tastează text...',
    3: 'Selectați dimensiunea',
    4: 'Selectează intervalul de timp',
    5: 'An',
    6: 'Lună',
    7: 'Selectează aspect ratio',
    8: 'Selectează categoriile',
    9: 'Moduri de joc',
    10: 'Selectează tipul',
    11: 'Atașează un link de YouTube',
    12: 'Tastează descrierea și url-ul. Format descriere:url',
    13: 'Selectează extra',
    14: 'Atașează un link',
    15: 'Titlul, autorul sau eticheta skinului',
    16: 'Selectează categoria',
    17: 'Tastează numele etichetei'
  },
  contribute: { 0: 'Contribuie' },
  nsfw: {
    0: 'Atenție!',
    1: 'Acest skin conţine conţinut sensibil sau pentru adulţi',
    2: 'Acest skin conține conținut sensibil sau pentru adulți pe care unii utilizatori îl pot considera deranjant',
    3: 'În regulă',
    4: 'pa o/'
  },
  removed: {
    0: 'Versiune indisponibilă',
    1: 'Autorul acestui skin a decis să elimine această versiune de pe site.',
    2: 'Treceți la versiunea disponibilă'
  },
  notify: {
    0: 'Probleme nerezolvate',
    1: 'Nu au fost completate toate câmpurile obligatorii',
    2: 'Arată',
    3: 'Nu a fost găsit',
    4: 'Banner-ul nu a fost găsit (În momentul actual, prima captură de ecran este folosită ca banner)',
    5: 'Nicio modificare',
    6: 'Nu au fost găsite modificări',
    7: 'ID-ul nu a fost găsit',
    8: 'ID-ul videoclipului nu a fost găsit, încercați un alt link (momentan numai YouTube este suportat)',
    9: 'Ups',
    10: 'Se pare că sesiunea dvs. a expirat, deschideți o nouă pagină și conectați-vă la contul dvs. (nu vă faceți griji, totul este salvat automat)',
    11: 'Există',
    12: 'Acest videoclip a fost deja adăugat',
    13: 'Există',
    14: 'Această etichetă a fost deja adăugată',
    15: 'Nu a fost găsit',
    16: 'Nu se poate șterge o etichetă ștearsă',
    17: 'Adăugat',
    18: 'Ai adăugat cu succes o nouă etichetă',
    19: 'UUps',
    20: 'Acest creator a fost deja adăugat',
    21: 'EZ',
    22: 'Un nou creator a fost adăugat',
    23: 'HUH',
    24: 'Nu se poate elimina un creator șters',
    25: 'Există',
    26: 'Aceeași modificare cu acest tip a fost adăugată mai devreme',
    27: 'Atenție',
    28: 'Același Url de acest tip a fost adăugat mai devreme',
    29: 'Atenție',
    30: 'You forgot to add a description for a url. Example: Description:url',
    31: 'Atenție',
    32: 'You forgot to add a url for description. Example: Description:url',
    33: 'Restaurat',
    34: 'Versiunea {name} a fost restaurată',
    35: 'Ștearsă',
    36: 'Versiunea {name} a fost ștearsă',
    37: 'Eroare',
    38: 'Seems like the server thinks you\'re a bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Neautorizat',
    1: 'Te rugăm să te conectezi în cont',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};