export default {
  title: {
    home: 'Domovská stránka',
    login: 'Prihlásiť sa tu',
    lists: { 0: 'Zoznamy' },
    tags: {
      0: 'Štítky',
      1: '{amount} Značky pre kategóriu {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inšpirácia',
      1: '«{amount}»'
    },
    sounds: { 0: 'Zvuky' },
    leaderboard: { 0: 'Rebríčky' },
    extend: { 0: 'Viac | Menej' },
    skin: {
      0: 'Tento skin obsahuje prvky z iných skinov',
      1: 'Kliknite tu pre viac informácií'
    },
    tools: 'Nástroje'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Zoznam zmien',
    1: 'Zoznam všetkých vývojárov ktorí boli zapojení vo vývoji tejto verzie',
    2: 'Nikto tu nie je',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: 'Nezoskupené',
    5: 'Nové',
    6: 'Opravené',
    7: 'Zmenené',
    8: 'Odstránenia'
  },
  ideas: {
    0: 'Nič sa nenašlo',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Vývojári',
    1: 'Zoznam všetkých vývojárov ktorí boli zapojení vo vývoji tejto verzie',
    2: 'Nikto tu nieje',
    3: 'Hľadanie hráčskeho mena zobrazí list profilov.',
    4: 'Editor',
    5: 'Role',
    6: 'Verzie'
  },
  tags: {
    0: 'Štítky',
    1: 'List všetkých značiek súvisiacich s týmto skinom',
    2: 'Tu to vyzerá prázdno.',
    3: 'Použite horne pole pre nájdenie nových značok',
    4: 'Značky sa nenašli',
    5: 'Skús hľadať niečo inakšie',
    6: 'Hľadať'
  },
  videos: {
    0: 'Videa',
    1: 'List všetkých video ukážok pre tento skin',
    2: 'Žiadne ukážky',
    3: 'Nájdite nejaké na YouTube alebo vytvorte vlastnú ukážku'
  },
  sources: {
    0: 'Atribúcia',
    1: 'List všetkých použitých prvkov a nástrojov v tejto verzii skinu',
    2: 'Trochu prázdno tu',
    3: 'Ak ste použili prvky z iných skinov alebo obrazov, pridajte ich do boxu hore',
    4: 'Nezoskupené'
  },
  checks: {
    0: 'Všetko',
    1: 'Metadáta',
    2: 'Zvýraznenie',
    3: 'Meno Skinu ne je špecifikovan=',
    4: 'Pridajte aspoň jedného autora skinu',
    5: 'Pridajte pár značiek',
    6: 'Veľkosť skinu nie je špecifikovaná',
    7: 'Vyberte aspoň jeden herný mód',
    8: 'Vyberte typ skinu (SD alebo HD)',
    9: 'Vyberte najmenej jeden pomer strán',
    10: 'Žiadny snímok obrazovky',
    11: 'Pridajte aspoň jeden snímok obrazovky z hrania',
    12: 'Odkaz na skin nie je špecifikovaný',
    20: 'Vyzerá to dobre',
    21: 'Každá chyba bola opravená. Dobrá práca!',
    22: 'Kontrolná listina',
    23: 'Pridajte aspoň jednu publikovanú verziu',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Skiny',
    1: 'Populárne',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Aktuálne',
    5: 'Náhodne',
    6: 'Všetke skiny',
    7: 'Pomer stran',
    8: 'Všetke skiny | osu skiny',
    9: 'Skin | Skiny | Skinny',
    10: 'osu Skiny od {name} | Všetke skiny od',
    11: 'Hľadať',
    12: '{name} skiny',
    13: 'Vyhľadaj skiny'
  },
  skin: {
    0: 'Edit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Screenshots',
    6: 'Iba hrateľnosť',
    7: 'Link na stiahnutie | stahovací link',
    8: 'Skupinové zdieľania | osu! Skupina',
    9: 'Reddit príspevok',
    10: 'Vývojári',
    11: 'Štítky',
    13: 'Videa',
    14: 'Nová Verzia | Spravovacia verzia',
    15: 'Aktualizovať | Nahrať',
    16: 'Herne mody',
    17: 'Názov skinu',
    18: 'Verzia | Verzie',
    19: 'Velikost',
    20: 'Metadáta',
    21: 'Hodnotenie',
    22: 'Stiahnutie',
    23: 'Stiahnutie bude k dispozícii čoskoro',
    24: '{amount} Zostávajúce sekundy',
    25: 'Niesi jeden z nás',
    26: 'Zdá sa, že nie ste autorom ani editorom tohto skinu',
    27: 'Skin urobený od',
    28: 'Žiadne štítky',
    29: 'Žiadne videá',
    30: 'Žiadny stvoritelia',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted at {author} request',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!'
  },
  drag: {
    0: 'Klikni tu',
    1: 'Alebo sem presuňte obrázky'
  },
  footer: {
    0: 'Zrobil cyperdark',
    1: 'Kredit',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: 'Umenie',
    2: 'Ikony',
    3: 'Všetky ikony sú prevzaté z {name}',
    4: 'Vlajky',
    5: 'Všetke obrázky vlajok sú od {name}',
    6: 'Lokalizácia',
    7: 'Niekto? [{lang}]',
    8: 'Vyzerá to tak, že CK zabudol ich pridať. {text}'
  },
  search: {
    0: 'Vyhľadať skin',
    1: 'Pozretia',
    2: 'Nazov',
    3: 'Hodnotenie',
    4: 'Velikost',
    5: 'Dátum',
    7: 'Nič sa nenašlo',
    8: 'Skúste nastaviť iné filtre vyhľadávania',
    9: 'Čaká sa na dotaz',
    10: 'Použi vyhľadávacie filtre alebo verzie toho skinu alebo jeho názov, autora alebo štítky',
    11: 'Stiahnutie',
    12: 'Meno/Názov',
    13: {
      0: 'Skiny',
      1: 'Štítky',
      2: 'Users',
      3: 'Zoznamy'
    },
    14: 'Search:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished'
  },
  tabs: {
    0: 'Hľadať',
    1: 'Edit',
    2: 'Zoznam'
  },
  undefined: {
    0: 'Prázdny',
    1: 'Bohužiaľ tu nič nie je, každopádne si môžete pozrieť iné stránky',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Neoprávnené',
    4: 'Ak chcete upraviť tento skin, musíte byť prihlásený.',
    5: 'Musíš byť prihlásený na to, aby si pridal nový skin.'
  },
  meta: {
    title: {
      0: 'Nájdi osu! skiny',
      1: 'Herné režimy, pomery strán osu skinov',
      2: 'Populárne osu skiny',
      3: 'Vyhľadajte osu skiny',
      4: 'Zoznam značiek, {name}',
      5: '{name} v{version} osu skin',
      6: 'Kredit',
      7: 'osu skiny',
      8: '{name} vyhľadaj osu skiny',
      9: 'Získaj inšpiráciu z ostatných osu! skinov',
      10: '{name} výrobca osu skinou',
      11: 'Search tags',
      12: '{name} najdené štítky',
      13: 'Novy skin',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! Contests'
    },
    description: {
      0: 'Získajte najlepšie osu! skiny na našej stránke! Naša obrovská knižnica má skiny pre všetke herné režimy, pomery strán a dokonca aj pre špičkových hráčov. Navyše máme špeciálnu sekciu pre fanúšikov anime. Zlepšite svoju hru s dokonalým vzhľadom. #osuskins #osugame #anime',
      1: '{views} Zobrazenia. osu skin pre {modes}, veľkosť je {size}, vytvoril {creators}. Podporuje {ratios}',
      2: 'Nájdite dokonali osu! skin s našou funkciou rozšíreného vyhľadávania. Pozrite si našu obrovskú knižnicu filtrovanú podľa herného režimu, pomeru strán a ďalších. Alebo si pozrite skiny používané špičkovými hráčmi.',
      3: 'Objavte na našej stránke rôzne skiny pre rôzne herné režimy a pomery strán. Vyberte si zo štandardných režimov, zachyťte rytmus, mánie a režimy taiko. Nájdite to, čo dokonale vyhovuje vašim herným preferenciám.',
      4: 'Nájdite dokonalý osu skin od najlepších hráčov na našej stránke. Pozrite si našu kolekciu obľúbených skinou a prispôsobte si svoju hru. Objavte širokú škálu štýlov a tém, ktoré vyhovujú vašim preferenciám.',
      5: 'Zoznam existujúcich značiek pre osu skiny.',
      6: '{name} kolekcia osu skinov!, bezplatné stiahnutie',
      7: 'Obrovské množstvo osu skinov pre {name}, stiahnite si zadarmo!',
      8: 'Všetke osu skiny vytvoril {name}',
      9: 'Nájdite inšpiráciu pre svoje ďalšie osu! skiny na našej stránke. Pozrite si rozmanitú kolekciu vzhľadov a objavte nové techniky a nápady. Nechajte sa inšpirovať a vytvorte si vlastné jedinečné skiny.',
      10: 'Vyhľadávaj pre štítky všade v štítkoch na tejto stránke.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: 'Login',
    1: 'Domovská stránka',
    profile_osu: 'osu! Profile',
    new_skin: 'Novy skin',
    notifications: 'Oznámenia',
    settings: 'Nastavenia',
    logout: 'Odhlásiť sa',
    load_more: 'Načítať viac',
    copy_short: 'Skopírovať krátky link',
    copied: 'Skopírované',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Späť na skin',
    source: 'Source',
    contest_voting: 'Vote here'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: 'Tvorca',
      1: 'Mixer',
      2: 'Animácie',
      3: 'Umenie',
      4: 'Spolupráca'
    }
  },
  tooltips: {
    0: 'Zobrazenia: {amount}',
    1: 'Obnoviť výsledky',
    2: 'Klesajúci | Stúpajúci',
    3: 'Obľúbene: {likes} / Zlé: {dislikes}',
    4: 'Stlačte ctrl+enter pre pridanie označenia',
    5: 'Upraviť verziu',
    6: '{s}Prihláste sa{p}, aby ste mohli ohodnotiť tento skin',
    7: 'Žiadny krátky popis',
    8: 'Žiadne URL',
    9: 'Stiahnuté bolo: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)'
  },
  lists: {
    screens: {
      0: 'Vitaj',
      1: 'Hlavné menu',
      2: 'Vyber pesničky',
      3: 'Menu mody',
      4: 'Mody',
      5: 'Odpočet',
      6: 'Hra',
      7: 'Spinner',
      8: 'Sekcia dokončenia',
      9: 'Sekcia nedokončená',
      10: 'Obrazovka Pauzy',
      11: 'Obrazovka prehrania',
      12: 'Obrazovka výsledkov',
      13: 'Preskočiť',
      14: 'Banner',
      15: 'Result screen (bottom)'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Zmiešané'
    }
  },
  select: {
    0: 'Nové',
    1: 'Opravené',
    2: 'Zmenené',
    3: 'Odstránené',
    4: 'Obrázky',
    5: 'Font',
    6: 'Umelec',
    7: 'Elementy skinu',
    8: 'Audio/Sfx',
    9: 'Nástroje',
    views: 'Pozretia',
    likes: 'Obľúbene',
    dislikes: 'Zlé',
    downloads: 'Stiahnutie',
    size_range: 'Vyber velikosti',
    date_range: 'Vyber časového obdobia',
    ratio: 'Vyber pomer stran | pomer'
  },
  placeholders: {
    0: 'Vyberte rolu',
    1: 'Vyberte verziu',
    2: 'Sem napíšte text...',
    3: 'Vyber velikosti',
    4: 'Výber časového obdobia',
    5: 'Rok',
    6: 'Mesiac',
    7: 'Vyber pomer stran',
    8: 'Vyberte kategóriu',
    9: 'Herne mody',
    10: 'Vložte typ',
    11: 'Vložte Youtube odkaz',
    12: 'Zadajte popis a url. Popis formátu:url',
    13: 'Výber extra',
    14: 'Vložte link',
    15: 'Názov skinu, autora, alebo označenie',
    16: 'Vyberte kategóriu',
    17: 'Napíš meno štítku'
  },
  contribute: { 0: 'Prispievanie' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: 'Tento skin obsahuje senzitívny obsah alebo kontent 18+',
    2: 'Tento skin obsahuje senzitívny obsah alebo kontent 18+, ktorý môžu nejaký ľudia nájsť hnusné',
    3: 'V poriadku!',
    4: 'čau o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Služba je nedostupná',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation',
    52: 'Warning',
    53: 'You need to choose type of asset'
  },
  header: {
    0: 'Oznámenia',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Neoprávnené',
    1: 'Prihláste sa na svoj účet',
    2: 'Zakázaný pohľad',
    3: 'Tato stránka ešte není na internete, zatiaľ.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No'
  }
};