export default {
  title: {
    home: 'Почетна',
    login: 'Пријави се',
    lists: { 0: 'Листе' },
    tags: {
      0: 'Ознаке',
      1: '{amount} ознаке ѕа категорију {name}',
      2: 'Претражи ознаке'
    },
    ideas: {
      0: 'Инспирација',
      1: '«{amount}»'
    },
    sounds: { 0: 'Звуци' },
    leaderboard: { 0: 'Табеле' },
    extend: { 0: 'Више | Мање' },
    skin: {
      0: 'Овај скин садржи елементе из других скинова',
      1: 'Кликни овде за више информација'
    },
    tools: 'Алатке'
  },
  home: {
    0: 'Доступно за преузимање',
    1: 'Највише: _name_ скинова',
    2: 'Погледано | Свиђања | Преузето',
    3: 'Објавите нови скин',
    4: 'Како инсталирати скин'
  },
  changelogs: {
    0: 'Списак измена',
    1: 'Списак свих ревизија урађених у тренутној верзији',
    2: 'Овде нема ничега',
    3: 'Али можете додати измене које сте направили овој верзији скина',
    4: 'Није груписано',
    5: 'Ново',
    6: 'Поправљено',
    7: 'Промене',
    8: 'Уклањања'
  },
  ideas: {
    0: 'Nothing found',
    1: 'Снимци екрана «{type}» нису отпремљени на сајт'
  },
  creators: {
    0: 'Креатори',
    1: 'Прикажи све креаторе који су учествовали у изради ове верзије',
    2: 'Овде нема никога',
    3: 'Тражење имена играча ће приказати листу профила.',
    4: 'Уредник',
    5: 'Улоге',
    6: 'Верзије'
  },
  tags: {
    0: 'Ознаке',
    1: 'Листа свих ознака повезаних са овим скином',
    2: 'Овде изгледа прилично празно.',
    3: 'Користите поље изнад да пронађете нове ознаке',
    4: 'Ознаке нису пронађене',
    5: 'Покушајте да потражите нешто друго',
    6: 'Претражи'
  },
  videos: {
    0: 'Видеа',
    1: 'Листа свих видео изложба за овај скин',
    2: 'Нема изложба',
    3: 'Потражите неке на YouTube-у или направите своју сопствену изложбу'
  },
  sources: {
    0: 'Средства',
    1: 'Листа свих коришћених средстава или алата у овој верзији скина',
    2: 'Некако празно овде',
    3: 'Ако сте користили средства из других скинова или уметности, обавезно их додајте у оквир изнад',
    4: 'Није груписано'
  },
  checks: {
    0: 'Све',
    1: 'Метаподаци',
    2: 'Истакните текст',
    3: 'Назив скина није наведен',
    4: 'Додај најмање једног креатора скина',
    5: 'Додај неколико ознака',
    6: 'Величина скина није наведена',
    7: 'Одабери најмање један gamemode',
    8: 'Изабери резолуцију слике (SD или HD)',
    9: 'Изабери најмање један однос резолуције',
    10: 'Нема отпремљених слика екрана',
    11: 'Add at least one gameplay screenshot',
    12: 'Link to the skin not specified',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Checklist',
    23: 'Add at least one public version',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Скинови',
    1: 'Популарно',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Скорашње',
    5: 'Насумично',
    6: 'Сви скинови',
    7: 'Размера слике',
    8: 'Сви скинови | osu! скинови',
    9: 'Скин | Скинови | Скинови',
    10: 'osu Skins by {name} | All skins from',
    11: 'Претражи',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Edit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Aнимација',
    5: 'Screenshots',
    6: 'Gameplay only',
    7: 'Download link | Download skin',
    8: 'Forum post | osu! Forum',
    9: 'Reddit пост',
    10: 'Креатори',
    11: 'Ознаке',
    13: 'Видеа',
    14: 'New Version | Manage versions',
    15: 'Update | Submit',
    16: 'Мод игре',
    17: 'Name of the skin',
    18: 'Version | Versions',
    19: 'Величина',
    20: 'Метаподаци',
    21: 'Rating',
    22: 'Downloads',
    23: 'Download will be available soon',
    24: '{amount} seconds left',
    25: 'You\'re not one of us',
    26: 'Seems like you\'re not an author or editor of this skin',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin'
  },
  drag: {
    0: 'Click here',
    1: 'or drag & drop images here'
  },
  footer: {
    0: 'Made by cyperdark',
    1: 'Credits'
  },
  credits: {
    0: 'Chibi',
    1: 'Arts',
    2: 'Icons',
    3: 'All icons are taken from {name}',
    4: 'Flags',
    5: 'All flag images are from {name}',
    6: 'Localisation',
    7: 'Anyone? [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Skin search',
    1: 'Views',
    2: 'Title',
    3: 'Rating',
    4: 'Величина',
    5: 'Date',
    7: 'Nothing found',
    8: 'Try using different search filters',
    9: 'Pending a query',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'Downloads',
    12: 'Name',
    13: {
      0: 'Скинови',
      1: 'Ознаке',
      2: 'Users',
      3: 'Листе'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Претражи',
    1: 'Edit',
    2: 'List'
  },
  undefined: {
    0: 'Empty',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Unauthorized',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'Gamemodes, aspect ratios osu skins',
      2: 'Popular osu skins',
      3: 'Search osu skins',
      4: 'List of tags, {name}',
      5: '{name} v{version} osu skin',
      6: 'Credits',
      7: 'osu skins',
      8: '{name} search osu skins',
      9: 'Get inspiration from other osu skins',
      10: '{name} created osu skins',
      11: 'Претражи ознаке',
      12: '{name} found tags',
      13: 'Нови скин'
    },
    description: {
      0: 'Get the best osu! skins at our site! Our huge library has skins for all gamemodes, aspect ratios and even top players. Plus, we have a special section for anime fans. Improve your gameplay with the perfect skin. #osuskins #osugame #anime',
      1: '{views} views. An osu skin for {modes}, the size is {size}, created by {creators}. Supports {ratios}',
      2: 'Find the perfect osu! skin with our advanced search feature. Browse through our huge library, filtered by gamemode, aspect ratio, and more. Or, check out skins used by top players.',
      3: 'Discover a variety of skins for different game modes and aspect ratios on our site. Choose from standard, catch the beat, mania, and taiko modes. Find the perfect fit for your gaming preferences.',
      4: 'Find the perfect osu skin from top players on our site. Browse our collection of popular skins and customize your gameplay. Discover a wide range of styles and themes to suit your preferences.',
      5: 'List of existing tags for osu skins.',
      6: '{name} osu skins collection!, free downloading',
      7: 'A huge amount of osu skins for {name}, download for free!',
      8: 'All osu skins created by {name}',
      9: 'Find inspiration for your next osu! skin at our site. Browse through a diverse collection of skins and discover new techniques and ideas. Get inspired and create your own unique skins.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Пријави се',
    1: 'Почетна',
    profile_osu: 'osu! Профил',
    new_skin: 'Нови скин',
    notifications: 'Обавештења',
    settings: 'Подешавања',
    logout: 'Одјави се',
    load_more: 'Учитај још',
    copy_short: 'Копирај кратки линк',
    copied: 'Копирано',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Назад на скин'
  },
  user: {
    roles: {
      0: 'Креатор',
      1: 'Миксер',
      2: 'Анимације',
      3: 'Arts',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Прегледи: {amount}',
    1: 'Освежи резултате',
    2: 'Смањење | Подизање',
    3: 'Лајкови: {likes} / Дислајкови: {dislikes}',
    4: 'Притисните ctrl+enter да додате ознаку',
    5: 'Измени верзију',
    6: '{s}Пријави се{p}, да бисте оценили овај скин',
    7: 'Нема кратког описа',
    8: 'Нема линка',
    9: 'Преузимања: {amount}'
  },
  lists: {
    screens: {
      0: 'Добродошли',
      1: 'Главни мени',
      2: 'Избор песме',
      3: 'Mode menu',
      4: 'Модови',
      5: 'Одбројавање',
      6: 'Gameplay',
      7: 'Спинер',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Екран за Паузу',
      11: 'Екран за Губитак',
      12: 'Екран за Резултат',
      13: 'Прескочи',
      14: 'Банер'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Мешано'
    }
  },
  select: {
    0: 'Ново',
    1: 'Поправљено',
    2: 'Промењено',
    3: 'Уклоњено',
    4: 'Уметност',
    5: 'Фонт',
    6: 'Артист',
    7: 'Skin element',
    8: 'Audio/Sfx',
    9: 'Алатке',
    views: 'Views',
    likes: 'Свиђања',
    dislikes: 'Несвиђања',
    downloads: 'Downloads',
    size_range: 'Select size',
    date_range: 'Select a date range',
    ratio: 'Select aspect ratio | ratio'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Select size',
    4: 'Select date range',
    5: 'Година',
    6: 'Месец',
    7: 'Select aspect ratio',
    8: 'Select categories',
    9: 'Мод игре',
    10: 'Select type',
    11: 'Paste a YouTube link',
    12: 'Type a description and an url. Format description:url',
    13: 'Select extra',
    14: 'Paste a link',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Упозорење!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'У реду',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Прикажи',
    3: 'Није пронађено',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'Нема промена',
    6: 'No changes were found',
    7: 'ID није пронађен',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Није пронађено',
    16: 'You cannot delete a deleted tag',
    17: 'Додато',
    18: 'You have successfully added a new tag',
    19: 'Упс',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Упозорење',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Упозорење',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Обрисано',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Успешно',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'Овај линк се не може користити као линк за преузимање',
    51: 'Предато на преглед'
  },
  header: {
    0: 'Обавештења',
    1: 'Пратите нас на овим платформама да бисте добијали обавештења о новим скиновима'
  },
  restricted_view: {
    0: 'Unauthorized',
    1: 'Молимо да се пријавите на свој налог',
    2: 'Ограничен приказ',
    3: 'Ова страница још није изашла.'
  }
};