export default {
  title: {
    home: 'Startsida',
    login: 'Logga in',
    lists: { 0: 'Listor' },
    tags: {
      0: 'Taggar',
      1: '{amount} taggar för kategorier {name}',
      2: 'Sök taggar'
    },
    ideas: {
      0: 'Inspiration',
      1: '«{amount}»'
    },
    sounds: { 0: 'Ljud' },
    leaderboard: { 0: 'Topplistor' },
    extend: { 0: 'Mer | Mindre' },
    skin: {
      0: 'Det här skinnet innehåller element från andra skins',
      1: 'Klicka här för mer information'
    },
    tools: 'Verktyg'
  },
  home: {
    0: 'Tillgänglig för nedladdning',
    1: 'Mest: _name_skins',
    2: 'Visningar | Gillar | Nerladdade',
    3: 'Publicera nytt skin',
    4: 'Hur man installerar skin'
  },
  changelogs: {
    0: 'Ändringslogg',
    1: 'Lista av alla revisioner gjorda i den nuvarande versionen',
    2: 'Ingenting här',
    3: 'Men du kan lägga till de ändringar som du har gjort i denna version av skinnet',
    4: 'Inte grupperad',
    5: 'Nytt',
    6: 'Fixningar',
    7: 'Ändringar',
    8: 'Tar bort'
  },
  ideas: {
    0: 'Ingenting hittat',
    1: 'Skärmdumpar av «{type}» laddades inte upp till webbsidan'
  },
  creators: {
    0: 'Skapare',
    1: 'Lista av alla skapare som var inblandade i skapandet av den här versionen',
    2: 'Ingen är här',
    3: 'Att söka efter en spelares namn kommer att visa en lista med profiler.',
    4: 'Redigerare',
    5: 'Roller',
    6: 'Versioner'
  },
  tags: {
    0: 'Taggar',
    1: 'Lista över alla taggar relaterade till detta skin',
    2: 'Det verkar ganska tomt här.',
    3: 'Använd fältet ovanför att hitta nya taggar',
    4: 'Taggar hittades inte',
    5: 'Prova att söka efter något annat',
    6: 'Sök efter'
  },
  videos: {
    0: 'Videor',
    1: 'Lista av alla video showcases för skinnet',
    2: 'Noll showcases',
    3: 'Sök efter några på YouTube eller skapa din egna showcase'
  },
  sources: {
    0: 'Tillskrivning',
    1: 'Lista av alla resurser och verktyg använda i den här versionen av skinnet',
    2: 'Ganska tomt här',
    3: 'Om du har använt resurser från andra skins eller konstverk, var snäll att lägga till dem i fältet ovanför',
    4: 'Inte grupperad'
  },
  checks: {
    0: 'Alla',
    1: 'Metadata',
    2: 'Höjdpunkt',
    3: 'Inget namn angivet på skinnet',
    4: 'Lägg till åtminstone en skin skapare',
    5: 'Lägg till ett par taggar',
    6: 'Storleken av skinnet är inte specificerad',
    7: 'Välj åtminstone ett spelläge',
    8: 'Välj filtyp (SD eller HD)',
    9: 'Välj åtminstone ett bildförhållande',
    10: 'Inga skärmbilder är uppladdade',
    11: 'Lägg till minst en skärmdump av spelet',
    12: 'Länk till skin ej angiven',
    20: 'Ser ganska bra ut',
    21: 'Varje problem har blivit fixat. Bra jobbat!',
    22: 'Checklista',
    23: 'Lägg till minst en offentlig version',
    24: 'Lägg till minst en skapare till denna version',
    25: 'Vissa skapare har inga roller'
  },
  skins: {
    0: 'Skins',
    1: 'Populärt',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Senaste',
    5: 'Slumpmässigt',
    6: 'Alla skins',
    7: 'Bildförhållande',
    8: 'Alla skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins av {name} | Alla skins från',
    11: 'Sök efter',
    12: '{name} skins',
    13: 'Utforska Skins'
  },
  skin: {
    0: 'Edit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Skärmbilder',
    6: 'Enbart gameplay',
    7: 'Nedladdningslänk | Ladda ner skinn',
    8: 'Forum inlägg | osu! Forum',
    9: 'Reddit inlägg',
    10: 'Skapare',
    11: 'Taggar',
    13: 'Videor',
    14: 'Ny Version | Hantera versioner',
    15: 'Uppdatera | Lämna in',
    16: 'Spellägen',
    17: 'Skinnets namn',
    18: 'Version | Versioner',
    19: 'Storlek',
    20: 'Metadata',
    21: 'Betyg',
    22: 'Nedladdningar',
    23: 'Nedladdningen kommer vara tillgänglig snart',
    24: '{amount} sekunder kvar',
    25: 'Du är inte en av oss',
    26: 'Verkar som om du inte är en författare eller redaktör för detta skinn',
    27: 'Skin av',
    28: 'Inga taggar',
    29: 'Inga videor',
    30: 'Inga skapare',
    31: 'Betygsätt skin',
    32: 'Upprösta och kommentera på reddit',
    33: 'Kommentera på osu! forumet',
    34: 'Fler skins från denna författare | Fler skins från dessa författare',
    35: 'Support the skin'
  },
  drag: {
    0: 'Klicka här',
    1: 'eller dra & droppa bilder'
  },
  footer: {
    0: 'Gjord av Cyperdark',
    1: 'Cred'
  },
  credits: {
    0: 'Chibi',
    1: 'Konstverk',
    2: 'Ikoner',
    3: 'Alla ikoner är tagna från {name}',
    4: 'Flaggor',
    5: 'Alla flagga bilder är från {name}',
    6: 'Språk',
    7: 'Någon? [{lang}]',
    8: 'Verkar som cyperdark glömde att lägga till dem. {text}'
  },
  search: {
    0: 'Skin sökning',
    1: 'Visningar',
    2: 'Titel',
    3: 'Betyg',
    4: 'Storlek',
    5: 'Datum',
    7: 'Ingenting hittat',
    8: 'Prova att använda olika sökfilter',
    9: 'Väntar på en sökning',
    10: 'Använd sökfiltren eller skriv in skinnets titel, författare eller taggar',
    11: 'Nedladdningar',
    12: 'Namn',
    13: {
      0: 'Skins',
      1: 'Taggar',
      2: 'Användare',
      3: 'Listor'
    }
  },
  tabs: {
    0: 'Sök efter',
    1: 'Edit',
    2: 'Lista'
  },
  undefined: {
    0: 'Tomt',
    1: 'Tyvärr finns det inget här, men du kan ta en titt på de andra sidorna',
    2: 'Tyvärr finns det inget här',
    3: 'Obehörig',
    4: 'Du måste vara inloggad för att kunna redigera detta skin.',
    5: 'Du måste vara inloggad för att kunna lägga till ett nytt skin.'
  },
  meta: {
    title: {
      0: 'Utforska osu! skins',
      1: 'Spellägen, bildförhållanden osu skins',
      2: 'Populära osu skins',
      3: 'Sök efter osu skins',
      4: 'Lista över taggar, {name}',
      5: '{name} v{version} osu skin',
      6: 'Cred',
      7: 'osu skins',
      8: '{name} sök efter osu skins',
      9: 'Få inspiration från andra osu! skins',
      10: '{name} skapade osu skins',
      11: 'Sök taggar',
      12: '{name} hittade taggar'
    },
    description: {
      0: 'Få det bästa osu! skinnen på våran sida! Vårat stora urval innehåller skinn för alla spellägen, bildförhållanden, och även toppspelare. Plus, vi har även en special avdelning för anime fans. Förbättra ditt gameplay med det perfekta skinnet. #osuskins #osugame #anime',
      1: '{views} visningar. Ett osu skin för {modes}, storleken är {size}, skapad av {creators}. Stödjer {ratios}',
      2: 'Hitta det perfekta osu! skinnet med våran avancerade sökfunktion. Bläddra genom vårat enorma urval, filtrerat på spelläge, bildförhållande, och mer. Eller, titta på skins använda av toppspelare.',
      3: 'Hitta en varierad mängd spellägen och bildförhållanden på våran sida. Välj mellan standard läge, catch the beat, mania, and taiko. Hitta den perfekta passningen för dina spel preferenser.',
      4: 'Hitta det perfekta osu! skinnet från toppspelare på våran sida. Bläddra genom våran samling av populära skins och anpassa ditt gameplay. Hitta en varierad mängd av stilar and teman som passar dina preferenser.',
      5: 'Lista av existerande tags för osu skins.',
      6: '{name} osu skins samling!, gratis nedladdning',
      7: 'En enorm mängd av osu skins för {name}, ladda ner gratis!',
      8: 'Alla osu skins skapade av {name}',
      9: 'Hitta inspiration för ditt nästa osu! skin på vår sida. Sök genom en varierad samling av skins och hitta nya tekniker och idéer. Bli inspirerad och skapa dina egna unika skins.',
      10: 'Sök efter taggar bland alla taggar på webbplatsen.'
    }
  },
  buttons: {
    0: 'Logga in',
    1: 'Startsida',
    profile_osu: 'osu! Profil',
    new_skin: 'Nytt skin',
    notifications: 'Notiser',
    settings: 'Inställningar',
    logout: 'Logga ut',
    load_more: 'Ladda mer',
    copy_short: 'Kopiera kortlänk',
    copied: 'Kopierad',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Tillbaka till skin'
  },
  user: {
    roles: {
      0: 'Skapare',
      1: 'Mixer',
      2: 'Animationer',
      3: 'Konstverk',
      4: 'Samarbete'
    }
  },
  tooltips: {
    0: 'Visningar: {amount}',
    1: 'Uppdatera resultat',
    2: 'Ner | Upp',
    3: 'Gillar: {likes} / Ogillar: {dislikes}',
    4: 'Tryck på ctrl+enter för att lägga till en tag',
    5: 'Redigera version',
    6: '{s}Logga in{p}, för att betygsätta detta skin',
    7: 'Ingen kort beskrivning',
    8: 'Ingen url',
    9: 'Nedladdningar: {amount}'
  },
  lists: {
    screens: {
      0: 'Välkommen',
      1: 'Huvudmeny',
      2: 'Välj låt',
      3: 'Läge meny',
      4: 'Mods',
      5: 'Nedräkning',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Avdelning Pass',
      9: 'Avdelning Fail',
      10: 'Pausskärm',
      11: 'Failskärm',
      12: 'Resultatskärm',
      13: 'Skippa',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Blandad'
    }
  },
  select: {
    0: 'Nytt',
    1: 'Fixad',
    2: 'Ändrad',
    3: 'Borttagen',
    4: 'Konst',
    5: 'Font',
    6: 'Artist',
    7: 'Skin element',
    8: 'Ljud/Sfx',
    9: 'Verktyg',
    views: 'Visningar',
    likes: 'Likes',
    dislikes: 'Ogillar',
    downloads: 'Nedladdningar',
    size_range: 'Välj storlek',
    date_range: 'Välj ett datumspann',
    ratio: 'Välj bildförhållande | förhållande'
  },
  placeholders: {
    0: 'Välj roller',
    1: 'Välj versioner',
    2: 'Skriv in text...',
    3: 'Välj storlek',
    4: 'Välj datumspann',
    5: 'År',
    6: 'Månad',
    7: 'Välj bildförhållande',
    8: 'Välj kategorier',
    9: 'Spellägen',
    10: 'Välj typ',
    11: 'Klistra in en YouTube länk',
    12: 'Skriv en beskrivning och en webbadress. Format description:url',
    13: 'Välj extra',
    14: 'Klistra in en länk',
    15: 'Skin titel, författare eller taggar',
    16: 'Välj kategori',
    17: 'Skriv namnet på taggen'
  },
  contribute: { 0: 'Bidra' },
  nsfw: {
    0: 'Varning!',
    1: 'Denna skin innehåller känsligt eller vuxet innehåll',
    2: 'Denna skin innehåller känslig eller vuxen innehåll som vissa användare kan hitta störande',
    3: 'Okej',
    4: 'Hejdå o/'
  },
  removed: {
    0: 'Version ej tillgänglig',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Problemen har inte blivit fixat',
    1: 'Not all required fields were filled',
    2: 'Visa',
    3: 'Hittades inte',
    4: 'Banner hittades inte (För nu används den första skärmdumpen som banner)',
    5: 'Inga ändringar',
    6: 'Inga ändringar hittades',
    7: 'ID hittades inte',
    8: 'ID för videon hittades inte, prova en annan länk (Just nu stöds endast YouTube)',
    9: 'Hoppsan',
    10: 'Ser ut som din session har gått ut, öppna en ny sida och logga in på ditt konto (oroa dig inte, allting sparades automatiskt)',
    11: 'Existerar',
    12: 'Denna video har redan lagts till',
    13: 'Existerar',
    14: 'Denna tagg har redan lagts till',
    15: 'Hittades inte',
    16: 'Du kan inte ta bort en raderad tagg',
    17: 'Tillagd',
    18: 'Du har lagt till en ny tagg',
    19: 'Hoppsan',
    20: 'Skaparen har redan lagts till',
    21: 'EZ',
    22: 'Ny profil har lagts till',
    23: 'VA',
    24: 'Omöjligt att ta bort en raderad skapare',
    25: 'Duplicera',
    26: 'Denna ändring har redan lagts till tidigare.',
    27: 'Duplicera',
    28: 'Denna URL har redan lagts till tidigare.',
    29: 'Varning',
    30: 'Du glömde att lägga till en beskrivning för webbadressen. Exempel: Description:url',
    31: 'Varning',
    32: 'Du glömde att lägga till en URL för beskrivningen. Exempel: Description:url',
    33: 'Återställt',
    34: 'Version «{name}» har återställts',
    35: 'Raderad',
    36: 'Version «{name}» har raderats',
    37: 'Error',
    38: 'Uppenbarligen tror servern att du är en robot.',
    39: 'Ser ut som din användarsession har gått ut, öppna en ny sida och logga in på ditt konto (oroa dig inte, allting sparades automatiskt)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Okänt fel',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'Du kan inte skicka denna version eftersom det är samma som den föregående.',
    45: 'Dessa ändringar har redan skickats för moderering',
    46: 'Klart!',
    47: 'Nya ändringar har lämnats in för moderering',
    48: 'Ändringar har uppdaterats med moderering',
    49: 'Konstig länk',
    50: 'Denna länk kan inte användas som en nedladdningslänk',
    51: 'Skickad till moderering'
  },
  restricted_view: {
    0: 'Obehörig',
    1: 'Vänligen logga in på ditt konto',
    2: 'Begränsad visning',
    3: 'Den här sidan är inte ute, än.'
  }
};