export default {
  title: {
    home: 'Startsida',
    login: 'Log in',
    lists: { 0: 'Listor' },
    tags: {
      0: 'Taggar',
      1: '{amount} taggar för kategorier {name}',
      2: 'Search tags'
    },
    ideas: {
      0: 'Inspiration',
      1: '«{amount}»'
    },
    sounds: { 0: 'Ljud' },
    leaderboard: { 0: 'Topplistor' },
    extend: { 0: 'Mer | Mindre' },
    skin: {
      0: 'Det här skinnet innehåller element från andra skins',
      1: 'Klicka här för mer information'
    },
    tools: 'Verktyg'
  },
  changelogs: {
    0: 'Ändringslogg',
    1: 'Lista av alla revisioner gjorda i den nuvarande versionen',
    2: 'Ingenting här',
    3: 'Men du kan lägga till ändringarna du gjorde till den här versionen av skinnet',
    4: 'Inte grupperad',
    5: 'Nytt',
    6: 'Fixningar',
    7: 'Ändringar',
    8: 'Tar bort'
  },
  ideas: {
    0: 'Ingenting hittat',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Skapare',
    1: 'Lista av alla skapare som var inblandade i skapandet av den här versionen',
    2: 'Ingen är här',
    3: 'Searching for a player\'s name will display a list of profiles.',
    4: 'Redigerare',
    5: 'Roller',
    6: 'Versioner'
  },
  tags: {
    0: 'Taggar',
    1: 'Lista över alla taggar relaterade till detta skin',
    2: 'Det verkar ganska tomt här.',
    3: 'Använd fältet ovanför att hitta nya taggar',
    4: 'Tags not found',
    5: 'Try searching for something else',
    6: 'Sök efter'
  },
  videos: {
    0: 'Videor',
    1: 'Lista av alla video showcases för skinnet',
    2: 'Noll showcases',
    3: 'Sök efter några på YouTube eller skapa din egna showcase'
  },
  sources: {
    0: 'Tillskrivning',
    1: 'Lista av alla resurser och verktyg använda i den här versionen av skinnet',
    2: 'Ganska tomt här',
    3: 'Om du har använt resurser från andra skins eller konstverk, var snäll att lägga till dem i fältet ovanför',
    4: 'Inte grupperad'
  },
  checks: {
    0: 'Alla',
    1: 'Metadata',
    2: 'Höjdpunkt',
    3: 'Name of the skin not specified',
    4: 'Lägg till åtminstone en skin skapare',
    5: 'Lägg till ett par taggar',
    6: 'Storleken av skinnet är inte specificerad',
    7: 'Välj åtminstone ett spelläge',
    8: 'Välj filtyp (SD eller HD)',
    9: 'Välj åtminstone ett bildförhållande',
    10: 'Inga skärmbilder är uppladdade',
    11: 'Lägg till minst en skärmdump av spelet',
    12: 'Länk till skin ej angiven',
    20: 'Ser bra ut',
    21: 'Alla problem blev fixade, vilket är ganska bra',
    22: 'Checklista',
    23: 'Add at least one public version'
  },
  skins: {
    0: 'Skins',
    1: 'Populärt',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Senaste',
    5: 'Slumpmässigt',
    6: 'Alla skins',
    7: 'Bildförhållande',
    8: 'Alla skins | osu skins',
    9: 'Skin | Skins | Skins',
    10: 'osu Skins av {name} | Alla skins från',
    11: 'Sök efter',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Edit',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animation',
    5: 'Skärmbilder',
    6: 'Enbart gameplay',
    7: 'Nedladdningslänk | Ladda ner skinn',
    8: 'Forum post | osu! Forum',
    9: 'Reddit inlägg',
    10: 'Skapare',
    11: 'Taggar',
    13: 'Videor',
    14: 'Ny Version | Hantera versioner',
    15: 'Uppdatera | Lämna in',
    16: 'Spellägen',
    17: 'Skinnets namn',
    18: 'Version | Versioner',
    19: 'Storlek',
    20: 'Metadata',
    21: 'Betyg',
    22: 'Nedladdningar',
    23: 'Nedladdningen kommer vara tillgänglig snart',
    24: '{amount} sekunder kvar',
    25: 'Du är inte en av oss',
    26: 'Verkar som om du inte är en författare eller redaktör för detta skinn',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Klicka här',
    1: 'eller dra & droppa bilder'
  },
  footer: {
    0: 'Gjord av Cyperdark',
    1: 'Cred'
  },
  credits: {
    0: 'Chibi',
    1: 'Konstverk',
    2: 'Ikoner',
    3: 'Alla ikoner är tagna från {name}',
    4: 'Flaggor',
    5: 'Alla flagga bilder är från {name}',
    6: 'Localisation',
    7: 'Anyone? [{lang}]',
    8: 'Seems like, cpol forget to add them. {text}'
  },
  search: {
    0: 'Skin sökning',
    1: 'Visningar',
    2: 'Titel',
    3: 'Betyg',
    4: 'Storlek',
    5: 'Datum',
    7: 'Ingenting hittat',
    8: 'Prova att ange olika sökfilter',
    9: 'Väntar på en sökning',
    10: 'Välj sökfilter eller skriv bara skintiteln, författaren eller taggen',
    11: 'Nedladdningar',
    12: 'Name',
    13: {
      0: 'Skins',
      1: 'Taggar',
      2: 'Users',
      3: 'Listor'
    }
  },
  tabs: {
    0: 'Sök efter',
    1: 'Edit',
    2: 'Lista'
  },
  undefined: {
    0: 'Tomt',
    1: 'Sorgligen nog finns det ingenting här, iallafall kan du titta på andra sidor',
    2: 'Sorgligen nog finns det ingenting här',
    3: 'Obehörig',
    4: 'Du måste vara inloggad för att kunna redigera detta skin.',
    5: 'You need to be logged in to add a new skin.'
  },
  meta: {
    title: {
      0: 'Discover osu skins',
      1: 'Spellägen, bildförhållanden osu skins',
      2: 'Populära osu skins',
      3: 'Sök efter osu skins',
      4: 'Lista över taggar, {name}',
      5: '{name} v{version} osu skin',
      6: 'Cred',
      7: 'osu skins',
      8: '{name} sök efter osu skins',
      9: 'Get inspiration from other osu skins',
      10: '{name} skapade osu skins',
      11: 'Search tags',
      12: '{name} found tags'
    },
    description: {
      0: 'Få det bästa osu! skinnen på våran sida! Vårat stora urval innehåller skinn för alla spellägen, bildförhållanden, och även toppspelare. Plus, vi har även en special avdelning för anime fans. Förbättra ditt gameplay med det perfekta skinnet. #osuskins #osugame #anime',
      1: '{views} visningar. Ett osu skin för {modes}, storleken är {size}, skapad av {creators}. Stödjer {ratios}',
      2: 'Hitta det perfekta osu! skinnet med våran avancerade sökfunktion. Bläddra genom vårat enorma urval, filtrerat på spelläge, bildförhållande, och mer. Eller, titta på skins använda av toppspelare.',
      3: 'Hitta en varierad mängd spellägen och bildförhållanden på våran sida. Välj mellan standard läge, catch the beat, mania, and taiko. Hitta den perfekta passningen för dina spel preferenser.',
      4: 'Hitta det perfekta osu! skinnet från toppspelare på våran sida. Bläddra genom våran samling av populära skins och anpassa ditt gameplay. Hitta en varierad mängd av stilar and teman som passar dina preferenser.',
      5: 'Lista av existerande tags för osu skins.',
      6: '{name} osu skins samling!, gratis nedladdning',
      7: 'En enorm mängd av osu skins för {name}, ladda ner gratis!',
      8: 'Alla osu skins skapade av {name}',
      9: 'Hitta inspiration för ditt nästa osu! skin på vår sida. Sök genom en varierad samling av skins och hitta nya tekniker och idéer. Bli inspirerad och skapa dina egna unika skins.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Logga in',
    1: 'Startsida',
    profile_osu: 'osu! Profil',
    new_skin: 'Nytt skin',
    notifications: 'Notiser',
    settings: 'Inställningar',
    logout: 'Logga ut',
    load_more: 'Ladda mer',
    copy_short: 'Kopiera kortlänk',
    copied: 'Kopierad',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Tillbaka till skin'
  },
  user: {
    roles: {
      0: 'Skapare',
      1: 'Mixer',
      2: 'Animationer',
      3: 'Konstverk',
      4: 'Samarbete'
    }
  },
  tooltips: {
    0: 'Views: {amount}',
    1: 'Uppdatera resultat',
    2: 'Ner | Upp',
    3: 'Likes: {likes} / Dislikes: {dislikes}',
    4: 'Tryck på ctrl+enter för att lägga till en tag',
    5: 'Redigera version',
    6: '{s}Logga in{p}, för att kunna betygsätta det här skinnet',
    7: 'Ingen kort beskrivning',
    8: 'Ingen url',
    9: 'Downloads: {amount}'
  },
  lists: {
    screens: {
      0: 'Välkommen',
      1: 'Huvudmeny',
      2: 'Välj låt',
      3: 'Läge meny',
      4: 'Mods',
      5: 'Nedräkning',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Avdelning Pass',
      9: 'Avdelning Fail',
      10: 'Pausskärm',
      11: 'Failskärm',
      12: 'Resultatskärm',
      13: 'Skippa',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Blandad'
    }
  },
  select: {
    0: 'Nytt',
    1: 'Fixad',
    2: 'Ändrad',
    3: 'Borttagen',
    4: 'Konst',
    5: 'Font',
    6: 'Artist',
    7: 'Skin element',
    8: 'Ljud/Sfx',
    9: 'Verktyg',
    views: 'Visningar',
    likes: 'Likes',
    dislikes: 'Dislikes',
    downloads: 'Nedladdningar',
    size_range: 'Välj storlek',
    date_range: 'Välj ett datumspann',
    ratio: 'Välj bildförhållande | förhållande'
  },
  placeholders: {
    0: 'Välj roller',
    1: 'Välj versioner',
    2: 'Skriv text...',
    3: 'Välj storlek',
    4: 'Välj datumspann',
    5: 'År',
    6: 'Månad',
    7: 'Välj bildförhållande',
    8: 'Välj kategorier',
    9: 'Spellägen',
    10: 'Välj typ',
    11: 'Klistra in en YouTube länk',
    12: 'Skriv beskrivning och url. Format beskrivning:url',
    13: 'Välj extra',
    14: 'Klistra in en länk',
    15: 'Skin titel, skapare eller tag',
    16: 'Select category',
    17: 'Type name of the tag'
  },
  contribute: { 0: 'Contribute' },
  nsfw: {
    0: 'Warning!',
    1: 'This skin contains sensitive or adult content',
    2: 'This skin contains sensitive or adult content that some users may find disturbing',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Version unavailable',
    1: 'Author of the skin decided to remove this version from the site.',
    2: 'Switch to available version'
  },
  notify: {
    0: 'Issues not fixed',
    1: 'Not all required fields was filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Exists',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forget to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forget to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like server thinks you\'re the bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Obehörig',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};