export default {
  title: {
    home: 'Ana',
    login: 'Giriş yap',
    lists: { 0: 'Listeler' },
    tags: {
      0: 'Etiketler',
      1: '{name} kategorisi için {amount} sonuç bulundu',
      2: 'Etiket arayın'
    },
    ideas: {
      0: 'İlham',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sesler' },
    leaderboard: { 0: 'Sıralama' },
    extend: { 0: 'Genişlet | Daralt' },
    skin: {
      0: 'Bu skin içinde diğer skinlerden elemntler barındırıyor',
      1: 'Daha fazla bilgi için buraya tıklayın'
    },
    tools: 'Toollar'
  },
  changelogs: {
    0: 'Güncelleme geçmişi',
    1: 'Güncel versiyondaki yapılan tüm değişikliklerin listesi',
    2: 'Burada hiçbir şey yok',
    3: 'But you can add the changes you made\'ve to this version of the skin',
    4: 'Gruplandırılmamış',
    5: 'Yeni',
    6: 'Düzeltmeler',
    7: 'Değişiklikler',
    8: 'Silinenler'
  },
  ideas: {
    0: 'Hiçbir şey bulunamadı',
    1: 'Screenshots of «{type}» were not uploaded to the site'
  },
  creators: {
    0: 'Yaratıcılar',
    1: 'Bu versiyonu oluşturmakta emeği geçenlerin listesi',
    2: 'Burada kimse yok',
    3: 'Bir oyuncunun ismini aratmak bir profil listesi görütüler.',
    4: 'Editör',
    5: 'Roller',
    6: 'Versiyonlar'
  },
  tags: {
    0: 'Etiketler',
    1: 'Bu skinle bağlantılı tüm etiketlerin listesi',
    2: 'Burası bayağı bi boş gözüküyor.',
    3: 'Yeni etiketler bulmak için yukarıdaki alanı kullanın',
    4: 'Etiket Bulunamadı',
    5: 'Başka bir şey aramayı dene',
    6: 'Ara'
  },
  videos: {
    0: 'Videolar',
    1: 'Bu skin için sergilenen tüm videoların listesi',
    2: 'Sergilenecek video yok',
    3: 'YouTube\'da arayın ya da kendi video\'nuzu oluşturun'
  },
  sources: {
    0: 'Özellikler',
    1: 'Skinde kullanılan tüm assetlerin ve toolların listesi',
    2: 'Burası bir tık boş kalmış',
    3: 'Eğer diğer skinlerden asset ya da resim kullandıysanız, yukarıdaki kutucuğa eklediğinizden emin olun',
    4: 'Gruplandırılmamış'
  },
  checks: {
    0: 'Hepsi',
    1: 'Metadata',
    2: 'Hightlight',
    3: 'Skin ismi belirtilmemiş',
    4: 'Skini oluşturan en az bir kişi ekleyin',
    5: 'Birkaç etiket ekleyin',
    6: 'Skinin boyutu belirtilmemiş',
    7: 'En az bir oyun modu seçin',
    8: 'Görsel çözünürlüğü seçin (SD ya da HD)',
    9: 'En az bir çerçeve oranı seçin',
    10: 'Ekran görüntüsü sağlanamıyor',
    11: 'En az bir oynanış görüntüsü ekleyin',
    12: 'Skin linki belirtilmemiş',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: 'Kontrol listesi',
    23: 'Herkese açık en az bir versiyon ekleyin'
  },
  skins: {
    0: 'Skinler',
    1: 'Popüler',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'En yeni',
    5: 'Rastgele',
    6: 'Tüm skinler',
    7: 'Çerçeve Oranı',
    8: 'Tüm skinler | osu skinleri',
    9: 'Skin | Skins | Skins',
    10: '{name} tarafıdan yapılan skinler | All skins from',
    11: 'Ara',
    12: '{name} skins',
    13: 'Explore skins'
  },
  skin: {
    0: 'Düzenle',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasyon',
    5: 'Ekran görüntüleri',
    6: 'Sadece Gameplay',
    7: 'İndirme linki | skini indir',
    8: 'Forum post | osu! Forum',
    9: 'Reddit postu',
    10: 'Yaratıcılar',
    11: 'Etiketler',
    13: 'Videolar',
    14: 'Yeni versiyon | Versiyonları düzenle',
    15: 'Güncelle | Gönder',
    16: 'Oyun modları',
    17: 'Skinin adı',
    18: 'Versiyon | Versiyonlar',
    19: 'Boyut',
    20: 'Metadata',
    21: 'Rating',
    22: 'İndirmeler',
    23: 'En kısa zamanda indirmeye açılacak',
    24: '{amount} saniye kaldı',
    25: 'Bizden biri değişsin',
    26: 'Görünüşe göre bu skinin yaratıcısı ya da editörü değilsin',
    27: 'Skini oluşturan',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators'
  },
  drag: {
    0: 'Buraya tıklayın',
    1: 'ya da resimleri buraya sürükleyin ve bırakın'
  },
  footer: {
    0: 'cyperdark tarafından yapıldı',
    1: 'Credits'
  },
  credits: {
    0: 'Chibi',
    1: 'Resimler',
    2: 'İkonlar',
    3: 'Bütün ikonlar {name}\'den alındı',
    4: 'Bayraklar',
    5: 'Bütün bayrak görselleri {name}\'dan alındı',
    6: 'Yerelleştirme',
    7: 'Herhangi birisi? [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: 'Skin aratın',
    1: 'Görüntülenme',
    2: 'Başlık',
    3: 'Rating',
    4: 'Boyut',
    5: 'Tarih',
    7: 'Hiçbir şey bulunamadı',
    8: 'Try using different search filters',
    9: 'Arama bekleniyor',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: 'İndirmeler',
    12: 'İsim',
    13: {
      0: 'Skinler',
      1: 'Etiketler',
      2: 'Users',
      3: 'Listeler'
    }
  },
  tabs: {
    0: 'Ara',
    1: 'Düzenle',
    2: 'Liste'
  },
  undefined: {
    0: 'Boş',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: 'Yetkiniz yok',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  meta: {
    title: {
      0: 'osu skinlerini keşfet',
      1: 'Oyun modları, çerçeve oranları osu skinleri',
      2: 'Populer osu skinleri',
      3: 'Osu skinleri arayın',
      4: 'Etiketlerin listesi, {name}',
      5: '{name} v{version} osu skin',
      6: 'Credits',
      7: 'osu skins',
      8: '{name} search osu skins',
      9: 'Diğer osu skinlerinden ilham alın',
      10: '{name} created osu skins',
      11: 'Etiket arayın',
      12: '{name} found tags'
    },
    description: {
      0: 'Sitemizden en iyi osu! skinlerini edinin! Devasa kütüphanemizde tüm oyunmodlarına, çerçeve oranlarına hatta top playerlara ilişkin skinler bulabilirsin. Artı olarak anime fanlarına yönelik bi bölümümüz daha var. Mükemmel skininle birlikte oyununu bir adım ileri taşı. #osuskins #osugame #anime',
      1: '{views} görüntülenme. {modes} yönelik bir osu skini , his weight is {size}, {creators} tarafından yaratıldı. Şu çerçeve oranlarını destekler: {ratios}',
      2: 'Gelişmiş arama özelliğimiz sayesinde mükemmel osu! skinini bulun. Devasa kütüphanemizi oyun modlarına, çerçeve oranlarına ve daha fazlasıyla filtereleyek tarayın. Ya da top playerlar tarafından kullanılan skinlere göz atın',
      3: 'Sitemizde farklı oyun modları ve çerçeve oranları için çeşitli skinler keşfedin. Standart, catch the beat, mania ve taiko modlarından istediğinizi seçin ve oyun tercihlerinize en uygun olanı bulun.',
      4: 'Sitemizde en iyi oyuncuların da kullandığı mükemmel skininizi bulun. Popüler skin koleksiyonumuza göz atın ve oyununuzu kişiselleştirin. Çok çeşitli stil ve temalardan tercihlerinize uygun olanları keşfedin.',
      5: 'osu skinleri için etiketlerin bir listesi.',
      6: '{name} osu skins collection!, free downloading',
      7: 'A huge amount of osu skins for {name}, download for free!',
      8: 'All osu skins created by {name}',
      9: 'Sitemizde bir sonraki osu! skininin için ilham kaynağı bul. Çeşitli koleksiyonumuza göz atın ve yeni teknikler, fikirler edinin. İlham alarak kendinize özgün skinler yaratın.',
      10: 'Search for tags among all the tags on the site.'
    }
  },
  buttons: {
    0: 'Giriş',
    1: 'Ana sayfa',
    profile_osu: 'osu! Profili',
    new_skin: 'Yeni skin',
    notifications: 'Bildirimler',
    settings: 'Ayarlar',
    logout: 'Çıkış yapın',
    load_more: 'Daha fazla yükle',
    copy_short: 'Linki kopyala',
    copied: 'Kopyalandı!',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Skine dön'
  },
  user: {
    roles: {
      0: 'Yaratıcı',
      1: 'Mixer',
      2: 'Animasyonlar',
      3: 'Resimler',
      4: 'Katılımcı'
    }
  },
  tooltips: {
    0: 'Görüntülenme: {amount}',
    1: 'Sonuçları yeniden yükle',
    2: 'Aşağı doğru artan | Azalan',
    3: 'Beğeni: {likes} / Beğenmeme: {dislikes}',
    4: 'Etiket eklemek için ctrl+enter basın',
    5: 'Edit version',
    6: '{s}Log in{p}, in order to rate this skin',
    7: 'Kısa açıklama bulunamadı',
    8: 'Url bulunamadı',
    9: 'İndirmeler: {amount}'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Ane menü',
      2: 'Song select',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Countdown',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pause Screen',
      11: 'Fail Screen',
      12: 'Result screen',
      13: 'Skip',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Yeni',
    1: 'Düzeltildi',
    2: 'Değiştirildi',
    3: 'Silindi',
    4: 'Resim',
    5: 'Font',
    6: 'Artist',
    7: 'Skin element',
    8: 'Audio/Sfx',
    9: 'Toollar',
    views: 'Görüntülenme',
    likes: 'Beğeni',
    dislikes: 'Beğenmeme',
    downloads: 'İndirmeler',
    size_range: 'Boyut seçin',
    date_range: 'Tarih aralığı seçin',
    ratio: 'Çerçeve oranı seçin | ratio'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Boyut seçin',
    4: 'Tarih aralığı seçin',
    5: 'Yıl',
    6: 'Ay',
    7: 'Ekran oranı seçin',
    8: 'Kategorileri seçin',
    9: 'Oyun modları',
    10: 'Tür seçin',
    11: 'YouTube bağlantısını yapıştırın',
    12: 'Type a description and an url. Format description:url',
    13: 'Select extra',
    14: 'Link yapıştırın',
    15: 'Skin title, author, or tags',
    16: 'Kategori seçin',
    17: 'Type the name of the tag'
  },
  contribute: { 0: 'Katkıda bulunun' },
  nsfw: {
    0: 'Uyarı!',
    1: 'Bu skin hassas veya yetişkinlere yönelik içerik barındırıyor',
    2: 'Bu skin rahatsız olabileceğiniz hassas veya yetişkinlere yönelik içerik barındırıyor',
    3: 'Alright',
    4: 'bye o/'
  },
  removed: {
    0: 'Sürüm mevcut değil',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Göster',
    3: 'Bulunamadı',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID bulunamadı',
    8: 'Videonun ID\'si bulunamadı, başka bir link deneyin (Sadece YouTube destekleniyor)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Mevcut',
    12: 'Bu video çoktan eklendi',
    13: 'Mevcut',
    14: 'Bu etiket çoktan eklendi',
    15: 'Bulunamadı',
    16: 'You cannot delete a deleted tag',
    17: 'Eklendi',
    18: 'Başarıyla yeni bir etiket eklediniz',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Looks like your user session has expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation'
  },
  restricted_view: {
    0: 'Yetkiniz yok',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};