export default {
  title: {
    home: 'Ana ekran',
    login: 'Giriş yap',
    lists: { 0: 'Listeler' },
    tags: {
      0: 'Etiketler',
      1: '{name} kategorisi için {amount} sonuç bulundu',
      2: 'Etiket arayın'
    },
    ideas: {
      0: 'Keşfet',
      1: '«{amount}»'
    },
    sounds: { 0: 'Sesler' },
    leaderboard: { 0: 'Sıralama' },
    extend: { 0: 'Genişlet | Daralt' },
    skin: {
      0: 'Bu skin içinde diğer skinlerden elemntler barındırıyor',
      1: 'Daha fazla bilgi için buraya tıklayın'
    },
    tools: 'Toollar'
  },
  home: {
    0: 'İndirilebilir',
    1: 'En fazla: _name_ skinleri',
    2: 'Görüntülendi | Beğenildi | İndirildi',
    3: 'Yeni bir skin yayınla',
    4: 'Skin nasıl indirilir',
    5: '{amount} Skin | {amount} Skin | {amount} Skin'
  },
  changelogs: {
    0: 'Güncelleme geçmişi',
    1: 'Güncel versiyondaki yapılan tüm değişikliklerin listesi',
    2: 'Burada hiçbir şey yok',
    3: 'Ama skinin bu versiyonuna yaptığınız değişiklikleri ekleyebilirsiniz',
    4: 'Gruplandırılmamış',
    5: 'Yeni',
    6: 'Düzeltmeler',
    7: 'Değişiklikler',
    8: 'Silinenler'
  },
  ideas: {
    0: 'Hiçbir şey bulunamadı',
    1: '«{type}» ekran görüntüleri siteye yüklenmemiş',
    2: '«{amount}» {name}'
  },
  creators: {
    0: 'Yaratıcılar',
    1: 'Bu versiyonu oluşturmakta emeği geçenlerin listesi',
    2: 'Burada kimse yok',
    3: 'Bir oyuncunun ismini aratmak bir profil listesi görütüler.',
    4: 'Editör',
    5: 'Roller',
    6: 'Versiyonlar'
  },
  tags: {
    0: 'Etiketler',
    1: 'Bu skinle bağlantılı tüm etiketlerin listesi',
    2: 'Burası bayağı bi boş gözüküyor.',
    3: 'Yeni etiketler bulmak için yukarıdaki alanı kullanın',
    4: 'Etiket Bulunamadı',
    5: 'Başka bir şey aramayı dene',
    6: 'Ara'
  },
  videos: {
    0: 'Videolar',
    1: 'Bu skin için sergilenen tüm videoların listesi',
    2: 'Sergilenecek video yok',
    3: 'YouTube\'da arayın ya da kendi video\'nuzu oluşturun'
  },
  sources: {
    0: 'Özellikler',
    1: 'Skinde kullanılan tüm assetlerin ve toolların listesi',
    2: 'Burası bir tık boş kalmış',
    3: 'Eğer diğer skinlerden asset ya da resim kullandıysanız, yukarıdaki kutucuğa eklediğinizden emin olun',
    4: 'Gruplandırılmamış'
  },
  checks: {
    0: 'Hepsi',
    1: 'Metadata',
    2: 'Hightlight',
    3: 'Skin ismi belirtilmemiş',
    4: 'Skini oluşturan en az bir kişi ekleyin',
    5: 'Birkaç etiket ekleyin',
    6: 'Skinin boyutu belirtilmemiş',
    // 7: 'Select at least one gamemode',
    8: 'Görsel çözünürlüğü seçin (SD ya da HD)',
    9: 'En az bir çerçeve oranı seçin',
    10: 'Ekran görüntüsü sağlanamıyor',
    11: 'En az bir oynanış görüntüsü ekleyin',
    12: 'Skin linki belirtilmemiş',
    20: 'Gayet iyi görünüyor',
    21: 'İyi haber! Hiçbir problem kalmadı!',
    22: 'Kontrol listesi',
    23: 'Herkese açık en az bir versiyon ekleyin',
    24: 'Bu versiyona en az bir yaratıcı ekle',
    25: 'Bazı yaratıcıların rolleri yok',
    26: '{amount} sayıda ekran görüntüsünün kategorisi yok',
    28: 'Oynanış ekran görüntüleri için oyun modunu seçin'
  },
  skins: {
    0: 'Skinler',
    1: 'Popüler',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'En yeni',
    5: 'Rastgele',
    6: 'Tüm skinler',
    7: 'Çerçeve Oranı',
    8: 'Tüm skinler | osu skinleri',
    9: 'Skin | Skins | Skins',
    10: '{name} tarafıdan yapılan skinler | All skins from',
    11: 'Ara',
    12: '{name} skinleri',
    13: 'Skinleri keşfet',
    14: 'Popüler skinler'
  },
  skin: {
    0: 'Düzenle',
    1: 'Ekstra',
    2: 'HD',
    3: 'FullHD',
    4: 'Animasyon',
    5: 'Ekran görüntüleri',
    6: 'Sadece Gameplay',
    7: 'İndirme linki | skini indir',
    8: 'Forum post | osu! Forum',
    9: 'Reddit postu',
    10: 'Yaratıcılar',
    11: 'Etiketler',
    13: 'Videolar',
    14: 'Yeni versiyon | Versiyonları düzenle',
    15: 'Güncelle | Gönder',
    16: 'Oyun modları',
    17: 'Skinin adı',
    18: 'Versiyon | Versiyonlar',
    19: 'Boyut',
    20: 'Metadata',
    21: 'Rating',
    22: 'İndirmeler',
    23: 'En kısa zamanda indirmeye açılacak',
    24: '{amount} saniye kaldı',
    25: 'Bizden biri değişsin',
    26: 'Görünüşe göre bu skinin yaratıcısı ya da editörü değilsin',
    27: 'Skini oluşturan',
    28: 'Etiket yok',
    29: 'Video yok',
    30: 'Yaratıcı yok',
    31: 'Skini değerlendir',
    32: 'Redditte upvote at ve yorum yap',
    33: 'osu! forumunda yorum yap',
    34: 'Bu yaratıcının diğer skinleri',
    35: 'Skini destekle',
    36: 'Mevcut değil',
    37: 'Ne yazık ki, bu skin silinmiş',
    38: 'Skin editörüne hoş geldiniz!',
    39: `Skin editörüne yeni misiniz? Arayüzde size rehberlik etmemize ve editörün tüm potansiyelini göstermemize izin verin!`,
    40: '{current} dan {max} kadarı tamamlandı',
    41: 'Daha sonra kontrol edin',
    42: `Haydi başlayalım`,
    43: 'Tebrikler!',
    44: 'Öğreticiyi başarıyla tamamladınız, iyi eğlenceler!',
    45: 'yükleyici'
  },
  drag: {
    0: 'Buraya tıklayın',
    1: 'ya da resimleri buraya sürükleyin ve bırakın'
  },
  footer: {
    0: 'cyperdark tarafından yapıldı',
    1: 'Credits',
    2: 'Kurallar',
    3: 'Kişiler'
  },
  credits: {
    0: 'Chibi',
    1: 'Resimler',
    2: 'İkonlar',
    3: 'Bütün ikonlar {name}\'den alındı',
    4: 'Bayraklar',
    5: 'Bütün bayrak görselleri {name}\'dan alındı',
    6: 'Yerelleştirme',
    7: 'Herhangi birisi? [{lang}]',
    8: 'Görünüşe göre cyperdark bunları eklemeyi unutmuş. {text}'
  },
  search: {
    0: 'Skin aratın',
    1: 'Görüntülenme',
    2: 'Başlık',
    3: 'Rating',
    4: 'Boyut',
    5: 'Tarih',
    7: 'Hiçbir şey bulunamadı',
    8: 'Farklı arama filtreleriyle aramayı deneyin',
    9: 'Arama bekleniyor',
    10: 'Arama filtresi, yaratıcı, etiketler ya da skinin başlığını kullanın',
    11: 'İndirmeler',
    12: 'İsim',
    13: {
      0: 'Skinler',
      1: 'Etiketler',
      2: 'Kullanıcılar',
      3: 'Listeler'
    },
    14: 'Ara:',
    15: 'Boyut:',
    16: 'Derecelendirme:',
    17: 'Görüntülenme:',
    18: 'İndirmeler:'
  },
  contests: {
    0: 'Yarışmalar',
    1: 'Resmi haber gönderisi',
    2: 'Başvuru',
    3: 'Hazırlanıyor',
    4: 'Oylama',
    5: 'Bitti',
    6: 'Yarışmalar',
    7: 'Oylama sayfası'
  },
  rules: {
    0: 'Son güncelleme',
    1: 'Skin Paylaşım Kuralları'
  },
  skinini: {
    0: 'Skin.ini editörüne hoş geldiniz!',
    1: `Skin.ini editörüne yeni misiniz? Arayüzde size rehberlik etmemize ve editörün tüm potansiyelini göstermemize izin verin!`,
    2: '{current} dan {max} kadarı tamamlandı',
    3: 'Sonuç yok',
    4: 'Arama teriminiz yazım hatası içeriyor olabilir'
  },
  tabs: {
    0: 'Ara',
    1: 'Düzenle',
    2: 'Liste'
  },
  undefined: {
    0: 'Boş',
    1: 'Ne yazık ki burada bir şey bulamadık yine de diğer sayafalara göz atmak isteyebilirsin',
    2: 'Ne yazık ki burada hiçbir şey yok',
    3: 'Yetkiniz yok',
    4: 'Bu skini düzenleyebilmek için önce giriş yapman gerekli.',
    5: 'Yeni bir skin eklemek için giriş yapmış olmanız gerekiyor.'
  },
  settings: {
    0: 'Ayarlar',
    1: 'Mouse scroll',
    2: 'Soldan sağa veya sağdan sola gezinmeye izin vererek resim karuseli için fareyle kaydırmayı etkinleştirin.',
    3: 'Yakınlaştır',
    4: 'Daha büyük skin önizlemesi için üzerine gelindiğinde görüntü yakınlaştırmayı etkinleştirin.'
  },
  meta: {
    title: {
      0: 'osu skinlerini keşfet',
      1: 'Oyun modları, çerçeve oranları osu skinleri',
      2: 'Populer osu skinleri',
      3: 'Osu skinleri arayın',
      4: 'Etiketlerin listesi, {name}',
      5: '{name} v{version} osu skin',
      6: 'Credits',
      7: 'osu skins',
      8: '{name} search osu skins',
      9: 'Diğer osu skinlerinden ilham alın',
      10: '{name} created osu skins',
      11: 'Etiket arayın',
      12: '{name} bulunan etiketler',
      13: 'Yeni skin',
      14: 'Site kuralları',
      15: 'osu! Yarışmaları',
      16: 'osu! skin oluşturma araçları'
    },
    description: {
      0: 'Sitemizden en iyi osu! skinlerini edinin! Devasa kütüphanemizde tüm oyunmodlarına, çerçeve oranlarına hatta top playerlara ilişkin skinler bulabilirsin. Artı olarak anime fanlarına yönelik bi bölümümüz daha var. Mükemmel skininle birlikte oyununu bir adım ileri taşı. #osuskins #osugame #anime',
      1: '{views} görüntülenme. {modes} yönelik bir osu skini , his weight is {size}, {creators} tarafından yaratıldı. Şu çerçeve oranlarını destekler: {ratios}',
      2: 'Gelişmiş arama özelliğimiz sayesinde mükemmel osu! skinini bulun. Devasa kütüphanemizi oyun modlarına, çerçeve oranlarına ve daha fazlasıyla filtereleyek tarayın. Ya da top playerlar tarafından kullanılan skinlere göz atın',
      3: 'Sitemizde farklı oyun modları ve çerçeve oranları için çeşitli skinler keşfedin. Standart, catch the beat, mania ve taiko modlarından istediğinizi seçin ve oyun tercihlerinize en uygun olanı bulun.',
      4: 'Sitemizde en iyi oyuncuların da kullandığı mükemmel skininizi bulun. Popüler skin koleksiyonumuza göz atın ve oyununuzu kişiselleştirin. Çok çeşitli stil ve temalardan tercihlerinize uygun olanları keşfedin.',
      5: 'osu skinleri için etiketlerin bir listesi.',
      6: '{name} osu skins collection!, free downloading',
      7: 'A huge amount of osu skins for {name}, download for free!',
      8: 'All osu skins created by {name}',
      9: 'Sitemizde bir sonraki osu! skininin için ilham kaynağı bul. Çeşitli koleksiyonumuza göz atın ve yeni teknikler, fikirler edinin. İlham alarak kendinize özgün skinler yaratın.',
      10: 'Site içerisindeki etiketler arasından birini arayın.',
      11: 'Tüm aktif/bitmiş osu! yarışmalarının listesi',
      12: '{title} yarışmasına {amount} sayıda giriş. {views} görüntülenme'
    }
  },
  buttons: {
    0: 'Giriş',
    1: 'Ana sayfa',
    profile_osu: 'osu! Profili',
    new_skin: 'Yeni skin',
    notifications: 'Bildirimler',
    settings: 'Ayarlar',
    logout: 'Çıkış yapın',
    load_more: 'Daha fazla yükle',
    copy_short: 'Linki kopyala',
    copied: 'Kopyalandı!',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Skine dön',
    source: 'Kaynak',
    contest_voting: 'Burdan oy ver',
    rules_agree: 'Katılıyorum',
    report_issue: 'Sorun bildir',
    ghost_creator: 'Hayalet yaratıcı',
    close: 'Kapat',
    quick_select: 'Hızlı Seçim'
  },
  choose: {
    0: 'İsteğe bağlı',
    1: 'Gerekli',
    2: 'En az bir seçenek seçin'
  },
  user: {
    roles: {
      0: 'Yaratıcı',
      1: 'Mixer',
      2: 'Animasyonlar',
      3: 'Resimler',
      4: 'Katılımcı',
      5: 'Sesler',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: 'Görüntülenme: {amount}',
    1: 'Sonuçları yeniden yükle',
    2: 'Aşağı doğru artan | Azalan',
    3: 'Beğeni: {likes} / Beğenmeme: {dislikes}',
    4: 'Etiket eklemek için ctrl+enter basın',
    5: 'Edit version',
    6: 'Skini değerlendirebilmek için {s}Giriş yap{p}',
    7: 'Kısa açıklama bulunamadı',
    8: 'Url bulunamadı',
    9: 'İndirmeler: {amount}',
    10: 'Her şeyi sıfırla',
    11: 'Kılavuzu göster',
    12: 'Kılavuzu kapat',
    13: 'Bir kuralı okundu olarak işaretlemek için üzerine gelin (Sarı okunmadığını gösterir)',
    14: {
      0: '[hl]{example}[/hl] - [b]eşittir[/b] {amount}',
      1: '[hl]{example}[/hl] - [b]büyüktür[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]küçüktür[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Seçimi Kaldır',
    16: 'Dosyayı kaldır'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Ane menü',
      2: 'Song select',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Countdown',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pause Screen',
      11: 'Fail Screen',
      12: 'Result screen (yukarı)',
      13: 'Skip',
      14: 'Banner',
      15: 'Sonuç ekranı (altta)',
      16: 'Başlangıç resmi'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Yeni',
    1: 'Düzeltildi',
    2: 'Değiştirildi',
    3: 'Silindi',
    4: 'Resim',
    5: 'Font',
    6: 'Artist',
    7: 'Skin element',
    8: 'Audio/Sfx',
    9: 'Toollar',
    10: 'Resim',
    views: 'Görüntülenme',
    likes: 'Beğeni',
    dislikes: 'Beğenmeme',
    downloads: 'İndirmeler',
    ratio: 'Çerçeve oranı seçin | ratio',
    sorting: 'Yüks. | Azal.'
  },
  sorting: {
    0: 'En çok | En az',
    1: 'En çok | En az',
    2: 'En yüksek | En düşük',
    3: 'En büyük | En küçük',
    4: 'En yeni | En eski',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Rol seç',
    1: 'Sürüm seç',
    2: 'Bir metin girin...',
    3: 'Boyut aralığı seçin',
    4: 'Tarih aralığı seçin',
    5: 'Yıl',
    6: 'Ay',
    7: 'Ekran oranı seçin',
    8: 'Kategorileri seçin',
    9: 'Oyun modları',
    10: 'Tür seçin',
    11: 'YouTube bağlantısını yapıştırın',
    12: 'Bir açıklama yazın ve url ekleyin. Format açıklama:url',
    13: 'Select extra',
    14: 'Link yapıştırın',
    15: 'Skinin adı, yaratıcısı ya da etiketi',
    16: 'Kategori seçin',
    17: 'Etiketin ismini yazın',
    18: 'Skinin ismini yazın',
    19: 'Yapımcı adını yazın',
    20: 'Dosya seçin',
    24: 'Oynanış adı yazın...',
    25: 'Aralık girin',
    26: 'Metin yazın'
  },
  contribute: { 0: 'Katkıda bulunun' },
  nsfw: {
    0: 'Uyarı, nsfw!',
    1: 'Bu skin hassas veya yetişkinlere yönelik içerik barındırıyor',
    2: 'Bu skin rahatsız olabileceğiniz hassas veya yetişkinlere yönelik içerik barındırıyor',
    3: 'Anladım',
    4: 'güle güle o/',
    5: 'Uyarı, furry!'
  },
  removed: {
    0: 'Sürüm mevcut değil',
    1: 'Skinin yaratıcısı bu versiyonu siteden kaldırmaya karar verdi.',
    2: 'Mevcut bir versiyona geç'
  },
  notify: {
    0: 'Sorunlar çözülemedi',
    1: 'Gerekli boşlukların tamamı doldurulmadı',
    2: 'Göster',
    3: 'Bulunamadı',
    4: 'Banner bulunamadı (Şuan, ilk ekran görüntüsü banner olarak kullanılıyor)',
    5: 'Değişiklik yok',
    6: 'Herhangi bir değişiklik bulunamadı',
    7: 'ID bulunamadı',
    8: 'Videonun ID\'si bulunamadı, başka bir link deneyin (Sadece YouTube destekleniyor)',
    9: 'Hay aksi',
    10: 'Görünüşe göre oturumunuzun süresi doldu, yeni bir sayfa açın ve hesabınıza giriş yapın (Endişelenmeyin, her şey otomatik olarak kaydedildi)',
    11: 'Mevcut',
    12: 'Bu video çoktan eklendi',
    13: 'Mevcut',
    14: 'Bu etiket çoktan eklendi',
    15: 'Bulunamadı',
    16: 'Silinmiş bir etiketi silemezsin',
    17: 'Eklendi',
    18: 'Başarıyla yeni bir etiket eklediniz',
    19: 'Hay aksi',
    20: 'Bu yaratıcı zaten eklenmiş',
    21: 'EZ',
    22: 'Yeni bir yaratıcı eklendi',
    23: 'HUH',
    24: 'Silinmiş bir yaratıcıyı tekrar silemezsin',
    25: 'Uyarı',
    26: 'Bu değişiklik zaten eklenmiş.',
    27: 'Uyarı',
    28: 'Bu url zaten eklenmiş.',
    29: 'Uyarı',
    30: 'Url için bir açıklama eklemeyi unuttun. Örnek: Açıklama:url',
    31: 'Uyarı',
    32: 'Açıklama için bir url eklemeyi unuttun. Örnek: Açıklama:url',
    33: 'Geri yüklendi',
    34: '«{name}» versiyonu geri yüklendi',
    35: 'Silindi',
    36: '«{name}» versiyonu silinmiş',
    37: 'Hata',
    38: 'Görüşüne göre sunucu sizin bir robot olduğunuza kanaat getirmiş.',
    39: 'Mevcut giriş oturumunuz zaman aşımına uğradı. Devam etmek için lütfen yeni bir sayfa açın ve hesabınıza tekrar giriş yapın. Bunu yaptıktan sonra bu sayfaya dönün ve tekrar deneyin.',
    40: 'Kimlik bilgileri uyuşmuyor (Hesabınıza tekrar giriş yapın. Merak etmene gerek yok, her şey otomatik olarak kaydedildi)',
    41: 'Bilinmeyen hata',
    42: 'Var olmayan bir skinde değişiklik yapamazsın',
    43: 'Görünüşe göre bu skinde değişiklik yapma iznin yok',
    44: 'Öncekiyle aynı olduğu için bu versiyonu gönderemezsin.',
    45: 'Bu değişiklikler zaten moderasyon için gönderilmiş',
    46: 'Başarılı',
    47: 'Moderasyon için yeni değişiklikler başarıyla gönderildi',
    48: 'Değişiklikler kontrollü olarak güncellendi',
    49: 'Garip link',
    50: 'Bu link bir indirme bağlantısı olarak kullanılamaz',
    51: 'Moderasyon için gönderildi',
    52: 'Uyarı',
    53: 'Asset türünü seçmeniz gerekir',
    54: 'Skin şu anda moderasyon altında. Lütfen işlenirken sabırlı olun',
    55: 'Başarılı',
    56: 'Yeni hayalet yaratıcı eklendi',
    57: 'Renk kopyalandı',
    58: `RGB kodu "{color}" şimdi panonuz aracılığıyla kullanılabilir!`
  },
  header: {
    0: 'Bildirimler',
    1: 'Yeni skinler hakkında bildirim almak için bu platformlarda bizi takip edin'
  },
  restricted_view: {
    0: 'Yetkiniz yok',
    1: 'Lütfen hesabınızda oturum açın',
    2: 'Kısıtlı görüntüleme',
    3: 'Bu sayfa henüz hazır değil.'
  },
  confirm: {
    0: 'Her şeyi sıfırla?',
    1: 'Kılavuzu göster?',
    2: 'Skin gönder?',
    3: 'Evet',
    4: 'Hayır',
    5: '.ini yi resetle?'
  }
};