export default {
  title: {
    home: 'Trang chủ',
    login: 'Đăng nhập',
    lists: { 0: 'Danh sách' },
    tags: {
      0: 'Các Tag',
      1: '{amount} tag của nhóm {name}',
      2: 'Tìm tag'
    },
    ideas: {
      0: 'Cảm Hứng',
      1: '«{amount}»'
    },
    sounds: { 0: 'Âm thanh' },
    leaderboard: { 0: 'Bảng xếp hạng' },
    extend: { 0: 'Hiển thị thêm | Hiển thị ít hơn' },
    skin: {
      0: 'Skin này chứa yếu tố từ skin khác',
      1: 'Nhấp vào đây để biết thêm thông tin'
    },
    tools: 'Công cụ'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: 'Nhật ký thay đổi',
    1: 'Danh sách tất cả những sửa đổi ở phiên bản hiện tại',
    2: 'Không có gì ở đây',
    3: 'Nhưng bạn có thể thêm vào những thay đổi đã hoàn thiện đối với phiên bản của skin này',
    4: 'Chưa nhóm',
    5: 'Mới',
    6: 'Sửa lỗi',
    7: 'Thay đổi',
    8: 'Xoá'
  },
  ideas: {
    0: 'Không thấy gì cả',
    1: 'Không có ảnh cho «{type}» được đăng trên trang này'
  },
  creators: {
    0: 'Tác giả',
    1: 'Liệt kê mọi tác giả có liên quan đến việc hoàn thành skin này',
    2: 'Không có ai ở đây',
    3: 'Tìm kiếm tên của người chơi sẽ hiển thị một danh sách các trang các nhân.',
    4: 'Trình chỉnh sửa',
    5: 'Vai trò',
    6: 'Phiên bản'
  },
  tags: {
    0: 'Các Tag',
    1: 'Danh sách tất cả các tag liên quan đến skin này',
    2: 'Có vẻ như không có gì ở đây.',
    3: 'Sử dụng ô trống bên trên để tìm các tag mới',
    4: 'Không tìm thấy tag',
    5: 'Hãy thử tìm cái gì đó khác',
    6: 'Tìm kiếm'
  },
  videos: {
    0: 'Video',
    1: 'Danh sách tất cả các video xem trước cho skin này',
    2: 'Không có xem trước',
    3: 'Tìm một vài video xem trước trên YouTube hoặc tự tạo'
  },
  sources: {
    0: 'Góp ý',
    1: 'Danh sách tất cả các asset hoặc tool trong phiên bản skin này',
    2: 'Khá là trống ở đây',
    3: 'Nếu bạn đã sử dụng asset hay tranh vẽ từ các skin khác, hãy nhớ thêm chúng vào hộp bên dưới',
    4: 'Chưa nhóm'
  },
  checks: {
    0: 'Tất cả',
    1: 'Metadata',
    2: 'Tâm điểm',
    3: 'Tên skin không xác định',
    4: 'Thêm vào ít nhất một tác giả tạo skin',
    5: 'Thêm một số tag',
    6: 'Kích thước skin không xác định',
    7: 'Chọn ít nhất một chế độ chơi',
    8: 'Chọn độ phân giải hình ảnh (SD hoặc HD)',
    9: 'Chọn ít nhất một tỷ lệ khung hình',
    10: 'Ảnh chụp màn hình không khả dụng',
    11: 'Thêm vào ít nhất một ảnh chụp màn hình gameplay',
    12: 'Liên kết skin không khả dụng',
    20: 'Trông ổn đấy',
    21: 'Mọi vấn đề đã được giải quyết. Tốt lắm!',
    22: 'Danh mục',
    23: 'Thêm ít nhất một phiên bản công khai',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles'
  },
  skins: {
    0: 'Skin',
    1: 'Phổ biến',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Gần đây',
    5: 'Ngẫu nhiên',
    6: 'Tất cả skin',
    7: 'Tỷ lệ khung hình',
    8: 'Tất cả skin | skin',
    9: 'Skin | Skin | Skin',
    10: 'Skin osu! bởi {name} | Tất cả các skin từ',
    11: 'Tìm kiếm',
    12: 'skin {name}',
    13: 'Khám phá các skin'
  },
  skin: {
    0: 'Chỉnh sửa',
    1: 'Bổ sung',
    2: 'HD',
    3: 'Full HD',
    4: 'Hoạt ảnh',
    5: 'Ảnh chụp màn hình',
    6: 'Chỉ gameplay',
    7: 'Tải skin | Tải skin',
    8: 'Bài viết Forum | osu! Forum',
    9: 'Bài viết Reddit',
    10: 'Tác giả',
    11: 'Các Tag',
    13: 'Video',
    14: 'Phiên bản mới | Quản lí phiên bản',
    15: 'Cập nhật | Xác nhận',
    16: 'Chế độ chơi',
    17: 'Tên skin',
    18: 'Phiên bản | Các phiên bản',
    19: 'Kích thước',
    20: 'Metadata',
    21: 'Đánh giá',
    22: 'Lượt tải xuống',
    23: 'Tải xuống sẽ sớm khả dụng',
    24: 'Còn {amount} giây',
    25: 'Bạn không phải một trong số chúng tôi',
    26: 'Có vẻ như bạn không phải là tác giả hay người chỉnh sửa skin này',
    27: 'Skin tạo bởi',
    28: 'Không có tag',
    29: 'Không có video',
    30: 'Không có tác giả',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately skin was deleted by {author} request'
  },
  drag: {
    0: 'Nhấn vào đây',
    1: 'hoặc kéo thả ảnh vào đây'
  },
  footer: {
    0: 'Làm bởi ck',
    1: 'Những người đóng góp'
  },
  credits: {
    0: 'Chibi',
    1: 'Tranh vẽ',
    2: 'Icon',
    3: 'Mọi icon được lấy từ {name}',
    4: 'Cờ',
    5: 'Mọi hình ảnh cờ được lấy từ {name}',
    6: 'Localisation',
    7: 'Có ai không? [{lang}]',
    8: 'Hình như cyperdark quên thêm chúng vào. {text}'
  },
  search: {
    0: 'Tìm kiếm skin',
    1: 'Lượt xem',
    2: 'Tiêu đề',
    3: 'Đánh giá',
    4: 'Kích thước',
    5: 'Ngày tháng',
    7: 'Không thấy gì cả',
    8: 'Hãy thử dùng các filter tìm kiếm khác',
    9: 'Đang chờ xử lý',
    10: 'Hãy sử dụng những filter tìm kiếm hoặc gõ tên skin, tác giả hay tag.',
    11: 'Lượt tải xuống',
    12: 'Tên',
    13: {
      0: 'Skin',
      1: 'Các Tag',
      2: 'Người dùng',
      3: 'Danh sách'
    },
    14: 'Search:'
  },
  tabs: {
    0: 'Tìm kiếm',
    1: 'Chỉnh sửa',
    2: 'Danh sách'
  },
  undefined: {
    0: 'Trống',
    1: 'Thật đáng tiếc, không có gì ở đây cả, nhưng bạn có thể xem những trang khác',
    2: 'Thật đáng tiếc, không có gì ở đây cả',
    3: 'Không thể truy cập',
    4: 'Bạn cần đăng nhập để chỉnh sửa skin này.',
    5: 'Bạn cần đăng nhập để thêm skin mới.'
  },
  meta: {
    title: {
      0: 'Khám phá các skin osu',
      1: 'Chế độ chơi, tỉ lệ của osu skin',
      2: 'Skin osu phổ biến',
      3: 'Tìm kiếm osu skin',
      4: 'Danh sách tag, {name}',
      5: '{name} v{version} osu skin',
      6: 'Những người đóng góp',
      7: 'skin osu',
      8: '{name} tìm kiếm skin osu',
      9: 'Lấy cảm hứng từ các skin osu khác',
      10: '{name} đã tạo skin osu',
      11: 'Tìm tag',
      12: 'Các tag chứa {name}',
      13: 'Skin mới'
    },
    description: {
      0: 'Tảỉ về những skin osu! tốt nhất từ trang của chúng tôi! Thư viện to lớn của chúng tôi có skin cho mọi chế độ chơi, tỷ lệ khung hình và cả kể cả những top player. Thêm vào đó, chúng tôi có một khu đặc biệt dành cho các fan anime. Cả thiện gameplay với một skin hoàn hảo. #osuskins #osugame #anime',
      1: '{views} lượt xem. Một skin osu cho {modes}, kích thước là {size}, được tạo bởi {creators}. Hỗ trợ {ratios}',
      2: 'Tìm những skin osu! hoàn hảo với tính năng tìm kiếm đã được cải thiện của chúng tôi. Tìm qua cả thư viện khổng lồ, lọc qua chế độ chơi, tỷ lệ khung hình, và hơn thế nữa. Hoặc, ghé qua các skin được sử dụng bởi các top player.',
      3: 'Khám phá các thể loại skin cho các chế độ khác nhau và các tỷ lệ khung hình trên trang của chúng tôi. Chọn từ standard, catch the beat, mania đến taiko. Tìm cho bản thân những gì phù hợp nhất với sở thích của bạn.',
      4: 'Tìm skin osu hoàn hảo từ các top player trên trang của chúng tôi. Lướt qua bộ sưu tầm những skin nổi tiếng và tùy chỉnh gameplay của bạn. Khám phá một loạt các phong cách và chủ đề phù hợp với sở thích của bạn.',
      5: 'Danh sách các tag tồn tại cho skin osu.',
      6: 'Bộ sưu tầm skin {name}!, tải miễn phí',
      7: 'Một lượng lớn skin osu cho {name}, tải miễn phí!',
      8: 'Tất cả skin được tạo bởi {name}',
      9: 'Tìm các nguồn cảm hứng cho skin osu! tiếp theo của bạn ở trang của chúng tôi. Điểm qua một bộ sưu tầm skin đa dạng và khám phá các kỹ thuật và ý tưởng mới. Lấy cảm hứng và tạo cho bản thân những skin độc đáo.',
      10: 'Tìm các tag trong tất cả các tag trên trang.'
    }
  },
  buttons: {
    0: 'Đăng nhập',
    1: 'Trang chủ',
    profile_osu: 'Trang cá nhân osu!',
    new_skin: 'Skin mới',
    notifications: 'Thông báo',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
    load_more: 'Tải thêm',
    copy_short: 'Sao chép liên kết ngắn',
    copied: 'Đã sao chép',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Quay trở lại skin'
  },
  user: {
    roles: {
      0: 'Tác giả',
      1: 'Mixer',
      2: 'Hoạt họa',
      3: 'Tranh vẽ',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Lượt xem: {amount}',
    1: 'Đang tải lại kết quả',
    2: 'Giảm | Tăng',
    3: 'Lượt thích: {likes} / Không thích: {dislikes}',
    4: 'Nhấn ctrl+enter để thêm tag',
    5: 'Chỉnh sửa phiên bản',
    6: '{s}Đăng nhập{p}, để đánh giá skin này',
    7: 'Không có mô tả ngắn',
    8: 'Không có url',
    9: 'Lượt tải: {amount}'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Dao diện chính',
      2: 'Chọn bài hát',
      3: 'Dao diện mod',
      4: 'Mod',
      5: 'Đếm ngược',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Secton Pass',
      9: 'Section Fail',
      10: 'Màn hình tạm dừng',
      11: 'Màn hình Fail',
      12: 'Màn hình kết quả',
      13: 'Bỏ qua',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Mới',
    1: 'Sửa đổi',
    2: 'Thay đổi',
    3: 'Xóa bỏ',
    4: 'Tranh vẽ',
    5: 'Phông chữ',
    6: 'Họa sĩ',
    7: 'Yếu tố skin',
    8: 'Âm thanh/Sfx',
    9: 'Công cụ',
    views: 'Lượt xem',
    likes: 'Thích',
    dislikes: 'Không thích',
    downloads: 'Lượt tải xuống',
    size_range: 'Chọn kích cỡ',
    date_range: 'Chon mốc thời gian',
    ratio: 'Chọn tỷ lệ khung hình | tỷ lệ'
  },
  placeholders: {
    0: 'Chọn vai trò',
    1: 'Chọn phiên bản',
    2: 'Hãy gõ gì đó...',
    3: 'Chọn kích cỡ',
    4: 'Chọn mốc thời gian',
    5: 'Năm',
    6: 'Tháng',
    7: 'Chọn tỷ lệ khung hình',
    8: 'Chọn danh mục',
    9: 'Chế độ chơi',
    10: 'Chọn thể loại',
    11: 'Dán một liên kết YouTube',
    12: 'Hãy gõ một mô tả và url. Định dạng: mô tả:url',
    13: 'Chọn thêm',
    14: 'Dán một liên kết',
    15: 'Tên skin, tác giả, hoặc tag',
    16: 'Chọn nhóm',
    17: 'Hãy gõ tên của tag'
  },
  contribute: { 0: 'Đóng góp' },
  nsfw: {
    0: 'Warning nsfw!',
    1: 'Skin có chứa các nội dung nhạy cảm hoặc người lớn',
    2: 'Skin có chứa các nội dung nhạy cảm có thể gây khó chịu cho một số người dùng',
    3: 'Được',
    4: 'tạm biệt o/',
    5: 'Warning furry!'
  },
  removed: {
    0: 'Phiên bản không khả dụng',
    1: 'Tác giả của skin đã xoá phiên bản này khỏi trang web.',
    2: 'Chuyển đến phiên bản khả dụng khác'
  },
  notify: {
    0: 'Vấn đề chưa được sửa',
    1: 'Một số ô quan trọng chưa được điền',
    2: 'Hiển thị',
    3: 'Không tìm thấy',
    4: 'Không tìm thấy banner (Hiện tại, ảnh chụp màn hình đầu tiên đang được dùng làm banner)',
    5: 'Không có thay đổi',
    6: 'Không tìm thấy thay đổi nào',
    7: 'Không tìm thấy ID',
    8: 'Không tìm thấy ID của video, hãy thử đường link khác (Hiện tại web chỉ hỗ trợ video YouTube)',
    9: 'Úi',
    10: 'Có vẻ như phiên đăng nhập của bạn đã hết hạn, hãy mở một trang mới và đăng nhập (Đừng lo, mọi thứ đã được tự động lưu lại)',
    11: 'Tồn tại',
    12: 'Video này đã được thêm vào',
    13: 'Tồn tại',
    14: 'Tag này đã được thêm vào',
    15: 'Không tìm thấy',
    16: 'Bạn không thể xoá tag đã bị xoá từ trước',
    17: 'Đã thêm vào',
    18: 'Bạn đã thành công thêm vào một tag',
    19: 'Úi',
    20: 'Người tạo đã được thêm vào từ trước',
    21: 'EZ',
    22: 'Người tạo mới đã được thêm vào',
    23: 'HUH',
    24: 'Không thể loại bỏ người tạo đã xoá',
    25: 'Nhân bản',
    26: 'Thay đổi này đã được thêm vào từ trước.',
    27: 'Nhân bản',
    28: 'Url này đã được thêm vào từ trước.',
    29: 'Cảnh báo',
    30: 'Bạn chưa thêm vào mô tả cho url. Ví dụ: mô tả:url',
    31: 'Cảnh báo',
    32: 'Bạn chưa thêm vào url cho mô tả. Ví dụ: mô tả:url',
    33: 'Đã khôi phục',
    34: 'Phiên bản «{name}» đã được khôi phục',
    35: 'Đã xoá',
    36: 'Phiên bản «{name}» đã được xoá',
    37: 'Lỗi',
    38: 'Dường như máy chủ nghĩ rằng bạn là bot.',
    39: 'Có vẻ như phiên đăng nhập của bạn đã hết hạn, hãy mở một trang mới và đăng nhập lại (Đừng lo, mọi thứ đã được tự động lưu lại)',
    40: 'Thông tin không khớp (hãy đăng nhập lại. Đừng lo, mọi thứ đã được tự động lưu lại)',
    41: 'Lỗi không rõ',
    42: 'Bạn không thể chỉnh sửa skin không tồn tại',
    43: 'Dường như bạn không có quyền chỉnh sửa skin này',
    44: 'Bạn không thể gửi phiên bản này vì nó tương tự phiên bản trước.',
    45: 'Các thay đổi đã được gửi để kiểm duyệt',
    46: 'Thành công',
    47: 'Các thay đổi mới đã được gửi để kiểm duyệt',
    48: 'Các thay đổi đã được cập nhật qua kiểm duyệt',
    49: 'Đường link lạ',
    50: 'Liên kết này không thể dùng làm link tải về',
    51: 'Đã gửi cho kiểm duyệt'
  },
  header: {
    0: 'Thông báo',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: 'Không thể truy cập',
    1: 'Hãy đăng nhập vào tài khoản của bạn',
    2: 'Lượt xem bị giới hạn',
    3: 'Trang này vẫn chưa được cập nhật.'
  }
};