export default {
  title: {
    home: 'Trang chủ',
    login: 'Đăng nhập',
    lists: { 0: 'Danh sách' },
    tags: {
      0: 'Các Tag',
      1: '{amount} tag của nhóm {name}',
      2: 'Tìm tag'
    },
    ideas: {
      0: 'Cảm Hứng',
      1: '«{amount}»'
    },
    sounds: { 0: 'Âm thanh' },
    leaderboard: { 0: 'Bảng xếp hạng' },
    extend: { 0: 'Hiển thị thêm | Hiển thị ít hơn' },
    skin: {
      0: 'Skin này chứa yếu tố từ skin khác',
      1: 'Nhấp vào đây để biết thêm thông tin'
    },
    tools: 'Công cụ'
  },
  changelogs: {
    0: 'Nhật ký thay đổi',
    1: 'Danh sách tất cả những sửa đổi ở phiên bản hiện tại',
    2: 'Không có gì ở đây',
    3: 'Nhưng bạn có thể thêm vào những thay đổi đã hoàn thành đối với phiên bản của skin này',
    4: 'Chưa nhóm',
    5: 'Mới',
    6: 'Sửa lỗi',
    7: 'Thay đổi',
    8: 'Xoá'
  },
  ideas: {
    0: 'Không thấy gì cả',
    1: 'Không có ảnh cho «{type}» được đăng trên trang này'
  },
  creators: {
    0: 'Tác giả',
    1: 'Liệt kê mọi tác giả có liên quan đến việc hoàn thành skin này',
    2: 'Không có ai ở đây',
    3: 'Tìm kiếm tên của người chơi sẽ hiển thị một danh sách các trang các nhân.',
    4: 'Trình chỉnh sửa',
    5: 'Vai trò',
    6: 'Phiên bản'
  },
  tags: {
    0: 'Các Tag',
    1: 'Danh sách tất cả các tag liên quan đến skin này',
    2: 'Có vẻ như không có gì ở đây.',
    3: 'Sử dụng ô trống bên trên để tìm các tag mới',
    4: 'Không tìm thấy tag',
    5: 'Hãy thử tìm cái gì đó khác',
    6: 'Tìm kiếm'
  },
  videos: {
    0: 'Video',
    1: 'Danh sách tất cả các video xem trước cho skin này',
    2: 'Không có xem trước',
    3: 'Tìm một vài video xem trước trên YouTube hoặc tự tạo'
  },
  sources: {
    0: 'Góp ý',
    1: 'Danh sách tất cả các asset hoặc tool trong phiên bản skin này',
    2: 'Khá là trống ở đây',
    3: 'Nếu bạn đã sử dụng asset hay tranh vẽ từ các skin khác, hãy nhớ thêm chúng vào hộp bên dưới',
    4: 'Chưa nhóm'
  },
  checks: {
    0: 'Tất cả',
    1: 'Metadata',
    2: 'Tâm điểm',
    3: 'Tên skin không xác định',
    4: 'Thêm vào ít nhất một tác giả tạo skin',
    5: 'Thêm một số tag',
    6: 'Kích thước skin không xác định',
    7: 'Chọn ít nhất một chế độ chơi',
    8: 'Chọn độ phân giải hình ảnh (SD hoặc HD)',
    9: 'Chọn ít nhất một tỷ lệ khung hình',
    10: 'Ảnh chụp màn hình không khả dụng',
    11: 'Thêm vào ít nhất một ảnh chụp màn hình gameplay',
    12: 'Liên kết skin không khả dụng',
    20: 'Trông có vẻ khá ổn',
    21: 'Mọi vấn đề đều đã được giải quyết. Tốt lắm',
    22: 'Danh mục',
    23: 'Thêm ít nhất một phiên bản công khai'
  },
  skins: {
    0: 'Skin',
    1: 'Phổ biến',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: 'Gần đây',
    5: 'Ngẫu nhiên',
    6: 'Tất cả skin',
    7: 'Tỷ lệ khung hình',
    8: 'Tất cả skin | skin',
    9: 'Skin | Skin | Skin',
    10: 'Skin osu! bởi {name} | Tất cả các skin từ',
    11: 'Tìm kiếm',
    12: 'skin {name}',
    13: 'Khám phá các skin'
  },
  skin: {
    0: 'Chỉnh sửa',
    1: 'Bổ sung',
    2: 'HD',
    3: 'Full HD',
    4: 'Hoạt ảnh',
    5: 'Ảnh chụp màn hình',
    6: 'Chỉ gameplay',
    7: 'Tải skin | Tải skin',
    8: 'Bài viết Forum | osu! Forum',
    9: 'Bài viết Reddit',
    10: 'Tác giả',
    11: 'Các Tag',
    13: 'Video',
    14: 'Phiên bản mới | Quản lí phiên bản',
    15: 'Cập nhật | Xác nhận',
    16: 'Chế độ chơi',
    17: 'Tên skin',
    18: 'Phiên bản | Các phiên bản',
    19: 'Kích thước',
    20: 'Metadata',
    21: 'Đánh giá',
    22: 'Lượt tải xuống',
    23: 'Tải xuống sẽ sớm khả dụng',
    24: 'Còn {amount} giây',
    25: 'Bạn không phải một trong số chúng tôi',
    26: 'Có vẻ như bạn không phải là tác giả hay người chỉnh sửa skin này',
    27: 'Skin tạo bởi',
    28: 'Không có tag',
    29: 'Không có video',
    30: 'Không có tác giả'
  },
  drag: {
    0: 'Nhấn vào đây',
    1: 'hoặc kéo thả ảnh vào đây'
  },
  footer: {
    0: 'Làm bởi ck',
    1: 'Những người đóng góp'
  },
  credits: {
    0: 'Chibi',
    1: 'Tranh vẽ',
    2: 'Icon',
    3: 'Mọi icon được lấy từ {name}',
    4: 'Cờ',
    5: 'Mọi hình ảnh cờ được lấy từ {name}',
    6: 'Localisation',
    7: 'Có ai không? [{lang}]',
    8: 'Có vẻ như cpol quên thêm chúng vào. {text}'
  },
  search: {
    0: 'Tìm kiếm skin',
    1: 'Lượt xem',
    2: 'Tiêu đề',
    3: 'Đánh giá',
    4: 'Kích thước',
    5: 'Ngày tháng',
    7: 'Không thấy gì cả',
    8: 'Hãy thử điều chỉnh cách chọn lọc khác',
    9: 'Đang chờ xử lý',
    10: 'Hãy chọn các filter tìm kiếm hoặc chỉ cần ghi tên, tác giả hay các tag của skin',
    11: 'Lượt tải xuống',
    12: 'Tên',
    13: {
      0: 'Skin',
      1: 'Các Tag',
      2: 'Người dùng',
      3: 'Danh sách'
    }
  },
  tabs: {
    0: 'Tìm kiếm',
    1: 'Chỉnh sửa',
    2: 'Danh sách'
  },
  undefined: {
    0: 'Trống',
    1: 'Đáng tiếc là không có gì ở đây, thay vào đó bạn có thế xem các trang khác',
    2: 'Đáng tiếc là không có gì ở đây',
    3: 'Không thể truy cập',
    4: 'Bạn cần đăng nhập để chỉnh sửa skin này.',
    5: 'Bạn cần đăng nhập để thêm skin mới.'
  },
  meta: {
    title: {
      0: 'Khám phá các skin osu',
      1: 'Chế độ chơi, tỉ lệ của osu skin',
      2: 'Skin osu phổ biến',
      3: 'Tìm kiếm osu skin',
      4: 'Danh sách tag, {name}',
      5: '{name} v{version} osu skin',
      6: 'Những người đóng góp',
      7: 'skin osu',
      8: '{name} tìm kiếm skin osu',
      9: 'Lấy cảm hứng từ các skin osu khác',
      10: '{name} đã tạo skin osu',
      11: 'Tìm tag',
      12: 'Các tag chứa {name}'
    },
    description: {
      0: 'Tảỉ về những skin osu! tốt nhất từ trang của chúng tôi! Thư viện to lớn của chúng tôi có skin cho mọi chế độ chơi, tỷ lệ khung hình và cả kể cả những top player. Thêm vào đó, chúng tôi có một khu đặc biệt dành cho các fan anime. Cả thiện gameplay với một skin hoàn hảo. #osuskins #osugame #anime',
      1: '{views} lượt xem. Một skin osu cho {modes}, kích thước là {size}, được tạo bởi {creators}. Hỗ trợ {ratios}',
      2: 'Tìm những skin osu! hoàn hảo với tính năng tìm kiếm đã được cải thiện của chúng tôi. Tìm qua cả thư viện khổng lồ, lọc qua chế độ chơi, tỷ lệ khung hình, và hơn thế nữa. Hoặc, ghé qua các skin được sử dụng bởi các top player.',
      3: 'Khám phá các thể loại skin cho các chế độ khác nhau và các tỷ lệ khung hình trên trang của chúng tôi. Chọn từ standard, catch the beat, mania đến taiko. Tìm cho bản thân những gì phù hợp nhất với sở thích của bạn.',
      4: 'Tìm skin osu hoàn hảo từ các top player trên trang của chúng tôi. Lướt qua bộ sưu tầm những skin nổi tiếng và tùy chỉnh gameplay của bạn. Khám phá một loạt các phong cách và chủ đề phù hợp với sở thích của bạn.',
      5: 'Danh sách các tag tồn tại cho skin osu.',
      6: 'Bộ sưu tầm skin {name}!, tải miễn phí',
      7: 'Một lượng lớn skin osu cho {name}, tải miễn phí!',
      8: 'Tất cả skin được tạo bởi {name}',
      9: 'Tìm các nguồn cảm hứng cho skin osu! tiếp theo của bạn ở trang của chúng tôi. Điểm qua một bộ sưu tầm skin đa dạng và khám phá các kỹ thuật và ý tưởng mới. Lấy cảm hứng và tạo cho bản thân những skin độc đáo.',
      10: 'Tìm các tag trong tất cả các tag trên trang.'
    }
  },
  buttons: {
    0: 'Đăng nhập',
    1: 'Trang chủ',
    profile_osu: 'Trang cá nhân osu!',
    new_skin: 'Skin mới',
    notifications: 'Thông báo',
    settings: 'Cài đặt',
    logout: 'Đăng xuất',
    load_more: 'Tải thêm',
    copy_short: 'Sao chép liên kết ngắn',
    copied: 'Đã sao chép',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! Forum',
    skin_return: 'Quay trở lại skin'
  },
  user: {
    roles: {
      0: 'Tác giả',
      1: 'Mixer',
      2: 'Hoạt họa',
      3: 'Tranh vẽ',
      4: 'Collab'
    }
  },
  tooltips: {
    0: 'Lượt xem: {amount}',
    1: 'Đang tải lại kết quả',
    2: 'Giảm | Tăng',
    3: 'Lượt thích: {likes} / Không thích: {dislikes}',
    4: 'Nhấn ctrl+enter để thêm tag',
    5: 'Chỉnh sửa phiên bản',
    6: '{s}Đăng nhập{p}, để có thể đánh giá skin này',
    7: 'Không có mô tả ngắn',
    8: 'Không có url',
    9: 'Lượt tải: {amount}'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Dao diện chính',
      2: 'Chọn bài hát',
      3: 'Dao diện mod',
      4: 'Mod',
      5: 'Đếm ngược',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Secton Pass',
      9: 'Section Fail',
      10: 'Màn hình tạm dừng',
      11: 'Màn hình Fail',
      12: 'Màn hình kết quả',
      13: 'Bỏ qua',
      14: 'Banner'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: 'Mixed'
    }
  },
  select: {
    0: 'Mới',
    1: 'Sửa đổi',
    2: 'Thay đổi',
    3: 'Xóa bỏ',
    4: 'Tranh vẽ',
    5: 'Phông chữ',
    6: 'Họa sĩ',
    7: 'Yếu tố skin',
    8: 'Âm thanh/Sfx',
    9: 'Công cụ',
    views: 'Lượt xem',
    likes: 'Thích',
    dislikes: 'Không thích',
    downloads: 'Lượt tải xuống',
    size_range: 'Chọn kích cỡ',
    date_range: 'Chon mốc thời gian',
    ratio: 'Chọn tỷ lệ khung hình | tỷ lệ'
  },
  placeholders: {
    0: 'Chọn role',
    1: 'Chọn phiên bản',
    2: 'Nhập văn bản...',
    3: 'Chọn kích cỡ',
    4: 'Chọn mốc thời gian',
    5: 'Năm',
    6: 'Tháng',
    7: 'Chọn tỷ lệ khung hình',
    8: 'Chọn danh mục',
    9: 'Chế độ chơi',
    10: 'Chọn thể loại',
    11: 'Dán một liên kết YouTube',
    12: 'Nhập mô tả và url. Định dạng mô tả:url',
    13: 'Chọn thêm',
    14: 'Dán một liên kết',
    15: 'Tiêu đề skin, tác giả, hoặc tag',
    16: 'Chọn nhóm',
    17: 'Hãy gõ tên của tag'
  },
  contribute: { 0: 'Đóng góp' },
  nsfw: {
    0: 'Cảnh báo!',
    1: 'Skin có chứa các nội dung nhạy cảm hoặc người lớn',
    2: 'Skin có chứa các nội dung nhạy cảm có thể gây khó chịu cho một số người dùng',
    3: 'Được',
    4: 'tạm biệt o/'
  },
  removed: {
    0: 'Phiên bản không khả dụng',
    1: 'Tác giả của skin đã xóa phiên bản này khỏi trang web.',
    2: 'Chuyển đến phiên bản khả dụng khác'
  },
  notify: {
    0: 'Không thể sửa vấn đề',
    1: 'Một số thông tin cần điền chưa được ghi',
    2: 'Hiển thị',
    3: 'Không tìm thấy',
    4: 'Không tìm thấy banner (Hiện tại, ảnh chụp màn hình đầu tiên đang được dùng làm banner)',
    5: 'Không có thay đổi',
    6: 'Không tìm thấy thay đổi nào',
    7: 'Không tìm thấy ID',
    8: 'Không tìm thấy ID của video, hãy thử đường link khác (Hiện tại web chỉ hỗ trợ video YouTube)',
    9: 'Úi',
    10: 'Cỏ vẻ phiên đăng nhập người dùng của bạn đã hết hạn, hãy mở trang mới và đăng nhập lại (Đừng lo, mọi thứ đã được lưu lại)',
    11: 'Tồn tại',
    12: 'Video này đã được thêm vào',
    13: 'Tồn tại',
    14: 'Tag này đã được thêm vào',
    15: 'Không tìm thấy',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Tồn tại',
    26: 'Same change with this type has been added earlier',
    27: 'Warning',
    28: 'Same url with this type has been added earlier',
    29: 'Warning',
    30: 'You forgot to add a description for a url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add a url for description. Example: Description:url',
    33: 'Restored',
    34: 'Version {name} has been restored',
    35: 'Deleted',
    36: 'Version {name} has been deleted',
    37: 'Error',
    38: 'Seems like the server thinks you\'re a bot',
    39: 'Looks like you\'re user session is expired, open new page and log into your account (Don\'t worry, everything is saved automatically)',
    40: 'Mismatched credentials (re:login in account. Don\'t worry, everything is saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit inexistent skin',
    43: 'Seems like you don\'t have permissions to edit this skin',
    44: 'You cannot submit this version as it is the same as the previous one',
    45: 'Those changes has been sent already on moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted to moderation'
  },
  restricted_view: {
    0: 'Không thể truy cập',
    1: 'Please login in account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  }
};