export default {
  title: {
    home: '首頁',
    login: '登入',
    lists: { 0: '清單' },
    tags: {
      0: '標籤',
      1: '以{name} 字首的有 {amount} 個標籤',
      2: '搜尋標籤'
    },
    ideas: {
      0: '素材參考',
      1: '«{amount}»'
    },
    sounds: { 0: '音效' },
    leaderboard: { 0: '排行榜' },
    extend: { 0: '更多 | 更少' },
    skin: {
      0: '這個skin有源於其他skin的素材',
      1: '點擊這裡以瞭解詳情'
    },
    tools: '工具'
  },
  home: {
    0: 'Available to download',
    1: 'Most: _name_ skins',
    2: 'Viewed | Liked | Downloaded',
    3: 'Publish new skin',
    4: 'How to install skin',
    5: '{amount} Skins | {amount} Skins | {amount} Skins'
  },
  changelogs: {
    0: '更新日誌',
    1: '列出所有對於目前版本的改動',
    2: '這裡什麼都沒有',
    3: 'But you can add the changes you\'ve made to this version of the skin',
    4: '未分類',
    5: '新',
    6: '修復',
    7: '改動',
    8: '移除'
  },
  ideas: {
    0: '無搜尋結果',
    1: 'Screenshots of «{type}» were not uploaded to the site',
    2: '«{amount}» {name}'
  },
  creators: {
    0: '創作者',
    1: '列出所有參與此版本的創作者',
    2: '人...呢?',
    3: '搜尋名子以顯示相關個人介面',
    4: '編輯者',
    5: '身分',
    6: '版本'
  },
  tags: {
    0: '標籤',
    1: '列出所有有關這個skin的標籤',
    2: '空空如也',
    3: '利用上面的區塊來找尋新標籤',
    4: '找不到標籤',
    5: '請嘗試搜尋其他內容',
    6: '搜尋'
  },
  videos: {
    0: '影片',
    1: '列出所有展示這個skin的影片',
    2: '沒有showcase',
    3: 'Youtube上尋找或者創建自己的showcase'
  },
  sources: {
    0: '來源',
    1: '列出當前版本skin的所用過的資源和工具',
    2: '啪 什麼都沒有',
    3: '如果你用了來自其他skin的資源, 請確定你有將它們加進上面的欄位',
    4: '未分類'
  },
  checks: {
    0: '所有',
    1: '內容',
    2: 'Highlight',
    3: 'Name of the skin not specified',
    4: '請添加至少一個創作者',
    5: '請添加一些標籤',
    6: '未標明skin的大小',
    // 7: 'Select at least one gamemode',
    8: '請選擇圖片解析度(SD 或 HD)',
    9: '請選擇至少一種長寬比',
    10: '無任何截圖',
    11: '添加至少一張遊戲畫面的截圖',
    12: '未標明skin的下載連結',
    20: 'Looks pretty good',
    21: 'Every issue was fixed. Good job!',
    22: '檢查',
    23: 'Add at least one public version',
    24: 'Add at least one creator to this version',
    25: 'Some creators doesn\'t have roles',
    26: '{amount} screenshots doesn\'t have category',
    27: 'Specifiy gameplay name for {mode} screenshots | Specifiy gameplay name for {mode} screenshot',
    28: 'Select gamemode for gameplay screenshots'
  },
  skins: {
    0: 'Skins',
    1: '熱門度',
    2: 'std | ctb',
    3: 'mania | taiko',
    4: '最新',
    5: '隨機',
    6: '所有skin',
    7: '長寬比',
    8: '所有 skin | osu skin',
    9: 'Skin | Skins | Skins',
    10: '{name} 創建的 osu Skins | 所有的skin源自於',
    11: '搜尋',
    12: '{name} skins',
    13: 'Explore skins',
    14: 'Popular skins'
  },
  skin: {
    0: '編輯',
    1: 'Extra',
    2: 'HD',
    3: 'FullHD',
    4: '動態',
    5: '截圖',
    6: '遊戲畫面',
    7: '下載連結 | 下載skin',
    8: '論壇貼文 | osu! 論壇',
    9: 'Reddit 貼文',
    10: '創作者',
    11: '標籤',
    13: '影片',
    14: '新版本 | 管理版本',
    15: '更新 | 提交',
    16: '遊戲模式',
    17: 'skin的名子',
    18: '版本 | 版本',
    19: '檔案大小',
    20: '內容',
    21: '評分',
    22: '下載數',
    23: '很快就會開始你的下載',
    24: '剩 {amount} 秒',
    25: '你不是我們之一',
    26: '看起來你好像不是此skin的作者或編輯者',
    27: 'Skin by',
    28: 'No tags',
    29: 'No videos',
    30: 'No creators',
    31: 'Rate skin',
    32: 'Upvote & comment on reddit',
    33: 'Comment on osu! forum',
    34: 'More skins from this author | More skins from this authors',
    35: 'Support the skin',
    36: 'Unavailable',
    37: 'Unfortunately, this skin was deleted',
    38: 'Welcome to the skin post editor!',
    39: `New to the skin editor? Let us guide you through the interface and show you the editor's full potential!`,
    40: '{current} of {max} completed',
    41: 'Check out later',
    42: `Let's get started`,
    43: 'Congratulations!',
    44: 'You have successfully finished the tutorial, have fun!',
    45: 'uploader'
  },
  drag: {
    0: '點擊此處',
    1: '或拖放圖片至此'
  },
  footer: {
    0: 'Made by cyperdark',
    1: 'Credits',
    2: 'Rules',
    3: 'Contacts'
  },
  credits: {
    0: 'Chibi',
    1: '美術',
    2: '圖示',
    3: '所有的圖示都源自於 {name}',
    4: '國旗',
    5: '所有的國旗都源自於 {name}',
    6: '語言',
    7: '尚未添加 [{lang}]',
    8: 'Seems like cyperdark forgot to add them. {text}'
  },
  search: {
    0: '搜尋skin',
    1: '觀看數',
    2: '標題',
    3: '評分',
    4: '檔案大小',
    5: '添加日期',
    7: '無搜尋結果',
    8: 'Try using different search filters',
    9: '看起來遇到了一些問題',
    10: 'Use the search filters or type the skin\'s title, author or tags',
    11: '下載數',
    12: '名子',
    13: {
      0: 'Skins',
      1: '標籤',
      2: 'Users',
      3: '清單'
    },
    14: 'Search:',
    15: 'Size:',
    16: 'Rating:',
    17: 'Views:',
    18: 'Downloads:'
  },
  contests: {
    0: 'Contests',
    1: 'Official newspost',
    2: 'Submission',
    3: 'Preparing',
    4: 'Voting',
    5: 'Finished',
    6: 'Contests',
    7: 'Voting page'
  },
  rules: {
    0: 'Last updated at',
    1: 'Posting Skins Guidelines'
  },
  skinini: {
    0: 'Welcome to skin.ini editor!',
    1: `New to the skin.ini editor? Let us guide you through the interface and show you the editor's full potential!`,
    2: '{current} of {max} completed',
    3: 'No results',
    4: 'Your query may contain typos'
  },
  tabs: {
    0: '搜尋',
    1: '編輯',
    2: '清單'
  },
  undefined: {
    0: '空',
    1: 'Unfortunately, there\'s nothing here, but you can take a look at the other pages',
    2: 'Unfortunately, there\'s nothing here',
    3: '未授權',
    4: 'You need to be logged in order to edit this skin.',
    5: 'You need to be logged in order to add a new skin.'
  },
  settings: {
    0: '設定',
    1: 'Mouse scroll',
    2: 'Enable mouse hover swipe for image carousel, allowing left-to-right or right-to-left navigation.',
    3: 'Zoom in',
    4: 'Enable image zoom on hover for larger skin preview.',
    5: 'English comments',
    6: 'Show English translation of the comments'
  },
  meta: {
    title: {
      0: '搜索skins',
      1: '遊戲模式, 長寬比 osu skins',
      2: '最熱門的skin',
      3: '搜尋osu skin',
      4: '標籤, {name}',
      5: '{name} v{version} osu skin',
      6: 'Credits',
      7: 'osu skins',
      8: '{name} 搜尋到的 osu skin',
      9: '從其他的skin獲得啟發',
      10: '{name} 創建了osu skin',
      11: '搜尋標籤',
      12: '{name} found tags',
      13: '新skin',
      14: 'Site rules',
      15: 'osu! Contests',
      16: 'osu! skinning Tools and Resources list'
    },
    description: {
      0: '你可以在這網站找到最適合你的skin, 我們龐大的資料庫有所有遊戲模式,長寬比甚至是各個大佬的skin. 另外也有以動漫分類的skin. 一個好的skin是你變強的開始. #osuskins #osugame #動漫',
      1: '觀看數 {views}. {modes} 適用, 長寬比 {size}, 由 {creators} 所創建. 另外支持 {ratios}',
      2: '利用我們最好的搜尋功能來在這龐大的資料庫中找你對應你遊戲模式, 長寬比或各個大佬的skin',
      3: '以不同的遊戲模式, 長寬比來找到各式各樣的skin. 從不同的模式找到最符合你遊戲習慣的skin.',
      4: '從我們的網站中找到大佬們用的skin. 瀏覽我們最受歡迎的skin來自訂你的遊戲體驗. 找到一個最符合你風格和主題的skin.',
      5: '所有標籤的列表',
      6: '免費下載 {name} !',
      7: '{name}, 有大量的skin可以免費下載!',
      8: '{name} 所創建的所有skin',
      9: '在我們的網站上參考不同人製作的skin來製作專屬於你自己的skin',
      10: 'Search for tags among all the tags on the site.',
      11: 'List of all active/finished osu! contests',
      12: '{amount} entries for {title} contest. {views} views'
    }
  },
  buttons: {
    0: '登入',
    1: '首頁',
    profile_osu: 'osu! 個人頁面',
    new_skin: '新skin',
    notifications: '通知',
    settings: '設定',
    logout: '登出',
    load_more: '加載更多',
    copy_short: '複製短鏈結',
    copied: '已複製',
    reddit_link: 'Reddit',
    osu_forum_link: 'osu! 論壇',
    skin_return: '回到上一頁',
    source: 'Source',
    contest_voting: 'Vote here',
    rules_agree: 'I agree',
    report_issue: 'Report issue',
    ghost_creator: 'Ghost creator',
    close: 'Close',
    quick_select: 'Quick select'
  },
  choose: {
    0: 'Optional',
    1: 'Required',
    2: 'Pick at least one option'
  },
  user: {
    roles: {
      0: '創作者',
      1: '混合者',
      2: '動畫',
      3: '美術',
      4: '連動',
      5: '音效',
      6: 'Gameplay'
    }
  },
  tooltips: {
    0: '點擊量: {amount}',
    1: '重新整理結果',
    2: '降序 | 升序',
    3: '喜歡: {likes} / 不喜歡: {dislikes}',
    4: '按下 ctrl+enter 以新增標籤',
    5: '編輯版本',
    6: '{s}Log in{p}, in order to rate this skin',
    7: '沒有描述',
    8: '沒有連結',
    9: '下載量: {amount}',
    10: 'Reset everything',
    11: 'Show guide',
    12: 'Close guide',
    13: 'To mark a rule as read, hover over it (Yellow indicates unread)',
    14: {
      0: '[hl]{example}[/hl] - [b]equal[/b] to {amount}',
      1: '[hl]{example}[/hl] - [b]above[/b] {amount}',
      2: '[hl]{example}[/hl] - [b]below[/b] {amount}',
      3: '[hl]{example}[/hl] - [b]from[/b] {amount} [b]to[/b] {amount_2}'
    },
    15: 'Unselect',
    16: 'Remove file'
  },
  lists: {
    screens: {
      0: 'Welcome',
      1: 'Main menu',
      2: 'Song select',
      3: 'Mode menu',
      4: 'Mods',
      5: 'Countdown',
      6: 'Gameplay',
      7: 'Spinner',
      8: 'Section Pass',
      9: 'Section Fail',
      10: 'Pause Screen',
      11: 'Fail Screen',
      12: 'Result screen',
      13: 'Skip',
      14: 'Banner',
      15: 'Result screen (bottom)',
      16: 'Beginning image'
    },
    cats: {
      0: 'NSFW',
      1: 'Furry',
      2: '混合'
    }
  },
  select: {
    0: '新',
    1: '已修復',
    2: '已改動',
    3: '已移除',
    4: '美術',
    5: '字體',
    6: '繪師',
    7: 'skin元素',
    8: '音效',
    9: '工具',
    10: '圖片',
    views: '觀看數',
    likes: '喜歡',
    dislikes: '不喜歡',
    downloads: '下載數',
    ratio: '長寬比 | 長寬比',
    sorting: 'Desc. | Asc.'
  },
  sorting: {
    0: 'Most | Least',
    1: 'Most | Least',
    2: 'Highest | Lowest',
    3: 'Largest | Smallest',
    4: 'Newest | Oldest',
    5: 'A-Z | Z-A'
  },
  placeholders: {
    0: 'Select roles',
    1: 'Select versions',
    2: 'Type some text...',
    3: 'Select size range',
    4: '選擇日期範圍',
    5: '年',
    6: '月',
    7: '選擇長寬比',
    8: '選擇類別',
    9: '遊戲模式',
    10: '選擇類別',
    11: '貼上Youtube連結',
    12: 'Type a description and an url. Format description:url',
    13: '選擇額外的',
    14: '貼上連結',
    15: 'Skin title, author, or tags',
    16: 'Select category',
    17: 'Type the name of the tag',
    18: 'Type the name of the skin',
    19: 'Type author name ',
    20: 'Select file',
    24: 'Type gameplay name...',
    25: 'Type range',
    26: 'Type text'
  },
  contribute: { 0: '貢獻' },
  nsfw: {
    0: 'Warning, nsfw!',
    1: '這個skin包含敏感或成人內容',
    2: '此skin包含一些可能會讓人感到不安的敏感或成人內容',
    3: 'Alright',
    4: 'bye o/',
    5: 'Furry Warning!'
  },
  removed: {
    0: 'Version unavailable',
    1: 'The author of the skin decided to remove this version from the site.',
    2: 'Switch to an available version'
  },
  notify: {
    0: 'Issues were not fixed',
    1: 'Not all required fields were filled',
    2: 'Show',
    3: 'Not found',
    4: 'Banner not found (Currently, the first screenshot is being used as the banner)',
    5: 'No changes',
    6: 'No changes were found',
    7: 'ID not found',
    8: 'ID of the video not found, try another link (At the moment only YouTube is supported)',
    9: 'Oops',
    10: 'Looks like your session expired, open a new page and log into your account (Don\'t worry, everything was saved automatically)',
    11: 'Exists',
    12: 'This video has already been added',
    13: 'Exists',
    14: 'This tag has already been added',
    15: 'Not found',
    16: 'You cannot delete a deleted tag',
    17: 'Added',
    18: 'You have successfully added a new tag',
    19: 'OOps',
    20: 'This creator was already added',
    21: 'EZ',
    22: 'New creator has been added',
    23: 'HUH',
    24: 'Impossible to remove a deleted creator',
    25: 'Duplicate',
    26: 'This change has already been added earlier.',
    27: 'Duplicate',
    28: 'This url has already been added earlier.',
    29: 'Warning',
    30: 'You forgot to add a description for the url. Example: Description:url',
    31: 'Warning',
    32: 'You forgot to add an url for the description. Example: Description:url',
    33: 'Restored',
    34: 'Version «{name}» has been restored',
    35: 'Deleted',
    36: 'Version «{name}» has been deleted',
    37: 'Error',
    38: 'Apparently the server thinks you\'re a robot.',
    39: 'Your current login session has timed out. To proceed, please open a new page and log back into your account. Once you\'ve done that, return to this page and try again.',
    40: 'Mismatched credentials (relogin in account. Don\'t worry, everything was saved automatically)',
    41: 'Unknown error',
    42: 'You cannot edit a nonexistent skin',
    43: 'Seems like you don\'t have permission to edit this skin',
    44: 'You cannot send this version because it is the same as the previous one.',
    45: 'These changes have already been sent for moderation',
    46: 'Success',
    47: 'New changes have been submitted for moderation',
    48: 'Changes have been updated in moderation',
    49: 'Odd link',
    50: 'This link cannot be used as a download link',
    51: 'Submitted for moderation',
    52: 'Warning',
    53: 'You need to choose type of asset',
    54: 'The skin is currently under moderation. Please be patient while it is being processed',
    55: 'Success',
    56: 'New ghost creator has been added',
    57: 'Color copied',
    58: `The RGB code "{color}" is now available through your clipboard!`
  },
  header: {
    0: '通知',
    1: 'Follow us on these platforms to receive notifications about new skins'
  },
  restricted_view: {
    0: '未授權',
    1: 'Please log into your account',
    2: 'Restricted view',
    3: 'This page is not out, yet.'
  },
  confirm: {
    0: 'Reset everything?',
    1: 'Show guide?',
    2: 'Submit skin?',
    3: 'Yes',
    4: 'No',
    5: 'Reset .ini?'
  }
};